/**
 *Submitted for verification at Etherscan.io on 2023-08-11
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

// 1 = Satellite Operator [M]
// 2 = Satellite Operator [F]
// 3 = Mars Pilot [M]
// 4 = Mars Pilot [F]
// 5 = Assault Team [M]
// 6 = Assault Team [F]
// 7 = Cyborg
// 8 = Robot
// 9 = Alien 
// 10 = Silicon-Based Lifeform
// // padding
// 20 = Mars Kongz
// 21 = Mars Mice 
// 22 = Mars Orc
// 23 = Mars Hoot
// 24 = Mars Cat 
// 25 = Mars Kaiju
// 26 = Mars Toad
// 27 = Mars Galactic Ape 
// 28 = Mars Doge 
// 29 = Mars Creature 
// 30 = Mars Duck 
// 31 = Mars Bear 
// // padding

contract ModelStorage {
    string public constant LABEL = "RACE ARMS";
    function getModel(uint256 modelId_) external pure returns (string memory) {

        if (modelId_ == 1) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVHcEzvzsBOLR/Mn5GgFcXDAAAAAXRSTlMAQObYZgAAAGRJREFUOMtjYBgFo2AUUASYFqDxVxagCmiGJqAKTA11gDE5wDpCQ2F8rjAQyRkaAhNQDV0AJuFGhIZGgY1oQAgAlSAZARKIAAqEIQuEAc2MQHIAULkqpkAAqgCSO4GSQIFQNAEALKwa/Lo8Om4AAAAASUVORK5CYII=";
        if (modelId_ == 2) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEVHcEzvzsDvzsBOLR/vzsBOLR9ebzdNAAAABHRSTlMAGQICfFz9ywAAAG5JREFUSMdjYBgFo2AUjIJBBgwIyDMZjIbRkAasofjlQ0Mc8Mu7uOBVwOri4oIhKIhkaQg2BS4uocgGYNjACBQMwKeABSjois8GkAKYESHY/KDiAjcCqw1gY6FGhOBR4EpIAcgIkA0u2AOPGAWuAK2wH08DK4VOAAAAAElFTkSuQmCC";

        if (modelId_ == 7) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAKlBMVEVHcEzvzsCtpsNOLR8AAABmX3f///81MEUODRKBeZfMn5FRNCsiFA4DAgFfLJQwAAAAAXRSTlMAQObYZgAAAI1JREFUSMdjYBgFo2AUjIJRMAqoCJiN8Uq7+B6RwifPohQ60xufArckpdAJmMIGcAvS0tJUMaSNBYVhFqglKSkpYLhaUFAQ6nC3NKWOJgwDBAXhKtySNMoLsCuAqHBLai9nwKFAEOhQliB8CoQhCjBtYDCEqgAqCFXSaCCgQIkBr4KpoQrYYg9ZQQAeBQAcaBoTcHZvLgAAAABJRU5ErkJggg==";
        if (modelId_ == 8) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAGFBMVEVHcEytpsNmX3cAAACBeZf///81MEUODRIW6RVJAAAAAXRSTlMAQObYZgAAAKVJREFUSMft0TEOwyAMBdBIPsGPFDHH9QEa0RwgLRdg8BXInCW5ft00nUCMnfiTJZ7ANl3X0tLS0tLyv/ibr54TONxrYI7gV+0BVe0rgIYI9FJ442psVhxbCXj4qwOX1gIgyFfMcU8rMkBT7GUxQeMH5DdMg0YO+AEuAUAWAwx3bNmmaFQbjsMJrMgWRazR2XBWPU2w5ABut95PwCzZXzwYe0qbvAEeKx8szTFgYAAAAABJRU5ErkJggg==";
        if (modelId_ == 9) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAG1BMVEVHcEyGnWhsgFOZsXodIhcyOydPaD1mfk96kF5cGebIAAAAAXRSTlMAQObYZgAAAKBJREFUSMft0DEOwjAQBMAUpmdtIlFiKwWtdR+wkd+QHp6QF/B0ziQKxTlJQ3lbekerk7tOo9FoNJo/xpSDOtvdPgP9HsiOcJbPaR3gHqIuuKwDFK9iwAAov4FBDHAfFpEJ9i3AxGAWxkUEeeHEz9YjzWBoAETe8KUC2NQCxEWwm2D0DPgMBh73xueNT0fxCx4etwY4vVw9swJsABB/cPgAN7cTx7tC9pgAAAAASUVORK5CYII=";
        if (modelId_ == 10) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEVHcEyx4OlxpLo1SFFId4swWWswKQjRAAAAAXRSTlMAQObYZgAAAKFJREFUSMftkMsNwyAMhiOxQE3TAXDonUczQCwYoAj2X6VQRblg0UuPfEf70+/Hskwmk8lk8keE/9F292HfgtxGgpWBTF++SkKGo5/g/bWW1QG6AIGo/ShgP2AlfwaQMqxQNvMNyAQLJ8AjtduETop5wk4AUNpxYk3MhCrgGWFjAkZ4pSrIgk1A7s0uNyGmKhR1496fUYEMVXDlzQpPqoKOH6kdF3nPms/TAAAAAElFTkSuQmCC";

        if (modelId_ == 20) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcExXMnNJKWIAAAA1GUsmuPCsAAAAAXRSTlMAQObYZgAAAJpJREFUSMftkNENwyAQQ0/KAvUlA/RcBgCxQINu/5kKUpt+QNKffuIfJPxkWycyNTU1NTX1Ry35h5300k/AegVU3279dzwCALXOzt/QBOO9q1UyHwF8dAEM7nv+LNDYAQp9EwsM7Beq0dwRG8BBg6Bu2NzX1sBBQ/smStjbRHAIKOCsQH2LnABbCZJIfY7OX4+n8CAgwilgm78A5X0SXIJkgmQAAAAASUVORK5CYII=";
        if (modelId_ == 21) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEz19fUAAADY2NiRkZG2+OzqAAAAAXRSTlMAQObYZgAAAH9JREFUSMftkMsRgCAMRBkrMGABgQqUWAH9F2X4jDpDwIvH7JF985aJMRqNRqPR/JglfNR+mwIewE4FALD2z/gWQFeHR8qCY5Ws4Ra42Am4p0Yw61AEGsEAGQlwTOBoIQOsoAoQiqfJhK0LI8BRzIC0UAE4U/nCPrguu1NZmAEXA44N9jAwNUIAAAAASUVORK5CYII=";
        if (modelId_ == 22) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEyuN0aBJUMAAABXE0FsAln6AAAAAXRSTlMAQObYZgAAAI5JREFUSMftjkESgzAIRTN6gYJeIJQDxOYCmub+ZyqRjl1gdNMlf5XJfzwIwePxeDyeP2bMN/WCl/0CMF0B0sPDfqdDID2YOv+kIiAjaFP5eOLTCGQofgkRzMkAGIF4J5qr2AtJvFQhKfA+BQC5TrphtcArCkG86YbUAZBL7wQFgEpvQxgUqKEJzoBxB5A/81IQFUnaqVsAAAAASUVORK5CYII=";
        if (modelId_ == 23) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAGFBMVEVHcEytpsMAAACBeZdmX3ff2PWHgZo3w+b7ejuAAAAAAXRSTlMAQObYZgAAAJRJREFUSMftkLsRxCAMBRk6eB7IERXcQAfGDRDQwJVw/Qcn8CexbCcO9SIN2llJGKPRaDQazYux8aFN822f4NIdQEAJ5+fjyUISxPg9BE0QWJS8LW59FQSEJW8EeWkDqm4n+gRh8Yal5BxWNkmXDUVagSABHo4V48giA7Xv2QE3mwuAFVxN8SN9P9DACi6m3wUwZvwBWTEVY0Zi6eEAAAAASUVORK5CYII=";
        if (modelId_ == 24) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEyQz/EAAABirNVGjrSO1hO9AAAAAXRSTlMAQObYZgAAAIdJREFUSMftkMERgCAMBBkr8IQCkAqU2IH0X5MBHH0E8OMz92K4ZYfEGI1Go9FofswUPurVDvsVWEYA95jltX8E3EPU4ZWygIQgvwrP0UYhwJHoJlhgvQTgbiK7yDQAuJPgKxCbANK5L3VG3x6dFXsR2A6ARFQA11leVvS2WLfHivKZrQs4ugD11Q6veTkhzgAAAABJRU5ErkJggg==";
        if (modelId_ == 25) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEyrmKuAcYgAAABiVWXkte+CAAAAAXRSTlMAQObYZgAAAKxJREFUSMftkMGRwzAIRTWjBvZjFxCwCzAiBUSK+q8p+JKLWLuA6J004g3wSWkymUwmv0K+FY4bQbdbwexqgDEpXQnChOVCKGCSv/H/u/kTEBnKdja197nBDuOhQQaq5VPKvkAZYwJorKuP0QqSIxaoefpSyYKMADUhQbJeN2yRIGyKNZXVhUeU3SFp/iCmIxZkYSQFYw+vh87FBRjwiu7PkL4Ip6pG/wjUYfsHy5MWCzVLEawAAAAASUVORK5CYII=";
        if (modelId_ == 26) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEzh2/4AAACvqMWBeZe7iEgaAAAAAXRSTlMAQObYZgAAAIRJREFUSMftkMsRgCAMRBkrcMUCMBWo2ABj+q9JPn4ORLx4zJ4y7GM3E2NUKpVKpfpRHX3Yk236EzC0gOijr5/dHRB9VDY9oWJA+kXPWG8AWF7oAqwTgJE50Al4IyV4ZriywioBiQgFEBry5nbbh9LwAsAz8uTNK7Dkhlk6P3JHaAPY9gPF6A72xeJpTwAAAABJRU5ErkJggg==";
        if (modelId_ == 27) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEVHcExMelUxYlYAAAC41KQ2VFOCG9OwAAAAAXRSTlMAQObYZgAAAKJJREFUSMftkM0NwyAMRpFYIJ9LBjAqd1CyABYLFCn7r1KIolyw0kuPvCN+fP4xZjKZTCaTP2K3H+VEj/VU8utJ2AuwjM/xDsgMDOUNd+guPAZYEF+DW0c8TgDAX0YS4jgKBDqwnQFZmaAJDuGDeHaAsqPzjhF67yQeUVmd34y1oncgVZBuHGxsaYJ2PEETgjepEC3a+TOYaa3GsdeF9pGE6hc/fRLnmK31fQAAAABJRU5ErkJggg==";
        if (modelId_ == 28) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAGFBMVEVHcEz76Mf5rl3Jup8AAADHi0qdi2ygbDNTUjLLAAAAAXRSTlMAQObYZgAAAKZJREFUSMftkLEOwiAQQG/oB3gS3Xuxuw2GmVB+QCJxNamBLyD9fSkDDtC6OPJG7uXdBYBGo9FoNP5Ip3+M1XN3rsg+9gRFAx7KZ5kDRIjFWB8v30DPikCHaHQOsFsRQD6egs4BWQicc7ekxnqBgKrgA8lV6Nm7JiCbFxMPVQNWNsCEiCImYuC+KTAXTBIqJ8A0RkF4kzZca98fBeTeAtnz/NoUXPgApYQbuw7ZbB4AAAAASUVORK5CYII=";
        if (modelId_ == 29) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEyauacAAABvloRPd2Suvv3yAAAAAXRSTlMAQObYZgAAAIhJREFUSMftkMsNgCAQRDdW4CIFADYgwQKM0H9NLqB44OPF487JMI83QQAOh8PhcH7MZD5qvQx7jShGAPU418eqCKjHqjavlAS2EsRbpnzKsxJQ76x5BLtqAcEnR3QFaAEYnFW9BVgIkN6J3gKstyIvtACbFBnw0AFIERfk1vr9DpMiPefoAugvbOIQBr8uAtgAAAAASUVORK5CYII=";
        if (modelId_ == 30) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEz////GvuYAAACZkbrHNHLoAAAAAXRSTlMAQObYZgAAAIdJREFUSMftkMENgCAMRUlYwCIDmOoAGBYwyP4z2ULQQxEvHvtPhP/yKDVGo9FoNJofY+NHvbthvwPMI4B6mOR1uAXUg6jjIyUBCoFFxHgLHAoBYmoECbYgAIDcHAQk0wEKEQrgzy7AxFqB0P+6pzHKjOkFYAUDPr0sjxXlhaW3fqgKPuRjAFzMpRCstvpC4AAAAABJRU5ErkJggg==";
        if (modelId_ == 31) return "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVHcEyibT8AAACCTyJuPBWaXkYyAAAAAXRSTlMAQObYZgAAAIdJREFUSMftkMERgCAMBBkr8IQCkAqU2IH0X5MBHH0E8OMz92K4ZYfEGI1Go9FofswUPurVDvsVWEYA95jltX8E3EPU4ZWygIQgvwrP0UYhwJHoJlhgvQTgbiK7yDQAuJPgKxCbANK5L3VG3x6dFXsR2A6ARFQA11leVvS2WLfHivKZrQs4ugD11Q6veTkhzgAAAABJRU5ErkJggg==";
        
        return "";
    }
}