// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: BAF Designs Varsity Club
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd    //
//    MO;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:0M    //
//    Md                                                                                                                                                                                                                                                                                                       .kM    //
//    Md    .:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;.   .xM    //
//    Md    lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:   .xM    //
//    Md    lWMMXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMMN:   .xM    //
//    Md    lWMMd                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                          ............................                                                   ......................                                                    .........................................                                         .OMMN:   .xM    //
//    Md    lWMMo                                        .ol::::::::::::::::::::::::::;;;;::,.                                           ,dc::::::::::::::::::::;;:,.                                              ,dc::::::::::::::::::::::::::::::::::::::ol.                                       .OMMN:   .xM    //
//    Md    lWMMo                                        ,o..looooooooooooooooooooooooolc::::cc.                                         :l 'oooooooooooooooooooc:,:o'                                             :o.'oooooooooooooooooooooooooooooooooooc.,o.                                       .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,;l:.                                       :l.lMMMMMMMMMMMMMMMMMMMMWO,,o,                                            :o.oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,,o.                                       .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.cl.                                      :l.lMMMMMMMMMMMMMMMMMMMMMM0,'o,                                           :o.oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,,o.                                       .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.o:                                      :l.lMMMMMMMMMMMMMMMMMMMMMMM0,'o,                                          :o.oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,,o.                                       .OMMN:   .xM    //
//    Md    lWMMo                                        ,o..:ccdXMMMMMMMMMKocccccclOWMMMMMMMMMk.co                                      :o..ccccl0MMMMMMMX0XNMMMMMMM0,'o;                                         :d..cccdXMMMMMMMMM0lccccccccccccdXMMMMMK,,o.                                       .OMMN:   .xM    //
//    Md    lWMMo                      .;.               .lc;:l'.OMMMMMMMMMx.'l;,:l.,KMMMMMMMMMk.co               .;.                    ,l:;co'.cXMMMMMMXc.'dWMMMMMMM0,'o;                        ,'              'o:;;l'.OMMMMMMMMMo ,c;;;;;;;:c..cdddddl.,o.               ',                      .OMMN:   .xM    //
//    Md    lWMMo                      ,0o                   .dc.OMMMMMMMMMx.:x:;cx;,KMMMMMMMMX:.o;               cK:                       .oc.oNMMMMMMNl....xWMMMMMMM0,'o;                      'Od                  .oc.OMMMMMMMMMo.lo''''''';kkl:;;;;;;;ll.              .xk.                     .OMMN:   .xM    //
//    Md    lWMMo                .:c;'.xW0;.,:c,             .oc.OMMMMMMMMMO,':ccc:'lNMMMMMMWO;'o:          '::,.,OMk'.;::.                .o:.dWMMMMMMNl.lkx;'kMMMMMMMM0,'o;               .:c;'.dWK:.,:c,             oc.OMMMMMMMMMo 'c::::::::coOl........           ,c;'.cXNl.';c;.               .OMMN:   .xM    //
//    Md    lWMMo                 'oKNXWMWXXXk;              .oc.OMMMMMMMMMWXXXXXXXXWMMMMMKx:,:l,            ,xXXXWMWXNXx,                'o;'kWMMMMMMNl.:xdkd.'OMMMMMMMMK;'o,               .lKNXNMMNXNO:.             oc.OMMMMMMMMMKxxxxxxxxxxx;.c:                   .:ONXNMMNXN0l.                .OMMN:   .xM    //
//    Md    lWMMo                   cXMMMMMWx.               .oc.OMMMMMMMMMMMMMMMMMMMMMMMWx'.,oo'             .dNMMMMMNl                 ,o,,OWMMMMMMWk;';::::,'oNMMMMMMMMK;'o;                ;KMMMMMWk.               oc.OMMMMMMMMMMMMMMMMMMMMMo.c:                     '0MMMMMMK,                  .OMMN:   .xM    //
//    Md    lWMMo                 .oKNNWMMNNXx;              .oc.OMMMMMMMMMXxdddddddONMMMMMN0d;;lc.          ,xXNNWMWNNXd'              :o';0MMMMMMMMMWNNNNNNNNNNWMMMMMMMMMK;'o;             .l0NNWMMNNNk;              oc.OMMMMMMMMMN00000000000c.c:                   .cONNNMMWNN0c.                .OMMN:   .xM    //
//    Md    lWMMo                .:c;''xMK:';:c,             .oc.OMMMMMMMMMx..c:::c..kMMMMMMMMNd.:o.        .cc;';0Mk,';c:.            cl':XMMMMMMMWNNNNNNNNNNNNNNNWMMMMMMMMK;'o;           .:c:,'dWXc.,:c,             oc.OMMMMMMMMMx.':;;;;;;;;,,d;                  .;c:,.lNNo.,:c;.               .OMMN:   .xM    //
//    Md    lWMMo                      ;Ko                   .dc.OMMMMMMMMMx.cx'.'xc.xMMMMMMMMMWd.ll              lK:                .ll.lXMMMMMMMWx;;::::::::::::,lXMMMMMMMMK;'o:                '0d.                 .dc.OMMMMMMMMMo.cd;;;,,,,,,,,.                        .kk.                     .OMMN:   .xM    //
//    Md    lWMMo                      .;.               .c:,;l'.OMMMMMMMMMx.'l,,,l'.xMMMMMMMMMMK,;d.             .;.           ;l;;;c;.oNMMMMMMMWk..coko;;;;;:xdl' cXMMMMMMMMK;'c:;;:o,           ;'              'oc;:l'.OMMMMMMMMMo ,c;;ll.                                ,,                      .OMMN:   .xM    //
//    Md    lWMMo                                        ,o..:c:oXMMMMMMMMMKl:c::::cdXMMMMMMMMMMK,;d.                           c: ,lclkWMMMMMMMMNkcl'.o:     .l,.:loKMMMMMMMMMKocll'.oc                           :o..clcdXMMMMMMMMM0lcl:.;x'                                                        .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.cl                            l:.kMMMMMMMMMMMMMMMMMo.l:     .l,,KMMMMMMMMMMMMMMMMMd.oc                           :o.oMMMMMMMMMMMMMMMMMMX;;d'                                                        .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx';o.                            l:.kMMMMMMMMMMMMMMMMMo.l:     .l,,KMMMMMMMMMMMMMMMMMd.oc                           :o.oMMMMMMMMMMMMMMMMMMX;;x'                                                        .OMMN:   .xM    //
//    Md    lWMMo                                        ,o.:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:,ll.                             l:.kMMMMMMMMMMMMMMMMMo.l:     .l,,KMMMMMMMMMMMMMMMMMd.oc                           :o.oMMMMMMMMMMMMMMMMMMX;;x'                                                        .OMMN:   .xM    //
//    Md    lWMMo                                        ,o..oddddddddddddddddddddddddddolc:::cc,                               c: :ooooooooooooooooo,.l:     .l,.cooooooooooooooooo,.oc                           :o.,ooooooooooooooooool.;d'                                                        .OMMN:   .xM    //
//    Md    lWMMo                                        .ol:::::::::::::::::::::::::::;;;;;:;.                                 :l,,;;;;;;;;;;;;;;;;;,:o,     .cc,;;;;;;;;;;;;;;;;;;,:o,                           ,dc;;;;;;;;;;;;;;;;;;;;;lo.                                                        .OMMN:   .xM    //
//    Md    lWMMo                                         ................................                                       .......................        .......................                             ........................                                                          .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMo                                                                                                                                                                                                                                                                                     .OMMN:   .xM    //
//    Md    lWMMKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkNMMN:   .xM    //
//    Md    lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:   .xM    //
//    Md    .:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;.   .xM    //
//    Md                                                                                                                                                                                                                                                                                                       .xM    //
//    Mk,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';OM    //
//    ollcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclcllo    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BAF is ERC721Creator {
    constructor() ERC721Creator("BAF Designs Varsity Club", "BAF") {}
}