// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: mark mcneill
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    ooooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooolllllllllllllccccccccccccccccc::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::    //
//    oooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooooooolllllllllllllllccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::    //
//    oooooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooooollllllllllllllllllccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::    //
//    ooooooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxxdxddxxddddddddddddddddddddddddoooooooooooooooooooollllllllllllllllcccccccccccccccccccccccccc::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;::::::::::::::::::::    //
//    oooooooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddoddddddddddxdddddddddddddddddddooooooooooooooooollllllllllllllllllccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    oooooooooodddddddddddxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddol::ccldollllooddxxxdddddddddddddddddddddddooooooooooooooollllllllllllllllllllllccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    ooooooooooodddddddddxxxxxxxxxxxdddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdolol::cc;'';:ccllc::cc;;ldxdodxxxddxddddddddddddddddddddooooooooooooooooollllllllllllllllllllllccccccccccccccccccccccc::::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    oooooooooooodddddddddxxxxxxxxxxxddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdlcc:;,,,,,;;;'',:::;;::;;:;'.;loccoxxdddxxxxxxxxdddddddddddddddddooooooooooooooooooooolllllllllllllllllllccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::    //
//    ooooooooooooddddddddddxxxxxxxxxxxddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc:,.....'',,,,,,''',,,,;;,',,'.'',;:coxddddxxxxxxxxxxxxxxdddddddddddddddoooooooooooooooooooooooooolllllllllllllllllccccccccccccccccccccccccccccc::::::::::::::::::::::::::::::::::    //
//    ooooooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl;'......'',,,,'''..'''',,,,'....'''..,:oollooxxxxxxxxxxxxxxxxxddddddddddddddoooooooooooooooooooooooooooooolllllllllllllllllccccccccccccccccccccccccccc::::::::::::::::::::::::::::::    //
//    oooooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxo:,......'''',,,'.....''''''''.....'''..',;:::loxkxdxxxxxxxxxxxxxxxxdddddddddddddddddddddddddooooooooooooooooooooooooolllllllllllllllllllllllllccccccccccccccccc::::::::::::::::::::::::    //
//    ooooooooooodddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddxddo:'.......''''''''...''''''''............'''',;:lxkxddxxkkkkxxxxxxxxxxxxxddddddddddddddddddddddddddddddddooooooooooooooooooooolllllllllllllllllllllllllccccccccccccccccccccccccccccccccccc    //
//    ooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdxkdlll:,........'''''.......''...''....''........'''..',:ldddxkkkkkkkkkkkxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooollllllllllllllllllllcccccccccccccccccccccccccccc    //
//    ooooodddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdxkdlol:c:'........'''''..............................''...'',,coxdxxxxkkkkkkkkkkxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddddddoooooooooooooooooooooooooollllllllllllllllllllllllllllllllll    //
//    dddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkxlcol;:c;;,.........''''.....................................'''',;coxkxxkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddooooooooooooooooooooolllllllllllllllllllooooooo    //
//    dddddddddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOkxddc,,'.',''....................................................''''.':oxdoxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddoooooooooooooooooooooooooooooooooo    //
//    dddddddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOd:;:c'............................''''''..........................'.....,clclxkOOkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddoooooooooddddddddddddddd    //
//    dddddddxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl,..,'...................',,,;,,,;:::::;;,;;,''''''......................';;;lxkkOOOOOOOkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddxxxxx    //
//    xxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxdc'..................',,,;;:ccccclooooooolcllccccccc;,''''..................''lxkkOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddxxxxxxxxxxxxxxxxx    //
//    xxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxl;................',,;:ccclloooodddddddddoodooooooolccccc:;'''................:cokOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    xxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000OO00OOkxdo:.............',;;::cclllodddddddddxxxxxddddddxddddddooollcc:::;,'...........,,cxkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    xxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000Oxdllc'..........',;;:cccccclodddddxxxxxxxxxxxxkxxxxxxxxxxddddddooollcc:,..........':oxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxkkkxkkkkkxxxxxxx    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000Okdo:,,,........',;;:::ccclloodddddxxxxxxxxkkkkkkkkkkxxkkkxxxxxxxddddddolc:,..........':clddxkOO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxkkkkkkkkkkkkkkkkkxxxxxxxx    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000000000Oko:,'........',;;:::ccclllooodddddxxxxxkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxdddolc;'...........'cldkOO0000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxx    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000Oxl;........,,;;::::ccclllooodddddxxxxxkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxddddoolc,...........'cxOO00000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxx    //
//    kkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000000000000000x:'......',,;;::::cccllooooddddxxxxxxxkkkkkkkkkxxxkkkkkkkkxxxxxxxxxxxxxdddollc;'.........;dkO0000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    kkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000Oo;'....',;,;;:::::cclllooodddxxxxxxxxxkkkkkkkkkxxkkkkkkkkkkkkkxxxxxxxxxdddoollc:,........;okkOO000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    kkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000000KKKKK0kc,'',,;:;;;;;;:::ccclloooddxxxxxxxkkkkkkkkkkOOOOOOOOkkkkkkkkxxkxxxxxxxddxddooolc:;.......';lkO0000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    kkkkkkkOOOOOOOOOOOOO00000OO0000000000000000000000000000000000000000000000000000000KKKKKK0kl,'',;;;;;;;;;;;::cccllllooodddxxxxxxkkkkkkkOOOOOOOOOkkkkkkkkkkkxxxxxxxxxxdddddolcc:'......,lkO0000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    kkkkOOOOOOOO00000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKK0kl,,,;;;;;;;;;;;;;::c::ccccllooddxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkxkxxxxxxxxxxddddoollc:'.....':oO000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddd    //
//    OOOOOOOOOO000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKOo:;;,,;:::;;;;;;::::::::cccloooddxxxxxxxkkkOOOOkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxdddddollll:,.....,lk000000000000000000000000000000000000000000000000OOOOOOOOOOOkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxddd    //
//    OOOOOO000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKOl;,,,;cc::;;;;;:::::cccccclllooddxxxxxxxkkkkkOOOOOOOOOOkkkkOOkkkkkxxkxxxxxddddddddoolllc:,''..'lk00KKKKKKKKKKKKKK00000000000000000000000000000000000OOOOOOOOOOkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    000000000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKk:,,;cccc:;;;;;;::::cccccccllooddxxxxxkkkkkkkOOOOOOOOOOOkkkOOOOkkkxxkkkxxxddddddddoooollcc:,'..'lOKKKKKKKKKKKKKKKKKKKKK00000000000000000000000000000000OOOOOOOOOOOkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    000000000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKXK0d,,::ccc::;;;::;::::cccclllloodxxxxkkkkkkOOOOOOOOOOOOOOkkOOOOOkkxxkkkkkxxddddddddoooooollol;,''':x0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000000OOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKK000000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKX0d;,;::::::;;;:::::::cclllllooddxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOkkkkkkOkkkxxxdddddooooooooolol:,,,,,cOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000000OOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    KKKKKKKKKKK000000000000000000000000000000000000000000K00000KKKKKKKKKKKKKKKKKKKKKKKKKKK0o;;::cc:::;;;::::::cccllllllooddxxkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkkOkkkkkkkxxxxddddooooolllooc;,,,;lOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000000000000000OOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOkkkkOOOO    //
//    KKKKKKKKKKKKK000000000000000000000000000000000000KKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKXKOl:::ccc:::;;;:;:::::::::::::::::ccloddxkkOOOOOOOOOOOOOOOOOkkkxxxxxxxxxxxxxxxxxdddooooolllllc:;;;:o0XXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    KKKKKKKKKKKKK0000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKOl::::cc:::::;:;;::;,,''''.........',:cldxxkkkkkkkkkkkkkkkxxdollllccccccllloodddddoooolloloollc;;:oOXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000000000000OOOOOO000000000000OOOOOOOOO    //
//    KKKKKKKKKKKKKKK000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXOl:::ccc:;;;;;;;:;,'...........''',,;::cloddxxkkkkkkkkkxxddolc:;;,'......',;:cclddoooollooooollc:cx0XXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000000000000000000000    //
//    KKKKKKKKKKK00KKKK000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXX0o:::ll:;;;;;;;;,......';::ccllllllllllcccloodxkkkkkkkxxdolcccc::;,'.........',;codollooooooolllllxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000000000000000    //
//    KKKKKKKKKKKKKKKKK00000000000000000000000000KK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXOl:cllc;;;;;;,,'.....,;coooddxxxxxxxxddolcclodxkkkOOkkxdolllllooolllllcc::;,'..',:lolloddoddlcclloOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000000000    //
//    KK0000000KKKKK00000000000000000000000000000KKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXX0occll:;;;;;;,'...',;:cloolcc:::::::ccooolcclddxkkkkkkxdolooddxxxdddoodxxdollc;'.',:cllodddddlclod0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000000    //
//    0000000000000000000OOOOOOkkkkkOOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXX0oclolc;;;;;,'''',,,;::;,'....','..''',;cllccoddxkkkxxdooooddoc:;;;,'',:cloddol:,'.,:llodooooloodx0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000    //
//    000000000000000OOOkkkkxxxddddddxxxxkkkkOOOOO00000000KKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXX0xllll:;;;;;,,,,,;;,,,....,;'.''',;:,',;cllc:cloxxkkxxolllll:,''''..,'.....,:clc:,'';clooooooooddx0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000000    //
//    OOOOOOOOOOOOOOkkkxxddoolllcccllllloodddxxxkkkOOOOO00000000KKKKKKKKKKKKKKKKKKKKKKXXXXXKOololc:;;;;;,,;;;;,,'..',;:c:;,',:clc:clolc:::lodxxxxdollodo:,;clc,.'...,;'...;::;,,;coooooodddddx0KKXKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000000000000000000000000000000000000OOOOO    //
//    xxxxxxkkkkkxxxxddollc::;,,,,,,,,;;::cclloooddxxxkkkkOOOOO000000000000000KKKKKKKKKKKKKkl:lolc:;,;;;;;;:::;,,;:cccclllloooollloool::::codxxxxdolloddolccllc;;,,;llc:,'',::c::cloooooodxxxxOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    oooooooooooooollc:;;,'.............'',,;;::cllloodddxxxkkkkkkkkkOOOOOOOO000000000000xc:clllc:,,;;;::cclcc::cooooddxxxddddooooolc::::coddddxdlloooddoollllloooodddddl:;:collllooooodxxxxkOOOOOOOOOOOOOOO000000000000000000000OOOOOOOOOOOkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkkkk    //
//    ;;:::::::::::;;;,''......................'',,,;;:cclloooodddddddddxxxxxkkkkkkkOOOOOd;',:collc,,;;::clllllcclloddxxxxxxxxdddddolc:c::codddddollooodxddddoooooddddxxxddoooddooooooodxxxkxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdddddddoooooooooooolllllllllooooooooooodddddddooooooooooooooooddddddddd    //
//    ....'''''''''...................................'',,;;:::cccccccclllloooodddddddddoc;;;;codo:,,,;::clllllollloddxxkkkkxxxxxdollccc::coddxxddoloddxxxxxxxxxxddddxxxxxxddddddoooooooxkkxdololccccccclllllooooddddddddooooooooooollllllcccccc::::::::::::;;;;;;;;;;;;;:::::::::cccccccc::::::::ccccccccccccccll    //
//    ......................................................''''''',,,,,,;;;:::ccccccccccccc::cool;,,,;:ccclloodddodddddxxxxxxxddoolcc::::clddxxddollodxxxkxxdddxxxxkkxxxxxxxxxxddooloodxkkxc,,cc;,;,;;;;;;;;:::::::::::::::::::;;;;;,,,,,,,,''''''..............                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract mcn is ERC721Creator {
    constructor() ERC721Creator("mark mcneill", "mcn") {}
}