// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: seven towering into
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//     in accordance with the trajectory of the three steps of the plane trees scattered around, forming the mountain to protect the spirit of the great array to lock the spirit machine. After more than 200 years of cultivation, the original second-order inferior quality spiritual pulse in the peak has been cultivated into the second-order middle quality spiritual pulse. Reiki is far more abundant than beyond the mountain.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//    And the Lord of this Fengshan, it is border state one of the four real Fu family.                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//    Fu Eleven sat on the futon on the stone terrace of the Green plum Pavilion.                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STI is ERC721Creator {
    constructor() ERC721Creator("seven towering into", "STI") {}
}