// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Andy K Bradburn
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMWWWMMMMMMWWWMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNkc:l0WMMMMMMMMMMMMMMMMMMMMMMMKocxNMMMMMMMMMMMMMMMMMXo:dXMMWKo:cxXMMMMMMKo:::::::clxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMKocxNNxcoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWk.   :KMMMMMWWWMWNNWMMMMMMWNNWk. :KWWWMMMMMWWWMMMMMM0' ,OWKo. .oKWMMMMMWO' .;cccc;. ;0WMWWWWWNWMMWWNNNWMMMMMMWNNNO' :KX: 'OWNNWMMMMWWWMMMMWWWMMMWWWWNWWWWWMWWNWWMMMMMMMMM    //
//    MMMMMMMMMWO, ';..cXMMMKo:loc;,:xXMWKd:,;c;. :0k:cOWMWkccOWMMMMM0' 'xd' .l0WMMMMMMMWO' 'kNNNXk' 'OWXd:cc;;dKOl;;;;:xXMWKd:,;:;. :KX: .:c;,:dKWWk:cOWMXd:oXWOc:l:,lOx:col;,;o0WMMMMMMM    //
//    MMMMMMMMMK: .kKc .oNMMO' .:do, .xN0; .cdo'  :KO' ;0W0, ;0MMMMMM0'  ..  ,OWMMMMMMMMWO'  .,,''. .oXMK;  'coO0o;:oo, .dN0; .cdo'  :KX:  ,odc. ;0Xl .dWMK; '0No. .:lx0l  'od:. :KMMMMMMM    //
//    MMMMMMMMXl. 'lo:. .xWMO' ,0WWd..oXd. cXMWx. :KNx..lOc..kWMMMMMM0'  .cc. 'xNMMMMMMMWO' .cddddl,..dNK; .xWMMNOolc:'  lXd. lXMWx. :KX: .kWMXc .xXl .dWMK; '0No. lNMMNl .dWM0, ,0MMMMMMM    //
//    MMMMMMMNd. .',,,.. ,0WO' ;KMWd. lXd. :KWNo. :KMXl..,..oNMMMMMMM0' .xWNk' .oXMMMMMMWO' 'ONNNNXo. ;KK; .OMMNx..;dkc. lXx. :KMNd. :KX: .dNWK: .xXl .oNWO' '0No..oNMMNl .xWM0, ,0MMMMMMM    //
//    MMMMMMWO' 'kXNNNKo. :KO' ;KMWx..oNXl..,c:'  :KMMK:   :KMMMMMMMM0' ,0MMWO; .:0WMMMMMO'  ',,;,'. 'xNK: 'OMMNd. 'll,  cXXl..,c:'  :XX:  '::,..lXWk. .:c;. '0No..dNMMNl .kWM0; ,0MMMMMMM    //
//    MMMMMMW0ooOWMMMMMXkodKXxokNMWKdo0WMNOoccdkdoONMMNd. ,0WMMMMMMMMNxoxXMMMWKdld0WMMMMMXxlllllooodkKWMNkoxXMMMNOocldxdokNMNOoccdkdoONNOoxkdlcoONMMNOoccokxoxNW0dd0WMMW0odKMMNkokNMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd:..'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxllxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkcclkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMNOo;..lXMMMMMMMMMMMWMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMWWWMMMMMMMMMMMMWWMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWKdlxXMMMMMNOooOXkodKMMXxlkNMW0dcclxxldKMMW0, .oNMMMMMMMMW0ookOOkxdlclxXMMMMMWOollllcllldkXWWKdlONMMWKdccldxooOWWKxlcldxoo0WXxoxxlcco0NMMXklccdxdlkNNOodXMMMNkldXMMXxlkNMMMMMM    //
//    MMMMMMMK: .oKXXXXx. 'OK: .kWM0, ;KNd..'ll;. .kWMNo.  .xWMMMMMMMNo. '::;,.  .c0WMMMMNl  .;::::'..;0Nx. cXMMK: .cdl' .dNk,..co:. .dNO' .;ll,..dNXl. ,ol,  :XXc .kWMMK: 'OMMO' :XMMMMMM    //
//    MMMMMMMWO,  .'''.. .xWX: .kWM0, ;00' 'OWW0, .kWWx..''.,0WMMMMMMNl  ....    ,cxXMMMMNl .lXWWWW0: .dNx. cXMMXl..cxd, .kKc .xWMXc .dNO' ,OWM0, ,OK; .kWWx. :KXc .kWMMK: .OMMO' :XMMMMMM    //
//    MMMMMMMMWx. .lxl. .oNMX: .xWWO' ;KO' ,OWM0, .kW0, ,Ok'.cXMMMMMM0;         .;lok0KNMNl  'loool;..:0Wx. ;0WWWXkool:. .xK: .xWMXc .dNO' ,0WM0, 'O0; 'OWWk. :KXc .dNMMK: .kWWk. :XMMMMMM    //
//    MMMMMMMMMNo..lKo..cKMMX:  ,oo; .lXNo..,oo;. .kKc .xWNo..dNMMMMNk'        ..,:::coxKXl  .,;;,'. ,OWWx. .;cd0O:,coc. 'ONx' 'ldc. .dNO' .;oo;..oXK; 'OWWk. ;KXc  .:lk0:  ,oo; .oNMMMMMM    //
//    MMMMMMMMMMXc..,. ;0WMMNxcldo:;:dXWMNOl:;cl' .k0ocxNMMXdcdXMMMMWk,         .....,:ldx;  :0XNNXo. cXW0ocol:cOXkl:;;:o0WMW0o:;:l; .dNO' 'lc;;lONMXxcoKMMKocxNNkcloc:d0xcoxo:;:xXMMMMMMM    //
//    MMMMMMMMMMM0;   ,OWMMMMMWMMMWWWMMMMMMMWWWX: .kWWWMMMMMMWWMMMMMM0,    ...   ..  .,;:;.  .'::::. .dNMMMMMWWWMMMMWWWWMMMMMMMWWWNo..oNO' :KWWWMMMMMMWMMMMMMWMMMMWMMWWWMMWMMMWWWMMMMMMMMM    //
//    MMMMMMMMMMMW0lclOWMMMMMMMMMMMMMMMMMMMMMMMNkldKMMMMMMMMMMMMMMMMMXl'.....''..''.......   ...',:ld0NMMMMMMMMMMMMMMMMMMMWWMMMMMMWOoo0WXdlkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0KXWMMMMMMMMMMMMMWKdc;'....,:llc:;'..  .',;cclxKWMMMMMMMMMMMMMMMMMWN0OkkOKNMMMMMMWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWXkocccokXMMMMMMMMMMMMMWKkoc;'...';cclllc;'.....',:ldO0KNWMMMMMMMMMMMMWKdl:;;clxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxddddoc;,,coOWMMMMMMMMMMMMMMWKko:,.....';clolc;.. .',;cc:cldONMMMMMMMMMMW0dc;'..':lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxoc:;,,;:llc:clxKMMMMMMMMMMMMMMMMMN0dl:;'....;coolc,......'...;co0WMMMMMMMMNOoc,.  .':oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dc;'... .,:odk0KNMMMMMMMMMMMMMMMMMMWN0xolc;...';clllc:,.....  .;cd0WMMMMWWN0xl:,..  .;cdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl;'.....';cldOKNMMMMMMMMMMMMMWNXK0Okxol::;,'...';ccclllc::;.. ';coxO0KKOxddl:;'..  .,:lkNMMMMMMMMMMMMMMMMMMMMMMMMMNK0OO0XWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxl:;,.....';::::cokKWMMMMMMMMMN0kdllc::;,'........'''..';:lll:,. ..';;:cclc:;,'.......':lxXMMMMMMMMMMMMMMMMMMMMMMMMMXklc::coONMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oc;,'...........':lkNMMMMMMMWXkl:;'..........''''........';clc:,'........''..  ..''...,:ld0WMMWX0kkk0XWWXK0KNWWWWMMNkl:,..,:oOWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdl:,...'...  ..,cldkOKNWMN0kdlc,. ....''''........';:;,...'',;;::;,'.....  ....;:;.  .';cd0XKOoc:::cdkxoccloxxxxO0koc,....;cdKWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc;...,;;'. .':cc::clxKXklc:;,...';cc;'......',;:lodoc;'......';;,'''.....,;;:cc;.   .;coooll:,..';llc;'.,::;;:cll:,.....':lkNMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:'..,:c:,...'''..':lxOdc;,''. .,cl:'...,:ccldxOKXNKkdl:;;,'..........';cldkkxo:,.  ';cl:,','. ..;c:,. ..,,...,;,....'..':lkNMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc;'...,::,.....  ';loxdll:;...';c:'...;cok0XNWMMMMMWNKOxdoc:;,''..',;cox0NWWOo:,.  ..,,...........................''...,co0WMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dl;'...';;;,'''. .,;;::::;,. .,cc,..';coOWMMMMMMMMMMMMWNXOol:,,,;:clxOKNMMMW0o:,...........',,......,;,'',;;;'''''....,:okNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkoc;'...','....   ..........':l:'..':lx0XNWWMMMMMMMMWN0kdc;'...,:lxXMMMMMMMXxl;'...''',,,;cllc:cc:clollclll:;'....';:ldONMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoc;'.  .................',:ll:'..,clllloxkOKWMMMMN0xlc:,....,;co0WMMMMMMMWKdc;'.......,;:clloxO0KKOxocc;,.....,:cok0NWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xl:,..  ..;:ccccccccccccclodol;...,::;',;::cokXWWKxl:,'....,:ldkKWMMMMMWNXK0kdlc::;'.......,:cokXNOdc:,.....,:cldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl:,....',:clllc:;;:clx0K0KXNKxl;'. .,'..',,,;cldkkdc;'. ..,:coOXWMMMMMMN0dollodxOOkolc:;,'....':lddl:,...',:coxOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dc;'...';cooolc;'...':lkNMMMMMNkoc;.......,;;,,',;cll:'....;cokXWMMMMMMMWOoc;'',:lxXWNK0Oxoc:,...':ll:'...,coxOXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc;...';coxkdl:,....,:ld0WMMMNOxoc:;,'......''.. .';::;....':lxXMMMMMMMMMNkl:,...,co0MMMMMWXOoc;'..;cc,...;cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oc,. .,coOOdl;'...':ldOXWMMMXxl:,'......'''.......''','. ..':lkNMMMMMMMMNOoc;'...;cdKMMMMMMMNOo:,..'::,..':lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdl:,. .,coxxl;'...;cokXWMMMMNkl:,...''''..',,;;;;,''''..  .';cd0WMMMMMMWNOoc;...';coOWMMMMMMMW0oc,..';:,..':lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:;,'.. .,:looc,. .,:ldKMMMMMXko:,. .,:ccc;'.',::cc:;,''....',;lxXMMMMMN0xdl:;...':lxKWMMMMMMMMWOo:,...;c;...;cxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMN0dl:,.......';clll:,.. .,:oONMMNKxo:,. .':ldxoc,'......''......';:coxXWMMWKxl:;'....';ld0WMMMMMMMMMXxl;'..':c;...;cdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXkl:,....';::ccodol:'.....,:lkNWKxoc:,.  .,co0XOdl:;,'........',;;:::cldk0X0dl;'. ..';::cld0NMMMMMMMWOoc,...;::,...;lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNkl:,...';:lldk0XXkl:'. ..,:ldKNOoc;'... .':lkNMWN0kxdlc:;;;;::c:,.....';:ldol:,.  .',;,'';coOXXXNWMWKdc;'..',,'...;cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXxl;.  .',,;clx0X0dc;'.  ..;lxKOoc,....'...;lxXMMMMWWNX0kxxxxdol:,.     .';cllc,.  ..... .,cloolodO0Odl:'..',,...,:lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXxl:'.     .';codoc;.......;cdkdc;...,;,...,:lkXNWMMMMMMMWNKOdl:,..  ....';cllc,. .''..  ..,,,'',:lol:;'..',,'..':lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMW0dl:,'.     .;cllc;. .';::ldOOoc,'';cl:,. .;clodxO0KXXNNKOdl:,.. ..',:::clddoc,. .';:;,...... .';ll:,'.',,,...':lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWNOdl:;..   .,:clc;...,:ld0NWXxlc:cccc:,. ...'',;:cclodolc;,.....,:cldO00KNKxl;'. .';;,,,,,,...';:;''',:;'...,:okXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMN0xlc;'.....',;,''';:lokOOkdlc:;,'....  .........'',,'.. ..';coxk0NWMMMMWKxl:,.........','...''..';:;...,:ld0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc:,'.    ....'',;::::;,..        .,;:;,.......... .';cokKWMMMMMMMMMWKdlc:;,''''...';;;,,,;:cc;'..';cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,.          .......         .':lll:,..'',,,,'..';ldKWMMMMMMMMWKOdlc:;'........,:loollll:,.. .':lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl:,.  ..     .....''. ......',:lddl:,...':lcc;...';cdONWMMMWKOxoc;,.......',,;:cokKX0dl:'.....;ldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc;. .',;,,;;;:ccc:,.. ..';ccodOXKkoc:;;;:;,,,,'...,:lxOKNXkoc:,'....';::clodddddkOOxoc,.....':lkXXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl;...':loddxxoll:,.....';cokXNWMMWXOxdol:'..';:;'..';cloool:,...',;:cok0KXKOxolc:::ll:'.....':looolod0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxl;...,:oONNXOoc;'...,::cox0NMMMMMMMMWNOoc;'';cll:,...,;,,,,'..';coxO0XWMWKxl:;'...':l:'..'....',,,';coONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl;...,:o0NKxl:,...';cdkKXWMMMMMMMMMMMMWKxollooolc,. ........',:lxKNMMMMMXxl:'. ..';cl:,...,'.......':ldOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:'..':lkOdc;'...':lxKWMMMMMMMMMMMMMMMMMWNXXXOoc;....,;;,'';cldONWMMWX0kxo:,...,:coxdl;...''''''...,:ccccokXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOo:'..':looc;...';cokXWMMMMMMMMWNKK00KXWMMMMMW0oc,....',;;:cld0NWMMMW0dc:;;'...,cokXKxl;'................,:lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0oc,...;cll;...';lxKWMMMMMMMMWXkdlccccokXMMMMM0oc,.     ..,:lxXMMMMMXxl;'....';coONW0oc,...,;::;,'..... .';ldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoc,...;cl:,...;cdKWMMMMMMMMMNxl:,...,:lkNMMMMXxl;'.     ..,cd0WNX0Oxol;'...;coxKWMXxl;'..,:oxkxoc;.......',;:ldONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc;...':lc;...,:oONMMMMMMMMMWKdc;....;co0WWNKK0xoc;'.     .;cdOOxoc::;;,...,coONMWKxl:'..':lxXWN0xl:,........';cdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:'...;lc;'..':lxXMMMMMMMMNKkdl:,...,coOXKkolcccccc;,..  .':lddoc;'.......;cokNWXkoc;'..';ldKWMMMXkoc,.......,cokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc;...,cc;...';cdKWMMMMMMWKxl:;'....,:lkXXdl;,'........  ..;coxdc;...',;;:clx0WWKdl:,...':ldKWMMMMMNOoc;'...';cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oc,...;c:'...;ldKWMMMMMMW0dc;'....,;cokXWKdc;'. ...... ..';coxdl:'..';coxO0KNWXOdc;'..';cokXWMMMMMMMWKkoccccldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOo:'..':c;...,:oOWMMMMMWKxoc;'..';cldOXWMMXxl:'. .,::,'...':lddoc;...';ldKMMMW0dl:,....;cd0WMMMMMMMMMMMWXK00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl;...,::,...;lxXMMMMMNkoc;'....,coONWMWN0xl:,. .';cc;'....';::cc:;,,:coONWMMKdc;'.....;cdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc;...,:;...,co0WMMMWKxl:,...',;coONMWXOdlc;'. ..,,,,''.     ..':lllllodxxxkOkol:;;,...,cdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:'..';;'..':lxXMMWXOdc;'...,:ldOKNNXOdc:,.....',,;::;;.       .';llc::::;;:cccclll:'..,:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc;...,:;...,:oOWWXkdc:,...';coOXX0kdlc:,.....',;;::ccc:,...     .'::,..'...''..',:c:'..,:lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOo:,...;c:'..':lkXKdl:'....,:loxkxol:;'.....'''...............     .,,'..'.  ..   ..,,...,cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:'..';c:,. .;cdOkl:'...,:cllllc:,'......''...................................     ....,:lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oc;...';:,...,coooc,...,clc::;,......,,,'....,;cccccc:::::::::cc:;;'... ...  ...    ..,:lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dc;'...',,'',::cc;...';:;'......';;,'.....,:ldO0KK00000OOOOOO00Oxdlc;'..''...','..';:ldONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl:,..........',,,',,,'....,;::::,....';:lx0NWMMMMMMMMMMMMMMMMMWXOo:,..';,...,:c:clx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dl:,..........;cc:,....,:cc:;'....,:ldkKNMMMMMMMMMMMMMMMMMMMMMWKdc,..';:,...;clokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:;:::,...;clc:,,,;::;'.....,:cdOXWMMMMMMMMMMMMMMMMMMMMMMMMXdc;...;c:,...,:lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                          //
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AKB is ERC721Creator {
    constructor() ERC721Creator("Andy K Bradburn", "AKB") {}
}