// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: H&ART BLOCK Fun
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0OOOOOOO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkkxxxkxxxxxkkkkkkxxxdkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkxxxxkO0KXWMMMMMMMMMMMMMWXdl0MMMMMMWX0OOOO000KKNWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdoxKWMMMMMMMMMMMMMMMMMMMMMMMWdlXMWXkdxxxkkkkxxxxxxdkNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWKxod0WMMMMMMMMMMMMMMMMMMMMMMMMMMMXllkddx0WMMMMMMMMMMMWKooKMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNOddONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,dKWMMMMMMMMMMMMMMMMWdlKMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0oo0WMMMMMMMMMMMWXOkxxxxxkOOKNWMMMMMMMOcOMMMMMMMMMMMMMMMMMMMNdoXMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXdlOWMMMMMMMMMMW0xddxO0KK0Okkxxxxd0WMMMMXldMMMMMMWKkxxxxxxxkOKWXlxMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWOlxNMMMMMMMMMW0xddkXWMMMMMMMMMMMMWklxNMMMWooWMMMNOddk0XNNNK0Oxxdd:lNMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNxl0WMMMMMMMMXkodONMN0OOOOOOOOKXNMMMMKldNMMMdoWMWOod0WMN0kO0Ok0WMNOc:0MMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXooXMMMMMMMMNxoxXMMXOkOKNWWNXK0OkOkOKWMXdl0WWdoWKoo0WMN0xOXWWWKkxONMNxl0MMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMKldNMMMMMMMWOldXMMNOx0NMMMMMMMMMMMMN0kx0WWklkNooklkWMWKxkXMMMMMMMXxkNMWdlXMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMKloNMMMMMMMXdl0WMW0xONMMMMMMMMMMMMMMMMWKxxXM0ldo;cOMMW0xKMMMMMMMMMMNxkWMKckMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXloNMMMMMMMKodXMMNkxXMMMMMMMMMMMMMMMMMMMMW0x0W0l,.lWMW0xKMMMMMMMMMMMMKxKMWdoNMMMMMMMM    //
//    MMMMMMMMMMMMMNx;cKMMMMMMMKlxWMMNkkNMMMMMMMMMMMMMMMMMMMMMMMKd0Wx..kMMKxKMMMMMMMMMMMMMNxOMMkc0MMMMMMMM    //
//    MMMMMMMMMMMNko:;OMMMMMMMNooNMMWkkNMMMMMMMMMMMMMMMMMMMMMMMMMOxX0''0MNkOWMMMMMMMMMMMMMWkkMMkcOMMMMMMMM    //
//    MMMMMMMMMW0odKdlNMMMMMMMklKMMM0xXMMMMMMMMMMMMMMMMMMMMMMMMMMNxONc;XMOxXMMMMMMMMMMMMMMMOkWMOcOMMMMMMMM    //
//    MMMMMMMMNxlOWWooWMMMMMMKlxWMMNxOWMMMMMMMMMMMMMMMMMMMMMMMMMMWkkWocXKx0MMMMMMMMNOOXWMMMOxWMKcxMMMMMMMM    //
//    MMMMMMMNdlKMMXlxMMMMMMWdlNMMM0xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkXddNkkWMMMMMMM0;  .dNMMOxNMNodWMMMMMMM    //
//    MMMMMMWdlKMMMWXNMMMMMMKcxMMMNxOMMMMMMMMMMMMMMWWWMMMMMMMMMMMMWOkdk0xXMMMMMMMX:    ,KMM0xXMMdlNMMMMMMM    //
//    MMMMMWxlKMMMMMMMMMMMMMxcKMMM0xKMMMMMMMMMMMMWO:';dXMMMMMMMMMMMKolxx0MMMMMMMWo     '0MM0xXMMxlXMMMMMMM    //
//    MMMMWxlKMMMMMMMMMMMMMMdoNMMWkkWMMMMMMMMMMMMk.    lXNMMMMMMMMMNd;:xNMMMMMMMK,...  '0MM0xXMMxlXMMMMMMM    //
//    MMMWkl0MMMMMMMMMMMMMMMdlNMMKxKMMMMMMMMMMMM0'     'd0MMMMMMMMMMk.'OMMMMMMMMx..... ;XMM0xXMMxlXMMMMMMM    //
//    MMMOckMMMMMMMMMMMMMMMMxlXMWkkWMMMMMMMMMMMK;      'o0MMMMMMMMMMx.:NMMMMMMMX; ..   cWMMKxKMMxlXMMMMMMM    //
//    MM0lkWMMMMMMMMMMMMMMMMkc0MKxKMMMMMMMMMMMMd. ,'.. ;OXMMMMMMMMMMd,OMMMMMMMMk.     .xMMM0xKMMdlNMMMMMMM    //
//    WOlkWMMMMMMMMMMMMMMMMM0cOMOkWMMMMMMMMMMMNc  .... cXNMMMMMMMMMWxkWMMMMMMMMk.     lNMMM0xXMWooWMMMMMMM    //
//    klOWMMMMMMMMMMMMMMMMMM0ckWkkMMMMMMMMMMMMK,  ..   dWMMMMMMMMMMNk0MMMMMMMMMNd,..;xNMMMM0xNMNldMMMMMMMM    //
//    l0MMMMMMMMMMMMMMMMMMMMOckNxOMMMMMMMMMMMMO.      ,KMMMMMMMMMMMKxKMMMMMMMMMMMNXXWMMMMMMOxWMOcOMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMxcKXx0MMMMMMMMMMMMO.     .kWMMMMMMMMMMM0xXMMMMMMMMMMMMMMMMMMMMMOkWWdlXMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMdlNKxKMMMMMMMMMMMMWOc;,':OWMMMMMMMMMMMM0kNMMMMMMMMMMMMMMMMMMMMWkOMXlxMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMdlN0xXMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMkkWMMMMMMMMMMMMMMMMMMMMXx0Mkc0MMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMdlNOxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl:KMMMMMMMMMMMMMMMMMMMMOxNNldWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMxcKOkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc;dNMMMMMMMMMMMMMMMMMMXx0WxlKMMMMMMMMMM    //
//    MMMMMM0OWMMMMMMMMMMMMMOckkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0kxcc0MMMMMMMMMMMMMMMMMWOxN0ckMMMMMMMMMMM    //
//    MMMMMMdlNMMMMMMMMMMMMMKcx0dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx0x:oxXMMMMMMMMMMMMMMMM0xKWdlNMMMMMMMMMMM    //
//    MMMMMWdoWMMMMMMMMMMMMMKcxNkOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxONc'kOdKMMMMMMMMMMMMMNOxKM0ckMMMMMMMMMMMM    //
//    MMMMMNodMMMMMMMMMMMMMMKcxMOkWMMMMMMMMMMMMMMMMMMMMMMMMMMMXxkNO. ;OOxkXMMMMMMMMWXOxOXMKldNMMMMMMMMMMMM    //
//    MMMMMNldMMMMMMMMMMMMMMKcxMOxNMMMMMMMMMMMMMMMMMMMMMMMMMMXxkN0:.,':ddxkkO00000OkkONW0dokNMMMMMMMMMMMMM    //
//    MMMMMXldMMMMMMMMMMMMMMKlkM0dXMMMMMMMMMMMMMMMMMMMMMMMWXOx0XxlccOodKxddddkOOO0KNMNOodONMMMMMMMMMMMMMMM    //
//    MMMMMXlxMMMMMMMMMMMMMMXlxMXdOMMMMMMMMMMMMMMMMMMWX0OOkkOOdoxxlkWxcKMWXkdxxxkkOkxc:OWMMMMMMMMMMMMMMMMM    //
//    MMMMMXldMMMMMMMMMMMMMMWxcKMKxkKNMMMMMMMMMMMWXOkOOOO00kdokKxlOWMNkox0WMMWK0OOkk0OlkWMMMMMMMMMMMMMMMMM    //
//    MMMMMWooWMMMMMMMMMMMMMMNklxXN0OOOOkOOOOOOOOOOOXXkxxxdxKN0odXMMMMMNOddxkOOk0NMMMMxcKMMMMMMMMMMMMMMMMM    //
//    MMMMMMxcKMMMMMMMMMMMMMMMMXxod0NMWNXXKKKXNWNKOxxdxO0XWW0ooOWMMMMMMMMMN0kkkk0NMMMMXldWMMMMMMMMMMMMMMMM    //
//    MMMMMMKcxMMMMMMMMMMMMMMMMMMNOxxxxxxkkkkxxxxxxOXWMMMWKdoOWMMMMMMMMMMMMMMMMMMMMMMMMxlXMMMMMMMMMMMMMMMM    //
//    MMMMMMWdlXMMMMMMMMMMMMMMMMMMMMWNX00OOOOOKNWMMMMMNOddokNMMMMMMMMMMMMMMMMMMMMMMMMMMkc0MMMMMMMMMMMMMMMM    //
//    MMMMMMMXldWMMMMMMMMMMMXxxXMMMMMMMMMMMMMMMMMMWKkddxk0WMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;lkxxxxxkkkkkKWMMM    //
//    MMMMMMMMKlxNMMMMMMMMMMWKxddONMMMMMMMMMNKOxxxxxx0NMMMMMMMMMMMMMMMMMWNXK00OOOkkxxxxxxkO0KXXNNXX0xodXMM    //
//    MMMMMMMMMKooKMMMMMMMMMMMMW0xddkkkxxxxxxxxOKNWMMMMMMMMMWX0OkxxxxkkkkkxxxxkkkO0KXWMMMMMMMMMMMMMMMOcOMM    //
//    MMMMMMMMMMNklxXMMMMMMMMMMMMMWKOOOO0KXNWMMMMMMMMMWNK0kxxxxkO00KXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlxWMM    //
//    MMMMMMMMMMMMNkod0WMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxxxdxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc;dNMMM    //
//    MMMMMMMMMMMMMMNOdokNMMMMMMMMMMMMMMMMMMMMMNOxxxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xddxkldNMM    //
//    MMMMMMMMMMMMMMMMWKxKMMMMMMMMMMMMMMMMMMW0xdx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxxxONMNOlxWMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkodONMMMMMMWNXK0OkxxkkkkkkxxkkkxxxxkkkkkkkkkkkkxkOKWMWKxdx0WMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkodKWMMMWX0kxxkkkkO0KXXNNNNXKK0KKKKK000OOOOO0KXNWMMMMXkddONMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0odKMMMWKxxxxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK00OxddxKWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdo0WMMNOddkXMMMMMMMMMMWNK0Okxxxxxkkkkkkkxxxxxkkkkxxxxd;oWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklkNMMNkoxKWMMMMMMMNXKOxxxxkkO0KKK000O000000KKXNWWMMMMMWooWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNdoKMMNOoxXMMMMMMWKkxxxxx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxlKMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMXooXMMNxdKMMMMMMWOddkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcOMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNooNMMMWNWMMMMMW0od0WMMMMMMMMMMMMWNK0OkkkkkkkOkkxxONMMMMMMMM0ckMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWxlKMMMMMMMMMMMXdo0WMMMMMMMMMMMXOxxxxxkkOOOOOkkkkOKNWMMMMMMMM0ckMMMMMMMMMMM    //
//    MMMMMMMMMMMWXXMMMMMMMMMMMKlxMMMMMMMMMMWOlkNMMMMMMMMMMNOddx0NMMMMMMMMMMMMMMMMMMMMMMMMMMKcxMMMMMMMMMMM    //
//    MMMMMMMMMMMNoxMMMMMMMMMMMKldNMMMMMMMW0ooKMMMMMMMMWWKxod0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXlxMMMMMMMMMMM    //
//    MMMMMMMMMMMKlxMMMMMMMMMMMMKxxxkO0KXKdlOWMMMMMMMW0dookXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXlxMMMMMMMMMMM    //
//    MMMMMMMMMMMKlkMMMMMMMMMMMMMMWKOkxxxxONMMMMMMMMXdoOXNMMMMMMMMMMMMN0kkkkkxkNMMMMMMMMMMMMNodWMMMMMMMMMM    //
//    MMMMMMMMMMMXldMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoxNMMMMMMMMMMMMXkdxxkOOOkOXWMMMMMMMMMMMMMolNMMMMMMMMMM    //
//    MMMMMMMMMMMWolNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMNOddxKWMMMMMMMMMMMMMMMMMMMMMWooWMMMMMMMMMM    //
//    MMMMMMMMMMMMKldWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdo0WMMMMMMMMMMMMMMMMMMMMMMMMKlxMMMMMMMMMMM    //
//    MMMMMMMMMMMMMKldNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMWNNMMMMMMxcKMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMXdlONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0o0MMMMMNodWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMW0ddxxOO000OOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXldWMMMMMkc0MMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNKOkkkxxxx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlxNMMMMMNooNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdd0WMMMMMWxc0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKWMMMMMMMMMWXkddxKWMMMMMMMOlOMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ddxxkOOOOkxddx0WMMMMMMMMMKlxWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOkxxkO0NMMMMMMMMMMMMNooNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxlKMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXlxWMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HFUN is ERC1155Creator {
    constructor() ERC1155Creator("H&ART BLOCK Fun", "HFUN") {}
}