// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Boicot Customs
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OkkxddoooooooooodoodddxxxxkOXMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMXkdddxxkO0XNWMMMMMMMMMMMMWX0O0XNMMMMMMMMMMMMMMMMNd.;KMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMN0kxol:;,'.....  ...           .....,OMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMO,...,'.....,:lxKWMMMMMW0o:'...,ckXMMMMMMMMMMMMMMO'.xWMMMMMMMMMMMMMMMMMMMW0occokKWMMNXKKKKKKKKK00k; .okxxxddooolllcc::coOWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNc. .xNXKOxol:...lXMMMMNd..:llc'...:OWMMMMMMMMMMMMKxONMMMMMMMMWMMMMMMMMMMMO,.''..;dXWMMMMMMMMMMMWXd. '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMO.  .kMMMMWKkc.'oKWMMMWd..oNMMWKx;..,kWMMMMMMMMWNXK00NMMMMMXxccd0WMMMMMMMX:.;O0o,..cOWMMMMMMMWKxc,.. '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNl.  'OWXOo;'':dKWMMMMM0, .;kXNWMWKc..,kXK00kxdl:,'..,OMMMWO,....'oXMMMMMWx. cNMWKl'.;OWMMWXko;..;dc. ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMO'   .::'.,lxKWMMMMMMMMO,....,;looo:....'.....';clc. ;KMM0o,.:l'...lXMMMMX:..lWMMMXo'.:kOd:...:d0NWo. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWo.   . .'cdkO0KKXWMMMMMNk,...    ...'...,oxk0KXWMWx. cNMXc. '0WKo,.,OMMMMO' .cXMMMNk;.....,lkKWMMMNl. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMK, ...,ooolllcc::::cox0XWWXOd:. 'okOKKl..:KMMMMMMMX: .oWMx.  lNMMWKxkNMMMMk. ..colc,.....l0NMMMMMMMNc..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMx. . .lNMMMMMMWNX0kdc;,:oOXWM0,.;0MMMMO, ,0MMMMMMMk. .xMXc  .xMMMMMMMMMMMNd.......,cdkc.;KMMMMMMMMMNl..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNl    .oWMMMMMMMMMMMMWN0dc;cONK:..dWMMMX: ;KMMMMMMWl. .OMO'  .kMMMMMMMMMW0c,lo,';o0NMMWo.oNMMMMMMMMMWo..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMK; .. .xMMMMMMMMMMMMMWX0xc';kNWo..,kWMMNl.cXMMMMMMK;  ,0Mx.  .dWMMMMMMNOc.,kWW0o;;cdkOo,cXMMMMMMMMMMMO;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMO' .. .kMMMMMMMWX0koc;,';cxXMMM0,..'o0NO,.kWMMMMMMO'  cXWd.   :KMMMWXk:..lKMMMMN0dl::clkNMMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMk. ...;0MNKOxoc,...,cokKNMMMMMMWx'...';'.dNMMMMMMMk. 'kMWx. . .ckkdc'..c0WMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMO'....'lc;...';ldOKNWMMMMMMMMMMMWOc'.';lOWMMMMMMMMKdxKWMMO' ........:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNx' .  ..,cox0XWMMMMMMMMMMMMMMMMMMMWXKKNMMMMMMMMMMMMMMMMMMNo....';lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWOc'',,:oOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWXKKXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BCC is ERC721Creator {
    constructor() ERC721Creator("Boicot Customs", "BCC") {}
}