// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Lord, protect me from the evil of people.
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                             dddddddd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    LLLLLLLLLLL                                                              d::::::d                                                                              tttt                                                           tttt                                                                   ffffffffffffffff                                                                             tttt         hhhhhhh                                                                                   iiii  lllllll                          ffffffffffffffff                                                                                    lllllll                                 //
//    L:::::::::L                                                              d::::::d                                                                           ttt:::t                                                        ttt:::t                                                                  f::::::::::::::::f                                                                         ttt:::t         h:::::h                                                                                  i::::i l:::::l                         f::::::::::::::::f                                                                                   l:::::l                                 //
//    L:::::::::L                                                              d::::::d                                                                           t:::::t                                                        t:::::t                                                                 f::::::::::::::::::f                                                                        t:::::t         h:::::h                                                                                   iiii  l:::::l                        f::::::::::::::::::f                                                                                  l:::::l                                 //
//    LL:::::::LL                                                              d:::::d                                                                            t:::::t                                                        t:::::t                                                                 f::::::fffffff:::::f                                                                        t:::::t         h:::::h                                                                                         l:::::l                        f::::::fffffff:::::f                                                                                  l:::::l                                 //
//      L:::::L                  ooooooooooo   rrrrr   rrrrrrrrr       ddddddddd:::::d             ppppp   ppppppppp   rrrrr   rrrrrrrrr      ooooooooooo   ttttttt:::::ttttttt        eeeeeeeeeeee        ccccccccccccccccttttttt:::::ttttttt            mmmmmmm    mmmmmmm       eeeeeeeeeeee          f:::::f       ffffffrrrrr   rrrrrrrrr      ooooooooooo      mmmmmmm    mmmmmmm        ttttttt:::::ttttttt    h::::h hhhhh           eeeeeeeeeeee             eeeeeeeeeeee  vvvvvvv           vvvvvvviiiiiii  l::::l         ooooooooooo    f:::::f       ffffff     ppppp   ppppppppp       eeeeeeeeeeee       ooooooooooo   ppppp   ppppppppp    l::::l     eeeeeeeeeeee                //
//      L:::::L                oo:::::::::::oo r::::rrr:::::::::r    dd::::::::::::::d             p::::ppp:::::::::p  r::::rrr:::::::::r   oo:::::::::::oo t:::::::::::::::::t      ee::::::::::::ee    cc:::::::::::::::ct:::::::::::::::::t          mm:::::::m  m:::::::mm   ee::::::::::::ee        f:::::f             r::::rrr:::::::::r   oo:::::::::::oo  mm:::::::m  m:::::::mm      t:::::::::::::::::t    h::::hh:::::hhh      ee::::::::::::ee         ee::::::::::::ee v:::::v         v:::::v i:::::i  l::::l       oo:::::::::::oo  f:::::f                  p::::ppp:::::::::p    ee::::::::::::ee   oo:::::::::::oo p::::ppp:::::::::p   l::::l   ee::::::::::::ee              //
//      L:::::L               o:::::::::::::::or:::::::::::::::::r  d::::::::::::::::d             p:::::::::::::::::p r:::::::::::::::::r o:::::::::::::::ot:::::::::::::::::t     e::::::eeeee:::::ee c:::::::::::::::::ct:::::::::::::::::t         m::::::::::mm::::::::::m e::::::eeeee:::::ee     f:::::::ffffff       r:::::::::::::::::r o:::::::::::::::om::::::::::mm::::::::::m     t:::::::::::::::::t    h::::::::::::::hh   e::::::eeeee:::::ee      e::::::eeeee:::::eev:::::v       v:::::v   i::::i  l::::l      o:::::::::::::::of:::::::ffffff            p:::::::::::::::::p  e::::::eeeee:::::eeo:::::::::::::::op:::::::::::::::::p  l::::l  e::::::eeeee:::::ee            //
//      L:::::L               o:::::ooooo:::::orr::::::rrrrr::::::rd:::::::ddddd:::::d             pp::::::ppppp::::::prr::::::rrrrr::::::ro:::::ooooo:::::otttttt:::::::tttttt    e::::::e     e:::::ec:::::::cccccc:::::ctttttt:::::::tttttt         m::::::::::::::::::::::me::::::e     e:::::e     f::::::::::::f       rr::::::rrrrr::::::ro:::::ooooo:::::om::::::::::::::::::::::m     tttttt:::::::tttttt    h:::::::hhh::::::h e::::::e     e:::::e     e::::::e     e:::::e v:::::v     v:::::v    i::::i  l::::l      o:::::ooooo:::::of::::::::::::f            pp::::::ppppp::::::pe::::::e     e:::::eo:::::ooooo:::::opp::::::ppppp::::::p l::::l e::::::e     e:::::e            //
//      L:::::L               o::::o     o::::o r:::::r     r:::::rd::::::d    d:::::d              p:::::p     p:::::p r:::::r     r:::::ro::::o     o::::o      t:::::t          e:::::::eeeee::::::ec::::::c     ccccccc      t:::::t               m:::::mmm::::::mmm:::::me:::::::eeeee::::::e     f::::::::::::f        r:::::r     r:::::ro::::o     o::::om:::::mmm::::::mmm:::::m           t:::::t          h::::::h   h::::::he:::::::eeeee::::::e     e:::::::eeeee::::::e  v:::::v   v:::::v     i::::i  l::::l      o::::o     o::::of::::::::::::f             p:::::p     p:::::pe:::::::eeeee::::::eo::::o     o::::o p:::::p     p:::::p l::::l e:::::::eeeee::::::e            //
//      L:::::L               o::::o     o::::o r:::::r     rrrrrrrd:::::d     d:::::d              p:::::p     p:::::p r:::::r     rrrrrrro::::o     o::::o      t:::::t          e:::::::::::::::::e c:::::c                   t:::::t               m::::m   m::::m   m::::me:::::::::::::::::e      f:::::::ffffff        r:::::r     rrrrrrro::::o     o::::om::::m   m::::m   m::::m           t:::::t          h:::::h     h:::::he:::::::::::::::::e      e:::::::::::::::::e    v:::::v v:::::v      i::::i  l::::l      o::::o     o::::of:::::::ffffff             p:::::p     p:::::pe:::::::::::::::::e o::::o     o::::o p:::::p     p:::::p l::::l e:::::::::::::::::e             //
//      L:::::L               o::::o     o::::o r:::::r            d:::::d     d:::::d              p:::::p     p:::::p r:::::r            o::::o     o::::o      t:::::t          e::::::eeeeeeeeeee  c:::::c                   t:::::t               m::::m   m::::m   m::::me::::::eeeeeeeeeee        f:::::f              r:::::r            o::::o     o::::om::::m   m::::m   m::::m           t:::::t          h:::::h     h:::::he::::::eeeeeeeeeee       e::::::eeeeeeeeeee      v:::::v:::::v       i::::i  l::::l      o::::o     o::::o f:::::f                   p:::::p     p:::::pe::::::eeeeeeeeeee  o::::o     o::::o p:::::p     p:::::p l::::l e::::::eeeeeeeeeee              //
//      L:::::L         LLLLLLo::::o     o::::o r:::::r            d:::::d     d:::::d              p:::::p    p::::::p r:::::r            o::::o     o::::o      t:::::t    tttttte:::::::e           c::::::c     ccccccc      t:::::t    tttttt     m::::m   m::::m   m::::me:::::::e                 f:::::f              r:::::r            o::::o     o::::om::::m   m::::m   m::::m           t:::::t    tttttth:::::h     h:::::he:::::::e                e:::::::e                v:::::::::v        i::::i  l::::l      o::::o     o::::o f:::::f                   p:::::p    p::::::pe:::::::e           o::::o     o::::o p:::::p    p::::::p l::::l e:::::::e                       //
//    LL:::::::LLLLLLLLL:::::Lo:::::ooooo:::::o r:::::r            d::::::ddddd::::::dd ,,,,,,      p:::::ppppp:::::::p r:::::r            o:::::ooooo:::::o      t::::::tttt:::::te::::::::e          c:::::::cccccc:::::c      t::::::tttt:::::t     m::::m   m::::m   m::::me::::::::e               f:::::::f             r:::::r            o:::::ooooo:::::om::::m   m::::m   m::::m           t::::::tttt:::::th:::::h     h:::::he::::::::e               e::::::::e                v:::::::v        i::::::il::::::l     o:::::ooooo:::::of:::::::f                  p:::::ppppp:::::::pe::::::::e          o:::::ooooo:::::o p:::::ppppp:::::::pl::::::le::::::::e                      //
//    L::::::::::::::::::::::Lo:::::::::::::::o r:::::r             d:::::::::::::::::d ,::::,      p::::::::::::::::p  r:::::r            o:::::::::::::::o      tt::::::::::::::t e::::::::eeeeeeee   c:::::::::::::::::c      tt::::::::::::::t     m::::m   m::::m   m::::m e::::::::eeeeeeee       f:::::::f             r:::::r            o:::::::::::::::om::::m   m::::m   m::::m           tt::::::::::::::th:::::h     h:::::h e::::::::eeeeeeee        e::::::::eeeeeeee         v:::::v         i::::::il::::::l     o:::::::::::::::of:::::::f                  p::::::::::::::::p  e::::::::eeeeeeee  o:::::::::::::::o p::::::::::::::::p l::::::l e::::::::eeeeeeee   ......     //
//    L::::::::::::::::::::::L oo:::::::::::oo  r:::::r              d:::::::::ddd::::d ,::::,      p::::::::::::::pp   r:::::r             oo:::::::::::oo         tt:::::::::::tt  ee:::::::::::::e    cc:::::::::::::::c        tt:::::::::::tt     m::::m   m::::m   m::::m  ee:::::::::::::e       f:::::::f             r:::::r             oo:::::::::::oo m::::m   m::::m   m::::m             tt:::::::::::tth:::::h     h:::::h  ee:::::::::::::e         ee:::::::::::::e          v:::v          i::::::il::::::l      oo:::::::::::oo f:::::::f                  p::::::::::::::pp    ee:::::::::::::e   oo:::::::::::oo  p::::::::::::::pp  l::::::l  ee:::::::::::::e   .::::.     //
//    LLLLLLLLLLLLLLLLLLLLLLLL   ooooooooooo    rrrrrrr               ddddddddd   ddddd ,:::,,      p::::::pppppppp     rrrrrrr               ooooooooooo             ttttttttttt      eeeeeeeeeeeeee      cccccccccccccccc          ttttttttttt       mmmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee       fffffffff             rrrrrrr               ooooooooooo   mmmmmm   mmmmmm   mmmmmm               ttttttttttt  hhhhhhh     hhhhhhh    eeeeeeeeeeeeee           eeeeeeeeeeeeee           vvv           iiiiiiiillllllll        ooooooooooo   fffffffff                  p::::::pppppppp        eeeeeeeeeeeeee     ooooooooooo    p::::::pppppppp    llllllll    eeeeeeeeeeeeee   ......     //
//                                                                                     ,:::,        p:::::p                                                                                                                                                                                                                                                                                                                                                                                                                                                                   p:::::p                                                  p:::::p                                                    //
//                                                                                     ,,,,         p:::::p                                                                                                                                                                                                                                                                                                                                                                                                                                                                   p:::::p                                                  p:::::p                                                    //
//                                                                                                 p:::::::p                                                                                                                                                                                                                                                                                                                                                                                                                                                                 p:::::::p                                                p:::::::p                                                   //
//                                                                                                 p:::::::p                                                                                                                                                                                                                                                                                                                                                                                                                                                                 p:::::::p                                                p:::::::p                                                   //
//                                                                                                 p:::::::p                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LSNTS is ERC1155Creator {
    constructor() ERC1155Creator("Lord, protect me from the evil of people.", "LSNTS") {}
}