// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Slappedtogether
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                     //
//    “Fifteen men on the Dead Man's Chest Yo-ho-ho, and a bottle of rum! Drink and the devil had done for the rest Yo-ho-ho, and a bottle of rum!”                                                                                                                                                                                    //
//    “For thirty years," he said, "I've sailed the seas and seen good and bad, better and worse, fair weather and foul, provisions running out, knives going, and what not. Well, now I tell you, I never seen good come o' goodness yet. Him as strikes first is my fancy; dead men don't bite; them's my views—amen, so be it.”     //
//                                                                                                                                                                                                                                                                                                                                     //
//    Of course these lines have absolutely nothing to do with this contract, I just liked them.                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                     //
//    7x7 is my favourite sum,                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                     //
//    Karel Appel is my favourite artist.                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                     //
//    He-man, absolute legend.                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                     //
//    Custard creams are underrated, and so are lemon curd sandwiches.                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract ST is ERC721Creator {
    constructor() ERC721Creator("Slappedtogether", "ST") {}
}