// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Overthink
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    logo                                                                                                                                                                                                                                                                                                            //
//    ENDEES                                                                                                                                                                                                                                                                                                          //
//    HOMEPRIVACYCONTACTDONATE                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Result                                                                                                                                                                                                                                                                                                          //
//    Download result: banner.txt (46.15 KB)                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//    Remember to use a monospaced font to show this banner.                                                                                                                                                                                                                                                          //
//    Preview                                                                                                                                                                                                                                                                                                         //
//    WNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx'.lOXXKkxdxxd;.,xOOOOOOOOOOKXNXKOkOx:.'loooooooooooooooooooooooooooooooooooooooooolloooooooloooooloooodddddddddddddddddddddooooood0XkoooooooooddddxOXKOkkkkkkkkkkkxdddddddddddddxdddddddddddddddddddddddddddddddddddddddxxddddxkOOOOOOOOkkO0XNNKOkxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0xok00kxddddddo;.;dOOOOOO0KXXK0OOOOOOx;.,cooooooooooooooooooooooooooooooooooooooooooloooooolooooolloooodddddddddddddddddddddooooodOKOooooooooooodxxOXXOkkkkkkkkkkkkxxddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxkOOOOOOOO0KXXK0Okxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NXKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNXd,:dddddddddd:.,dOOKKXXK0OOOOOOOOOOkc.'coooooooooooollooooooooooooooooooooooooooooooooooololc,..,:lddddddddddddddddddddddoooodOXOoloooolooooddk0XXOkkkkkkkkkkkkkkxddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxkkOOOO0KXXK0kkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNXXKKOc.,odddddddddl:d0XKK0OOOOOOOOOOOOOOko'.:looooooooooooooooooooooooooooooooooooooooooolloolc,.;;..,,;coddddddddddddddddddoooodOXkoooooooooddddx0XKOkkkkkkkkkkkkkkkkxddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO0KXXXKOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    XKKKKKKKKKKKKKKKKKKKKKKKXXNNXXKKKKKK0l.'ldxxxdxO0KKkclxOOOOOOOOOOOOOOOOOOd,.;loooooooooooooooooooooooooooooooooooooooloooolc,':kNK:;OOl;,;codddddddddddddddoood0Kkoooooodddddddx0XKkkkkkkkkkkkkkkkkkkxxdddddddddddddddddddddddddddddddddddddddddddddddddddddddxk0XXK0Okxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    XKKKKKKKKKKKKKKKKKKKKXXNNXXKKKKKKKKKK0d'.cdkO0KK0Oxo;.;xOOOOOOOOOOOOOOOOOOx;.,coooooooooooooooooooooloooooooooooolloooool:,,lONWWWk,oNWXOo:,,codddddddddddoood0Kkoooodddddddddx0XOxxkkkkkkkkkkkkkkkkkkxdddddddddddddddddddddddddddddddddddddddddddddddxdddxxO0KK00Oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKKKKKKKKKKKKKXXNNXXKKKKKKKKKKKKKKKkcoOKKOkxdxxdd:.,dOOOOOOOOOOOOOOOOOOkc.'cooooooloolooooooooooooloooooooooooooool;',l0NWWWMMXl,OWWWWNOo;,,coddddddddood0KkoodddddddddddkKXOxdxkkkkkkkkkkkkkkkkkkxxdddddddddddddddddddddddddddddddddddddddddddddddxkOKKK0kdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKKKKKKKKKKXXNNXXKKKKKKKKKKKKKKKKXXNN0l:odddxxddddc''lkOOOOOOOOOOOOOOOOOko'.:loooooooooooooooooooooooolloooooooll;',oKWWWWWWWWW0;cXWWWWMWNOo:,,codddddod0XkddddddddddddxkKXOdddxxkkkkkkkkkkkkkkkkkkxxdddddddddddddddddddddddddddddddddddddddddddxk0KK0Oxdoooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKKKKKKKKXNNNXKKKKKKKKKKKKKKKKXNNNXXK0o.'ldddddddddl,.cxOOOOOOOOOOOOOOOOOOd,.;loolooooooooooooooooooooolloloool;';oKWWWWWWWWWWMWd,xWWWWWMWWWN0o:,,:cloxKXkxdddddddddddxkKKkxddddxkkkkkkkkkkkkkkkkkkkxdddddddddddddddddddddddddddddddddddddddxxO0KK0Oxdoooooooddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKKKKXXNNXXKKKKKKKKKKKKKKKKXNNNXKKKKKK0d,.cdddddddddo;.;xOOOOOOOOOOOOOOOOOOx;.'cooooolooooooooooooooooooolooc;':xXWWWWWNWWMWWWWWK:;0WWWWWMMWWWWN0oc:;l0KkddddddddddddxOXKkxddddddxkkkkkkkkkkkkkkkkkkxxdddddddddddddddddddddddddddddddddddxxOKKK0kdoooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKXXNNXXKKKKKKKKKKKKKKKXXNNXXKKKKKKKKKKKk;.;odddddddxd:.,oOOOOOOOOOOOOkOOOOOkc..coooooooooooooooooooolloolc,':kNWWWWWKd:lKWWWWWWWk,lNMMMWXkxKNWWWWWNKK0l,:odddddddddxOXKxdddddddddxkkkkkkkkkkkkkkkkkkxddddddddddddddddddddddddddddddddxk0KK0Oxdooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKXXNNXXKKKKKKKKKKKKKKKXXNNXXKKKKKKKKKKKKKKKOc.,odddddxxxdc''lkOOOOOOOOOOOOOOOOOko'.:looooooooooooooooooool:''cONWWWWWKo,''.lNWWWWWWNl,kWWWWK:.':d0NWWWWWN0d:,,:ldddddx0X0xddddddddddxkkkkkkkkkkkkkkkkkkkxddddddddddddddddddddddddddddxO0KK0Oxdoooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    XXNNXXKKKKKKKKKKKKKKXXNNNXKKKKKKKKKKKKKKKKKKKK0o''lddddxxdddl,.cxOOOOOOOOOOOOOOOOOkd,.,loooooooooooooooool:',cONMWWWW0o,':ll,'kWWWWWWW0;cKWWWWk',:;,cONNWWWWWNKdc,,:ldx0X0xddddddddddddxkkkkkkkkkkkkkkkkkkxxdddddddddddddddddddddddxkO0KK0kddooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NXXKKKKKKKKKKKKKKXXNNXXKKKKKKKKKKKKKKKKKKKKKKKK0d,.cdddddddddo;.;xOOOOOOOOOOOOOOOOOOx:.'colloolloooooool:,,o0WWWWWNOl,,:lddoc.:XMMWWWWWd,dWMWWNl'lxdx0XkloONWWWWWKxc,cOXOxdddddddddddddxxkkkkkkkkkkkkkkkkkkxxdddddddddddddddxxddxk0KKKOxdooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    KKKKKKKKKKKKKKXNNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;.;dxxxddddxd:.,dOOOOOOOOOOOOOOOOOOkc..:lolooooooloc;';dKWWWWWNOc',:oxkOOdl;'dWWWWWWWXc;0WWWW0;,d0XOdoc;,;oOXWMWWWKKKo,:ldddddddddddddxxkkkkkkkkkkkkkkkkkkxdddddddddddddddxxO0KK0kxdoooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdo    //
//    KKKKKKKKKKKXNNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOc.,oxxxxddl:,..'lkOOOOOOOOOOOOOOOOOko'.;loooooooc,.;xXWWWWWXx;',coxO0000koc',0WMWWWWWO;lNMWWWd,dXk;',;clc;,;lkXWWWWWKxc;,;ldddddddddddxxkkkkkkkkkkkkkkkkkxxdddddddddddxkO0KK0kxdooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo;.    //
//    KKKKKKKXXNNNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o''ldoc;',:okx;.cxOOOOOOOOOOOOOOOOOOd,.,looooc,';xXWWWWWXx;',coxO000000Odo:.lNWWWWWWNo,kWWWWXO00x:'...,:clc;,:kNNWWWMWXxc;,;lddddddddxxkkkkkkkkkkkkkkkkkkxddddddddxk0KK0Okddoooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc..c    //
//    KKKKXNNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d,.'',cdO0KKKOc.;xOOOOOOOOOOOOOOOOOOx:.'clc,'ckNWWWWWXd;';coxO000000000kdo,'kWWWWWWWK::KWWWWNdcdl:,.....';clx0kcckKWMMWWXkl;,;lodddddxxkkkkkkkkkkkkkkkkkxxddddxk0KK0Oxdoooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo..o0    //
//    KXNNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkoox0KKKKKKKK0o',dOOOOOOOOOOOOOOOOOOkl..',lONWWWWWKo;';ldkO000000000000xdl':KWWWWWWWx,dNWWWNo'cdo:'......'dKkoc;,;cxKNWWMWXkl;,;codddxkkkkkkkkkkkkkkkkkkxxdddxkOkxdooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc.,k0    //
//    NNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d,'lkOOOOOOOOOOOOOOOOkl''l0WMWWWN0l,':ldk000000000000000Odo;'dWWWWWWMXc;OWWWWK;'odo;.....,d0o'',:ll:,,:dKNWWWWXkl;,;cddxkkkkkkkkkkkkkkkkkkxxdddddooooooooooooooooooooooooooooooooooooooooooooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl..d0    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;'ckOOOOOOOOOOOOOxl,,oKWWWWWNOc'':odxO00000000000000000kdl,;0WWWWWWWO:xWWWWWx';odc'...,d0l'....';cll:,,:d0NWWWWXOl;,;cdkkkkkkkkkkkkkkkkkkxdooooooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:.'d    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOc.;xOOOOOOOOOOxc,;dKWWWWWNOc'':oxk00000000000000000000Oxdc'lNWWWWWWNK0XWWWWXc',cd:..;xOc'........',:ll:,,:d0NWWWWXOo;,:lxkkkkkkkkkkkkkxxdoooooooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc'.    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o',dkOOOOOkdc,:xXWWWWWNk:..coxO00000000000000000000000Oxo,'kWWWWWWWNocKWWWWO,.,ol,;kO:.............',:ll:,,:oONWWWWNOo:,;ldkkkkkkxxxxddddooooooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl    //
//    XKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d,'lkOOkd:,:kNWWWWWXx:,;''oO00000000000000000000000000kdl':XWWWWWWWk,oNWWWNd'.:ddOk:.................',:llc;,;oONWWWWNOo:,;ldxxxxdddddddoooooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;'cxo;,cONWWWMWKd;,cxOkxk000000000000000000000000000Oxd;'dWMMWWWWXc,OWWWMKk:'xXk;.....................',:llc,,;lOXWWWWNOo:,;codxdddddddooooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOc.',lONWWWWWKo,,lxO0KKK0O000000000000000000000000000kxl';0WWWWWWWO;cXWWWWWOd00o,........................',;clc;,;lkXWWWWN0o:,;codddddddoooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d;,oKWWWWWW0o,,lkO00KK0KK0OO00000000000000000000000000kd:'oNWWWWWWNd,xWWWWWWXdldc'...........................';coc;',lkXWWMWN0d:,,:odxddoooooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOo;;dKWWWWWNOl,;okO00KKKKKKKK0OO0000000000000000000000000OxolONWWWWWWWK::KWMWWWK;'oo;.............................',;:c:,,;cxKWWWWN0d:,,:oddoooooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    dollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc,;dXWWWWWNOc,:okO0KKKKKKKKKKKK00O00000000000000000000000K0kkKkxXWWWWWWWk,oNMMMMWd';dc'................................';:cc:,,cxKNWMMN0dc,,:looooooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    lllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc,..;xXWWWWWXx:..lk00KKKKKKKKKKKKKKKK0OO00000000000000000000000KXKc'dWWWWWWWNocKMWWWMXc.cd:...................................';:ll:,,:d0NWWWNKdc,,;cooooooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kc;ckNWWWWWXx:,cc;lOKKKKKKKKKKKKKKKKKKK0OO000000000000000000000KNKko';0WWMWWWWXKKNWWWWWO,,ol,.....................................';cll:,,:d0NWWWNKxc,';coooooooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0x:;lONWMWWWXd;;lkK0OO00KKKKKKKKKKKKKKKKKKK0OO0000000000000000000XNN0kd:.lNMWWWWWW0cxWWWWWNo.:dc'.....................................'.';cll:,,:oONWMWWKxc,,;coooooooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d;,l0WWWWWWKo;;oOKKKKK00O0KKKKKKKKKKKKKKKKKKK00O00000000000000000XNXK0Oxo,'kWWWWWWWXc;0WWWWWK;'lo;..........................................',:llc;,:oONWWWWKxc,';cloooooooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOo;;oKWWWWWN0l;;dOKKKKKKKK00O0KKKKKKKKKKKKKKKKKKKK0OO00000000000000XNXK000kdl'cXWWWWWWWk,oKNWWWWx';dl,......................................'.....',:loc;,;oOXWWWWKxc,',cloooooooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOo;;dKWWWWWNOc';d0KKKKKKKKKKK00000KKKKKKKKKKKKKKKKKKK000000000000000XNXK0000Oxd;'dWWWWWWWNo,ckWMWWXl.cd:'..............................................';:llc;,;lkXWWWWXkl;',cloooooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kl;:xXWWMWWNOc,.'dKKKKKKKKKKKKKKK00O0KKKKKKKKKKKKKKKKKKK00O0000000000XNXK0K0000kxl':KWWWWWWW0;.:XMWWW0,'oo;.................................................',:llc;,;lkXWMMWXkl;',clooooooooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kc,:kNWWWWWNkc,cxlckKKKKKKKKKKKKKKKK00O0KKKKKKKKKKKKKKKKKKK00O0000000KXNXK00K0000OxdokXWWWWWWWWd,,dWWWMNd.;oc'...................................................',;:cc;',cxKWWMWXkl;',:looooooooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0x:,ckNWWWWWXx:;lkKKOO0KKKKKKKKKKKKKKKKK00O00KKKKKKKKKKKKKKKKKKK0O00000KXNXK000000000OkKOlOWWWWWWMXOc;0WWWMK:.cl;...................................................'...,;clc;',cxKWWMWXOl;,,:looooooodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d:;lONWWWWWKd;,lOKKKK0O0KKKKKKKKKKKKKKKKKKK0O00KKKKKKKKKKKKKKKKKKK0OO00KXNXK000000000KKXKo.:XWWWWWWWWO,lNWWWWk',lc,.....................................................'..',;:cc;,,cd0NWWWXOl;',:loooddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOd:;o0WMWWWWKo;;oOKKKKK00O0KKKKKKKKKKKKKKKKKKKK0000KKKKKKKKKKKKKKKKKKK00O0XNXK000000000KXNXko;'xWWWWWWWWNo,kWWWWNl.;l:'..........................................''...............',:cc;,,:d0NWWWNOo:,,:ldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOo;;dKWWWWWW0o,;oOKKKKKK000O0KKKKKKKKKKKKKKKKKKKKK00O0KKKKKKKKKKKKKKKKKKK00XNXK000000000KXNX0koc';0WWWWWWWWK;:KWWWW0;'cl;..........................................''''................',:cc;,':o0NWWWNOo;,;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOl,;xXWWWWWN0l;:d0KKKKKKKKKK0O0KKKKKKKKKKKKKKKKKKKKKK00O0KKKKKKKKKKKKKKKKKKKNNK0000000000KXNXK0Odl;.lNWWWWWWWWx,oNWWWWx';lc'................................................................',:cc:,';oONWWWNOo:,,coxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWWWWWNXKKKKKKKKKKKKKKKKKKKKKKKKKKK0kl;:xXWWWWWNOc;cx0KKKKKKKKKKKK0O0KKKKKKKKKKKKKKKKKKKKKKKK0O00KKKKKKKKKKKKKKKKNNX00O0000000KNNXK000xl:.'OWWWWWWWWXc;OWWWWXc.cl;'..................................................................',:cc:,,;oOXWMWN0o:,,cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    WWWWWWWWWWWWNKKKKKKKKKKKKKKKKKKKKKKKKK0xc;cONWWWWWXk:,ck0KKKKKKKKKKKKKK0O0K0KKKKKKKKKKKKKKKKKKKKKKK0000KKKKKKKKKKKKKKNNXKK00O00000KNNXK0000Ooc;.cXWWWWWWWWO;cXWWWWO,,ll,.....................................................................',;cc:,,;lkXWWWN0:.cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    //
//    NNNNNNNNNNNNNXK000000000000000000000Od:;lONWWWWWXx:':x0KKKKKKK000000KK00O0000KKKKKK00KKKKKKKK0KK00KK00O0KKKKKKKKKKKKNNXKKKK00O000KNNK0000000kl:'.dWWWWMWWWNo,xWWWWNo.;l:'......................................'................................',:llc;,;lkXWWK;'oxxddddddxxxxxdxxddddxxddxxdddddddddddxxxxd    //
//    oooooooooooooollcccccccccccccccccc:,',l0WMWWWWXx:'.;lxO0000000000000000OO00000000000000000000000000000OO00KKKKKKKKKNNKKKKKKKK0OOKNNK00000000Ol,'.;0WWWMWWWWK::KWWWWK;.,;'..........................................................................',,;;,'.cKWWx',:ccccccccccccccccccccccccccccccccccccccccc    //
//    KXKKKKXKKKKKKKKK0OOOOOOOOOOOOOOOxc',oKWWWWWWKd::okOOO000KK0000000000K000O0000000000000000000K00000000000O0KKKKKKKXNNKKKKKKKKKK0KNNKKK0KKK0K00Okxc'oNWWWWWWMWk,oNWWWWk';xd;'....'''.........'..''.''..''...................................''...........,oOl'dNMXc'd00000000000000000000000000000000000000000    //
//    WWWWWWWWWWWWWWWWWNXKXKKKKKKKKKOo;:dKWWWWWW0l;:d0KKKKKKKKKKKKKKKKKKKKKKK0O0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0O00KKKKXNNKKKKKKKKKKKXNX00KKKKKKKKKKKK0k;'kWWWWWWWMXl,OWWWWNl'oOd,.''''''..''''''''''''''''''''..''''''.................'''''....''''..........:O0;;0WWO,:0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    WWWWWWWWWWWWWWWWWWNXKKKXKKKKOl;:xXWWWWWN0l,:x0KKKKKKKKKKKKKKKKKKKKKKKKK0O0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OO0KKXNNKKKKKKKKKKKXNXK0O0KKKKKKKKKKKK0o'cXWWWWWWWW0;cXWWMW0;;kkc'''...''''''''..''''''''''..''''''.'''........'........''...''''''...........'dKd'lNWNo'dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    WWWWWWWMMWWWWWWWWWWNXXKKXKkc,:kNWWWWWNOc,:xKKKKKKKKKKKKKKKKKKKKKKKKKKKK0O0KKKKKKKKKKKKKKKKKKKKKKKKKKKK                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract THINK is ERC721Creator {
    constructor() ERC721Creator("Overthink", "THINK") {}
}