// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Hache De Henry
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//      .xNWWWWWWWWWNNKOo;.      ........'''''.......                                                                                                                                                                                                                                                                 //
//      .xNWWWWWWWWWWWWWNXKOdc,.     .......''''..........                                                                                                                                                                                                                                                            //
//       ,kNWWWWWWWWWWWWWWWWWNX0ko:'.     ........'..........                                                                                                                                                                                                                                                         //
//        ,0MWWWWWWWWWWWWWWWWWWWWWNKOxl;..    .......'''''.........                                                                                                                                                                                                                                                   //
//     .;oONWWWWWWWWWWWWWWWWWWWWWWWWWWNXKko:'.     .....''''''......                                                                                                                                                                                                                                          ..',    //
//    oKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKk' ''.    ....'''',,''.....                                                                                                                                                                                                                               ...,;cldxkO    //
//    XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX:;KXOdc;..   ....'',,,,,'.....                                                                                                                                                                                                                    ...,,:ldxkO0000KKK    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:dWWWWWNKOdc,.    ....''',,,'.....                                                                                                                                                                                                        ..',:cldxkO000KKXXXXXXXXXX    //
//    0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMOcOMWWWWWWWWWX0xl;..   ....'''',''....                                                                                                                                                                                              .';:loxkO0KKXXXXXXXXXXNXXXXXXXXXX    //
//    xxkkO0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxlXMWWWWWWWWWWWWWNXOdc,.    ....'''....                                                                                                                                                                                      ... .ck0KXXXNNNNNNNNNNNNNNNXNNNNNNNNNXXX    //
//    WWNK0OOOkO0KNWMWWWWWWWWWWWWWWWWWWWWWWWNddWWWWWWWWWWWWWWWWWWWWX0xl;..    ......                                                                                                                                                                               ..,:ldkOKd.:XNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNX    //
//    WWWWWWWWXKOOkkkO0XWWWWWWWWWWWWWWWWWWWMXokWWWWWWWWWWWWWWWWWWWWWWWWNKko:,.                                                                                                                                                                              ..,:ldk0KXNNNNNWX:,KWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    WWWWWWWWWWWWWNKOkkkkkOKNWWWWWWWWWWWWWM0d0MWWWWWWWWWWWWWWWWWWWWWWWWWWNNX0o. ...   ..                                                                                                                                                              .,:oxOKXNWWWWWWWWWWWWWd'kWNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWNX0OkkkO0KNWWWWWWWWWOdXMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNK;..''   ...                                                                                                                                                       ..,cok0XNWWWWWWWWWWWWWWWWWNWO,oWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWXKOkkkkO0XWWWWkxWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0,.,;'.  ..                                                                                                                                                   .,ldk0XNWWWWWWWWWWWWWWWWWWWWWWWWWX::XWWWWWWNNNNNNNNNNNNNNNXNNNNNXK0kdl    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0OxxxxxdckWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO'.,;'  ...                                                                                                                                                  'xXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo,OWWWWWNNNNNNNNNNNNNNNX0Oxolccccclo    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOl'ckO0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWk..;;'   ..... ..    . ..  .. ..   . .. .. .. .   .  .   ...     ..   .     .    ...   . .. ..  .        .  . .. .. .. .. ..  ..   .  . .. ..  .             'ONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'oWWWWNNNNNWWWNX0kxoollllloxk0XNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOl0NK0OOOOO0XWWWWWWWWWWWWWWWWWWWWWWx..;,'   ....                                                                                                                                                'OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK,:XWWWNXKOxdoooooooxk0KXNNNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxdNWWWWWNX0OOOOO0KNWWWWWWWWWWWWWWWWo.';;'    ...                                                                                                                                                .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNc.lxdooooodxk0KNNWWNNNNNXNNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNdxWWWWWWWWWWWWNK0OOOO0KXWWWWWWWWWWNl.;c:'   ...                                                                                                                                               . .xWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxddo; ,dk0KNNWWWNNNNNNNNNNNNXXNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMKoOMWWWWWWWWWWWWWWWWNX0OOOOO0KNWWWWN:.:lc'    ..                                                  ........         .....   .                                    ..............                 .  oNWWWWWWWWWWWWWWWWWWNK0kxxdddddxO0XK;:XWNNWWNNNNNNNNNNNNNNNNXNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM0oKMWWWWWWWWWWWWWWWWWWWWWWX0OkkkkkOk'.:lc'    ....... ..............    ...................      ..........       ...........  ......................          ................                .  ;XWWWWWWWWWWWNKOkxxxxxxxO0XNWWWWWWWWo,OWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNN    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkdNMWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOxc..,c;.    ......................   .......................   ..........        .........   .....................           ................                .. ,KWWWNX0OkxxkxxxkOKNWWWWWWWWWWWWWWWWk'dWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNN    //
//    dddxOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNxkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM0'.,;,.    ....... ..............   ....... ............................       ..........   .....................           ................                   .lxxxxxxkO0XNWWWWWWWWWWWWWWWWWWWWWWWK,:NWWWWWWWNNNNNNNNNNNNNXNNNNNNNNN    //
//    NKOkxdxxxxO0XWWWWWWWWWWWWWWWWWWWWWMXdOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO..:c,     ''....................   .....    ...........................       ..........         ...............          ..................                   ;OKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNc,0WWWWWNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    WWWWWWWNKOkxxxxxkOKNWWWWWWWWWWWWWWMKdKMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.:ddc.    ,'...........            ......  .     ........... ..........       ..........         ..........               ........ .........                   cNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd'xWWWWWWNNNNNNNNNNNNNNNXNNNNNNNN    //
//    WWWWWWWWWWWWWNX0OkxxxxkO0XNWWWWWWWWOxXMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo'okxc.    ''.........  .           .......        ..........  .........       ..........         .........               .........  .........                  ;XMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0'cNWNWWNNNNNNNNNNNNNNNNNXKkoclxk    //
//    WWWWWWWWWWWWWWWWWWWWNK0kxxxxxkOKNWWxxWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNl.lxxc.   .,'.............          ......          ......... ..........       ...........        .........              ..........  .........                  '0MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX:,KWNWWNNNNNNWNNXK0kdoc;,.    .c    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWX0Okkxxo,:k0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX:.lxx:    .,'..................     ........         .......  ..........       ...........        .........              .........   ..........                 .kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo.kWWWWNXK0kdoc;,..     ...   ;K    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO;:xxxxxxkO0XNWWWWWWWWWWWWWWWWWWWWWWK;.ldd;    .,'...................     .........   ..........    .........       ...........         ........              .........   ..........                  oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx.;xdl:;'..    ...',;:clodl.  .x    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0ckMWWWXKOkxxxxxkO0XNWWWWWWWWWWWWWWW0'.ldd;    .;'...................    ................''...      .........       ...........         ........             ..........    ..........                 cNWWWWWWWWWWWWWWWWWWWWWWWWWNX0Oxol:,.      ..';:clodxkkkkxxxxdd;   c    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkl0MWWWWWWWWWWXKOkkkkxxkO0XNWWWWWWWWO..ldd;    .;'...................    ......................    ..........       ...........        .........             ..........    ..........                 ,KMWWWWWWWWWWWWWWWWNK0kdoc:,..    ..'. ;odxkO0000OOOOOkkkkxxxxxl.  '    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxoNMWWWWWWWWWWWWWWWWWXKOkxxxxxxO0XNWx..col'    .'..............          .......................   ..........       ...........        .........             .........................                .OWWWWWWWWNK0Oxdlc;'..   ..';cllodddo,..;d00000000OOOOkkkkkkkxxd'       //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNodWWWWWWWWWWWWWWWWWWWWWWWWWWX0Oxxxxd, .';,.    .'..........              .........      .........  ..........       ...........        .........            ..........................                .dNX0kdl:,'..   ..';:lodddddol:,'..      :0000000OOOOOOkkkkkkxxx:       //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMKlkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKc  ..'.    .,..........              .........       ........     .......       ...........        ........            ............................                ....  ..',:codkOKXXNKo,..               ,k000000OOOOOOOkkkkkkxxc.      //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMOlOMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNl.,clc.    ',..........               ........       ........     ........     ...........         .........           ............ ...............                   .ckO0KXNXXXXXXXXXKc                  .d000000OOOOOOOkkkkxdxxo'      //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxlKMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX:.lddc.    ',..........              .........       ........     .........   ............         .........          ...........       ............                  .xNXXXXXXXXXXXXXXXd.                  c0000000OOOOOOxddxddxkkc.     //
//    XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdoNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK;'odd:.   .,;..........              .........       ..   ..     ........................          ........            ..........        ...........                   lXXXXXXXXXXXXXXXXO'                  ,O00000OOkdc;'..'dkkkkkd'     //
//    xxxkkkO0KXWWWWWWWWWWWWWWWWWWWWWMXlxWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0''oxd:.   .;;..     ...              .........       ..  .. ...   ......................           .......            .... .....         ...........                   ;KXXXXXXXXXXXXXXX0;                 .:k000Okx:.       ,xkkkkx:     //
//    WWNK0OkkxkkkkkkO0XNWWWWWWWWWWWWM0lkMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO',dxd;    .:;.... .....              .........        .........      .................             ....              .........           ...........                   .kNXXXXXXXXXXXXXXKc     ..',;:cldxc.;kxl:,..,c.        ,odolc,     //
//    WWWWWWWWWWWNK0OOkkkkkkkkO0KXWWWMkc0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.;ddo,    .:;..........               ........        .........            ..  .....                                                      ..........                   .oKKXXXKKKXXXXXXXXOllodxOO0000Oxol,  .      .:;         ....''.    //
//    WWWWWWWWWWWWWWWWWWWWNK0Okkxxxdxd;'d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd.:doo,    .:,.                                        .   ..                .... .............                                                                          cXXXXx,.'',,:clllccccc:;;,'...               ..         ;oodd;    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKk;,lodxkxkkO0KNWWWWWWWWWWWWWWWWWWWWWWNl.cddo.    .,'........            ........         ...............         ........................                             .   ................                     ;0NXXc                                       ,c.        .cdodl    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXokMWWNXK0OkkxxxxxxxkO0XNWWWWWWWWWWWWNc.coo:.    .'.  ........         ..........     .....................      .......  ................   ......                   .. .................                     .kXXK;                              ..       .cc.        .lddo    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMKoOMWWWWWWWWWWWNXK0OkxdddddddxkO0XNWWX:.,:;'     ...  ........         ..........    .................... ..     .....     ...............   .......                   ...................                     .oOko.                     .,.      ..        'o,         ,odd    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMOoKMWWWWWWWWWWWWWWWWWWWWWNX0Oxddoooooc. .;:,.    .,.............       ..........    ............ ..........     ......  ..     ...........  ......                   ....................                      .cl,               ..      ;'       '.        :o.         :dd    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMkdXMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKOl. ':c,.    ,:..............      ..........   ..........      .......      ........        ..........  .......                  .......... ...  ...                       ;KNd.              ..      ,;       .,        .lc.        .ld    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxdNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNd..col,.    ;:..............      ..........   ..........      .......      .....            .........  ........                 .........                              .. 'OXc               '.      .;.      .:'        'd;         'o    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNdxWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXl.,odo;.   .;:...............     ..........   ..........       ........    .........          .......  ........                 .........                              .. .xK;               ,'      .;.       :c.       .co.         ;    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWMXokMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXc.;dxd:.   .::................    ..........   .........        .......     ..........     .  .......   ........                 .........                           .  .'  l0,      .                                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract FRTNBL is ERC1155Creator {
    constructor() ERC1155Creator("Hache De Henry", "FRTNBL") {}
}