// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: ABADDON
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                    ..........    .                                                                                                 //
//                                                                                                                                                                                         ...,:odxxkk0KKKXXXKK0OkkO0xc:'                                                                                             //
//                                                                                                                                                                                        :OXXNNWWWWWWWWWWWWWWWWWWWWWWWWO:.                                                                                           //
//                                                                                                                                                                                      .:xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKxl;.  .;l,.,:,'.  .                                                                         //
//                                                                                                                                                                                    .c0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOxxxONk:co:''.,dxo,.                                                                     //
//                                                                                                                                                                                  .l0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXKd,':xKNWX0o'.                                                                  //
//                                                                                                                                                                                   ;OXNWNNXKkdolc:oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXNWWWWWWNXOc.                                                                //
//                                                                                                                                                                                    ..;:;'..       :0NWWWWWWWWWWWWWWNOc:lodk0XNWWWWWWWWWWWWWWWWWWWNk;.                                                              //
//                                                                                                                                                                                                    .dXWWWWWWWWWWWWWW0;     ..;lkKNWWWWWWWWWWXKNWWNKOl.                                                             //
//                                                                                                                                                                                                     .lXWWWWWWWWWWWWWWKl.        .,cdOXWWWWWWKOk0NWN0dl.                                                            //
//                                                                                                                                                                                                       ;ONWWWWWWWWWWWWWN0;           .,o0NWWWWW0dkN0:..                                                             //
//                                                                                                                                                                                                        .dXWWWWWWWWWWWWWWKo.            .dXWWWWXd::.                                                                //
//                                                                                                                                                                                                         .c0WWWWWWWWWWWWWWN0c.           .dNWWWWWK:                                                                 //
//                                                                                                                                                                                                           'dXWWWWWWWWWWWWWWXd.           cXWWWNKl.                                                                 //
//                                                                                                                                                                                                            .lXWWWWWWWWWWWWWWNk'         'kWWWKd'                                                                   //
//                                                                                                                                                                                                              cKWWWWWWWWWWWWWWNd.   .':lkKNWWXc                                                                     //
//                                                                                                                                                                                                               'xNWWWWWWWWWWWWWO:;lx0XNWWWWWKl.                                                                     //
//                                                                                                     ..                                                                                                         .dXWWWWWWWWWWWWNXNWWWWWWWWXO:                                                                       //
//                                         .,'..                                                    .,dKO,                                                                                                        ;0NWWWWWWWWWWWWWWWWWWXkxdc'.                                                                        //
//                                    .;ldkXNXK0Od:'.                                             .cOXWWNl                                                                                                       .kNWWWWWWWWWWWWWWNNNOo;.                                   . ..                                      //
//                                  'o0NWWWWWWWWWWNXOc.                                           ,ONWWWW0;                    .,,.                                                                             'kNWWWWWWWWWWX0d:;;;'.                                     'lllc;,.    .lo,,loc,..                    //
//                               .,d0NWWWWWWWWNXXWWWWN0c.                                         ;ONWWWWWd.                   .oOklcl,...                                                                     .oKNNXNNNWNKOd,.                                ..,'....'dkc',:lkXKc..,..c0XXWWWNKOko.                 //
//                              .:ONWWWWWWWNX0xc;oookKXXO;                                        ;KWWWWWWO'                    ;ONWWN0kO0d;.                                                           .',,;oxdx0XKxc;;:,.                          .cdkxkOOOO0KNXO0KO0NW0xOKXNWWKOOkdxKNWWWWWWWWWWKd;.              //
//                           ..'oKWWWWWWWWNx;.       ..,cl.                                       'OWWWWWWX:                    cKWWWWWWWWWXOc.                                                      .:kKNNNNWWWWWWWN0c.''..                         .xNWWWWWWWWWWWWWWWWWXXNNWWWWWWWWWWWWWWWWWWWWWWWWWX:              //
//                         .:OKXWWNKkdlloo;.                                                      :KWWWWWWWk.                  :KWWWWWWWWWWWWNk,                                                   .ckXWWWNXOdlcxNWWWWNXXNX0o'.                       .xNWWWWWWWWWWWWWWWW0l::coxkKXNWWWWWWWWWWWN0kOKXNK:              //
//                      .,oOXWWNKOd,                                                              :KWWWWWWWK;                 '0WWWWWWWWWWWWWWW0,                                                'oKNWWN0d:..   :KWWWWWWWWWWNXOl.                      .c0NWWWWWWNXXNWWWWWXOd:.  ..,:lkKXXWWWWNd....,'.               //
//                     'kNWWNKx:.                             .;lxko.                             :KWWWWWWWNl                 .kWWWWWWWWWWWWWWWNc                                             .cOXNWWNk:.        'o0XWWWWWWWNNW0'                        .cONWWWWNOolokXWWWWWNKx;.     ..,xXWWX:                      //
//                    ;kNWNOc.                               .xNWWWNl                             :KWWWWWWWWk.                .oNWWWWN0KWWWWWWWNd.                                           .oXWWWNO:.            .;xXNWWWWNNNd.                          .cKWWWWWXd.'xNNNWWWWWN0d;.     .xKxo;.                     //
//                  .lKWWNk.                                 .dNWWWWk.                           .kWWWWWWWWW0,                'xNWWWWWNNWWWWWWWWNO;.                                         oNWWWXo.                 ':d0NWWWNOol:.                         'lkKNWWN0dx0dxNWWWWWWWNOl,.  .ol.                        //
//                 .lXWWNk'                                   lNWWWWXc                           .OWWWWWWWWWK;                cKNWWWWWWWWWWWWWWWWWXo.                                       .kWWWXl.                     .cxOKWWWWW0o'                          .ckKNWX0XKKNXXWWWWWWWWNOc.                            //
//                .oXWWNk.                                    ,0WWWWW0c                          .xWWWWWWWWWNl                :XWWWWWWWWWWWWWWWWWWWKo.                                      cXWWNx.                          ,kNWWWWWKx:.                          .lOXWWWWNKXWWWWWWWWWWNKd:.                         //
//               .dNWWWO'                                     .dNWWWWWXc                         .dWWWWWWWWWWd.               :XWWWWWWWWWWWWWWWWWWWWN0c.                                   .xWWWNo                            'kNWWWWWWNOc.                           ,xXWWWWWWWWWWWWWWWWWWN0o.                       //
//               cXWWWX:                                       :KWWWWWW0;                        .kWWWWWWWWWW0'              .xNWWWWWWWWWWWXk0NWWWWWWWNO:                                   cXWWW0;                            .cKWWWWWWWN0c.                           'cxXWWWWWWXkk0KNWWWWWWKd;.                    //
//              ;0WWWNd.                                       .OWWWWWWWk.                       .dNWWWWWWWWWX:              ,0WWWWWWWWWWWW0;'xNWWWWWWWWXx,                                 .oNWWW0:                             'xXWWWWWWWXx,                             'ckXWWWNKxokXWWWWWWWWNOc.                  //
//             ;0WWWWO'                                        .xNWWWWWWXl                       .oNWWWWWWWWWNl              ,0WWWWWWWWWWWWK; .lKWWWWWWWWWXxl;                               'kXNWWXo.                            .lKWWWWWWWW0:                              .c0NWWWNNWWWWWWWWWWWWNO:.                //
//            .dWWWWXc                                          :XWWWWWWW0,                      'xNWWWWWWWWWWk.             :XWWWWWWWWWWWXd.   ;ONWWWWWWWWWWXd'                              .',ckXN0c.                            ,kNWWWWWWWK;                               .,l0NWWWWWWWWWWWWWWWWNk'               //
//            ,0WWWWk.                                          .kWWWWWWWXo. .',;cccll:c:lxocodxk0NWWWWWWWWWWW0'             cXWWWWWWWWWWW0,     .c0NWWWWWWWWWWKd,                                .c0NN0o'                           .dXWWWWWWNd.                                 .:ONWNNWWWWWWWWWWWWNx,              //
//           .oNWWWNo                                           .xWWWWWWWWN0O0XNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0'            .dNWWWWWWWWWW0:.       .oKWWWWWWWWWWWXl                                 .:ONWXkc'                         .dNWWWWWW0,                                   .;lod0WWWWWWWWWWWWW0,             //
//           '0WWWWK;                                            lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0;             oNWWWWWWWWWWXOo.  .;c:;:kNWWWWWWWWWWWKdc;:c:.                            .cOXWWXkl,.                      :XWWWWWWXc                                        ,ONWWWWWWWWWWWXc             //
//           cXWWWWO.                                            ,KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.           'OWWWWWWWWWWWWWNOdkKNWWWNNWWWWWWWWWWWWWWWNNWNO,                             .;xKNWWN0xl;.                .;ONWWWWWWWx.                                        :KWWWWWWWWWWWNx.            //
//           oNWWWNo                                             .kWWWWWWWWWWWNKKKKXXXKKXXXXK00000KNWWWWWWWWWWWO'           :XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:                                .:ONWWWWNKOxl:,'......';cd0NWWWWWWWWXc                             .',.        .:ONWWWWWWWWWW0,            //
//           lNWWWNl                                              oNWWWWWWWWNx;.....'.....'........oXWWWWWWWWWWX:           cNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk;.                                'OWWWWWWWWWWNXXKKKKXNNWWWWWWWWWWWWO'                          'lx0XNO'         .lKWWWWWWWWWk.            //
//           cXWWWWk.                               .;.           :XWWWWWWWWNd.                    '0WWWWWWWWWWX:           oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0d'                               ,kXWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk'                          'OWWWWNx.           ;0WWWWWWW0,             //
//           cXWWWWXc                              'xKc           .xWWWWWWWWW0;                    '0WWWWWWWWWWNd.         .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,.                             .kNWWWWWWWWWWWWWWWWWWWWWWNKKKx;.                           :KXNWWKo;;,','''',;ckNWWWNNXO;              //
//           :KWWWWWk.                           'oKWNl            cXWWWWWWWWWk.                    cXWWWWWWWWWW0,         'OWWWWWWWWWWWWW0oloodolodxkOOOKXXXXK0KOOXWWWWWWWWWWWWXd.                             ,x0KNWWWWWWWWWWWWWWWWWWWNd,.                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CHAOS is ERC721Creator {
    constructor() ERC721Creator("ABADDON", "CHAOS") {}
}