// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Outsider Story by Chain Virus
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//         OOOOOOOOO     UUUUUUUU     UUUUUUUUTTTTTTTTTTTTTTTTTTTTTTT   SSSSSSSSSSSSSSS IIIIIIIIIIDDDDDDDDDDDDD      EEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRR           SSSSSSSSSSSSSSS TTTTTTTTTTTTTTTTTTTTTTT     OOOOOOOOO     RRRRRRRRRRRRRRRRR   YYYYYYY       YYYYYYY    //
//       OO:::::::::OO   U::::::U     U::::::UT:::::::::::::::::::::T SS:::::::::::::::SI::::::::ID::::::::::::DDD   E::::::::::::::::::::ER::::::::::::::::R        SS:::::::::::::::ST:::::::::::::::::::::T   OO:::::::::OO   R::::::::::::::::R  Y:::::Y       Y:::::Y    //
//     OO:::::::::::::OO U::::::U     U::::::UT:::::::::::::::::::::TS:::::SSSSSS::::::SI::::::::ID:::::::::::::::DD E::::::::::::::::::::ER::::::RRRRRR:::::R      S:::::SSSSSS::::::ST:::::::::::::::::::::T OO:::::::::::::OO R::::::RRRRRR:::::R Y:::::Y       Y:::::Y    //
//    O:::::::OOO:::::::OUU:::::U     U:::::UUT:::::TT:::::::TT:::::TS:::::S     SSSSSSSII::::::IIDDD:::::DDDDD:::::DEE::::::EEEEEEEEE::::ERR:::::R     R:::::R     S:::::S     SSSSSSST:::::TT:::::::TT:::::TO:::::::OOO:::::::ORR:::::R     R:::::RY::::::Y     Y::::::Y    //
//    O::::::O   O::::::O U:::::U     U:::::U TTTTTT  T:::::T  TTTTTTS:::::S              I::::I    D:::::D    D:::::D E:::::E       EEEEEE  R::::R     R:::::R     S:::::S            TTTTTT  T:::::T  TTTTTTO::::::O   O::::::O  R::::R     R:::::RYYY:::::Y   Y:::::YYY    //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T        S:::::S              I::::I    D:::::D     D:::::DE:::::E               R::::R     R:::::R     S:::::S                    T:::::T        O:::::O     O:::::O  R::::R     R:::::R   Y:::::Y Y:::::Y       //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T         S::::SSSS           I::::I    D:::::D     D:::::DE::::::EEEEEEEEEE     R::::RRRRRR:::::R       S::::SSSS                 T:::::T        O:::::O     O:::::O  R::::RRRRRR:::::R     Y:::::Y:::::Y        //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T          SS::::::SSSSS      I::::I    D:::::D     D:::::DE:::::::::::::::E     R:::::::::::::RR         SS::::::SSSSS            T:::::T        O:::::O     O:::::O  R:::::::::::::RR       Y:::::::::Y         //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T            SSS::::::::SS    I::::I    D:::::D     D:::::DE:::::::::::::::E     R::::RRRRRR:::::R          SSS::::::::SS          T:::::T        O:::::O     O:::::O  R::::RRRRRR:::::R       Y:::::::Y          //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T               SSSSSS::::S   I::::I    D:::::D     D:::::DE::::::EEEEEEEEEE     R::::R     R:::::R            SSSSSS::::S         T:::::T        O:::::O     O:::::O  R::::R     R:::::R       Y:::::Y           //
//    O:::::O     O:::::O U:::::D     D:::::U         T:::::T                    S:::::S  I::::I    D:::::D     D:::::DE:::::E               R::::R     R:::::R                 S:::::S        T:::::T        O:::::O     O:::::O  R::::R     R:::::R       Y:::::Y           //
//    O::::::O   O::::::O U::::::U   U::::::U         T:::::T                    S:::::S  I::::I    D:::::D    D:::::D E:::::E       EEEEEE  R::::R     R:::::R                 S:::::S        T:::::T        O::::::O   O::::::O  R::::R     R:::::R       Y:::::Y           //
//    O:::::::OOO:::::::O U:::::::UUU:::::::U       TT:::::::TT      SSSSSSS     S:::::SII::::::IIDDD:::::DDDDD:::::DEE::::::EEEEEEEE:::::ERR:::::R     R:::::R     SSSSSSS     S:::::S      TT:::::::TT      O:::::::OOO:::::::ORR:::::R     R:::::R       Y:::::Y           //
//     OO:::::::::::::OO   UU:::::::::::::UU        T:::::::::T      S::::::SSSSSS:::::SI::::::::ID:::::::::::::::DD E::::::::::::::::::::ER::::::R     R:::::R     S::::::SSSSSS:::::S      T:::::::::T       OO:::::::::::::OO R::::::R     R:::::R    YYYY:::::YYYY        //
//       OO:::::::::OO       UU:::::::::UU          T:::::::::T      S:::::::::::::::SS I::::::::ID::::::::::::DDD   E::::::::::::::::::::ER::::::R     R:::::R     S:::::::::::::::SS       T:::::::::T         OO:::::::::OO   R::::::R     R:::::R    Y:::::::::::Y        //
//         OOOOOOOOO           UUUUUUUUU            TTTTTTTTTTT       SSSSSSSSSSSSSSS   IIIIIIIIIIDDDDDDDDDDDDD      EEEEEEEEEEEEEEEEEEEEEERRRRRRRR     RRRRRRR      SSSSSSSSSSSSSSS         TTTTTTTTTTT           OOOOOOOOO     RRRRRRRR     RRRRRRR    YYYYYYYYYYYYY        //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract OSCV is ERC1155Creator {
    constructor() ERC1155Creator("Outsider Story by Chain Virus", "OSCV") {}
}