// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: DTMS
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                  //
//                                                                                                  //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMN00000000KXNWMMMMMMN000000000000000XMMWX000KNMMMMMMMMMWX000NMMMMMMWNK0OkkkO0KNWMMMMMMM    //
//    MMMWx.     ....':o0WMMWx.   .         .oWMX:   .;kNMMMMMWKo'. .xMMMMNkc'..     ...,l0MMMMM    //
//    MMMWd  .:dddolc'  .:0WMKxdddd:.  ;ddddd0WMK;     .;kNMWKo.    .xMMMXc  .;odxxxdoc;'cKMMMMM    //
//    MMMWd  .OMMMMMMNx.  ,KMMMMMMMO. .dMMMMMMMMK;   .,. .;dl.  ',. .xMMMO.  ;KWWWNXXKKKKNMMMMMM    //
//    MMMWd  .OMMMMMMMWd. .dWMMMMMMO. .dWMMMMMMMX;   cXO:.    'dXk. .xMMMXc   .,,,'......;oKWMMM    //
//    MMMWd  .OMMMMMMMWd. .dWMMMMMMO. .dMMMMMMMMK;   cNMWOc.,dXMMk. .xMMMMNkl;'''';::c:,.  'OMMM    //
//    MMMWd  .OMMMMMMWO'  ,0MMMMMMMO. .dWMMMMMMMK;   cNMMMWXNMMMMk. .xMMMWXKNWNNNWWMMMMNl  .dWMM    //
//    MMMWd. .lOOOkxo;.  ;0WMMMMMMMO. .dWMMMMMMMX;   cNMMMMMMMMMMk. .xMMWk'.,coxkO00OOxl.  ;KMMM    //
//    MMMWd.        ..,ckNMMMMMMMMMO. .dWMMMMMMMX;   cNMMMMMMMMMMk. .xMMWOl;..         ..;xXMMMM    //
//    MMMMXkxxxxxxkk0XNMMMMMMMMMMMMNOxkXMMMMMMMMW0xxxKWMMMMMMMMMMNOxkXMMMMMWX0Oxddoodxk0XWMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                  //
//                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////


contract DTMS is ERC721Creator {
    constructor() ERC721Creator("DTMS", "DTMS") {}
}