// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: BLACKblanc
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
//                                                                                     //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:,'.......';:lxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWN0xo:,..    ........     ..,cokKNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMN0d:'.  .':loxkO0KKKKKK00Okdoc;'.  .,cxKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNOo,.  ':dOKNWMMMMMMMMMMMMMMMMMMMWNKko;.  .;dKWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWKd,. .;oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'  .:kNMMMMMMMMMMMMMM    //
//    MMMMMMMMMWKo.  'o0WMMMXOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.  ,dXMMMMMMMMMMMM    //
//    MMMMMMMMXo.  ;kNMMMMMMO'.;d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'  'xNMMMMMMMMMM    //
//    MMMMMMNx'  ,kNMMMMMMMMO.   .,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'  ;0WMMMMMMMM    //
//    MMMMMXl. .dNMMMMMMMMMMO. ,dl'..'ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMWKl. .dNMMMMMMM    //
//    MMMW0;  ;0WMMMMMMMMMMMO. :XMNOo,. .:xKNWMMMMMMMMMMMMMMMMMMMMMMMMWk' .cXMMMMMM    //
//    MMWO,  cXMMMMMMMMMMMMMO. :XMMMMW0d,  .';kWMMMMMMMMMMMMMMMMMMMMMMMW0;  :XMMMMM    //
//    MM0,  lNMMMMMMMMMMMMMMO. :XMMMMWKd'  .;l0WMMMMMMMMMMMMMMMMMMMMMMMMMK;  cXMMMM    //
//    MX:  cXMMMMMMMMMMMMMMMO. :XMMW0l.  ,dXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  oNMMM    //
//    Wo  ,KMMMMMMMMMMMMMMMMO. :XNx;. .:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk. .kMMM    //
//    0' .xWMMMMMMMMMMMMMMMMO. :XKl.  'kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  :XMM    //
//    o  ;XMMMMMMMMMMMMMMMMMO. :XMWKd,. ,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. .kMM    //
//    ;  oWMMMMMMMMMMMMMMMMMO. :XMMMMNOc. .cdkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  oWM    //
//    ' .kMMMMMMMMMMMMMMMMMMO. :XMMMMMMWKc   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo  :NM    //
//    . .OMMMMMMMMMMMMMMMMMMO. :XMMMMMMM0, .,dNMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMd. ;XM    //
//    . .OMMMMMMMMMMMMMMMMMMO. :XMMMMMWO, .dXNMMMMMMMWKl:kWMMMMMMMMMMMMMMMMMWd. ;XM    //
//    ' .kMMMMMMMMMMMMMMMMMMO. :XMMMMWO' .:llkNMMMMW0l.  'OMMMMMMMMMMMMMMMMMWo  :NM    //
//    ;  oWMMMMMMMMMMMMMMMMMO. ;XMMMWO' .do.  ,kNW0l. .;. ;KMMMMMMMMMMMMMMMMX:  oWM    //
//    o  ;XMMMMMMMMMMMMMMMMMO. :XMMWO' .xWWOd:..,:. 'dXNd. :XMMMMMMMMMMMMMMMO. .kMM    //
//    0' .xWMMMMMMMMMMMMMMMMO' :XMWk. .xWMMMMNk;. 'dXMMMNo. cNMMMMMMMMMMMMMNl  :XMM    //
//    Wo  ;KMMMMMMMMMMMMMMMMNOk0WWk. .kWMMMMMMMNOkXMMMMMMNl .oNMMMMMMMMMMMWk. .kMMM    //
//    MX:  cXMMMMMMMMMMMMMMMMMMMWk. .kWMMMMMMMMMMMMMMMMMMMXc .dWMMMMMMMMMM0,  oNMMM    //
//    MM0,  lNMMMMMMMMMMMMMMMMMWx. .kWMMMMMMMMMMMMMMMMMMMMMK: .kWMMMMMMMMK;  cXMMMM    //
//    MMWO,  cXMMMMMMMMMMMMMMMWx. 'kWMMMMMMMMMMMMMMMMMMMMMMMK; 'OMMMMMMM0;  :XMMMMM    //
//    MMMM0;  ;0WMMMMMMMMMMMMWd. 'OWMMMMMMMMMMMMMMMMMMMMMMMMM0, ,0MMMMWk' .cXMMMMMM    //
//    MMMMMXc. .dXMMMMMMMMMMMXd:l0WMMMMMMMMMMMMMMMMMMMMMMMMMMW0lcOWMWKl. .dNMMMMMMM    //
//    MMMMMMNx'  ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'  ;0WMMMMMMMM    //
//    MMMMMMMMXo.  ;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd'  'xNMMMMMMMMMM    //
//    MMMMMMMMMWKo.  'o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.  ,dXMMMMMMMMMMMM    //
//    MMMMMMMMMMMWXd,. .;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'  .:kNMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNOo,.  ':dOKNWMMMMMMMMMMMMMMMMMMMWNKko;.  .;dKWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMN0d:'.  .':loxkO0KKKKKK00Okdoc;'.  .,cxKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN0xo:,..     .......     ..,cokKNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:,'.......';:lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                     //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////


contract BLncK is ERC1155Creator {
    constructor() ERC1155Creator("BLACKblanc", "BLncK") {}
}