// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Editis Editions
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                    //
//                     ..',;,,''''..                                                                                                                                                                                                                                                                                                  //
//                 .''''''''''...'''','.                                                                                                                                                                                                                                                                                              //
//               .';:::cc:;,ld;.......',,.                                                                                                                                                                                                                                                                                            //
//             .,;:odO0o.    ;c.     .  .;:.                                                                                                                                                                                                                                                                                          //
//            ,lcodl'.cl,.    ':'.       .';.                                                                                                                                                                                                                                                                                         //
//           'oxOO;    'll;.   .;;..     ...'.                                                                                                                                                                                                                                                                                        //
//          .dOxdxl.    .:l;.    .''.     ...'.                                                                                                                                                                                                                                                                                       //
//          'dkl.,ol,.    .,,.     ',.     .':l.                                                                                                                                                                                                                                                                                      //
//          .lxl. .;ll'    .,:;.    ','.    .ckc.                                                                                                                                                                                                                                                                                     //
//           ,od;   .cl,     'cc,.   .,,.    'od;                                                                                                                                                                                                                                                                                     //
//           .;oo'   .;lc;.   .;cc'   .;;.    .cl;                                                                                                                                                                                                                                                                                    //
//            .:oo,    ,lol'    ,cc,.   ',..   'oo'                                                                                                                                                                                                                                                                                   //
//             .,lo:.   .cll;.   .;cc.   .,:,.  .;c,                                                                                                                                                                                                                                                                                  //
//               .':l:,. .,cc:,.  .';;,.  .;:,.  .;l;.      ........  ..                                                                                                                                                                                                                                                              //
//                  .,:::.  .;c;..   .:c.   .;;.  .:oolc:,,,'''......:o;                                                                                                                                                                                                                                                              //
//                    .cdo;.  .,;:;.  .:l,   .cc..'lxo;,'''..    .;dKXx.                                                                                                                                                                                                                                                              //
//                     .ldoc,.  .;ll'  .;:'   :kxoddl;.. ...  .:dKNNNW0l.                                                                                                                                                                                                                                                             //
//                      'clll:.   .:l,   .coloo;,,;;;:;'. .,lkKNKx:':xk0O;                                                                                                                                                                                                                                                            //
//                        ..,od,    .,:;,cddc:;'......',;lkXN0o;.    .cxO0c                                                                                                                                                                                                                                                           //
//                           .coo'   .d0Od;. ..''''.';okXWMWk'        .cdoxl.                                                                                                                                                                                                                                                         //
//                             .:doccol:;'.   .',:ok0NWMMMWWNx,.. ....'lkxocc.                                                                                                                                                                                                                                                        //
//                               ;kxc'...  ..':oOXNMMMN0kl,;xNKo:;,,,,,,;lo,,c,                                                                                                                                                                                                                                                       //
//                              .ll,,,,'..':oOXWMWNXOl,.    .dKl.    ..'''cdl,,,.                                                                                                                                                                                                                                                     //
//                              'cc;;;:ldkKNWWNOo:,.         .x0xc;,;::;,'..;c'.,.                                                                                                                                                                                                                                                    //
//                               .c00O0XWMW0o:'               .dKNN0d:'..    'c;...                                                                                                                                                                                                                                                   //
//                                 l0xxNMM0,                   'oxkd;.        .ll;'.                                                                                                                                                                                                                                                  //
//                                  lOclOdoc.               ..,lkkOc            ,llc,.                                                                                                                                                                                                                                                //
//                                  .oOc;:lx:              ;olllcckk:,..;;',:;'..,xOo:;.                                                                                                                                                                                                                                              //
//                                   .ox'.dkd:          .':ol;,.  ckdc'.',..;lxxolk0dccc.                                                                                                                                                                                                                                             //
//                                    .ll..okd,      .';clc;.   .;oo:.       .cOKO0xc:od;.                                                                                                                                                                                                                                            //
//                                      co.,o:;:'...;cc;'.   .,:l:'.          ,xOkOOl,,co;.                                                                                                                                                                                                                                           //
//                                      .lkc,,:loxdll:'    .;lxl'          .,odc. .lO0Okxxc.                                                                                                                                                                                                                                          //
//                                       .d0d,,::oo,.    .:dol,          .cxx:.    'oOKWKOOo.                                                                                                                                                                                                                                         //
//                                        .kNKxxo;;;. ..'co:.         .,lxo,.  'cdOKKKXWWNNO;.                                                                                                                                                                                                                                        //
//                                        .d0k:.',,cooxd:,.        .:kOx:..':dOKX0o;'.'lKWXKKOl.                                                                                                                                                                                                                                      //
//                                         .:lo;. .;lOO:       .,lx00d:;cd0KKOdl,.      cX0::kXO:.                                                                                                                                                                                                                                    //
//                                           .cko,'ldoc:'    .lONN0xookXWN0c.           'ONo..:0N0d,                                                                                                                                                                                                                                  //
//                                            .oX0c,:doxd,.:xXN0kdx0NWWKo;.              oNx.  .o0NXk:.                                                                                                      .:OKOdxkooOKNKxdx0XWWNKd'                 cXk.    .:xXN0c.                                                               //
//                                              .ldc:okkKWNX0kKWWNOo;.                 .,kWK,       'oKNOc.                                                                                                                                                                                                                           //
//                                                    .,xOdkXWWWWk'               .':coONWW0,        ,OWWN0l.                                                                                                                                                                                                                         //
//                                                      .cold0NWWXkl,        .;cokKXXX0xllk0o.   .'ckXWXooKWKo'                                                                                                                                                                                                                       //
//                                                       .:ccoKNko0NKo.  .,lkXNWWN0o'..    ,xOdlx0NWWN0c..xWWWKo'                                                                                                                                                                                                                     //
//                                                         .:kNWXd:ckK0kk0NWNOl;;'.      .:dONWWWWWWWx.  '0WKkOXXx;.                                                                                                                                                                                                                  //
//                                                           .,:dK0c.'cONWWW0,        .,o0NWWNx:;l0NWx.  .ONl .,xXXO:.                                                                                                                                                                                                                //
//                                                               ,x0Ol..lKWW0'    .,lxONWNkllc.   .;x0x, .xK,    .lKNO:                                                                                                                                                                                                               //
//                                                                 .cxxc..lKNO:..o0XWWN0d:.          'ldo:xO'      'oKXx:::'.                                                                                                                                                                                                         //
//                                                                    'okc':KWN00NW0l:,.                'l0Ko.     .:0WWWWWNO,                                                                                                                                                                                                        //
//                                                                     .cO0OXWWWWWNo.                     .o0O:. .:ONWWWWWWWK,                                                                                                                                                                                                        //
//                                                                       .:kKXNWWWWNkl,                   .cKWN0x0NWWWWWWWWW0,                                                                                                                                                                                                        //
//                                                                          ..;dKKkONWXk:.               'dNWWWWWWWWWWWWWWWWO.                                                                                                                                                                                                        //
//                                                                              .cloxkkOK0o'           .oKWWWWWWWWWWWWWWWWWWx.                                                                                                                                                                                                        //
//                                                                                .';::;;oO0x;.       .dNWWWWWWWWWWWWWWWWWWNo                                                                                                                                                                                                         //
//                                                                                    .';;,;xKKx:.   :0NWWWWWWWWWWWWWWWWWWWX:                                                                                                                                                                                                         //
//                                                                                       '::ldOXNOolxXWWWWWWWWWWWWWWWWWWWWWK;                                                                                                                                                                                                         //
//                                                                                         .;loddONWWWWWWWWWWWWWWWWWWWWWKocddc.                                                                                                                                                                                                       //
//                                                                                            .:lox0NWWWWWWWWWWWWWWWWWNKx,  .cdl'                                                                                                                                                                                                     //
//                                                                                               'cxXWWWWWWWWWWWWWWWNO;.,lo;. .;dd;.                                                                                                                                                                                                  //
//                                                                                                 .:xXWWWWWWWWWWWKl:ll'  .coc.  ,dxl,                                                                                                                                                                                                //
//                                                                                                    ,kNWWWWWNklcl;. ,ll,. .cxo,. 'okd:.                                                                                                                                                                                             //
//                                                                                                     .,::cldkc  .:o:..,oxc. .cxd;. .;dxo;.                                                                                                                                                                                          //
//                                                                                                            'ol.  .ldc. ,dkl.  ,lc'   'cdko;.                                                                                                                                                                                       //
//                                                                                                             .:xl.  'dOl..,okc.  'loc.   ,x0Oc.                                                                                                                                                                                     //
//                                                                                                               'odc. .;kOl. 'okl.  'odl'   'lO0o,                                                                                                                              .oOd, .cOk,  ,dOo'  .lxo'   .:xOx;.                  //
//                                                                                                                  .dNXx' .oOd.  ,oOd,  .:do,    .o0k;                                                                                                                                                                               //
//                                                                                                                   .lOXKo. 'xOl.  'oOd'   ,oo,    ;0Xd.                                                                                                                                                                             //
//                                                                                                                     .'oOOo'.c00l.  .lxo'   'lo;   'ONO,                                                                                                                                                                            //
//                                                                                                                        .;k0o..ckOo'  .cxl.   ,oo'  .kW0;                                                                                                                                                                           //
//                                                                                                                          .:Ok, .;k0l.  .cxl'   ,lc. ,OW0;                                                                                                                                                                          //
//                                                                                                                            .okc. .;dd;.  .:dd;.  ':,.lXWO'                                                                                                                                                                         //
//                                                                                                                              ,xk:.  ,odc.  .:kx,   .;xNWNo                                                                                                                                                                         //
//                                                                                                                               .cOkc.  'dkc.  .;lc.  ,OWWWx.                                                                                                                                                                        //
//                                                                                                                                 .ckOd;..,oo;.   ,cll0WWWXl                                                                                                                                                                         //
//                                                                                                                                    ,oOOd:,;cl;..,oKWWWWXo.                                                                                                                                                                         //
//                                                                                                                                      .;okOOkOXXXNWWWNKx;                                                                                                                                                                           //
//                                                                                                                                          .;cdxxxkkxo:.                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract eds is ERC721Creator {
    constructor() ERC721Creator("Editis Editions", "eds") {}
}