// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: years old was thrown
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//     home to die, the reason is not beautiful enough, not smart enough, even if raised to sell out, get the money is not enough to spend on her. Then in follow the same fate of children to join the beggars together this large organization, mixed 4 years to 17 years old, was Ji Xiaoyan to directly occupy. Ji Xiaoyan estimate, she can be so easy to occupy, mostly this child was not willing to live much will, and, he fell down, with Ji Xiaoyan words, this is the life of the! The BEGGARS 'WELFARE OF NEW TIMES IS STILL MUCH GOOD, EVERYONE HAS "UNIT" THE SMALL BEDROOM HOUSING THAT RATIONS, ALTHOUGH NOT HOW, BUT STILL HAVE ROOM GENS AT LEAST! Every month,    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract YOWT is ERC721Creator {
    constructor() ERC721Creator("years old was thrown", "YOWT") {}
}