// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Neural Echos
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd:;:dXMMMMMMMMMMMWKx:,'.':kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx' .:lcdXMMMMMMMMMKl.  .:lolcoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl..lKWMWOOWMMMMMMMO,  .oKWMMMWkxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. lNMMMMXKWMMMMMM0,  .dWMMMMMMXdkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. .xMMMMNdoXMMMMMK;   .xWMMMMMM0,cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   :KWN0c.:NMMMMWd.    'kNMMWXx' cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'    .,'. .dWMMMMNl      .,::;.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.         ;KMMMMMWl              ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        .kWMMMMMMk.            ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:       .kWMMMMMMMK;           'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'    .:0WMMMMMMMMM0;        .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOKWMMN0OK0o::lONMMMMMMMMMMMMNkc,..'cxKWW0xkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'  cXM0; .xWMMWMMMMMMMMMMMMMMMMMMWNNNWMMMWO, 'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xdkOKWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,   .kNk' .oNNK00XWMWNNNWMMNNNNNXXXX00NWX0O0KOl..,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxdOXOc,'.,dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'    .ll;,;cxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.    .oOc. .co:'. ..cKO;.,kWNl'..,,.....,:.   ..,,.. .:xKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    ..     .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'            .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdc'...     ':.   ..  .'.   c:   dWNc    .           'c,.      .,cd0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc             .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'             .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkdl;'...,cdl.              .cl'   ..  .dWWd..  ..   .lOxc:,,:,.           .,coxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.             ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0l.             ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Okdc;,..    .;lxKNNd.                          .dMMOc.   .    cXMMK;     .;:.            ..,:coONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   ..         ,cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNWMWXOo;..        .;c'  .lNMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okdolc;,'..        .,cdOXWMMMNl.             ,oll;'''''.   .xMMKx,   ..    :KMNl     c0Ko.          ....';cdkOOOOOOOO00KXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx' .o0k:.          .:d0Kxold0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNk:...:o:.           .c0N0; .xNMMMMMMMMMMMMMWWNXKOkxolc:;'...                   .;lxOXNWMXl       ,:.     ,dxl,...';.    :0Kd;.    ..    ;0MXo.    ..       ......''......         ..'cOWMMMMWNXXKKKXXNWMMMMMMMMMMMMMMMMMK; .dXNk:.           ..    .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0;                  'o0WXo. .kWMMMMWNXKOkdol:;,...                     .',.           .':l:.    .,xNk.            .lx'     ..        ..    ,OWWKd;..     ..:xOo,.                   'cx0KOxoc:,'.......';cd0NMMMMMMMMMMMMMM0;  ;OWWKo'                 .kMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMK;                .:xXWNk,  ,kWMMMWO:'..                              ,d0NWXOdc,.            .lOO0NMMNx;.       .'l0WWd.              ..    .:KMMMWX0kxxxO0XWMK,         .,coxxdoc;;cll:'.                  .;OWMMMMMMMMMMWWMKl. .c0WMNk:                'xKWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWKkl'               .c0WMW0:. .lKMNKXMM0;                                 .,lkKWMMMNKko:'.     .cOWMMMMMMMMWXOxdoodk0kooodoc:'....;:lo::ccokkxxO0KNMMMMMMMMMMMMMMMX:         'dOOOxoc:'.                          .OMMMMMMMMMNdlKWWk,  .dNMMNk;.               .;oONMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWXx;.                .l0WMMNd.  'kWMXc'xWMMXo.                   .',.            .,lkKNMMMWNKkdc:l0WMMMMMMMMMMMMMMMMMMMK,     '0NXKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.                                             oWMMMMMMMMNc ,0MMXl.  ;OWMMW0c.                .;o0NMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWKd:.                  :KWMMNk;  .cKMMX:  lNMMMWk,              .,cx0NWKx;.             .,cx0NWMMMMMMMWWNXXXXNWWMMMMMMMMMWo      ;KMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNWWMMMMWO:.                        .;:c;.            .dMMMMMMMMWx.  ,OWMNx'  .c0WMMNd,.                 .,oKWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMW0c.                   'oXMMW0:.  'xNNXx,   .x00NWMXl.           .oXMMMMMMMWKd;.              .:0MMNKkoc;'.....',;cdONMMMMM0'      cNMMMMMMMMMMMMMMMMMMMMMN0dl:,'...'',;coxOXWWKd;.                .;cd0XWMMNc            ,KMMMMNkl:::.   .;dXMK:   .lKWWKc.    .               .oXMMMMMMMMMMMMMM    //
//    MMMMMMMMMMXo.                ...   ,kNKc.   ;0WWx'    .:,..'oNMWO;           .;xXMMMMMMMMWKd:.          .:k0kc'.               .,xNMMNl       lKOxolloddOXWMMMMMMMWXo'.                .;lkXNKkoc;'....',:coxOXWMMMMMWKl.           .kWMMWNx.   'l.    .kMMXo.   'od'   ...                  ;0MMMMMMMMMMMMM    //
//    MMMMMMMMMXc             .''.   ...  .,.   ,o0WMWl     ;c.   .lx0NXd.            'o0WMMMMMMMMWKkc'.    .:xxc.                      cXMO.       ..         .;dXMMMMWk'                       .:xXWMWNNNXNNNXkl;;okKKKOd:.            'kWNOl;..     '.    .xMMWNKo.      ...  .::;'.             :XMMMMMMMMMMMM    //
//    MMMMMMMMMk.             ..,cl:. .'.     .oXWWMMN:              .'lOOl.            .:xXWMMMMMMMMMN0dc;cdo,           ..'..          lKc                      'dNMWk.           ....            .l0WMMMN0d:.      ...               :00o,                 oWMMMMW0;    .'. .od:.                .OMMMMMMMMMMMM    //
//    MMMMMMMMWd                  .ok;  ..   ,OWMWWMMK;                 .;dx:.             .ckXWMMMMMMMMMWXd'           ,o0XNN0l.        'c.                        lXX;         'd0KXX0xc.           .lK0l,.                         'dkc.                   cXMMNWMMK,   .. ,kd.           ..     .kMMMMMMMMMMMM    //
//    MMMMMMMMWo     .,.            lO; ..   oWMWXNWNx.                    'od:.              'lkXMMMMMMWO;           'xNMMMMMMK;         .          .;cc,.         .dk.        .OMMMMMMMWKo.           .;.                         .lxc.                   . .cxK0OWMN:  .. .kx.            .;.    .kMMMMMMMMMMMM    //
//    MMMMMMMMWl     ;,             .xx.    .xMNkodc,. ''                    'ox:.               'ckXWMNx.           ;0WMMMMMMMXl..                .cKWMMNd.         ,c.        '0MMMMMMMMMW0;           .:l,.                   .;dkl.                    .l:   .''c0Kc     ;O:              ;;    .kMMMMMMMMMMMM    //
//    MMMMMMMMWl    .:'              lx.     l0l...   .c;                     .lkkc.                .:dl.           :KMMMMMMMMMMWX0Oxolc,.         cNMMMMMX;         .'.        .dWMMMMMMMMMMXc           .oXOl,.             .;d0XKxol;.                   ..    ...dk,     'x;              ;;    .xMMMMMMMMMMMM    //
//    MMMMMMMMWl     :;             .ol      lKo.:;                        .ckK0OKX0o'                             ,0MMMMMMMMMMMMMMMMMMWx.        .kMMMMMMNc          ..         '0MMMMMMMMMMMK,           'OMMWKkoc:;,,,;:ldOXWMNKKWMMWk'                       .dx:xXo      cc             ':.    .xMMMMMMMMMMMM    //
//    MMMMMMMMWl     .:,            ':.  .  'OOlx0;                       'xNMMMMXKWWXx;.           .c,            oWMMMMMMMNK0XNWMMMMMX:         '0MMMMMMNc                      ;0MMMMMMMMMMWl            dWMMMMMMMWWWWWMMMMMMMNNWMMMMMKc.                      ,O0ldo.  .   ''          .,;.     .OMMMMMMMMMMMM    //
//    MMMMMMMMMO'     .';'.       ...   ..  'clO0;                      .l0WMMMMMMWWMMMW0l'        ,OK;            lWMMMMMW0:...';codk0o.         ;XMMMMMMWl.          .           'kNMMMMMMMM0,            oWMMMMMMMMMMMMMMMMMMMWWMMMMMMMNO:..                    .x0o,.  ..   ... .....'',.      ;kWMMMMMMMMMMMM    //
//    MMMMMMMMMMKl.      .'.....  ..   ..   .o0k'                    .:l0WMMMMMMMNXWMMMMMWXkc.   .lXMX:            .ck0K0kc.                      cNMMMMMMWo.          ..           .;d0XNNKOl.            .kMMMMMMMMMMMMMMMMMMMMXkkXWMMMMMMX0O;                    .lKk,   ..        ....       .oNMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWx.                   .. .;k0l.                    .xWWMMMMWX0OolOWMMMMMMMMWXxllOWMMWx.              ...                         oWMMMMMMWd'.         .:,             ..'..               :XMMMMMMMMMMMMMMMMMMMMW0:,:oKMMMMMMMx.                    .'oko,...                  .oNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNl                  .'.,d0o. ....                 ,KMMMMMMWx. ,OWMMMMMMMMMMMMMMMMMMMNl                             ..          .xWMMMMMMMx,.          :k;                               ;0MMMMMMMMMMMMMMMMMMMMMMMKc..kWMWNXNM0'            .,,.'c;;'  cKk:''.                 'OMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWx.                ..,ckKd. .;cxocoddc;'.         cXX00KXXO;.:0MMMMMMMMMMMMMMMMMMMMMMXo.                          :l.          .kMMMMMMMMk;.          .OXl.                           .cKMMMMMMMMMMMMMMMMMMMMMMMMMNd..ckKK0kOx'        .ok0XNWKood;,.  :0Xd,..    ...         ;0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMk'.        ..'.   ..cXKc   .,.;:kNNMMWNO,        'ox0XX0l..lXMMMMMMMMMMMMMMMMMMMMMMMMWO;                       ,xKc           '0MMMMMMMMOc.           oWWO;.                       .;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.'OWMMNk;.       .dWMMNOdxc.  '.   ,k0;..  .;'.        ..;0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMx...         .:,....lk,    '.  .,,,oKWW0;       '.cXMMMWk'cXMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.                 .:kNMO.           ;KMMMMMMMM0o'           ;KMMNOc.                   'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo:0MMMMKc:,       .xN0:.      ..    .d: ..,c.       ..   '0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMx.  ..        .c,. .l;    .'.       .oo'        ;cdWMMMWocKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;'.       .';lkXWMMNl            :NMMMMMMMMKd,           .xMMMMWKxc'.           .;lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXldWMMWKx:.         '.        ..     ,;   ;;         '.  ;KMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMO.  ..        .;.  .,.    ..                    .:kKNMMKlkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Okkkk0KNWMMMNOdc.            ;0WMMMMNOo:,.            .oXMMMMMMNKOxollllodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOdKNKOx:.                ...  .      '.  .,        .'.  ;XMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWx.  .'.       .'   '.        'll:,.....           'coxOdoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.                .oNMMXc                   ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,;''.           'llooxkKX0:        .'   ..     ....   .xWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMX; ..  ....    .   ''        ,0MMWWNXKKOl.              .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                   .OMMk.                    ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'           ..:dKWMMMMMMMMXc        ';.       ...  ..  oWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNc  .'..         ';'        ;KMMMMMMMMMMWKxl;.    .,,',ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                   .OMMk.                    .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kxkx, .;ld0NWMMMMMMMM                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Echos is ERC721Creator {
    constructor() ERC721Creator("Neural Echos", "Echos") {}
}