// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: CosmicLove
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
//                                                                                     //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDTTqQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMP  _RMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ  :@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM%. ,@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM%  `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMD$ymMMMMMMMMMMMMMO. [email protected]    //
//    MMMMMMMMMMMMMMMMMMMu  "@[email protected]:  ZMMMMMMMMMMMWi  vQMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMo  "NMMMMMMMMMMMW;  UMMMMMMMMMMK^  vQMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMQf  [email protected]"  pMMMMMMMMMWt  iWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMQj  [email protected];  aXDQMMMMMHv  |KMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMH*  iWQmw=|:        .:!suZD{  "@MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMR|  ;:   :i{uLTwTLu=!.   .  `%MMMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]"    ;5DMMMMMMMMMMMMMNn:    -=ZMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]    ,LHMMMMMMMMMMMMMMMMMKu'     !AQMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMHn, ``  "XMMMMMMMMMMMMMMMMMMMMMO/   `  !ZMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMME/  vw' -mMMMMMMMWh=^|[email protected]~  vn: [email protected]    //
//    MMMMMMMMMMMMMMMML` ;UMJ  aMMMMMMMZ;  :/,  /OMMMMMMMP. [email protected] _$MMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMQo .oQMM*  $MMMMMMR"  LMMMx  |QMMMMMMQ|  5MME/. LMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMT  cQMMMf;`0MMMMMMH|.`{NKZ/  cMMMMMMMM^ .uMMMm,  TMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMQJ  [email protected] .jMMMMMMMNv'--. .,[email protected]: .UMQw_  5QMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMo. _TQR~..pMMMMMMMMELJzJTNMMMMMMMMMy..|RU!  "$MMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMME|  "hg:_:$MMMMMMMMMMMMMMMMMMMMMMT::'s/  _LWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXj. `|!!_vmMMMMMMMMMMMMMMMMMME1":.. .tPQMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNu".,;: .*%QMMMMMMMMMMMMQ%1`    ;oOMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMQPo/..   [email protected]@NmSLj;    "JZQMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMQmLj".             ."f6NMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMH|..*QMMMMMMMMMMMMMMMMMMMMMX:. oMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMT..-`CMMMMMMMMMMMMMMMMMMMMM=-.._NMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]"..-:/KMMMMMMMMMMMMMMMMMMMP-_'..jQMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMM=.`}s:,oMMMMMMMMMMMMMMMMMMW|::u|`.hMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMO. `E%`.:NMMMMMMZ|||qMMMMMMw..|Hn. ^MMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMML  |QQ^..LMMMMMMs  .;@MMMMMi..nMm. .XMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM^  5MMn  tMMMMMP...  uMMMMM` .mMQ^  nMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMK;  UMMS  "WMMMMs  _  "KMMMW  ;KMMJ  zMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMQ|  nMMP .;KMMM%`-,Z~:,FMMMK  "WMM^  5MMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMML  _P%j`.xMMMMI`.jMn__cMMMM~.:u%u. ,OMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMQy.   ..fWMMMD"..FMN_.'mMMMO^..   :PMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMN6LLANMMMMM6  |WMMt. nMMMMMXqLTUKMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM}  eMMMn  iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQ"  qMMMZ  "DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD_  PMMMm.._NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW" .CMMMZ..;DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMf``tWMHt  zMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    [email protected]|  "I/  !DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMPj/,:|LQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                     //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////


contract CSLV is ERC721Creator {
    constructor() ERC721Creator("CosmicLove", "CSLV") {}
}