// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Editions by Dave Markel
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWWMMMWXNWMMKKWMMWNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc:0MXl'dNMX:'kWXl;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNo.,x:.cXWWWx..o:.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMKxodo'  .lXNdc0Wk.  .lddkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMXo:;;:,..xXo. ,00' ';;;;:kWMMMMMMMMMMMMMMMMMMMMMMKxx0WMMMMMMMMMMMMWNk::kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c:xNMMNOolcdXMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWWMMMWWWNx..,.,:....oNWWWWMMWWMMMMMMMMMMWx;;;cOMMMMo  cNMMMMMMMMMMMMWXd..oNMMMMMMMMMMMMMMMMMMMMMMMMKl;lKMMMMMk'.cXMNo. .;oXMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMXo;kWWx;,,,.  '0Nc   ',,,lKM0cc0MMMMMMMMMO. .. :XMMMo  :NMKxxOkoodONMWW0llOWWOdk0koloONMMMNOdoodONMMO. .OMMMMMKockN0l.  ;dOWW0xoooxKWMNkdOXkoxXMM    //
//    MMMMMWk'.xWX: .cxo'.dx'.cdo' .kWO'.dNMMMMMMMMNc .oc .dWMMo  :NMd  .,'.  cKWNl  cWX;  .''.  oNWk, .;,. ;0MO. .OMMMMMx. ;Xk,.  ';x0c..';. .xW0' ....,OMM    //
//    MMMXkxx: .cko. ,xxc.   ;xxc. :xo. ,dxxKMMMMMWx. :XO. '0MMo  :NMd  ;KWO'  dWWl  cWX;  cXNo  ,K0' .lOO:  cNO. .OMMMMMx. ;XMK, .kMNc  ;k0o. '00' .cO0KWMM    //
//    MMM0:','  .,,.  ','.   .,,.  .,.  .,,,xWMMMMK,  'lc.  cNMo  :NMd  :NMN:  lWWl  cWX;  dMMx. ,Kx. .,,;,..oNO. .OMMMMMx. ;XMK, .kMK,  .;,,'.:K0' .kMMMMMM    //
//    MMMWWWXo.'ONO'.oNNo..'.cXWO,.lXK:.:KWWWMMMMWo  .,,,,. .kWo  ;XMd  ;XWk' .kWWl  cWX;  dMMx. ,KO. .dXXKO0NMO. .kNNNNWx. ;XMK, .kMNc  cKXX0OXW0' .kMMMMMM    //
//    MMMMMWd.,0WO' .,;,.'OK; ';;.  cXXc.cXMMMMMMO. .OWWWNo  ;Xk.  :Kd   ''. 'xNWWl  cWX;  dMMx. ,KWx. .,;'.:XMO.  ....,Ox. ;XMK, .kMMK:  .;,.'kW0' .kMMMMMM    //
//    MMMMMWkl0MWOoodl.  .kK;  .cdddxKMXddNMMMMMMKddOWMMMMXxdxXWOolxNd  .lodkXMMMW0dd0WWOdxKMMXxdONMWXkollod0NMXkddddddxKKxdONMNkoxXMMMNOdolldkXWNkoxXMMMMMM    //
//    MMMMMMWWWX0000Oc.;l....::.;k0000OKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMd  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMKl,,,.. .xWk..lN0'  .',,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxdOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMNXKXk,...'OWOkNXc....xXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMK:.lXx..kWMXc.cKd.'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXxxNMWOlxNMXooXMWOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract EDN is ERC1155Creator {
    constructor() ERC1155Creator() {}
}