// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Highley Reviewed
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxolc:;;,,,,,,,,,,,;;:clodk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdl:,'''',;::clllooooooolllc::;,'''',;cdkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc,''';:loxkkOOOOOOOOOOOOOOOOOOOOOOOkkxdlc;,'',:okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'.';coxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxdl;'.';oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNOo,.';ldkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxl;'.,ckXWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0o,.':odoc:;;,;lxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkoc'.'lONMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNk:..:oxd:'',:ccc,.'lkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd:'.;dXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXd,.'lxkd:.':okOOOOkc.'oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxl,.'oKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXd'.,okOko'.:xOOOOOOOOx:.;xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd;.'oKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNk,.,okOOOo'.ckOOOOOOOOOOl..oOOOOOOOkl:okOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl. 'dXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0:..lkOOOOx;.;xOOOOOOOOOOOd,.:kOOOOOOd'.lkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxl;'';,.;OWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNd..:xOOOOOOx,.ckOOOOOOOOOOOk;.;xOOOOOkc.,dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdc'':dOK0o..oXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc..lkOOOOOOOk:.,dkkkkOOOOOOOkc.'dOOOOOx,.ckOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxc''cx0KKKKKx;.;0WMMMMMMMMMMM    //
//    MMMMMMMMMW0;.,dOOOOOOOOOOxc'',;;lkOOOOOOkc.'dOOOOOl.'oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl'.:x0KKKKKKKKOc.'kWMMMMMMMMMM    //
//    MMMMMMMMW0,.:xOOOOOOOOOOOOkxolloxkOOOOOOkl.'oOOOOk:.;xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd;.,d0KKKKKKKKKKK0l..xWMMMMMMMMM    //
//    MMMMMMMM0,.:xOOOOOOOOOOOOOOOOOOOOOOOOOOOkl.'dOOOOd,.:oolodkOOOOOOOOOOOOOOOOOOOOOOOOOOOkl'.ckKKKKKKKKKKKKKK0o..xWMMMMMMMM    //
//    MMMMMMMK;.;xOOOOOOOOOOOOOOOOOOOOOOOOOOOOkc.,dOOkd:...',,,',lxkOOOOOOOOOOOOOOOOOOOOOOOx:.,o0KKKKKKKKKKKKKKKK0l..kMMMMMMMM    //
//    MMMMMMNc.,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOk:.,oo:,'..,okO0Oo..,lkOOOOOOOOOOOOOOOOOOOOko,.:kKKKKKKKKKKKKKKKKKKK0c.,0MMMMMMM    //
//    MMMMMWx..oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOx;...';lo,.c0KKKK0l..,xOOOOOOOOOOOOOOOOOOOkc.'lOKKKKKKKKKKKKKKKKKKKKKk,.lNMMMMMM    //
//    MMMMMK,.ckOOOOOOOOOOOOOOOOOOOOOOOOOOOkxl,..;ok0Kk,.oKKKKKKx, .lOOOOOOOOOOOOOOOOOOd;.,x0KKKKKKKKKKKKKKKKKKKKKKKd..kMMMMMM    //
//    MMMMWd.'dOOOOOOOOOOOOOOOOOOOOOOOOOOko:'...,xKKKKx'.dKKKKKKO:..:kOOOOOOOOOOOOOOOko,.:kKKKKKKKKKKKKKKKKKKKKKKKKKO; cNMMMMM    //
//    MMMMX; :kOOOOOOOOOOOOOOOOOOOOOOOOxl,.,co;.:OKKKKd''dKKKKKK0l..,xOOOOOOOOOOOOOOkl..lOKKKKKKKKKKKKKKKKKKKKKKKKKKKo.'OMMMMM    //
//    MMMMk..oOOOOOOOOOOOOOOOOOOOOOOOxl,.,lxOd'.oKKKKKd.'xKKKKKKKo,.'dOOOOOOOOOOOOOx:.'o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKk'.dWMMMM    //
//    MMMWd.'dOOOOOOOOOOOOOOOOOOOOOOd;.,lxOOk:.;OKKKKKx''dKKKKKKKd;..oOOOOOOOOOOOOx;.'d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKK0: cNMMMM    //
//    MMMWl ,xOOOOOOOOOOOOOOOOOOOOOOxookOOOOo'.oKKKKKKk,.dKKKKKKKd:'.lOOOOOOOOOOOx;.,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0c :XMMMM    //
//    MMMNc ;kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOk:.:OKKKKKKO;.l0KKKKKKx:'.lOOOOOOOOOOx;.,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl.;KMMMM    //
//    MMMNc ;kOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl.'dKKKKKKK0l.;OKKKKKKxc'.lkOOOOOOOOx:.'xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl.;XMMMM    //
//    MMMNl ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOd,.l0KKKKKKKKx'.dKKKKKKxc'.lkOOOOOOOkc.'dKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0c :XMMMM    //
//    MMMWd.'dOOOOOOOOOOOOOOOOOOOOOOOOOOOx:.;OKKKKKKKKKO:.:OKKKKKxl,.lOOOOOOOkl..o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0: cNMMMM    //
//    MMMMO..oOOOOOOOOOOOOOOOOOOOOOOOOOOkc.,xKKKKKKKKKKKx,;xKKKKKkl,.lOOOOOOOd'.c0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk,.dWMMMM    //
//    MMMMX; :kOOOOOOOOOOOOOOOOOOOOOOOOko.'d0KKKKKKKKKKKKOO0KKKKKkl,.lOOOOOOx;.;kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..OMMMMM    //
//    MMMMWd.'dOOOOOOOOOOOOOOOOOOOOOOOOo'.l0KKKKKKKKKKKKKKKKKKKKKkl,.lOOOOOkl.'xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKO: cNMMMMM    //
//    MMMMMK,.ckOOOOOOOOOOOOOOOOOOOOOOd,.l0KKKKKKKKKKKKKKKKKKKKKKxl'.lOOOOOd'.l0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKd..kMMMMMM    //
//    MMMMMWd..oOOOOOOOOOOOOOOOOOOOOOd,.cOKKKKKKKKKKKKKKKKKKKKKKKxc'.oOOOOk:.;kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk,.lNMMMMMM    //
//    MMMMMMXc.,xOOOOOOOOOOOOOOOOOOOd,.cOKKKKKKKKKKKKKKKKKKKKKKKKxc'.oOOOOo'.oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0c.,KMMMMMMM    //
//    MMMMMMMK;.:xOOOOOOOOOOOOOOOOOd,.cOKKKKKKKKKKKKKKKKKKKKKKKKKd:'.oOOOk:.:OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0l.'OMMMMMMMM    //
//    MMMMMMMM0,.:kOOOOOOOOOOOOOOOd,.cOKKKKKKKKKKKKKKKKKKKKKKKKKKd:.'oOOOo..dKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o..kWMMMMMMMM    //
//    MMMMMMMMWO,.:xOOOOOOOOOOOOko'.lOKKKKKKKKKKKKKKKKKKKKKKKKKKKd;.'dOOx;.:OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0l..kWMMMMMMMMM    //
//    MMMMMMMMMW0;.,dOOOOOOOOOOkl'.o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKd;.'dOkl.,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOc.'kWMMMMMMMMMM    //
//    MMMMMMMMMMMKc.'okOOOOOOOkc.'d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKd:''oOo'.o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;.;0WMMMMMMMMMMM    //
//    MMMMMMMMMMMMNx..:xOOOOOx:.,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKxl,.lo'.c0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o..oXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0:.'lkOOd;.;kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOx:.''.lOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0x;.;OWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNk,.,oo,.cOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOl;:d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk:.'dXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXd'...l0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0x:..lKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXd,.,oOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d;.'oKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNk:..:d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kl'.;dXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0o,.'cxOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kl,.'lONMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNOl,.':ok0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Odc,.,lkXMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'',:oxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdc;'':oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc,'',:ldkO0KKKKKKKKKKKKKKKKKKKKKKKKK0Okdlc;,',:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdl:;,,,;;:clooddxxxxxxdddoolc:;,,'',;cokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxolc::;;,,,,,,,,,,;;:clodk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXXNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HVRV is ERC721Creator {
    constructor() ERC721Creator("Highley Reviewed", "HVRV") {}
}