// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Six N. Five x LG Art Lab
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//    The artist Ezequiel Pini, known as Six N. Five, has garnered international acclaim for his pioneering use of 3D technology in creating immaculate and dreamlike worlds of digital art. His works invite viewers to momentarily pause between two worlds – one physical and the other digital – for moments of respite, contemplation and rejuvenation. The five works in this exhibition, created specifically for the collaboration with LG Art Lab, explore Six N. Five’s preoccupation with windows on other worlds and the transfigurative skies that rise above them. For years, the artist has tried to combine different disciplines to reinterpret the sky and its immensity beyond perceived limits, and he has taken this opportunity as a new canvas to create his own realities: “Among The Sky.” Among The Sky is co-curated by Six N. Five and Derrick Li; supported by Triple X.     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SIXnFIVE is ERC721Creator {
    constructor() ERC721Creator("Six N. Five x LG Art Lab", "SIXnFIVE") {}
}