// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: JYD
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                ';,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,.                   .:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:.                                                              .',,,,,'',,''''''''''''''''''''''''''''',,,.    //
//                                               .dKKOkkxxxxxxxxxxxxkkkkkkkkkkOOOOOOOOO00000kl,.                 ;KWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXc                                                           ...;oxddddddddddddddddddddddddddddddddddxkkO0k,    //
//                                               .xXXXXK0OkxxxxxxxxxxxxkkkkkkkkkkkOOOOOO0000kddl,.               ;KWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXc                                                        ......;odddddddddddddddddddddddddddddxxkkOO00000O;    //
//                                               .xXXXXNXXK0OOkkxxxxxxxxxkkkkkkkkkkOOOOOOOOOxooddl,.             ;KWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXc                                                    ..........,oddddddddddddddddddddddddxxkkOO0000000000O;    //
//                                               .xXXXNNNNNNXXK0OkkxxxxxxxxxkkkkkkkkkkOOOOOOxllooddl,.           ;KNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXc                                                 .............,lddddddddddddddddddxxxkkOO0000KKKK0000000O;    //
//                                               .xNNNNNNNNNNNNXXK00OkkkkxxxxkkkkkkkkkkkOOOOdllloodddl,.         ;KNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNXc                                              ...'............,lddddddddddddxxxxkkOO000KKKKKKKKKKK000000O;    //
//                                               .xNNNNNNNNNNNNNNNNXXK0OkkkkkkkkkkkkkkkkkkOkdccclloooddl,        ;KNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNXc                                           ...''..............,lxxxxxxxxxxxkkOO000KKKKKKKKKKKKKKKKK00000O;    //
//                                               .xNNNNNNNNNNNNNNNNNNNXXK00Okkkkkkkkkkkkkkkkoc:ccclloooddl'      ;KNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNXc                                       ...''...............'',:oxxxxxkkOOO000KKKKKKKKKKKKKKKKKKKKKK00000O:    //
//                                               .kNNNNNNNNNNNNNNNNNNNNNNNXKK0OOkkkkkkkkkkkko::::ccclloooddl'    ;KNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNXc                                    ...'''.............'',;cldxkkkOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00O:    //
//                                               .kNNNNNNNNNNNNNNNNNNNNNNNNNNXXK00OOkkkkkkkxl;;:::::cclllooddl,  :KWNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNXc                                 ..''''............'',:coxO0KKK000KKKKKKXXXXXXXKKKKKKKKKKKKKKKKKKKKKKK0KO:    //
//                                               .kNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNXKK0OOkkkkxo:;;;;;:::cclllooddl,lXNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNXc                             ...'''''.........'',;:ldkOKKXXXXXXXKXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKK0KO:    //
//                                               .kNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNNNXXK0OOkkOkoc:;;;;;::cccllooddONWNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNWXc                          ...''''.........'',;coxO0KXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK0K0:    //
//                                               .kNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWNNNXK00XNX0koc:;;;;::cccllodONWNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNWXc                       ..'''''''.....''',:ldkOKXXNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKK0c    //
//                                               .kNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXNWWWNX0koc:;;::::ccllkNWWWWNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNWWWWNc                   ...''''''''...'',;:ldk0XXNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKK0c    //
//                                               .kNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWX0koc:;;;::cckXNNWWNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNWWWWWNl                ...''''''''..'',;coxOKXNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK0c    //
//                                               .kNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMWWN0koc:;;::xXNNNWWWNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNNWWWWWWMNl             ..''''''..'''',:ldk0XNNWWWWWWWWNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK0c    //
//                                               .kNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMWNKkoc::dKXNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNWWWWWWMMNl         ...'''''''''',;coxOKXNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0c    //
//                                               .kNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMWNKkox0KKXXNNNNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNWWWWWMMMMMWl      ...''''''''',;cok0XNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0c    //
//                                               .ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMWNK0000KXXXNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNWWWWWWMMMMMMWl   ..''''''''',:ldOKXWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0c    //
//                                               .ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMX0OOO00KKXXXNNNNNNNNXXNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXNNNNNWWWWWMMMMMMMMWd..''''''',;cox0XNWMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0l    //
//                                               'ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOOOOO00KKXXXNNNNNXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXXXNNNNWWWWMMMMMMMMMMWk,'''',;cdk0XWMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0l    //
//                                               'ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKK0KKKKXXXNNNNNNNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNWWWWMMMMMMMMMMMMWXd,,:lxOKNWMMMMMMMMMWXXXNNXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKXXXNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0l    //
//                                               'ONNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWWWWMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMWN0kxddk0XWMMMMMMMMWNK0kdoclxkkkkkkkkkkkkkxxxxxxxxxxxkkkkkkOO000KKKXXXNNNNXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0l    //
//                                               'ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMWNKOxxxOKNWMMMMMMWNK0kxoc:;,,,,cdxxxxxxxxxxxxxxkkkkkOOO000KKKXXXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0l    //
//                                               'ONNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMWNKOkkkOKNWMMMMWNX0kxoc:;,,,,'''''':dxxkkkkkkOOO000KKKKXXXNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0000l    //
//                                               'ONNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMNK0OOO0XWMMMWNX0Oxol:;,,,''''',,;:clodxOO000KKKXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK00000l    //
//                                               'ONNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMNXK000KNWMWNX0Oxoc:;,,,,,,,;:clodxkO0KXNNNNXXNNNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK000000000l    //
//                                               'ONNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWMMMMMMMMMMMMMMMMMWWWWWMMMMWXKKKKXNWNXKOxol:;,,,,;:clodxk0KKXNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK00000000000l    //
//                                               'ONNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNWWWMMMMMMMMMMMMMWWNNWWWWNXXXXXNXKOxol:;;;:clodxO0KXNNWWWMMMMMMWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0000000000000000Ol    //
//                                               'OXXXXXXXXXNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXNNWMMMMMMMMWWNNXXNNNNXXK0OxdolclloxkO0KXNWWMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0000000000000000000OOOOOl    //
//                                               'kKKKXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKKXXNNXNXXXKKKXKK0OOkxxxxkO0KXNWWMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK0000000000000000000OOOOOOOOOOOOOOOl    //
//                                               'x00000KKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0OkkxkkkOO0KKK000KXNWWMMWMMMWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkc    //
//                                               .dkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOO0000000000000000000000000000OOOOOOOOOOOOOOkxoc::clldxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkkxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddd:    //
//                                               .looooooooooooodddddddddddddddddddooddooodoolllllllllllllllllcccccccccc:::::::::;;;;:::::::::::;;;,,;:cc,...,:;;;;;;;:ccllooollcc::::::::::::::::::ccccccccccccclllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllll;    //
//                                               .:ccccccccccccccccccccccccccccccccccccccccc:;;;;;,,,,,,,,,,,,,,,,,'',,,,,,,;;;;:::::::;;,,'''....,coxxl'   ..,,,'''......';:cllodddxdddollc::;;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc,    //
//                                               .;::::::::::::::::::::::;::::;::::;;;;;;;;;,'''''''''''''',,,,,;;;;:::cccccc::;;,,'.........';ldOKK0d,     ...'''..''''..........',;:lodxxkOOOOkkxxdollc::;;,,,,''''''''''',;::::::::::::;::::::;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;:;'    //
//                                               .,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',,,,;;;::::cccccccccc::;;,''..............':lx0XNNX0o,        ...........''''..... .........',;:codxkO00KKK00Okkxddollc::;;,,;ccccccc::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'    //
//                                               .',,,,,,,,,,,,,,;;;;;;;;;;;;;;;;:::::::::::::cccccllllccc::;;;,''...................,:ok0XNNNXKOo'          ..............''''''....   ............',;:codxkO00KKXXKK00OOkxxxdddddoooollllccccc:::::;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.    //
//                                               .',,,,,,,;;;;;;;;;;;;;:::::::::::::::::::::ccccc::;;,,''.......................';cdkKXNWNNNXKOl'            .................'',,,,'......  ................',;:clodxkO0KKX0kdxxxxxxxxxxxxdddddooolllllcccc::::;;;;;,,,,,,,,,'''''''''''''''''''''''''''''''''''.    //
//                                               .,;;;;;;;;;::::::::::::::::::::;;;;;,,,,,''''''............................';ldOKXNWNNNNXK0kl'              ....................''',,,,'....    .....................',;:cll:::cclloodddxxxxxxxxxxxxxxxddddoooollllccc:::;;;;;,,,,,''''''''''''''.''''.....'''''.    //
//                                   ......'',;;:::::::::::::::::::::;;;;;;,,,'''''.....................................,:lxOKXNNNWNNNXXK0kl'                .......................''',,;,,'....    ..  .......................'''',,;;;:cclloodddxxxkkkkkkkxxxxxxxddddooooolllccc:::;;;,,,'''''.................    //
//                     ......'',,;;::ccclllllllllc:::::::::;;;;;,,,'''''...........................................',:oxOKXNNNNNNNNXXK0Oxc'                  ..........................''',,,;;,'....   .   .   .............................''',,;;::cllooddxxxkkkkkkkkxxxxxxxxdddddoooolllcc:::;;,,,''..........    //
//         ......'',,;;::::cccccccccccccccccccccc:;;,,,''''....................................................';coxOKXNNNNNNNNNNXXK0Oxc'                    .............................''',,;;;;,'...        ..........................................'',,;;:cclooddddddddddddddddddooooooooolllccc::;;;,'''..    //
//      ...................................................................................................,;cox0KXNNNNNNNNNNNXXK0OOxc.                      ............................'',,,;;;;;;;;,..                   ...................................................................................       //
//     ...................................................................................'...........',:ldk0KXNNNNNNNNNNNNXXKK0Okdc.                        ..............................'',,,;;;;:;;'.           .       ...........................................                                               //
//      ..............................................................................''',;;......',:ldk0KXNNNNNNNNNNNNNXXKK0OOkdc.                          .................................'',,,;;;;'....                ...........................................                                               //
//      ..........................................................................'',,;::cll;'';:ldk0KXXNNNNNNNNNNNNXXXXKK0Okxdc.                            ...................................''',,;;:;'.......           ...........................................                                               //
//      .....................................................................'',,;;:clloddxdoodk0KXXXNNNNNNNNNNNNXXXXKK00Okxdc.                              ......................................'',,okxo:'......         ...........................................                                               //
//      ................................................................''',,;:cclooddxxxxkkOKKXXXXXNNNNNNNXXXXXXXKK00Okkxd:.                                ........................................''lO00Oxo:'......       ..........................................                                               //
//      ............................................................'',,;;:cllooddxxxxxkkkkkKXXXXXXXXXXXXXXXXXXKK00OOkxxd:.                                  ..........................................ck00000Oxo:,.......  .....................................                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JYD is ERC721Creator {
    constructor() ERC721Creator("JYD", "JYD") {}
}