// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Makisarts
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    .......................................................................................................................................................................................................................................................................................................... .    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                           .lxl.                                                                                                                                                                                                                                                                    //
//                                         .lKWMWKl.                                                                                                                                                                                                                                                                  //
//                                         cXMMMMMXl.                                                                                                                                                                                                                                                                 //
//                                          ,xXMNx,                                                                                                                                                                                                                                                                   //
//                                   .'.      ,c,      .'.                                                                                                                                                                                                                                                            //
//                                 .lKN0c.           .:ONKo.                                                                                                                                                                                                                                                          //
//                               .lKWMMMWOc.       .:OWMMMWKo.                                                                                                                                                                                                                                                        //
//                             .lKWMMMMMMMW0c.   .:OWMMMMMMMWKo.                                                                                                                                                                                                                                                      //
//                           .lKWMMMMMMMMMMMW0c':OWMMMMMMMMMMMWKo.                                                                                                                                   ....                                                                                     ....                    //
//                         .lKWMMMMMXxlxNMMMMMWNWMMMMMNklxXMMMMMWKo.                        ,xkkkkl.            .okkkkk:           .lkkkkx;            ckkkkkd.      .okkkkkd,    ;xkkkx;      .,cdk0KKK0Okoc'   :kkkkkl.          ;xkkkkc.  :kkkkkkkkkkxdo:.     .okkkkkkkkkkkkkkx;     'cdk0KKKK0kdc,.              //
//                       .lKWMMMMMXx,   ,xNMMMMMMMMMNk;   'dXMMMMMWKo.                      cWMMMMWk.          .xWMMMMWo           lNMMMMM0,          .xMMMMMK,    .lKWMMMNk,     oWMMMNl     ;ONMMMMMMMMMMMWO'  ,0MMMMXc         .OMMMMX:  .dWMMMMMMMMMMMMWXk;   '0MMMMMMMMMMMMMMWo   ,xXMMMMMMMMMMMW0,              //
//                     .lKWMMMMMXx,       ,xNMMMMMNk;       'dXWMMMMWKo.                    cNMMMMMWk'        .kWMMMMMWo          ;KMMMMMMWk.         .xMMMMMK,  .:0WMMMWO;       oWMMMNl    cXMMMMN0kdxk0XNO,    cXMMMMO'        oWMMMNo.  .dWMMMWKkxkk0NMMMMNo. .lxxxkXMMMMWKkkkx;  ;KMMMMWKkxdxOKN0;               //
//                   .lKWMMMMMXx,           ,xNMNk;           'dXMMMMMWKo.                  cWMMMMMMWO,      .kWMMMMMMWo         .OMMMWNWMMNo.        .xWMMMMK, ;kNMMMW0c.        oWMMMNl   .kMMMMNl.     .,.     .dWMMMWkcccccccdXMMMWk.   .dWMMMNc    .:0MMMMX;      .oWMMMNc      .dWMMMWd.     .,.                //
//                 .oKWMMMMMXx,      ..       ,l;       ..      'dXMMMMMWKo.                cNMMMMMMMW0,    'kWMMMMMMMWo        .dWMMWklKMMMX:        .xMMMMMXdxNMMMWKl.          oWMMMNl   .xMMMMNd.              .OMMMMMMMMMMMMMMMMMK,    .dWMMMNc     .xWMMMX:       oWMMMN:       dWMMMWx'                        //
//               .oKWMMMMMXx,      .cOXk;.            ;kX0c.      'dXMMMMMWKo.              cWMMMWKKMMMK;  'OWMMXKNMMMWo        cXMMMK;.oWMMM0'       .xMMMMMMWMMMMNd.            oWMMMNl    :XMMMMWKxl;..          ;KMMMMMWNNNNWMMMMNc     .dWMMMNo....,dXMMMMO'       oWMMMN:       ,0MMMMWXko:'.                   //
//             .lKWMMMMMXx,      .cOWMMMNk;.        ;kNMMMW0c.      'dXMMMMMWKl.            cWMMMNo;OWMMKc,OWMMK:cXMMMWo       ,0MMMWo  'OMMMWx.      .xMMMMMMMMMMMNo.            oWMMMNl     ;ONMMMMMMWX0d:.        lNMMMWx,''lXMMMWd.     .dWMMMMNXXXXWMMMMWO,        oWMMMN:        ,xNMMMMMMWN0xc.                //
//             .c0WMMMXx,      .c0WMMMMMMMNk;.    ;kNMMMMMMMW0c.      'dXMMMW0c.            cWMMMNl 'OWMMNXWMM0; :XMMMWo      .xWMMMXo,,;kWMMMNl      .xMMMMMMMMMMMMWk'           oWMMMNl      .,lkKNMMMMMMWKl.      .xWMMMO' .dWMMWO'      .dWMMMWXNMMMMMN0d;.         oWMMMN:          'lkKNMMMMMMWXd.              //
//               .l0Kx,      .c0WMMMMMMMMMMMNk;.;kNMMMMMMMMMMMW0c.      'dK0c.              cWMMMNl  .kWMMMMW0,  :XMMMWo      lNMMMMMWWWWWMMMMMK;     .xMMMMMWOoOWMMMMKc.         oWMMMNl          .,cd0WMMMMNo.      '0MMMWo.;XMMMX:       .dWMMMNolXMMMMK:            oWMMMN:             .':o0NMMMMWx.             //
//                 ..      .c0WMMMMMNkoONMMMMMNXNMMMMMWOoxXMMMMMW0c.      ..                cNMMMNl   .xNMMWO'   :XMMMWo     ;KMMMMWWWWWWWWMMMMMO.    .xMMMMMX; .oXMMMMNx.        oWMMMNl              .lXMMMM0'       :XMMMKokWMMNo        .dWMMMNc ;0MMMWK:           oWMMMN:                 .:KMMMMK;             //
//                       .c0WMMMMMNx,  .:ONMMMMMMMMMWO:.  ,xXMMMMMW0c.                      cWMMMNl    .oKXx'    :XMMMWo    'OMMMMKl;;;;;;:xWMMMWd.   .xMMMMMK,   ;OWMMMW0:       oWMMMNl     ,do;..    :KMMMMO.       .oNMMWWWMMWk.        .dWMMMNc  ,OWMMMXo.         oWMMMN:        .od:..    ,0MMMMK,             //
//                      .oNMMMMMNx,      .:ONMMMMMWO:.      ,xXMMMMMNo.                     cNMMMWo      ..      cNMMMWo   .dWMMMNl        .OMMMMXc   .xMMMMMK,    .dNMMMMXo.     oWMMMNl   .lXMMWX0kkkOXMMMMXc         .kWMMMMMMK,         .dWMMMNc   .xWMMMNx.        oWMMMN:       :0WMWX0kkkOXWMMMNo.             //
//                       .c0WMNx,          .:ONMNO:.          ,xXMW0c.                      cWMMMWd              lNMMMWo   cXMMMMk.         cXMMMMK,  .xMMMMMK,      :0WMMMWO,    oWMMMNl   .l0NMMMMMMMMMMMNO:           ,0MMMMMNc          .dWMMMNc    .dNMMMW0,       oWMMMN:      .cONWMMMMMMMMMMW0c.              //
//                         .co,      ..      .;o:.      ..      ,lc.                        ,dxxxx;              ,dxxxx;  .cxxxxd,          .cxxxxx;   :xxxxxo.       .oxxxxxl.   ;xxxxd,     .,coxO000Okdc,.             ;dxxxxc.           ;xxxxd,     .:xxxxxl.      ;xxxxd'        .':oxO000Okdl;.                //
//                                 .;kKk;             ,xKO:.                                                                                                                                         .                                                                                        .                       //
//                                ;kNMMMNk;         ,xNMMMNO;                                                                                                                                                                                                                                                         //
//                                :0WMMMMMNk;     ,xNMMMMMW0:                                                                                                                                                                                                                                                         //
//                                 .c0WMMMMMNk;.;kNMMMMMW0c.                                                                                                                                                                                                                                                          //
//                                   .c0WMMMMMNKNMMMMMW0c.                                                                                                                                                                                                                                                            //
//                                     .c0WMMMMMMMMMW0c.                                                                                                                                                                                                                                                              //
//                                       .c0WMMMMMW0c.                                                                                                                                                                                                                                                                //
//                                         .c0WMWOc.                                                                                                                                                                                                                                                                  //
//                                           .cd:.                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    ............................................................................................................................................................................................................................................................................................................    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MKS is ERC721Creator {
    constructor() ERC721Creator("Makisarts", "MKS") {}
}