// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: JTBOLLY COLLECTIBLES
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//              JJJJJJJJJJJTTTTTTTTTTTTTTTTTTTTTTTBBBBBBBBBBBBBBBBB        OOOOOOOOO     LLLLLLLLLLL             LLLLLLLLLLL         YYYYYYY       YYYYYYY             CCCCCCCCCCCCC     OOOOOOOOO     LLLLLLLLLLL             LLLLLLLLLLL             EEEEEEEEEEEEEEEEEEEEEE       CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTIIIIIIIIIIBBBBBBBBBBBBBBBBB   LLLLLLLLLLL             EEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS     //
//              J:::::::::JT:::::::::::::::::::::TB::::::::::::::::B     OO:::::::::OO   L:::::::::L             L:::::::::L         Y:::::Y       Y:::::Y          CCC::::::::::::C   OO:::::::::OO   L:::::::::L             L:::::::::L             E::::::::::::::::::::E    CCC::::::::::::CT:::::::::::::::::::::TI::::::::IB::::::::::::::::B  L:::::::::L             E::::::::::::::::::::E SS:::::::::::::::S    //
//              J:::::::::JT:::::::::::::::::::::TB::::::BBBBBB:::::B  OO:::::::::::::OO L:::::::::L             L:::::::::L         Y:::::Y       Y:::::Y        CC:::::::::::::::C OO:::::::::::::OO L:::::::::L             L:::::::::L             E::::::::::::::::::::E  CC:::::::::::::::CT:::::::::::::::::::::TI::::::::IB::::::BBBBBB:::::B L:::::::::L             E::::::::::::::::::::ES:::::SSSSSS::::::S    //
//              JJ:::::::JJT:::::TT:::::::TT:::::TBB:::::B     B:::::BO:::::::OOO:::::::OLL:::::::LL             LL:::::::LL         Y::::::Y     Y::::::Y       C:::::CCCCCCCC::::CO:::::::OOO:::::::OLL:::::::LL             LL:::::::LL             EE::::::EEEEEEEEE::::E C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TII::::::IIBB:::::B     B:::::BLL:::::::LL             EE::::::EEEEEEEEE::::ES:::::S     SSSSSSS    //
//                J:::::J  TTTTTT  T:::::T  TTTTTT  B::::B     B:::::BO::::::O   O::::::O  L:::::L                 L:::::L           YYY:::::Y   Y:::::YYY      C:::::C       CCCCCCO::::::O   O::::::O  L:::::L                 L:::::L                 E:::::E       EEEEEEC:::::C       CCCCCCTTTTTT  T:::::T  TTTTTT  I::::I    B::::B     B:::::B  L:::::L                 E:::::E       EEEEEES:::::S                //
//                J:::::J          T:::::T          B::::B     B:::::BO:::::O     O:::::O  L:::::L                 L:::::L              Y:::::Y Y:::::Y        C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E:::::E            C:::::C                      T:::::T          I::::I    B::::B     B:::::B  L:::::L                 E:::::E             S:::::S                //
//                J:::::J          T:::::T          B::::BBBBBB:::::B O:::::O     O:::::O  L:::::L                 L:::::L               Y:::::Y:::::Y         C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E::::::EEEEEEEEEE  C:::::C                      T:::::T          I::::I    B::::BBBBBB:::::B   L:::::L                 E::::::EEEEEEEEEE    S::::SSSS             //
//                J:::::j          T:::::T          B:::::::::::::BB  O:::::O     O:::::O  L:::::L                 L:::::L                Y:::::::::Y          C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E:::::::::::::::E  C:::::C                      T:::::T          I::::I    B:::::::::::::BB    L:::::L                 E:::::::::::::::E     SS::::::SSSSS        //
//                J:::::J          T:::::T          B::::BBBBBB:::::B O:::::O     O:::::O  L:::::L                 L:::::L                 Y:::::::Y           C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E:::::::::::::::E  C:::::C                      T:::::T          I::::I    B::::BBBBBB:::::B   L:::::L                 E:::::::::::::::E       SSS::::::::SS      //
//    JJJJJJJ     J:::::J          T:::::T          B::::B     B:::::BO:::::O     O:::::O  L:::::L                 L:::::L                  Y:::::Y            C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E::::::EEEEEEEEEE  C:::::C                      T:::::T          I::::I    B::::B     B:::::B  L:::::L                 E::::::EEEEEEEEEE          SSSSSS::::S     //
//    J:::::J     J:::::J          T:::::T          B::::B     B:::::BO:::::O     O:::::O  L:::::L                 L:::::L                  Y:::::Y            C:::::C              O:::::O     O:::::O  L:::::L                 L:::::L                 E:::::E            C:::::C                      T:::::T          I::::I    B::::B     B:::::B  L:::::L                 E:::::E                         S:::::S    //
//    J::::::J   J::::::J          T:::::T          B::::B     B:::::BO::::::O   O::::::O  L:::::L         LLLLLL  L:::::L         LLLLLL   Y:::::Y             C:::::C       CCCCCCO::::::O   O::::::O  L:::::L         LLLLLL  L:::::L         LLLLLL  E:::::E       EEEEEEC:::::C       CCCCCC        T:::::T          I::::I    B::::B     B:::::B  L:::::L         LLLLLL  E:::::E       EEEEEE            S:::::S    //
//    J:::::::JJJ:::::::J        TT:::::::TT      BB:::::BBBBBB::::::BO:::::::OOO:::::::OLL:::::::LLLLLLLLL:::::LLL:::::::LLLLLLLLL:::::L   Y:::::Y              C:::::CCCCCCCC::::CO:::::::OOO:::::::OLL:::::::LLLLLLLLL:::::LLL:::::::LLLLLLLLL:::::LEE::::::EEEEEEEE:::::E C:::::CCCCCCCC::::C      TT:::::::TT      II::::::IIBB:::::BBBBBB::::::BLL:::::::LLLLLLLLL:::::LEE::::::EEEEEEEE:::::ESSSSSSS     S:::::S    //
//     JJ:::::::::::::JJ         T:::::::::T      B:::::::::::::::::B  OO:::::::::::::OO L::::::::::::::::::::::LL::::::::::::::::::::::LYYYY:::::YYYY            CC:::::::::::::::C OO:::::::::::::OO L::::::::::::::::::::::LL::::::::::::::::::::::LE::::::::::::::::::::E  CC:::::::::::::::C      T:::::::::T      I::::::::IB:::::::::::::::::B L::::::::::::::::::::::LE::::::::::::::::::::ES::::::SSSSSS:::::S    //
//       JJ:::::::::JJ           T:::::::::T      B::::::::::::::::B     OO:::::::::OO   L::::::::::::::::::::::LL::::::::::::::::::::::LY:::::::::::Y              CCC::::::::::::C   OO:::::::::OO   L::::::::::::::::::::::LL::::::::::::::::::::::LE::::::::::::::::::::E    CCC::::::::::::C      T:::::::::T      I::::::::IB::::::::::::::::B  L::::::::::::::::::::::LE::::::::::::::::::::ES:::::::::::::::SS     //
//         JJJJJJJJJ             TTTTTTTTTTT      BBBBBBBBBBBBBBBBB        OOOOOOOOO     LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLYYYYYYYYYYYYY                 CCCCCCCCCCCCC     OOOOOOOOO     LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLEEEEEEEEEEEEEEEEEEEEEE       CCCCCCCCCCCCC      TTTTTTTTTTT      IIIIIIIIIIBBBBBBBBBBBBBBBBB   LLLLLLLLLLLLLLLLLLLLLLLLEEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS       //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JTBYC is ERC721Creator {
    constructor() ERC721Creator("JTBOLLY COLLECTIBLES", "JTBYC") {}
}