// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Chroma Cycles
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//            CCCCCCCCCCCCCHHHHHHHHH     HHHHHHHHHRRRRRRRRRRRRRRRRR        OOOOOOOOO     MMMMMMMM               MMMMMMMM               AAA                            CCCCCCCCCCCCCYYYYYYY       YYYYYYY        CCCCCCCCCCCCCLLLLLLLLLLL             EEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS     //
//         CCC::::::::::::CH:::::::H     H:::::::HR::::::::::::::::R     OO:::::::::OO   M:::::::M             M:::::::M              A:::A                        CCC::::::::::::CY:::::Y       Y:::::Y     CCC::::::::::::CL:::::::::L             E::::::::::::::::::::E SS:::::::::::::::S    //
//       CC:::::::::::::::CH:::::::H     H:::::::HR::::::RRRRRR:::::R  OO:::::::::::::OO M::::::::M           M::::::::M             A:::::A                     CC:::::::::::::::CY:::::Y       Y:::::Y   CC:::::::::::::::CL:::::::::L             E::::::::::::::::::::ES:::::SSSSSS::::::S    //
//      C:::::CCCCCCCC::::CHH::::::H     H::::::HHRR:::::R     R:::::RO:::::::OOO:::::::OM:::::::::M         M:::::::::M            A:::::::A                   C:::::CCCCCCCC::::CY::::::Y     Y::::::Y  C:::::CCCCCCCC::::CLL:::::::LL             EE::::::EEEEEEEEE::::ES:::::S     SSSSSSS    //
//     C:::::C       CCCCCC  H:::::H     H:::::H    R::::R     R:::::RO::::::O   O::::::OM::::::::::M       M::::::::::M           A:::::::::A                 C:::::C       CCCCCCYYY:::::Y   Y:::::YYY C:::::C       CCCCCC  L:::::L                 E:::::E       EEEEEES:::::S                //
//    C:::::C                H:::::H     H:::::H    R::::R     R:::::RO:::::O     O:::::OM:::::::::::M     M:::::::::::M          A:::::A:::::A               C:::::C                 Y:::::Y Y:::::Y   C:::::C                L:::::L                 E:::::E             S:::::S                //
//    C:::::C                H::::::HHHHH::::::H    R::::RRRRRR:::::R O:::::O     O:::::OM:::::::M::::M   M::::M:::::::M         A:::::A A:::::A              C:::::C                  Y:::::Y:::::Y    C:::::C                L:::::L                 E::::::EEEEEEEEEE    S::::SSSS             //
//    C:::::C                H:::::::::::::::::H    R:::::::::::::RR  O:::::O     O:::::OM::::::M M::::M M::::M M::::::M        A:::::A   A:::::A             C:::::C                   Y:::::::::Y     C:::::C                L:::::L                 E:::::::::::::::E     SS::::::SSSSS        //
//    C:::::C                H:::::::::::::::::H    R::::RRRRRR:::::R O:::::O     O:::::OM::::::M  M::::M::::M  M::::::M       A:::::A     A:::::A            C:::::C                    Y:::::::Y      C:::::C                L:::::L                 E:::::::::::::::E       SSS::::::::SS      //
//    C:::::C                H::::::HHHHH::::::H    R::::R     R:::::RO:::::O     O:::::OM::::::M   M:::::::M   M::::::M      A:::::AAAAAAAAA:::::A           C:::::C                     Y:::::Y       C:::::C                L:::::L                 E::::::EEEEEEEEEE          SSSSSS::::S     //
//    C:::::C                H:::::H     H:::::H    R::::R     R:::::RO:::::O     O:::::OM::::::M    M:::::M    M::::::M     A:::::::::::::::::::::A          C:::::C                     Y:::::Y       C:::::C                L:::::L                 E:::::E                         S:::::S    //
//     C:::::C       CCCCCC  H:::::H     H:::::H    R::::R     R:::::RO::::::O   O::::::OM::::::M     MMMMM     M::::::M    A:::::AAAAAAAAAAAAA:::::A          C:::::C       CCCCCC       Y:::::Y        C:::::C       CCCCCC  L:::::L         LLLLLL  E:::::E       EEEEEE            S:::::S    //
//      C:::::CCCCCCCC::::CHH::::::H     H::::::HHRR:::::R     R:::::RO:::::::OOO:::::::OM::::::M               M::::::M   A:::::A             A:::::A          C:::::CCCCCCCC::::C       Y:::::Y         C:::::CCCCCCCC::::CLL:::::::LLLLLLLLL:::::LEE::::::EEEEEEEE:::::ESSSSSSS     S:::::S    //
//       CC:::::::::::::::CH:::::::H     H:::::::HR::::::R     R:::::R OO:::::::::::::OO M::::::M               M::::::M  A:::::A               A:::::A          CC:::::::::::::::C    YYYY:::::YYYY       CC:::::::::::::::CL::::::::::::::::::::::LE::::::::::::::::::::ES::::::SSSSSS:::::S    //
//         CCC::::::::::::CH:::::::H     H:::::::HR::::::R     R:::::R   OO:::::::::OO   M::::::M               M::::::M A:::::A                 A:::::A           CCC::::::::::::C    Y:::::::::::Y         CCC::::::::::::CL::::::::::::::::::::::LE::::::::::::::::::::ES:::::::::::::::SS     //
//            CCCCCCCCCCCCCHHHHHHHHH     HHHHHHHHHRRRRRRRR     RRRRRRR     OOOOOOOOO     MMMMMMMM               MMMMMMMMAAAAAAA                   AAAAAAA             CCCCCCCCCCCCC    YYYYYYYYYYYYY            CCCCCCCCCCCCCLLLLLLLLLLLLLLLLLLLLLLLLEEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS       //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CC0 is ERC721Creator {
    constructor() ERC721Creator("Chroma Cycles", "CC0") {}
}