// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: GUN METAL - EDITIONS
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                     `;;/|i|\/_.                                                                                                                                                                                                                                                                                                //
//                               ;s}onL6TT6noyo5Lnuafj\`        :Lzz]]zz]}xxJJJuv.        iuJJaaaJJJJJJJJJIIxxJIJJxuj             }5ooooyaJJJJJan-     ~nxJJJJaaaaaaaaao}              -uyaaaaaJJJJJJJJJJJJJJJJJJJxJxxJLa[jjj[[[[[[[[[[[[[x5Ixxxe}ffffffff}}}ff}f}[[]}}}}}}ff}}fxx}][}f}eexe}n:        _JaxIIIIIxxxxexyn,                         //
//                           .toTqLoJyaJe[oIJ[?jjzrv[l}ouf:     jL.`"!":`!jl\:~z6u        6yooyaou5525LLLLTTTLkbYgqUNx           _STSPZZ%%%ZZZZ6qj     LPZZZZZZ%%%%%%E%SZ;            ;U%EEE%Z%SZZZZZPPP8US8USUU8gqpTTgLYYYYYYY66b66bkTTTTTy5L5oI}}}ll[jlritr?il}}av"!||tll[c\|trl\"\!tlIuuII%a       }L}I2LLLTLLTbTTTSP.                         //
//                         -cT65L55yI}[lrtsvj[i/!!!\i\ivvzLn!   Tc;/|!/\i5oj/~c]6J       "8juuou2nLLLT66dTYYppFCSPZZ%NI          [%%%%EmmOXmmmEuC!    `SPNNNOOXNNNNNNNNOOu           !Z%[email protected]%ZdSZZZZZZPSPSLbbTTTTTLLLLLLnnnn25yLn5ooaoyJJJf[}ju8}yp}uUa|\!"t}oovvJzrjrr[[l[JLnuLUY      "SvroT6TTTkYF$UUSNo                          //
//                        "dYLLnnnn2ox[rrri|itjr|"\|iv\vs|!?kL_:F~rjl\i[?Jya[eacZ"       aTxounLLnLTbb6bbTn6gSUSUSP%%[email protected]         bP%EmEEEEmOX%EJb     [email protected]@@@[email protected]%          rEONNOONNEEEmNOOXmmXm%%%ZZ%ZZZZZSZSkLLdY66kTTTLLLLLLL5ounLL5n5uouuaaouou5jo5tJnt"/ij[xxztrli|tjj[j[}oouuok%`     [email protected]~                          //
//                       [ULTTTTL5n5ofcj[[ti||?[Icj~;~iifyf\iuTF8/![ujJr|jlv\ryod        YIyooonnLT6Ydbbd6Tb6pSSSPZZZ%[email protected]       ZP%EXmmmmmOOXp2J     TZOENNNNXm%XXZ%NNONN_        [[email protected]%%mEZZZZ%%ZZPUPSY6TTLLLLLLLLnn52LLLLLLLLn5oooyyu2n5fzu]\oeij}jzaJ[e[?jsljjeI}}]yI]xJyN|     6}v}][TkT6LT$UPF%p                           //
//                     .nCTbTbbTLLLL2ouyuL5uajIoJz]xl}}IJ[?|ijtIz_"ti~;""iv]vIjg[       tS[uuoL5nnLTbdbdYqFSSSSUPZZ%%%%ZNg`     "EONOEUEOOOXONyY;     [email protected]@@NNOZEOONONmu      -6OONNOOOONNOXOmEXZmEEE%EZZZZZ%ZZ%ZgPZ%ZZPPZZPUUg$gdbCYbkTTLLLnnLnouooyou5ufoo[]y]}a[][j[vcjIuyjs[xo2u}}xJxcjPu    [email protected]                           //
//                     u8TkTTbYkTkTL5yn8%ZUPpTL5qn]r|i|i\;rj|!jvxv}Jjv!/ij}riJjP_       LLonLuunnLLTbdYCYFUUUSPPPPZ%%%Z%%Ng-    xZXNEEONNNNXOEyT     ;[email protected]@@@@@NNmNNNNNOXO%-    ;[email protected]%E%%%ZZZZZZZPPSqSSSUg$pFpY66bTTLLLLLL25nn5uunL2nJIx[JooJz}]uJJJynnJxyuLLLofzoxyy6$    tnl]uLTdYnC$8SSPXO:                           //
//                    iZ6Y6LTTbdkbLnnbZ%%OTi`  .}mlieji|\""~|t[?t?x5xos/~|yfcxuk        Sey5no2LLL2uLYCpp88SUSPZPPZZZZ%%%%OF-   6ZmmOONNNNNOXTLj     [email protected]@[email protected][   /[email protected]@NOOOOOOXXOOO%%mmXOOXm%%EEmmEm%%Z%%%ZZZZZSFgSSSFUUpppCYd6bTTLLLLL2LLnoJoLn252aJJaoIJounyooyouuo5nLun2uouu2Lkm_   LjvJTk6USFSSSSSPNT                            //
//                   .qTY6dkTTbkLTLLLPSZm\      :ULlxx]j]jvjccjrt[e}xolttjuvxlUc       ,F}ou5ouLLLLLT6CgUU8USSZPUZZZ%PPZZZZX$, ~E%%EmOOONOXXXJF:     [email protected]@NNNNNOp  [email protected]@@@@NOONNXmmONOmmZ%mmXXmP%mmEZZZZm&&[email protected]&[email protected]@[email protected]@@@N8TLLLLLnoouLLTONNNNZoJ}yoyJxy5LYONULLkTLTLnnLLnOt  -SljLT6YUS$g8SPSZKr                            //
//                   i%T6bLY6TTTLTTLddqm\        .lueexeeeeeeLoc}}?!]Jfs?\irfcP:       lLuu52unnLLLkT6YqYZZPPPPPPPZPZZZZ%%Z%NS_I%%EEEXOmXXOXZuT     "[email protected]@[email protected]|[[email protected]%%EEm%%%%EmmEEXmmmmmmmEEmDMQQDQMMMQQNuLLLLLLL22nLLUQQQQN5oouuunnnn5LNQQdynnLTLTT6dLT%5  sUly66dg8pqT6PSP%%.                            //
//                   LS8qpFYYTLLLLnnTLPL   ;axx}z][cllvv????rnxl}fJ]xaxtll]o}5T        T[u2nLuLLTTTkkYYYpg88SPPZPSSZZSSZZ%%%EN%ZPXmm%EmXONXEnYr     xZXmE%[email protected]$TXOOONNNONNZZXNONXZmN%5ZmEmEEEEEXmmEEmXXmmE%mEmmE%%%Z%mE%ZZZZZPPSURMMMMMQQQQQ$uT6TTTTLLLL6L%QQWOu5n2u5nkkLou%QQW6JunnLLLLTTLL8U  [email protected]                             //
//                  `STFqqqd6CFTTLLkLnE!   TLooxj]jl?lsvr|\|||\tjsljll[[vscyrSs       _pyuunLuLLTTT6bddYYFUSSPPPPS$SY$PZZZZ%EEEPSE%%%S%mOXEmyg.     [email protected]%PZ%[email protected]@ZLPOOmmmmmOEXmEEEmmmmmEEEEmE%EmE%%[email protected]@[email protected]@NE5nnnnnn2n5uLgNNNXLonLLLLbLuLLLbm__Uv[TYqFUSSUS8SZmR/                             //
//                  |@ZPSZ%ZPZZPPUFT56Y    FTLnouuoyIJJezjv?rr?clrslscjljzu]jS.       l%522nLnnLLLTTTTbd6YqpFg8$$ujPdqgpSPPPPPPZSPPZSSSPZZZY5o     |%YPPZZZZZZZZk8%LZZZZZPPPPgCUZZZZZLTNZPZZPPPSZZZZPSUZZZZZPPPPPSSSSSSSSUU$g$8gg$S%o[[zexJyoZIod6bTLLTbb666ZSZTxLLnn2uoaounPY}[email protected]                              //
//                  [email protected][$]   ~Nqn5uuuooyaaJIe}z]z]]]]]]][]]]}ui25        LUouuu555nn2nnLLLTLTTb6YqFSvYNmSSSSPPPPPPPPZZZZZZZZZZxY~     n8UZZZZZZZ%ZZkkx8ZZZZZZZZZZZZZZZPuLrS6PPZZZZZZZZZZZPPPSPPPPPPPU$PSSUUUUUUUU$FCC$m_        [email protected]%nYxin6YCppg$USSPZNe                              //
//                  [email protected]$g$gYL}l%\   uELLLLLL5uuuuoooyaIIIIJIxIxxxxxIJ/S|       :ELu5522nnnLLLLLTTb6dYFFFg8Y!F;pmSSPSSSSSPPPPZZZZZZZZP}k     .ZbZZZZZZZZZZP$]_8TZZZZZZZZZZZZZ8o6/|ECZZZZZZZZZZZZZZZZPPPPPPPSLl]z}xJyoooooooooSx        \Ytk666YYd666Y6YD%uLTTTLLLLLLLLLooouuuunLLTTTTTT6dbbP%$|]bCpCpg8USSPZ%O;                              //
//                  |@ZSSUUUUUU8gYuz\Cl   :eooxxy6nn255uuoooooooooyyoyyyooz;F:       oZu22nnnnLLLLTTTTb6YYp$$$$Uo[L `6mSSSSSSPPPPPPPPPZPPPLuf     rm8ZZZZZZZZZZLY; L$ZZZZZZZZZZZZdoT; nPPPPPPPPZZZZPPPZZPPZPPPSSSOuj[]}fxxxxxxxxx}~         nJJY66dddd66666UNuLTTTTTTTLLLTTTTLTTTTTkkb6bkk66YddYSDY\uYg$8UUUUSSPPX6                               //
//                  :mZSSUUUU8$ggqTottY`    ._|XZLLLnnn25uuuL2uuuuuuuuooouusFx.   -iL8u2nnLLLLLLLTTTTb66YYqpFg$Utbr  .TESSSSSSSSSSSPPPPPPP]6;     TZPPPPPPPZZZPLT  !PqPZZPPZPPZPLuL` .PgSPPPPPSPPPPPPPPPPPSSSSSSSE-                        .F|LYddY6dYYYYd6PoTbkbbTTTTTTTTTTTTTTTTkbbbbbYYd666YCSX[[email protected]            ...                //
//                   uNPSUU8$$gFFCYk5[odxe}[oTPdLLLLLLLLnnnLL6Tnnn2255uuuuuuuCbkLLLLounLLLLLLLTTTT6bk666YYYCCpgT/p`   .LEUUUUSSSSSSSSSSSS$}T     ,ZCSSSSSPPPPP$Y[   T6PPPPPPPPSu5u.  rOSSSSSSSSSSSSSSSSSSSSSUUU8U%LLLLLLLnLnnnnnnnT[       rkr6YYY6dYdYYYd6uT6bb66b6kTTTTTbkkkkbkb66666dYdddYdYq8T/[LFFFFg$88UUUPmPUUUSSSPPPPZZZ%O~               //
//                   `CESUU88$$FpCqqdbTLTdbTTTTTTTTTLLLLLLLusL8Lnnnnnn225255nnnn552nLLLLLLLLLTTT6ddqk66ddYYqqCpx[L     .L%UUUUUUUSUUUSSSS55j     sEpSSSSSSSSSSu6_   jZUSSSSSS8yLz    TZUSSSSSSSSSSSUUUUUUUUU8UU$gFF$g$gggppppFFFFCma       TfoYYYYdddYddYddk6666d6666b6T5u5u55n252nL66ddd6dYqqCF$6\udpgFFgg8UUUUUSSPPPPPPPZZZZZZEZ.               //
//                    -dXSU8$ggFFFFpqCYYddd66bkTTkTTTTLLk6ojLPESLnLnnnnnnnnnLLLLLLLLLLLLLLLTTTTbL[[TbddYYCpqpCF|6i      .L%UU88UUUUUUSSSUjY:     TSUSSSUSSSSSULT    `FyoooooajTv    ,ZgUUUUUUUUUUUUU88UUUUU8$$$ggg$gg$$g$FCpCqYYYCm"      :C|Ld6ddY6b6666ddd6d666666ddUCJIJJJIIIIJ|IYddYqqYqCCpCpUanYg8$$8$8U8UUSSSSSPPPPPPPZZZZNu                //
//                      |ZXS8gFFFpFCCqqYddd666bkkkkTk6CY2[xgl :o%S6LLLLLLLLLLLLLLLLLTTTkTTTk6CkIiubTdYYqqqCpFFn/b         e%$UU8UUUUUUUU6aL     ;%qUSSSSSSSSSbgv     "f}fxIJJ[:     [EUUUUU88$88888$$$$$$$$ggggFFggpFggggpCqYqYYdZk       ]o[dd66666bTbb6666bb6kkb666gX!         qtcddYqCqqdYCCCpCkdF$gF888UUUUUSSSSSSSPPPPPPPPZN~                //
//                       .|$EPSU$$gFpCqYddY666666dYpYLocyLI:    :oPZ66TTTTLTLTTTTTTTTTkbYqp65[[email protected]          f%$8UUUUUUUUUJbi     f%UUUUUUUUUSUop,                    6S88U$$$$gg$$$$$$gFFFppCppppppppppFpCqYYYdY6qNl       Tt2kkkkTTTTTLTTTkkkkbTkTbbYOj          ZevYYYqqqYqqqCpppFFFF$$8UUUUUUSSSSSSSPPPPPPPPP%8                 //
//                          ~xTPFL6$U88$gg$FFFgYLnozsJnuj:        .i2Ydn2TqpqqqYYYqCFpkLozlz5yz"iNYqqqqqqqqqY6/6/           eEpCCqCCCCCYjC.     68CCCCCCppppYLT                    ~EdYYYYYYYd6666d666bbkkTTkTTTTkkTTTbkTTTLLLLLY%-      "6tLnu5nn5ooouunnnLLLLLLLLLEu           LerTTbkk6666666dYYYYYqYqqCCppFggggg$$$8$$$$88UNJ                 //
//                             :v[zy2noeIJJx}}jzIoyx}r-              `|j[[aunuxz}}z[eyofax}r_   -oyexef}z][[[[ey             [2JJIxef}z]u}      eu[[[[[[[[[[[n/                    iT[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[L|       iSu5uuuuuuuuuuuuuuuu55uu55ul.           zqn555255555555555555uuu55uuuuuuuuuuuuuuuuuuoyj`                 //
//                                  -"iis}xef[ri",                         .;!iirtiii"_.           .....                       .......                                                                                                    ,;;;;;;;;;;;;;;;;;;;;;;;_.              `____________::::::::::::::::::::::::::::::.                    //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract GNMTLE is ERC1155Creator {
    constructor() ERC1155Creator("GUN METAL - EDITIONS", "GNMTLE") {}
}