// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Greener Pastures
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                __,[email protected]@NRMMNNNgg,                                                                                                                                                  //
//                                                                                       _,___          [email protected]@@@@@@BR$T++|||||||||||[email protected],                                                                                                                                              //
//                                                                                   [email protected]@@@[email protected]@@g_    [email protected]$||+||||||||||||||||||||||||T%@g                                ,[email protected]@gg                                                                                                      //
//                                                                               [email protected]+|____|[email protected]  _,@@P|||||||||||||[email protected]$"||||ZY||||||||[email protected],                      [email protected][email protected]_                                                                                                    //
//                              ___,,ggggggggggggggg;,  _ggggggggg_      _ ,[email protected]@@@[email protected]|||||g+|||[email protected]@[email protected]@@P|||||||||||[email protected]"-------------||||||[email protected]                    [email protected]$$$$&amp;L$|l&amp;[email protected]                                                                                             //
//                         ,,ggBB$T+||||||||||Tl|[email protected]@@NB$$$%[email protected]@@@g__,[email protected]@@@B$||||[email protected]||;@@I|||||||||%@@M||||||||||j$_------------------||||[email protected]                    [email protected]&amp;[email protected]                                                                                                 //
//                     [email protected]|||||||||||||||||||||||||||||||||||||%@@@@@@NT|l||||||]@[email protected]@||||||||||||||||+Z$Ngg||[email protected]|||[email protected]@                    '[email protected]&amp;[email protected]_                                                                                                  //
//                  [email protected]@RT||||||||||||||||||||||||||||||||||||||||||[email protected]@@||||l||||l||[email protected][email protected]@|||||||||||||||||||||[email protected]@KL---------------------|||$$F                    _"%@@[email protected]_    [email protected]@@g,_                                                                                          //
//                 [email protected]@K+|||||||2wM$T7""|"7TT*Mwg||||||||||||||||||||||[email protected]||||||||||l|T|%[email protected]||||||||||||||||||||||%[email protected]|||[email protected]                       [email protected]    ,@@B$lll&amp;@@_                                                                                     //
//               ,@@@||||||jW$|-------|--|-----_+1w||||||||||||||||||||||||||||||||||||ll|||l||||||||||||||||||||||][email protected]|||[email protected]                            __   [email protected]@l&amp;$$$&amp;[email protected]_                                                                                //
//              [email protected]@P|||||$C---|--------------------|1g|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||[email protected]_----------------|||[email protected]                        __ _     @@Tll$&amp;[email protected]                                                                                     //
//             ]@@P|||||"_------------------------|--"Bg|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||]@p---------------|||[email protected]                      ,[email protected]@@gg/@@[email protected]_                                                                                        //
//            [email protected]@@|||||L------------------------------_]@@Z||||||||||||||||||||||||[email protected]@@@@[email protected]@g|||||||||||||||||||||||||||%p--------------|||[email protected]@                     ]@$&amp;$$&amp;&amp;[email protected][email protected]                                                                             //
//            [email protected]@L||||L------------------------------|[email protected]@g||||||||||||||||||[email protected][email protected]|||||||||||||||||||;[email protected]@@@@@g_------------|||[email protected]@                     ]@$&amp;&amp;$$$$$$$$&amp;[email protected][email protected]@_                                                                            //
//            ]@@L|||l--|---------------------------------+%[email protected]@[email protected]||||||||[email protected][email protected]||||||||||||||||[email protected]$ll$$ll%@p------------||[email protected]@                     ]@@$$$$&amp;$$&amp;$$$$$|llT&amp;&amp;[email protected]                                                                         //
//             @@W||||L---------------------------------------|||T++|||||||||||[email protected][email protected]@@@NNMBB$T||||||||||||||||[email protected][email protected]@@K-------------||[email protected]@_                    %@@$$$&amp;&amp;[email protected][email protected]@                                                                                  //
//             [email protected]@|||||_--------------------------------------_l||l|||||||||||||TT$$T||||||||||||||||||||||||||[email protected]@[email protected]@@@@M$$$_--------------||[email protected]                     [email protected]$&amp;&amp;$$&amp;$l$$$&amp;&amp;[email protected]@                                                                       //
//             "@@W||||--------------------------------------|-|||||||||||||||||||||||||||||||||||||||||||||||||[email protected]@MTT|||||JK--------------||[email protected]                       _-7*[email protected]@@@[email protected]@[email protected]@_                                                                                           //
//              ]@@p||||----------------------------------------||||||||||||||||||||||||||||||||||||||||||||||||||||[email protected]@[email protected]@@@gg_-----|------||[email protected]                                _"7J%NBBC                                                                                            //
//               ]@@p|||L------------------------------------|--|||||||||||||||||||||||||;ggg|||||||||||||||||||||[email protected]@@@@$L|l|[email protected]||[email protected]                                                                                                                                    //
//                ]@@||||L--|-----------------------------------|||||||||||||||||||||||[email protected]@@@@@@[email protected]@@g,|||||||||||@@@@[email protected]&amp;[email protected][email protected]||$P                                                                                                                                //
//                [email protected]@||||--|-----------------------------------|||||||||||||||||||||||[email protected]@@@@@@$T|||[email protected]@|||||||||[email protected]$ll$T$&amp;[email protected]$$----------|[email protected]_                            [email protected]@@@@@@gggg_                                                                                     //
//                 [email protected]@p|||L---------------------------------|---||||||||||||||||||||||[email protected]@@@@[email protected][email protected]|||||||$$W$$lllll$$$lll|$K-----|--||[email protected]                             @@[email protected]@@gg;_                                                                                  //
//                  ]@@||||------------------------------------||||||||[email protected]||||||||||||[email protected]@$$$$|ll&amp;&amp;llll&amp;$$p|ggggg$$llllllLl&amp;$$$l&amp;$$$----"_|-||@P                            [email protected]@@$$&amp;@@@@@@@@@@$$$&amp;[email protected]@g_                                                   //
//                   [email protected]|||L--------------------------------|--||||||||$P|@K||||||||||||[email protected][email protected]@NB$$R$$llllllllll$Ll&amp;[email protected]@-|"__--||$P_                            @@[email protected][email protected]@@@[email protected]                                                                          //
//                   ]@@||||-----------------------------------||||||||||||||||||||||||[email protected]$l||llllllllll$]$||||||[email protected]|llllllll&amp;$|Ll$$C____-|||@P_                            [email protected]@[email protected]@&amp;&amp;[email protected]@[email protected]@                                                                  //
//                    [email protected]|||-----------------------------|----||||||||||||||||||$||||||[email protected]&amp;l&amp;$|lllllTlllll$$||||||[email protected]|lllll&amp;&amp;[email protected]@P,,-||||[email protected]_                             ]@@[email protected]@                                                              //
//                    [email protected]@|||---|`_|--------------------"_|---||||||||||||||||||[email protected]||||||[email protected]$&amp;$&amp;$l&amp;$&amp;$$$l&amp;[email protected]|||||||[email protected]@$l$llll&amp;@[email protected]|||||[email protected]_gggg,                          [email protected][email protected]                                                      //
//                    [email protected]||L--|-_|-----------------|"__|--||||l||l|||||||||||||[email protected]||||||[email protected]@&amp;&amp;L||[email protected]||||||||||[email protected]@$|[email protected]@[email protected]@[email protected]@P*- ]@[email protected]@ggg_                  [email protected]@[email protected][email protected]_                                                                      //
//                     ]@@||||----|||-----------||"___|---||,@@[email protected]@@@g||||||||||||%@g|||||[email protected]$l&amp;$ll&amp;[email protected]$|||||||||||||[email protected]@P7___     ^[email protected]$$$$$$lll$&amp;[email protected]@@ggg, _       [email protected]$$$$$$$$$$$$$$$$$$$$$$&amp;[email protected]                                                               //
//                     [email protected]@||||---|- ___""'""______.||--|||[email protected]@$$$$%[email protected]@@Ll|||||||||[email protected]@||||Z%@@$lll&amp;[email protected]@$|||||||[email protected]%TTT|T||||]@@N,_        _]%@[email protected][email protected]@[email protected]@[email protected]                                                                           //
//                      [email protected]@|||||||-|||-,,   .,-||--||||[email protected]@[email protected]@@|||ll|||||||[email protected]@|l||T$BNNM$T|||||||ll|||ll|||||||||||||@@@%@g_          [[email protected][email protected][email protected]_                                                                               //
//                       [email protected]@||||||||||-----||||||||[email protected]@@[email protected]@@$$$$$$ll|[email protected]@gT|||||ll||||[email protected]@gl||||||||||||||||||||||||||||||||||[email protected][email protected]            _][email protected]@[email protected]@[email protected]                                                                                //
//                         _7*[email protected]@g|||||||||||||[email protected]@@@$$&amp;[email protected]@[email protected][email protected]@@@gg|||||||||%[email protected]@gl|||||||||||||||||||||||||||||||[email protected]@ll|&amp;@@               [email protected]$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$K                                                                         //
//                              +"7*[email protected]@@M$$$$&amp;&amp;$|lllll&amp;[email protected][email protected][email protected]||[email protected]@@@@@@@[email protected]@g|l|||||||||||||||||||||||||||]@@[email protected]                  -][email protected]@@[email protected]@[email protected]$%%[email protected]@[email protected]                                                                      //
//                                      [email protected]@$&amp;$|T||[email protected]@[email protected][email protected]&amp;llL$$$l&amp;Ll$$&amp;&amp;[email protected]@@ll||||||||||||||gggggggI|||]@@lllll|[email protected]_        ,[email protected]@@@@@@@B|+||||[email protected]||||||[email protected][email protected]                                                               //
//                                    ;@@$$$ll$l||llllllllllll$&amp;[email protected]@$$$$$&amp;[email protected]$l$&amp;&amp;lIlll&amp;[email protected]@[email protected]@g|l|||||||lTT|||||||||||||]@@[email protected]_    ,@@N$||||||L||||||[email protected]||||||||[email protected][email protected]                                                               //
//                                  ,@@$$$$$$$$llL||llllll||ll$$&amp;[email protected]@[email protected][email protected]@ll$ll|[email protected]@[email protected]@@@||l|||||||||||||||||||||[email protected]|[email protected], ]@B|||||l|||K/||[email protected]$|||%@@[email protected][email protected]@[email protected]@`                                                                                //
//                                 [email protected]@$$$$&amp;$$$l&amp;l||||||||l$TlL|&amp;&amp;|[email protected]@[email protected]$||T|%@@[email protected]@$&amp;&amp;&amp;[email protected][email protected]@||l||||||||||||||||||||[email protected]@Lll$lllll|ll|[email protected]@@K||||||||||||+|||||||||||||+|l|]@@@@@@@@@NP7_                                                         //
//                               [email protected]@$$$$$&amp;l$$$&amp;$&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;lllLlL||||&amp;&amp;[email protected]@L;@&amp;[email protected]|]@@&amp;&amp;[email protected]@@@@$T&amp;[email protected]@@[email protected]@||||||||||||||||||||||[email protected]@l&amp;[email protected]||||[email protected]@@||l|||||||||||||||||||||||||||l|@[email protected]_ _                      //
//                               @@$$$$&amp;lllll$$$lll||lll|lIllll|||[email protected]||$$$$$ll&amp;@|]@l&amp;$$&amp;[email protected]@&amp;[email protected]||||||||||||||||||||||]@@Tlllll$|L||lllll$T|l|||||||||||||||||||||||||||||[email protected]@7                                                                           //
//                             [email protected]$$$$$|$$$&amp;[email protected]$lll&amp;||lll&amp;lllllT|||l&amp;$$W|]@$$$&amp;$$&amp;@|[email protected]&amp;&amp;ll$$$$$$$lll&amp;[email protected]|||||||||T%%[email protected]|||||||@@Wllll$$Mll&amp;|||lT|$l|||||||||||||||||||||||------|||@@                                                        //
//                             [email protected]$$$$$lllll$$$llllllL|||lll|||l||||[email protected]|[email protected]$$$&amp;$$$||[email protected]$$$$$&amp;&amp;[email protected]@[email protected]|||||||||||||||+|||||[email protected]@[email protected]&amp;@|lll&amp;[email protected]||||||||||||||||||||||||------|||[email protected]                                                                            //
//                             [email protected][email protected]&amp;&amp;&amp;$lL||||||l$Ll$|||||[email protected]||%@NB$T||||@@$$$&amp;&amp;$l$&amp;[email protected]@[email protected]@||l|||||||||||||||||[email protected]@@@@l$$$W$ll&amp;$&amp;&amp;&amp;$]M|||||||||||||||||||||||||||||||||@$                                                        //
//                     _      [email protected]$$$$$L$lllllllll$$$$l$$$&amp;&amp;$l&amp;ll&amp;l&amp;&amp;@|&amp;[email protected]|||[email protected][email protected][email protected]@||||||||||||||||||||@@Bl&amp;@[email protected][email protected]&amp;[email protected]@@@$|l||||||||||||||||||||||||||||||||@$                                                            //
//                     _     [email protected]@$$$$$&amp;$$ll&amp;&amp;&amp;&amp;$$&amp;||||&amp;&amp;l$ll$$&amp;&amp;ll&amp;[email protected]@@|l&amp;[email protected]@[email protected]$$$l&amp;&amp;$$&amp;&amp;[email protected]@T||||||||||||||||||[email protected]@@[email protected][email protected][email protected]@@@$|$||||||||||||||||||||||||||||||||||@@                                //
//                           ]@$$$$$$ll$lllll$$|||l$lll$WLl$$$llT$|[email protected]@@$&amp;[email protected]@[email protected]@l$$$l$$ll|[email protected]@&amp;||||||%Wg||||||||||[email protected]@$$$$$&amp;@@[email protected][email protected][email protected][email protected]$lll$|||||||||||||||||||||||||||L-||||[email protected]@                                                                                    //
//                          [email protected]@[email protected]$$$llllT|lllllll$l&amp;l&amp;&amp;&amp;l|l&amp;[email protected]@[email protected][email protected]@$&amp;$llll&amp;@@l$$&amp;[email protected]@@T||||||||||+TNg||||[email protected]@[email protected][email protected]@[email protected][email protected]@$|[email protected]|||||||||||||||||||||||||||||||||[email protected]                                                                //
//                          ]@$$$$$$Wlll$$$$LlTllll|l|$||ll&amp;|[email protected]@[email protected][email protected][email protected]@&amp;[email protected]@@l||||||||||||||[email protected]@@@$$W||@@[email protected]@[email protected]&amp;[email protected]|||||||||||||||||||||||||||||||||]@P                                                                                    //
//                          [email protected]$$$$$$ll|[email protected]@@BR$T||l|l|||||lT|$&amp;[email protected]@[email protected][email protected]$$$$$$$$&amp;@@$l&amp;[email protected]$$$&amp;&amp;@||||||||||l|@@[email protected][email protected],[email protected]@&amp;@&amp;[email protected][email protected]|l&amp;&amp;&amp;$L|||||||||||||||||||||||||||||||||]@P                                                        //
//                        _]@[email protected]@$$&amp;$$l$$$lllllllllll&amp;$$$$l$|lIl||[email protected]@[email protected]@$$&amp;[email protected][email protected]&amp;$&amp;[email protected][email protected]|||ll|[email protected]@@[email protected]$$$$&amp;[email protected][email protected]@[email protected]&amp;&amp;@l$W|||||||||||||||||||||||||||||||||]@                                                                 //
//                       [email protected]@&amp;$$$$&amp;$|l&amp;$$&amp;$&amp;&amp;&amp;l$&amp;&amp;$$$&amp;$$$$$$$lL|[email protected][email protected]@[email protected]$$F||[email protected][email protected]@@@$l|[email protected]$$$$$L|||[email protected]@@@@B$$$&amp;[email protected]@@@@B$$$$$&amp;@@[email protected]@|||||||||||||||||||||||||||||||||[email protected]                                                 //
//                      [email protected]@$$$&amp;$$|llllll$$$$$l$&amp;&amp;&amp;$&amp;$$$$$$&amp;$&amp;Ll&amp;[email protected]@[email protected]@@[email protected]||[email protected][email protected]@@@@[email protected]|$||[email protected]@B$$&amp;$&amp;$$&amp;$$$$$$&amp;&amp;$l$$$$&amp;@@[email protected][email protected]@|||||||||||||||||||||||||||||||||@@                                         //
//               _    [email protected]@[email protected]$$l|lllll|[email protected]&amp;$$l$$&amp;$$&amp;$&amp;$$$l$l$$|llllll|TT%@@@@$&amp;@[email protected]@@[email protected]@$&amp;[email protected]@@@BB$$$NBM$$$&amp;$$$$$$$$$$&amp;$$$$lllll&amp;$$&amp;@@[email protected][email protected]||||||||||||||||||||||||||||||||[email protected]                                                         //
//                     [email protected]@[email protected]|[email protected]$&amp;$l|ll$$&amp;&amp;@$&amp;&amp;l&amp;l&amp;$&amp;l$&amp;T,[email protected][email protected]@@[email protected]$$$$$&amp;[email protected]@$$$$$$$$$$$$$$$$$$$$$&amp;$&amp;$$$$$$&amp;&amp;$llllllllllllll$$&amp;@@[email protected]+]@|||||||||||||||||||||||||||||||[email protected]                                       //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract GRIN is ERC721Creator {
    constructor() ERC721Creator("Greener Pastures", "GRIN") {}
}