// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: THE ART HEIST MUSEUM
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                         //
//        /$$$$$$  /$$$$$$$  /$$$$$$$$/$$   /$$ /$$$$$$$$/$$$$$$  /$$$$$$  /$$$$$$$$/$$      /$$ /$$   /$$  /$$$$$$  /$$$$$$$$ /$$   /$$ /$$      /$$                                                                                                                                                                      //
//     /$$__  $$| $$__  $$|__  $$__/ $$  | $$| $$_____/_  $$_/ /$$__  $$|__  $$__/ $$$    /$$$| $$  | $$ /$$__  $$| $$_____/| $$  | $$| $$$    /$$$                                                                                                                                                                        //
//    | $$  \ $$| $$  \ $$   | $$  | $$  | $$| $$       | $$  | $$  \__/   | $$  | $$$$  /$$$$| $$  | $$| $$  \__/| $$      | $$  | $$| $$$$  /$$$$                                                                                                                                                                        //
//    | $$$$$$$$| $$$$$$$/   | $$  | $$$$$$$$| $$$$$    | $$  |  $$$$$$    | $$  | $$ $$/$$ $$| $$  | $$|  $$$$$$ | $$$$$   | $$  | $$| $$ $$/$$ $$                                                                                                                                                                        //
//    | $$__  $$| $$__  $$   | $$  | $$__  $$| $$__/    | $$   \____  $$   | $$  | $$  $$$| $$| $$  | $$ \____  $$| $$__/   | $$  | $$| $$  $$$| $$                                                                                                                                                                        //
//    | $$  | $$| $$  \ $$   | $$  | $$  | $$| $$       | $$   /$$  \ $$   | $$  | $$\  $ | $$| $$  | $$ /$$  \ $$| $$      | $$  | $$| $$\  $ | $$                                                                                                                                                                        //
//    | $$  | $$| $$  | $$   | $$  | $$  | $$| $$$$$$$$/$$$$$$|  $$$$$$/   | $$  | $$ \/  | $$|  $$$$$$/|  $$$$$$/| $$$$$$$$|  $$$$$$/| $$ \/  | $$                                                                                                                                                                        //
//    |__/  |__/|__/  |__/   |__/  |__/  |__/|________/______/ \______/    |__/  |__/     |__/ \______/  \______/ |________/ \______/ |__/     |__/                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                         //
//    00000000000000000000KKK0kkxkkOOO00000KKKKKKK0OOkkO00Oxoollc::clc::ccccccllllodk0K0OkkkkO00KKKKKKKKKKKKK00OOOkkxxkO0KKKKKK000000000                                                                                                                                                                                   //
//    00000000000000000KKK0OkkxkkOO0000000KKKK000OkkO00Okxoollccc::ccc:::cccccllllllodxkO00OkkkOO00KKKKKKKKKKKK000OOOkkxxkO0KKKKKK000000                                                                                                                                                                                   //
//    00000000000000KKK0OOkkkkkOO00000KKKKKK00OkkO00Okdolllcccccc:::cc:;::c::cccllllllllodxkO00OkkkOO000KKKKKKKKK00000OOkkxxxkO00KKKK000                                                                                                                                                                                   //
//    00000000000KK00OOkkkOOOO000KKKKKKKK0OOkkO00Okdollcccccccccc:::cc:;::::::ccccclllccclllldxkO00OkkkkO0000KKKKKKKK00OOOOOkkxxxkOO0KKK                                                                                                                                                                                   //
//    00000000K00OOkkkkOO0000000KKKKK00OOkOO00Oxdllcccccccccccc::::::::;:::::::cccccccccccccllllodxkO00OkkkkO0000KKKKKKK00000OOOkxxxxxkO                                                                                                                                                                                   //
//    0000KKK0OkkkkkOO000KKKKKKKKK00OkkkO00Oxdllllc:ccccccccccc:::::::::;:::::cccccccccccccccllc:cclodxkO00OkkkkO0000K000KK00000OOOOkxdd                                                                                                                                                                                   //
//    00KK0OOkxkkOOO000KKKKKKK000OkkkO00Oxollcccllc::cccc:ccccc::::;;:::;;::;::::cccccccccccclc:::ccccclodxO000OkkkkOO000KKKKKK0000OOOkk                                                                                                                                                                                   //
//    00OkkxkkkOO000000KKKK00OOkkkO0Okxolllcc:::clcc::::::ccccc::;;;;;;;;;;;;;;;:::ccccccc::ccc:::ccccccccclodxkO0OkxxxkO0000KK0000000OO                                                                                                                                                                                   //
//    kkxkkkOO00000KKKKKK0OOkkOO0Okxollcccccc::;:ccc:::cclccc:::;;;;,;;;;,;;,;;;;;;;:::ccc::cc:;:::cccccccccccccldxkOOOkkkkkOO0000000000                                                                                                                                                                                   //
//    kkkOO0000KKKKKKK0OOkkkO0Okdollccccccccc:::;:cc::clcc::;;;;;;;;,,;;,,,,,,;;;;;;;;;;:::::::::c::c:cccccccc:::cccldxkO0OkxxxkkOO00000                                                                                                                                                                                   //
//    OO0000000KK000OOkkOO0Oxdolccccccccccc:::::;;:::c:::;;;;;;;;;;,,,,,,'',,,;;;;;;;;;;;;;:::::cccccccc:cccc::::cccc::cldxkOOOkxxxkkOO0                                                                                                                                                                                   //
//    000000KK000OkkkO00Oxdlllc::cccccccc:::::::::::::;,;;;;;;;;;;,,,'.......',,;;;;;;;;;,;::;;;::ccccccccc::::::ccc:;:::::cldxkOOOkxxxk                                                                                                                                                                                   //
//    K000000OOkkkO0Okxdlccllccc::cc:::::cccccc:::;;::;,,;;;;;;,,,'..............',;;;;;,,;;;,,;;;::::ccccccc:;:cc:;;;:::::::::cldxkOOkx                                                                                                                                                                                   //
//    0000OkkkkO0Okxollcc:::clccc::::::cclccc::;;;;,;:;;,,;;;,,'....................',,;;,,;,,,;;;;;;;:::::cc:;:::;;;::::::::::::::cloxk                                                                                                                                                                                   //
//    0OkkkkOOOkdollcccccc::::ccc:::ccllcc::;;;;;;;,,,;;,,,,'............. .............'',,,,,;;;;;;;;;;;:::::::;;;:::::::::::::::::;:c                                                                                                                                                                                   //
//    kkkOOOxdolllcccccccc:::;::cc:cllc:::;;;;;;;;;,,,;;,'.........  ........... ...........',,;;;;;;;;;;;;;;::::;:::::::::::::::::;;;;:                                                                                                                                                                                   //
//    OOOxdollllllllcccc::::::;::ccc:;;;;;;;;;;;;;;;,,'.................................... ....',;;;;;;;;;;;::;,;;;;::::c::::::;:;;;;::                                                                                                                                                                                   //
//    xdollcclllllccccccc::ccc:::::::;,,;;;;;;::;;,'............. .........................  .  ....',;;;;,,;;,,,,;;;;;;:::::::::;;;;;:c                                                                                                                                                                                   //
//    ollllccccllccccc:ccccccc::;;,;::;,,;;:::;,..................................................  ....',,,,,',,,;;;;;;;;;;;;::;,,;;;co                                                                                                                                                                                   //
//    kxollllcc::cccclllcc:::;;;;;,,,;;;,;:;,........................................................   ...'',,;,,;,;;;;;;;;;,,,;;,,:ll:                                                                                                                                                                                   //
//    loxxdlccc:::llllc::;;;;;;;;;;,,,,;;,..............................'''''''''......................     ...',,;;;;,,,,,,,,',;;,,;;,'                                                                                                                                                                                   //
//    :::loddlc:::cc:;;;;;;;;;;;;;;;;,'.............................',,,,,,,,,,,,'''.......................     ...',;;,,,,''',,,,,,,,,,                                                                                                                                                                                   //
//    oc:::cloc:::::;,,;;;;;;;;::;;'............................''',,;;;,;;;;;;;;;,,,'.......................       ...',,,'',,,,,,,,,'.                                                                                                                                                                                   //
//    kxdc;;;::::::::;;,,;;::::;'............................'''',;;;;;;;;;;;;;;;;;;;,,,'',,;;,'............            ....'','',,,'...                                                                                                                                                                                   //
//    kkkl'.,;::::::;;;;;;::,'..........................'''',,,cxO00Oxc:;;;;;;;;:::;;:;;:clloxdl:,'...........   ..         ....'''...                                                                                                                                                                                     //
//    ddxc...'',;;;;;;;;;,'.........................'',,;clc::xKXNNNNXKOd:::::::::::::;:cclodOOdc;'...........   .              ...                                                                                                                                                                                        //
//    xxo,.......',;;,,......................''....'',,,;cdo:o0KXXXNNXXXOc;;;;;;:::::;;;::ccoddoc:;,'........                                                                                                                                                                                                              //
//    xko.........................................''''',,;;,;dO0KKKXXXKKx:::;,;;;;;;;;;::::cclollcc::;,'...........                .                                                                                                                                                                                       //
//    dxo,........................................'''''',,,,,cdk0XXKKXKOolOKx;,,,,,,,;;;;;;;;::c::;;::;;,''...........                                                                                                                                                                                                     //
//    xdo;.................................''''.......''''''',;ok0KKKXxc;:kXXk:,,,,,,,,;;;;;;;;:;;;;;;;,,,,'..........              . ..                                                                                                                                                                                   //
//    kko'.................................'''........''''''',,cdxkO0KOdc;ckKX0o;,,,,;,,,,;;;;;;;;;;;,;:,''''........              .....                                                                                                                                                                                   //
//    kko'.................................'''''.''''''''''''',cxOkk0XXXK0OkOKNXd;,;::;,,;;,,;;;;;;;;,,;,''''...............                                                                                                                                                                                               //
//    kOo'.................................'''''''',''''',,,:oxO0KXXNNNNNNNX0OKNKOo:::;;;;;;;;;;;;;,,,,,'''.......................                                                                                                                                                                                         //
//    kOo'................................'',,'''',,,,,,:lox0KXXXNNNNNNNNNNNNKOKXNXx:::;;,;;;;,,,,,,,,','''........................                                                                                                                                                                                        //
//    kOo'.................................'''''',,,,,,lOXXXXXXXNNNNNNNNNNNNNXOkKNNKo:::;,;;;;,,,,,',,,'.''........................  ..                                                                                                                                                                                    //
//    kOo'............................'''.,,'''',,,,,,:OXKKXXNNNNNNNNNNWWWWWWN0xOXNN0c,,,;;;,,,,,''''''''..........................  ...                                                                                                                                                                                   //
//    OOo.......................''....''''''.'',,',,,,cOK0kOKXNNNWWWNNNNNNNNXKkxkKNWN0l;;;;;,,,,,,'','''............................  ..                                                                                                                                                                                   //
//    OOo'...........''.........''''''''''''.',;,',,,,cOK0xoxO0KXNNWWNNNNNNXXKOk0XXNWWXkc;;;;;;,,'''''''.....'''.................... ...                                                                                                                                                                                   //
//    OOo'...........''........'''''''''''''..',,;;;;,:kXXklokOKXNWWWWWWWWWWNNKOkxOKNNNKd;;;;;;;,,,,,;,'''''........................ ...                                                                                                                                                                                   //
//    OOo'....'...............''','','','''''''';;;;;;:kXXOllOKKXNNWWWWWWWWNNNKkl:cx0NWKOd:;;;;;;;,,;;,'''''......'.....................                                                                                                                                                                                   //
//    OOo'....'........'..'......',',,',,'''''',::;;;;cOXN0c:kKKKXNNWNNWWNNNNX0d:;::dKWWKxc;,;;,,;;;;,,'''''''''''''....................                                                                                                                                                                                   //
//    OOo'...........'''.''.....'',,,,,,,;,,,,,;;:;;;;l0XXOcl0XXXXNWWNNNWWNNNXOo;;;;:oOKOl;;;;;;;;::;;,''''''''''..''..''...............                                                                                                                                                                                   //
//    OOo'...''..........','..''''',,;;;;;,,;;;;;;;;;cxKKKklkXNNNXNWWNWWWNWWWXOo;;;;;;:c:::;;;;;;;:;;;,,'''''''''''''.'''...............                                                                                                                                                                                   //
//    OOo'....''.......'.',,''','',;;;;;;;;;::;;;;;;;xXNXXklxKXNNNNWWWWWWWWWWNKo:;;;;;;;;:;;;,;,,;;;;:;,'....''''''''''.................                                                                                                                                                                                   //
//    OOo'.'''''......'''..'''';;'',;::;,,;;;::::;:;:OWWNNxlkKKXNNNWWWWWWWWNXK0d:::::::;;:::;;;;;;;;;:;,,,'''''''',,'''.''..............                                                                                                                                                                                   //
//    OOo'.''''.......''.''''',,,,,;;;;;,;;;:;;::::;c0NNWKdxXNNXXXNNNNNNNNNXXNXx::ccccc::::;;;;;;;;;;;,,,,'','',,,,,'...................                                                                                                                                                                                   //
//    OOo'..''.......'''',,'''',,,,;;;;;;;::::;;;;;;lKNNNOlkNNNNKKXXNXXXXXNNWWXdclolllc:::::;;;;;;;;;;,,,,''.''''''''.....'.............                                                                                                                                                                                   //
//    O0o'............'',,'''''',,::;;;;;,;;;;;,;;;;oXWWKlc0NNWWNXKXXNXXXNWWWWXdcdxdoolc::::;;,,;;;,,;;,,''.''''',,''..''''.............                                                                                                                                                                                   //
//    OOo'...........',',,''',,',;clloc;:::;,,''',;;dNWNd;l0XNWWWNXXNNNXNWWWWWNklloooolc::;;,,,;;;;'',;,'''',''',,,'..'''''..''.........                                                                                                                                                                                   //
//    OOl...........',,,''.',;'',;,,,,;:::;,,,,',,,;kWWO:,ckXNNWWWNXXXXXNWWWWWWXd:lllll:;,,,,,',,;,,,,,,''''''',,''.''','............ ..                                                                                                                                                                                   //
//    OOo...........'',,''''',,,;;;;;;::;,''''''',':0WW0c;cxKXNNWWNKxdOXXNNNWWWNOc:c:cc:;,,,,''''',,'',,,'',,,,,,'''''.'............. ..                                                                                                                                                                                   //
//    OOl......'....',,''''',,,;;;::;:::,''''',,,,,oXWNNKK0O0XXNNNNN0xOXXXXNWWNNKd;;;;;,,,,,,'',,,',,,;;,,,,,''''''''.''................                                                                                                                                                                                   //
//    OOl...........',,,,''',,,;;;;;;::;,','.''''';xNNNNNWN00KXNNNNNXxdOKXXNNWWNNk:;;,,'',,,,''',,,,''',,;;,''''''''.........''.........                                                                                                                                                                                   //
//    OOl...........',;;;''''',;;:;;,,;:;,'...'...'lXNNWNNNKO0XNNNNNXd:lxKXXNWWNN0c,;;,',;,,,'.',''''.',''''....''...........'''........                                                                                                                                                                                   //
//    OOl...........',,,'..'',,,;::,,;;;;'...'.....,kNNWWNNX0OKXXXNNKo,,ckKXNWWNNKl',,'';;;,'''''''.......'......'..''.......'''........                                                                                                                                                                                   //
//    0Ol...........',,,'..',,,,;:;;::;'............oKXNNNNNKOOKXXXXKo,,,ckXNNWNNXo''''',,',,''''''........',''''..'''......''''........                                                                                                                                                                                   //
//    0Ol.....''....';;,,'''',,;:;;;;,,,'..''.......oXXNNNNNXOOKKXXX0l,,,,l0NNWWNXd;,',,,,,,,''','..'..''...';;'...'.',,'....''''.......                                                                                                                                                                                   //
//    0Ol..''''''...,;;;,,,';;,,;:::,','''''''.....'oKXXNNNNNKkOKXXNKl'',,;dXNWWNXo,',;;,,,,,'''''''''.''.'',,;,','''.','....'.''.......                                                                                                                                                                                   //
//    0Ol....''.....,;;,'''';;,,;:c;''''''',,'......lKXXNNNNNXOk0XNXKd;,','cONWWNXd,',::,,,,,''''''''''....''.'',,''',,'.....''.........                                                                                                                                                                                   //
//    0Ol....'''....',;;,,,;,,,,;;::,'''''',,.......l0KXNNNXXXK00KKKKkc,,,',o0XNNN0l,:::;,,,,'''''''','......',',,'.',,''....::'........                                                                                                                                                                                   //
//    0Oc.......'...,;;;,,,',,,::,,;,''''',,,'......lOKKXNNXXXXKKKKXX0l,;;,,,lkO0KXk:,;;,,,,,'..'''.',,'......'''''.'''''...;xo...''....                                                                                                                                                                                   //
//    OOc.......'...,;;;,,,,;',;:,'',''''',,,.......cOXNNWWNNXXKXNNNXKd:;,''',lxx0XXx;'',;,,'...'''.',,''.......','.''''.........'......                                                                                                                                                                                   //
//    OOc........''.',,;;,,;;,,,;;;,,,,,',,;,.......:ONNNWWWNXXKKNNNNXxc;''..'ckO0XNKo,''',''..',,''''''',......',''..''''....';'.'''...                                                                                                                                                                                   //
//    0Oc...'''..'..,,,,;,'',;;,,:c;'',,,,,'........;x0000000KX0OXNNNNOl;''.',:k00KXXk,.'';,''.'',''','''........'''''''''''...'..''....                                                                                                                                                                                   //
//    0O:.......'...',;;;,,;;,'''::'.''''','........'dOkdokKKXNkxKXNNXx:,.'';,,oO00KXO:.',,'''..'''''',,''..'....',,''',',,''...'''.....                                                                                                                                                                                   //
//    0O:.......''..',;;;;,,,',''cl,.,,'',,'.........dKKK00NNNNOoOXNNXx:,',,;,,;oO0KXKl''...''...'''''''''''',....',;,,''''''...''......                                                                                                                                                                                   //
//    0O:.....''.'..',,;;;;,,;,,;cc,',,,,,,'....'...,kXXX00NNNNKdxKNNN0kc',,,,'',o0KXKo''....'..',''.''',,,',;,.'.',;,'''''''..''''.....                                                                                                                                                                                   //
//    0O:...'''.',,.,;;;,,:;;::::::,,;;;,;;'...,,...;0NXN0OXNNNXkxOXNNXXOc,,,'',':xKXXd''...''..''''..'',;,,,;,'..',,,,,,;;,''',,'......                                                                                                                                                                                   //
//    0O:.'..'',,,,.,;;;;;,;:c:;:c;,;;:::c:'..','...:KNNN0OXWWNX0kk0NNXXXk:,,,,,,,lOXXx,'''''.......''''',;;;;;,'''',,,,',,'''',;,'.....                                                                                                                                                                                   //
//    0O:...',,,,''.,;;;;,,;;:::c:;,;:c::c;...',....lKNNNOOXNNNKK0kkXWNXNKo;;;;;;;:kXN0:'..,,......'''',,,;;,,,;,,,''',;,'....'''''.....                                                                                                                                                                                   //
//    0O:.''',''....,,,;;,,;;::cc:;,:l:;::,...;;'..'dXNNNOkXNNNXKK0kKNNNX0occccccccxXNNOl;,,;;;;;;;;,..,::;:;;;;,;,''',;;;,''''',''.....                                                                                                                                                                                   //
//    0O:...''''...',,,;;;;:::cc:;::cc::::'...,::;':0NNNXKKXXXXXXXK0XNXXKKKKKKKKK0OkOKNWX0xl:ccc::c:,'',;;;,;;;;;;,,,,,,,,,,,,',,''.....                                                                                                                                                                                   //
//    0O:.'''''.'..',,,;::;:::cc:;;;c:;;;'..';clcc:l0NNNXXXXXXXXXXXNNNXXKXXXXXXXXXXXKKXNNNN0l::::::c:;,,,'',,',,,'''''''''''''.'........                                                                                                                                                                                   //
//    0k:.'''''''...,,,;:::::ccc:;;:::;;;'';cllloolcoO00O00KKKKKXXXNNNXXXXNXXXXXNNNXXXXXXXXklllllcllcc;;::::cccccc:;;:::cccccc::,,,''''.                                                                                                                                                                                   //
//    0k:',,,,''''';loodddddooooollllodolclddolllooodxxxxxxxxxkkkkOOO00000000000000OOOOOOkdccllllcllcc::clcccllooolccccclllllllccc:;;;,'                                                                                                                                                                                   //
//    0k:',,''',;;;:oddddddooolllllllloolodddodoodddxkkkkkkxxxxxxxxxxxxxxxxxxxdddxxdddddddoolllcccccccc::::::::::::::::::::cc:::::::;;;'                                                                                                                                                                                   //
//    0k:,,,,;;;;;;;coxkkkkkkkxxxxxxxollooooodddddddxkkkkkxkkkkkxxxxkkkkxxddoododdddxxxdddoollloooloollccokOkkkkkkkkkkkkkkkkkkkkkkkkdc;,                                                                                                                                                                                   //
//    0kc;::cc;,,,;cx0KXXXXXXXXXKKK0kollllooooooooodxkkkkxxkkkkxxxddxkkkkxdddddddddddxddoooooddddddddddollxkkkOOO000000KKK000000000000xc                                                                                                                                                                                   //
//    0kl:::;;;,;cx0KKKKKKKKK000OOkdooodoooooooodooddddddddddddddooooodddddddddxxxdooooooooloddxxxxddxxdool;,cc;;::cclooodxxxkkOO00KKKK0                                                                                                                                                                                   //
//    0kl;;;;;:lxO0OOkkkxddxoooool::lllllooolllclllloodddddolllcc:::::ccccllllloooooooooolllllcloooooodxxdooldx:..',coc;,;;;:c:,;::llood                                                                                                                                                                                   //
//    0k:,::;;:llcllc::cccdkdooldxl;;;::::lllllcccllllolllcc:::;;;;;;:cc::::clllllllolcccc:::ccllloddddddddl:cloccloxxxl:cldxko'..,;co:.                                                                                                                                                                                   //
//    Od;,cl:;'',:dkdoclodkxdolokxl::::c:cclllcc:cc:;;;;;;;:;,'',,,,;cllllllccllllllllccc:::ccllodoooolllll:;;cxkl'',:odllddoloc,cdxkOk:                                                                                                                                                                                   //
//    d;'cxxxdl:cdxdllloxdl:;:ck0Ooccc:cc:::cc:::::;;;;;;;;:;'..,;;;;:cccccc::::::cccllc:::::cccloooooollllccloxkd;;lxO0klcllloxl;;;;:oo                                                                                                                                                                                   //
//    o:clc:::;:xkdoolok00Okodkkkdc::::::;:cc:;;;;;,,;::::;,,,,',;;;;;:::::c::::::::::llllc:cllccllllllllllc;,;clxxdxkkkOdcoxxkxo;;:coxk                                                                                                                                                                                   //
//    ldxdc:;;;dOOOkxxxdolodxOOdc:;::::::::::cccc:;;;:::clccc:;,,,,',;;;:::c::::::::;:::cllc::ccccclllllllllc:codkOdldxxOkc,:clodolodxxk                                                                                                                                                                                   //
//    lxkddooldkkxxxxOOxoollk0OOOdlcccccc::c:clccc::cc::clcc::;,,,,;,;,,;::c:;;:;;::;::::cclllcclcc:ccclll:coc:cccdxodkkkko:coxO0x:'',cd                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract VAULT is ERC721Creator {
    constructor() ERC721Creator("THE ART HEIST MUSEUM", "VAULT") {}
}