// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: residential areas,
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    encountered good luck, picked up something rich people do not want, change a little money, every month of life is completely enough. Because THE BEGGARS HELP (OF COURSE THIS IS THE NAME JI XIAOYAN GAVE THEIR ORGANIZATION TO TAKE) THE INTERNAL EXCHANGE SYSTEM IS STILL VERY HUMANIZED, WHO LET THE PEOPLE HERE ARE THE BOTTOM OF IT! As long as they don't get caught stealing, people in many places generally don't care about their "bottom rung" workers. And occasionally give them little jobs to do. However, you have to clean yourself up or you will never have a "business".    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract RA is ERC721Creator {
    constructor() ERC721Creator("residential areas,", "RA") {}
}