// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: IslesOfAda
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMXOOOOOOOO0NMMMMMMMMMMMMMM0c;.. ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMOc,.   .;lKMMMMMMMMMMMMMMXO:   ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMK,   cNMMMMMMMMMMMMMMMMMMd   ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMK,   cWMMMMW0xolloodONMMMd   ;XMMMMMMWXkdolodkXWMMMMWKkolllodONMMMMMMMM    //
//    MMMMMMMMMK,   cWMMWO;. 'loo, .OMMMd   ;XMMMMW0c..,lo:. .lXMM0:. .loo;..xMMMMMMMM    //
//    MMMMMMMMMK,   cWMMK;   lNMMK;,OMMMd   ;XMMMWk.  :XMMWo   :XN:   :XMMXc'kMMMMMMMM    //
//    MMMMMMMMMK,   cWMMNc    'cx0KXWMMMd   ;XMMMK,   'llll,   .kWo    .cx0KKWMMMMMMMM    //
//    MMMMMMMMMK,   cWMMMNkc'    .;xNMMMd   ;XMMMO.   :ddddddddxXMNOc'.   .,oXMMMMMMMM    //
//    MMMMMMMMMK,   cWMMXxkNN0d:.   oWMMd   ;XMMMK,   lNMMMMMMMMMNkkXN0xc.   cNMMMMMMM    //
//    MMMMMMMMMK,   cWMMk..OMMMNc   oWMMd   ,KMMMWk.   :kKXXKOdo00'.xWMMWo   lNMMMMMMM    //
//    MMMMMMMOc,.   .;lKO' .;cc;..,dNM0l'   .;:oXMW0l'.  .....'cKK; .;cc;..'oXMMMMMMMM    //
//    MMMMMMMXOOOOOOOkONWKOkxddxk0NMMMXOkOOOOkk0NMMMMN0kxddxxxOXWWXOkxddxk0NMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OkkO0XWMMMMMMMMMMMMNxc:'..:0MMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNkc,..',;,..;ox0WMMMMMMWO, 'kx,..kMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWk,   :OXWWNO:   .:0WMMMMO'  :NMN0KWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWd.   oNMMMMMMNl    .kWMMNc   :KXNWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMO.   ;XMMMMMMMMK,    '0WO:.   .;;oXMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMo    lWMMMMMMMMWc     oWN0:   ;0KXWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWo    lWMMMMMMMMWl     lWMWc   :NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMx.   :NMMMMMMMMN:    .xMMWc   :NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXc   .xWMMMMMMWx.    cNMMWc   :NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXl.  .xNMMMMNx.   .lXMMMWc   :NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWOc.  ,ldol'  ';c0WMMWOl.   .lxXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxoccccldONWMMMMMNkdddddddkXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNKKKNMMMMMMMMMMMMMMMMMMXxoc;'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMX:...oNMMMMMMMMMMMMMMMMM0l,   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNl    .xWMMMMMMMMMMMMMMMMMMx.  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMx...   '0MMMMMMMMMMMNK0OOO0o.  '0MMMMMMNK0OOO0XWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM0, l0,   :XMMMMMMMNkc'..,;::'   '0MMMNx:'.;:,...:OWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNc ,KMk.   oWMMMMMK:   :0NWMWd.  '0MMWo   '0MNd.  '0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWd..dXXKc   .kMMMMNc   ;XMMMMMk.  '0MMMXkkkOXKOo.  .kMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMO. .::::;.   ,KMMM0'   lWMMMMMk.  '0MMMWKxl::cc;.  .kMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMX; ;0NNNNNO,   cNMM0'   ;XMMMMMk.  '0MMXc.  :0NW0'  .kMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNl .OMMMMMMWx.  .dWMNl    c0XNWNd.  '0MMx.  .dWMMO.  .kMMMMMMMMMMMMM    //
//    MMMMMMMMMMNOc. 'o0WMMMW0o.   .lOWXl.   ..',:,   .lON0,   .;:c:.   :kXMMMMMMMMMMM    //
//    MMMMMMMMMMXdlllllkWMMMWklllllllkNMW0dc:::ldK0dllllxNMKdc::cdOKklllloKMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract IoA is ERC1155Creator {
    constructor() ERC1155Creator("IslesOfAda", "IoA") {}
}