// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cody A Banks Editions
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOkOOOOkkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKKK0kxOXNWWNXOxx0NNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNK0OOO00XNNNNNNNNNNNNNNNNNNNNNNNNKOkkOOOOOO0NNNNNNNNNN0dkXNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNXOkkkxdkOOOOkOOKXNNNXXKKKKXNNNNNNNOdxOXWWWWWNNNNWNWNNNNNNXxxKNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNKxxKOxOOKNWNNK0OOOOOOOOOOOOOOkOKNXkxKWNNNNNNNWNXOkOO0NNNNNNNOdk0OOOOO0KXNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNxxXOxXWNNNNNNNNXNNNWWNXK000XNKOkxoxXWNNNNNN0OOOkOKXXXNNNNX0OkoldkOOdoodkOkOXNNNNNNNNNNN    //
//    NNNNNNNNNNNW0d0WXNNNNNNNN0kOOOOOOOOkOOOOkkONXx:oOkkkOOOxx0XNNNXXK00OOkkOkxkO0XNX0OO0NNKOkk0NNNNNNNNN    //
//    NNNNNNNNNNNWOdXWNNNNNNNNX0KKOOOkk0NNNNNNNkldxddddxxdddoodxdxkOOOOOOO0XNWXXNWNNNNNNNNNNNNN0xxKNNNNNNN    //
//    NNNNNNNNNNNNkxNNNNNNNNNNNNNXXXXKKXNNNNXkddxkOOOOOOOOOOOOOkdod0NWWWNNNNNNNNNNNNNNNNNNNNNNNNNkdKWNNNNN    //
//    NNNNNNNNNNWXdkNNNNNNNNNNNNNNNNNXKK0KKkddkOOOOOOOOOOOOOO0XNNKxoxKWNNXXNNNX0kOOO0NNNNNNNNNNNWXdOWNNNNN    //
//    NNNNNNNNNNNkdXNNNNNNNNNNNNNKOkOOOOOxclkOOOOkdodxkxddxkOO00XNKOdoxkOOOOOOkxdx0XXNNNNNNNNXXXKkdKWNNNNN    //
//    NNNNNNNNNNOdKNNNNNNNNNNNNKkxOKNWWWNxoOOOkddxxxxxkxdddxOkxkO0K0OdckNNNKkOOkOKXNNNNNNKkkOOOOkOXNNNNNNN    //
//    NNNNNNNNWKdOWNNNNNXK00KN0dONNNNNNNkoxOOOkxoodddddddddddodkOO00OOodXNNKKXNNNNNNNNNKkxOXNNNWWNNNNNNNNN    //
//    NNNNNNNNNXxxXNXKOkkOOOOxlkNNNNNNNNxoOOOOOOOOkxxdddddxkkOOOOOOOOOxo0WNNNNNNNNNNNXOdONNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNKOkOOkOKNWNNWOoKWNNNNNNXdoxddxxxxddxkOOOOOOOOOOOOOOOOOxcdOO0KNNNNNNXOxkXNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNxxNNNNNNNNNOllx0NNNXKOkddkOkxddxxxxddkOkdoOK0OOkkkO00kkkKNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNOd0WNNNNNNNNkdxxKNNNNNNNXkllodOXNNNXKkdlokKNNNNNNNKOxldKNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNOd0NNNNNNNNNN00OONNNNNNNNNNxoOXWNNNNNNNNOdONNNNNNNNNNNXOxkKNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNkd0NNNNNNNNNNNNNNNNNNNNNNNNNxxKXNNNNNNNNNNKdkNNNNNNNNNNNNNOdONNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNXxxKNNNNNNNNNNNNNNNNNNNNNNNNXx;oKXNNNNNNNNNNNKOXNNNNNNNNNNNNNKdkNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNKdk0xOXNNNNNNNNNNNNNNNNNNNNXkl;;;:oKNNNNNNNNNNNNNNNNNNNNNNNNNNWKdONNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNXdk0dOOONNNNNNNNNNNNNNX0KNKdc;::::;;cxKNNNNNNNNNNNNNNNNNNNNNNNNNNkdXWNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNkxXkkOd0NNNNNNNNNNNNNXxx0x:;:::::::::;:okKNNNNNNWNNNNNNNNNNNNNNNW0dKWNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNWXdkNNXxxNNNNNNNNNNNNNWOdKx;:::::::::::;;,,:ox0XN0kOKNNNNNNNNNNNNNWOdKWNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNxkNNKx0NNNNNNNNNNNNNKdk0c;:;:::::::::::;;;;;;cx0KOdOXO0NNNNNNNNNXxkNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNN0dONNNNNNNNNNNNNNNNNKOOd:;;;;::::::::::;cddddxkkx00xxxx0NNNNNNNXxxXNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNKkkO0KKXXXXNNNNNNXKOkkxc,;;;;;:::::::;oXWNNNNNNKkxkk0NWNNNWNKkxOXNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNKOOOOOOOOOOOOOOOkOKXo;:::::;;;;;;:cxXNNNNNNNNNNKOkkOOOOOOkkOXNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNWNNO:;:::::;;;,':kXNNNNNNNNNNNNNNNXK0000KNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk;;::::::::;'c0WNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW0c;:::::::::;;oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:;::::::::::;cONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l;::::::::::;:dXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXd:;::::::::::;l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc;::::::::::;lKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0c;::::::::::;xNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNx;::::::::::;cKWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNW0:;:::::::::;;xNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWKl;::::::::::;lXWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXo;::::::::::;c0WNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CAB is ERC1155Creator {
    constructor() ERC1155Creator("Cody A Banks Editions", "CAB") {}
}