// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: SellisetART
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                //
//                                                                                                //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//    SELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISETSELLISET    //
//                                                                                                //
//                                                                                                //
//                                                                                                //
//                                                                                                //
//                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////


contract Selliset is ERC721Creator {
    constructor() ERC721Creator("SellisetART", "Selliset") {}
}