// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Letterhythm Open Edition
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMNOxxxxkkOO000000OkkXMMMMMMMMMMMMNOllONMMMMMMMWXK0OOOkkkdOWMMMMMN0OOOOOOOOOOOOkkkxdokNMMMMMMMMMMMNKNMMWXKNMMMMMW0xloKWMMWNXNMMMMWXK0OkkkkkkkkkkOO0XWMNK0kxddddddxKMMWXkoxXWMMMMMWXOkkkkkkkOOkkkOKWWNNN0kxdollllllodk0KXKOxxdoooooooooldKMMMMWXKNN0OOkkkOOOOkxkNMWKOXWMMMWKo;,,xWMMMMMMMMMNXWMMMMMMMM    //
//    MMMMMMMMNl.........'''''',';OMMMMMMMMMMXx:....cONMMMNk:'.........oWMMMXd;'.............   ..dWMMMMMMMMN0d;lXW0dkNMMMMWOl'...;0WXd;,;lkXWWNKO:.       ..,dOKOl;,'........;OWXx;...;oKWMNkc'......... ..:ONW0xXWNKx'       .c0Kk:'..............:KMMWKdxOo,............oXKo,.,dXMWO, ...oWMMMMMMMMWxdNMMMMMMMM    //
//    MMMMMMMM0,..''.....''..'''',xWMMMMMMWXd;.......'dNMXl............oWWKo'       . .. .....  .'xMMMMMWXOo;...cxc.;KMMMNk:.......:Oo......,oXMMMK;       ;xKWXo. ...........;Ok;'.....;dko;........   ..cONW0l'lNMMMWd.      ,0Wk' ...............cXW0o',o:.............'cc,.....:00;  ...dWMMMMMMWKl.cXMMMMMMMM    //
//    MMMMMMMMK,.........'........lKWMMMWKo'.cl,......,OXl. ...........o0o. .:dxxxdl,.'lxxO0x'....xMMMWXd,........  cXMWO;...'''....:, ....  .;OWMWo.     .dWWK:.  ...........:0Kx:...;oddddxkkxxxxxxxxxkKWNO:...oWMMMMX:......lX0,  ..........   ..l0o.  ''  ............,c;.....,oOl  .,;;xWMMMMMNx,. ;KMMMMMMMM    //
//    MMMMMMMMXc.lxxxxdo:;clloool:,oXMMWk'  ;KW0c......oo.  .,:cccloooxx:. ..xMMMNOc,.':kNMMk'....xMMNk,........    cXWk'  .lx:'.......,,...   'OWWd.......xWK:   .,c:'......:0WMMXkloookXWMMMMMMMMMMMMMWXk:... .xWMMMMXc.'....l0c  .:odxxd:.    'dO0o.     .'coodddooodo:lKXd;.;dKWk. ,kXNko0WMMW0c....'kWMMMMMMM    //
//    MMMMMMMMWxxNMMWXxc'cXMMMWOc..cXMMO'   cXMMXc.....,' .:OXWWMMMMMMMx.....xMMXo,''..',xWMk'....kMXl.......co'    cXX:....lNx......c0NX0x:.   ;KWx'...'''oOc  .l0XWO;...'''xWMMMMXd,,kMMMMMMMMMMMMMMWKo,.....,dXMMMMMXc','..'lo..c0WMWKdod,... :XMK;     .dXWMMMMMMWXkc.;xOxc:oddd, ;KNOl'.,xNNd'.....,0MMMMMMMM    //
//    MMMMMMMMMXXMNOl'  .lNMNO:.   cXMNl....cXMMWd...... .lXMMMMMMMMMMWx.....kMMXx;'...;dKWMk. ...kXc. ..,'.cXK;    :X0,  ..lNO,.....kMMMMMNO;  .dWk,......',. 'kWMMM0;.....'dWMMWk;..;0MMMMMMMMMMMMW0l'.....,o0WMMMMMMXc.''''':,.cXMWKl..x0;....:XMK,    'kWMMMMMWXkl;.   .       ..'O0c'.....ll.  .  .oWMMMMMMMM    //
//    MMMMMMMMMMW0c.     cX0c.     cXMK; ...;KMMMk.  .  .lNMMMMMMMMMMMWx.....kMMMWXd,,dKWMMMk.....dx. .;;. .xMK;    ;KO'  ..lN0,  . ,KMMMMMMMXl. ;KO;......   ;0WMMMM0;......dWMMk'...,OMMMMMMMMMMWOc.. ...;oxl:oKWMMMMXc.,'''''.;KW0l.  .OK;  ..cXMK,  ..:XMMMN0dc,.......       ...dNO;.....,'.      .dWMMMMMMMM    //
//    MMMMMMMMMMKc.     .cXO;.   ..cXM0, ...,0MMMO'     ;KMMMMMMMMMMMMWx'...'kMWKkxdccddx0KXd.....l:.,o;.  .oWK;    ,00,  ..cX0,    :XMMMMMMMMXc 'Ok,......  ,0MMMMMM0;.....'dWMNo....'kMMMMMMMMNk:......;dxl,'..;xNMMMXl',''''..x0l.    .O0;  ..cXMK;  ..:XWKd:.........':'...   ..:KMW0c..,l;.       .xMMMMMMMMM    //
//    MMMMMMMMMMWXl.   ..cNWKl.....cXMK; ...'OMMMK;    .oWMMMMMMMMMMMMWx,...,kMWKc.''''.:0XNx.  ..:;:0d.    cNX:    'O0;....:X0,    :XMMMMMMMMM0,.kk,.......:kWMMMMMM0;......oWMWo.....xMMMMMMNk;.  .. .lKk,....';oXMMMXl';;,,'.cX0;.    .k0;.  .cNMK;....:0x,......... 'ONo...... .xWMMNd..cc. .,,    .kMMMMMMMMM    //
//    MMMMMMMMNKXWK:.....cNMM0,....cXMX:... 'OMMMK;  . .kMMMMMMMMMMMMMWx'...'kMMXc......cXMMO'   .,l0Wd.   .cNXc    .OK;....:X0,    :XMMMMMMMMMWo,OO,...'..lKNMMMMMMM0;.'....oWMWd.....xMMMMWO:.   .   ;KMNk:.';oKWMMMMNl.,,,;,,kMWO'    ,00,   .cNMK;....,:. .....,,.  lNWd...... ,KMW0:. ... .:0l  ...kMMMMMMMMM    //
//    MMMMMMMMKk0NWo.....cNMMK;....cXMNc... .kMMMX:  . 'OMMMMMMMMMMMMMWx....'OMMXc......:XMMO'  ..,kWWx.  ..lNNc    .kX:....:X0,    :XMMMMMMMMMMkoKO,......dWWMMMMMMM0;......oWMMx.....xMMWKl.   ...  .dWMMMKddKWMMMMMMNc.'',,':0MMX:  . ;K0, ...cNMK:.....   ..;oko.   lNWd'......cNM0,      .cKWo.   .kMMMMMMMMM    //
//    MMMMMMMWK0KNWo.....cNMMK;....cXMNo. . .:KMMNc. . .kMMMMMMMMMMNNMWx....,OMMXl......:KMMO' ...,OMMk'....cNNl    .xXc....cX0,    :XMMMMMMMMMWkxNk,......xWWMMMMMMM0:''....oWMMk.....xMNx'   .;o;   .kNOxdoooooodkXMMNl.,''''lXMMXc  . ;K0,....cNMK:....   'o0NM0'    oWWd'......oWWd.      :XMWo.   .kMMMMMMMMM    //
//    MMMMMMMWK0KNNo.....lNMMK;....cXMWo....  'dKKc.   .xMMMMMMMMMXoxWWd. ..;0MMXc......:KMMO' ...;0MM0,....cNNl    .xX:   .:X0,    ;XMMMMMMMMM0:dWk,.''...xWWMMMMMMM0:'.....oWMMk'....xXo.  .,dXk. ..,ONd.       .dNMMNl'''.''oXMMXc... ;K0,....cNMK:....  :KWMMMx.   .dWWx,'.....kMWd. ..  ;KMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWXXXNWo.....lNMMK;....:XMWd'...   .';.    .,lllollccc'.cNWo.   ;KMMXc......:KMMO' ...:XMM0,....cNWo.   .kX:  ..cX0'    ;KMMMMMMMW0,'kMO,.'....xWWMMMMMMM0:....'.oWMMk.   .oo. .,dXWWo....;KMX:       :XMMMNl.''..'oNMMK:....:X0;....cNMK:...  :KMMMMMx.   .dWWx,,'...'kMWd...  .kMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWNXKNWo.....cNMMK;....:XMWx..........       ....       ;XNl.   ;KMMXl''....:KMMO'  ..lNMM0;....cNWd.   .kX:....lN0,    ;KMMMMMMWk' :XMk,......dWWMMMMMMM0:.'',,'oWMMk. ...;' .lKWMMNl. ..:XMWd..'....oWMMMNl''...'oXMMK:....cX0;....cNMK:.....kMMMMMMx.   .dWWd'.....'kMWd..  .lNMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMNKXNWo.....cNMMK;....:XMMx.....lo...      ......      ,KX:    'OMMXc......;KMMk' ...xWMM0;....cXWo.   'kX:....lNK;    ,KMMMMW0c. .kWMO;'''...dWWMMMMMMMKc''',,'oWMMk'......'kWMMMMXc. ..cXMWx,,,,,'.dWMMMNl.'....lXMMK:....cX0,....lNMXc....;KMMMMMMx. . .dWWx'......kMWd... .xMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKkONWo.....lNMMK;. ..:XMMk'....xN0o;.     ......      ;XX;    .xMMXc......;KMMk'....xMMM0;....cXWo.   'OK:....lNK;    ;KMMW0l.  .dNMMO;......dWWMMMMMMMKc'''''.oWMMO,.... ,OMMMMMMK:....lNMWx,''''..xMMMMNl.'....cXMMK:....cN0,....lNMXc....:XMMMMMMx. ...dWWx'......kMWd.....xMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKO0NWo.....lNMMK;    :KMMk'....xWMWNo.   .:kOkkxxddoc'cNK;    .oWMXc......;KMMk'....xMMM0;....cXWo.   'OK:....lNX:    ;KW0l'....dNWNWO;''....dWWMMMMMMMKc',,,'.lWMMO,.....kWMMMMMMK;....lNMWx,''''..xMMMMNl',,...cXMMK;....lN0,....lNMX:....:KMMMMMMx.   .dWWx'.....'kMWd. ...xMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKO0NWd.....lNMMK;    ;KMMO'....xWMMMx.....dWMMMW0dOWW0ON0'     cNMXc......;KMMk'....xMMM0;....:XNl.   'OK:....lNX:  . 'oc... .;OX0OKWO,.''...dWWMMMMMMMKl,,,,'.cNMMO,....cXMMMMMMM0;....lNMWx'',''.'kMMMMNc.,'...cKMM0;....oW0,....oNMK:....:KMMMMMMk.   .oWWx'.....'kMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKKXWWd.....cNMMK;    ;KMMk.....xWMMMk.....dWMNOc'..cONWWk.     ,0MXc......;0MMk'....xWMM0;....cXNl....'OK;....lNK:     .....,dKOclKMMO,...'''dWWMMMMMMMKl;;,''.;KMM0,....oWMMMMMMM0;....oWMWd'.'...'kMMMMNc......cKMM0;....dW0,....lNMX:....;KMMMMMMk.   .oWWx'.....'kMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMNKXXWWd.....lNMMK;  ..;KMMk'...'xWMMMk'....oNO:'......dNWo.    .'xWXc......;0MMk'....xWMM0;....cXNl....'OK:....lNK;     ...,d0k:..dWMMO,......dNWMMMMMMMKc,;,,'..kMM0;....oWMMMMMMM0,....dWMWd'...'..xMMMMNl......cXMM0;....dW0,....oWMX:....;KMMMMMMk.   .oWWx'.....'kMWd.....xMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWXKXWWd.....lNMMK;  . ;KMMk'...'dWMMMk'....oN0c.....':kNNc    .cxONXc......;0MMk'....xWMMK;....:XNo....'OK:...;k0l.     .;xXXo. ..xMMMO,......dWWMMMMMMMKl,,,,,. :XM0;....dWMMMMMMMO'....xMMWx'.'.'..xMMMMNc......cKMMO,....dWO,....oWMX:....;KMMMMMMx.   .oWWx'.....,kMWd....'kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWK0KNWd.....lNMMK;  ..;KMMk'....dWMMMO'....oNMNO:.,lONMM0'  .colo0WNl......,0MMO,...'kMMMK;....:XNo....,0K;.:oo:..     .dNMMO'....xMMMO,......dWWMMMMMMMKc,,;;;. .oN0,....xMMMMMMMMk'....xMMWd'......dWMMMNc......:KMMk'....dWO,....oWMX:....;KMMMMMMk. . .oWWk,.....'kMWd....'kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKO0NWd'....lNMMK:.   ;KMMO,....xWMMMO,....lNMMNxd0WMMMX: .:o:.:KMMNl......,0MMO'...,kMMMK;....:XNo....;KKlcc,...      ,0MMMk.....xMMMO,......dNWMMMMMMMKl,;;::'  .xk,....xMMMMMMMMx....'kMMWd...''..oWMMMNl......:KMMk.....lWO' ...oWMX:. ..;KMMMMMMk... .oWWx'.'''''kMWd....'kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKO0NWd'''''oNMMK:.   ;KMMO,..ckNMMMMO'....oWMWOxXMMMMXo;lxc. .xMMMNl......,0MMk'...,OMMMK;....:XNl...'okl,......    ..,0MMMx.....dWMMO,......dNWMMMMMMMKl,,,,;'.  ';....'kMMMMMMMWx....'xMMWd'',,'..cNMMMNl......:KMWx.....cN0,....oWMX:  ..;KMMMMMMk... .oWWx'...'.'kMWd....'kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKOKNWd.....lNMMK:....:KMMO:lONWMMMMMO'...'kWXo,xWMMMWKOKk'   .OMMMNl......,0MWx....'OMMMK;....cXNc.,cc;..  ...........;0MMMk.....oNMMO;......dNWMMMMMMMKc,,,,;',.    ...'kMMMMMMMWd.....xMMWd...... ;KMMMNc......:KMWd. .. ;K0,....oWMX:  . ;KMMMMMMk'.. .oWWx'.....'kMWd.....kMMMMWo. ...kMMMMMMMMM    //
//    MMMMMMMWXKKNWd.....cNMMK:....;KMWXKKxcl0WMMMO'  .lOd' '0MMMMMMWk.    'OMMMNl......,0MWx....'OMMMK;....cXXo,;..    .',..:kc....:KMMMO,....cNMMO;......dNWMMMMMMMKc'''...co.    ..'kMMMMMMMWx.....dWMWd'..... .OMMMNl......:KMWo......xO,....oWMX:....;KMMMMMMk'....oWWx......'kMWd.....kMMMMXc.....kMMMMMMMMM    //
//    MMMMMMMNK0KNWd.....cNMMK:....:KMWKd,...;xXMWx..';;.  .oNMMMMMWO:.   .,OMMMNl......,0MWd....'OMMMK;....;dl'.    ..:do' ;KXc....cXMMM0;....cXMMO,......dNWMMMMMMM0;..    ,Od.    .'kMMMMMMMWx.....dWMWd'..... .oWMMNl......:KMWo......,c'   .oWMXc....;KMMMMMMk'....oWWx'.....'kMWd.....kMNKdc,... .kMMMMMMMMM    //
//    MMMMMMMNKKNWWd.....cNMMX:....:KW0:.....';kWXc','.   .lXMWMMMNxcxc. ..,OMMMNl......,0MWd....'OMMMK:... ...   ..;o0Xo. .xWX:. ..lNMMM0,....cXMMO,......oNWMMMMMMMk.      cXNd.    .oNMMMMMMMx.....dWMWd......  :XMMNl......:KMNo... ',... ...oWMXc....;KMMMMMMO'....oWWx'.....'kMWo. ...:o;..;c... .kMMMMMMMMM    //
//    MMMMMMMNKXNWWd.....cNMMX:....:KMNk:...;dKWNd,..   .:OXKKNMMNd:ONo. ..,0MMMNl......,0MWd... ,0MMMK;    .....,oONMNo.  ;KMK;   .lNMMM0;....:KMMO,......dNWMMMMMMNl      ;0MMWo.    .:kNMMMMMk.....dWMWd'.....  .xWMNl......:KMNl.   ,d,    ..oWMX: .. ;KMMMMMMO,....oWWx......'kMWd.        .do.....kMMMMMMMMM    //
//    MMMMMMMWKKXNWo.....cNMMXc....;KMMMXdcxXWXk:.   ..cOXOdONMMNo'dWWo..  ,0MMMNl......;0MWd.  .dNWXx;.     .'ckXMMMMk.  .cNM0'   .lNMMMK:.....dWMO,......oNWMMMMMM0,    .;0MMMMx.      .:kNMMMx.  ..dWMWd'......  :XMNl......:KMNl... ;0d.    .oWMX:....;KMMMMMMO,...'dWWx'.....'kWK;       ..lKo.   .kMMMMMMMMM    //
//    MMMMMMMWXKKNWd.....cNMMXc....:KMMMMWNWXd,.   .':kKx;'dWMMXl.cXMWo.   ,0MMMNo'.....;0MNl.,oKXOl,.      .oKWMMMMMNc   .lNMO.    ,0MMMK;.... .oN0;......oNWMMMMW0;.   .cKMMMMMk..     ...;o0Nx.  ..dWMWd'....... .dWNl......:KMNc....;KXc     lNMXc....;KMMMMMMO,....dWWx'......xO,      .:d0NWd. . .kMMMMMMMMM    //
//    MMMMMMMWNXKNWd.....cNMMXc..'.:KMMMMMXd'   ..,,cOO:. ;KMMNo.'OMMNl.   ,0MMMNo......,0W0ldXNk:.....   ..:XMMMMMMMK,   .oWMk.    .oWMMK;....  .;c'......oNWMMMNd'   .'xX0x0WMMk.... ........c:. ...xWMWd......,:. ,0Nl......:KMXc....:KMk.    .:xO:....;KMMMMMMO,....oWWx'.'....l;      .dWMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWNKKWWd.....cNMMX:....:KMMMNx,.  .,:;.,O0,  .oWMWk. lNMMNc.   ,KMMMNo......,0WNNXx;.  ...,.....:XMMMMMMM0' ...lNMk.     .dNMK;......  .   ....oNWWXx;. .':x0Ol,.,xNMk.....cd;.......    .xMMWx,.....,x;  cKo......:KMX:....:KMO'     ........;KMMMMMMO'....oWWx.......,...    .xMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKk0NWd.....cNMMXc....;KMMKc.  .:xd' .dNo.  .xMMK; .kMMMX:  . ;KMMMNo......,0MWO;.  ..'lO0:....:XMMMMMMMO'  ..lNMk.      .cKK:....;o'        .;dkOxoodk0XN0l,.....oNk'....xWXk:.....    .dWMWk;.....,Ox. .cc.''''.:KMX:  . :KMO' .   ...     ,KMMMMMMO'....oWWx.......'dKo.   .kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWK0KWWd'....cNMMXc....;0WO,  .:kXx.  ;KK;   .xMNo. ,0MMMX:    ;KMMMNo...''.,0No. ...;dKWMK:....:KMMMMMMMO'....cXMk.   .,' .;l,  ..;KO;.        .'cd0XWMMMW0c'''.'ckNk'....xMMMNOl,..     'o0Xd'.....,0Xc  ...''''.cKMK:....:XMO'.. ..,..     .cONMMMMO'....oWWx'......lNWo.   .kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKk0NWd'....cNMMXc....;0k' .:OWMO'   lNk. ...xM0'  ,0MMMX:    ;KMMMNo..',;',kd. .'cONMMMMK:....:KMMMMMMMO,....;KMk.   .od. ..     :KMNd.          ..,cdOXWMXo''lOWMMk. ...xMMMMMWXx,     ...;;......,0M0;   .''.''lKMK;....:XMO,....oXkc.      .;dKWMO'.. .oWWx'......xWWo. . .kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWK0KWWd.....cNMMXc....,o, .dNMMNc   .dWx.....xWx.  'kMMMX:.   ;KMMMNo'',,,';l' .:ONWWNNNN0;....;0NNNNNXOd,....,OMk.   .dNd. .     'OWM0;...         ....,cx0KO0WMMMMk.   .xMMMMMMMWd.    ..... .....;0MWk'   ...''cKMK;....cXMO,....dWMK:.     . .'l0k'   .lWWx'......xWWd..  .kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWKOKWWd.....cXMMXc....''.cKWMMMK;   .kWx.....xWo....lNMMK:.   ;KMMMNd'''''.''.,xOdl:::::;,.    .,;;;;;''l:.....dWx.   .xMW0:.      'cdd,.''...';;..   ..  ..;o0WMMMMk... .xMMMMMMMWd.    .....    ..,0MMWd.    .''cKMK:....cXMO'....dWMXl... .......':.   .lNWk,.....'xMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMWX0XWWx'....cNMMXc. ....oNMMMMMO.   .OWx. ...xWo....'kWMXc..  :XMMMNd'.......;0k,.....'...      .'.....'dc.....cXx.   .kMMMNd.     ...........lXXKko;..    .. ,0MMMMk'....xMMMMMMMWd.. .'lo;.       .c0NMNd.    ..cKMK:....cXMk'....xWMXl....,xd;.   ..  ..lWWx'..',''xMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMMWWMWx.....cXMMXc  . .lNMMMMMMx.   'OWx.....dWk.....;OWK:....cXMMMNd'..''..;0Nl..........      .......,Od.....,ko.   'OMMMMX:.    ....    ...lKNMMMWKko:.... .xMMMMk'...'OMMMMMMMWo....,OWXx,       ..:xNNl     .cKMK:....:XMk'....xWMXc....;0MNkc'      .lNWx'.....'xWWd. ...kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMM00WWd.....cXMMXc.   .OMMMMMMWd.   'OMk....'dWK:.....;O0; ...cNMMMNd'..''..dWX:..',;;;;,'.    .';,,,;:xN0;.....;;.  .;KMMMMX:..  .''.        'co0NMMMMMWKko;..oWMMMx.   .kMMMMMMMWo....,0MMWd...     ...:0o.     .xWK:...;xNMO'....xMMXc....;0MMMWKl.    .lNMk,......xWWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMWdlXWd.....cNMMXc.   ,0MMMMMMWo.   'OMk'....dWWk'.....,c'....cNMMMNo......'kMXlck0KXXXXX0;....,OXXXXNWMMNo'..''.. .,dKWMMMMX:. . ,OKx:.       ...;lxKNMMMMMNOldNMMWd. .  :XMMMMMMNo....oNMMWx'....   ....cl..     .lx:':xXMMMO'....xMMXc....;KMMMMMNl.   .lNMO,......xMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMWl.c0d'..,ckWMMXc. . ,0MMMMMMWo.   .kMO,....dWMNd'...... ....cNMMMWd......,OMNKNMMMMMMMMX:....:KMMMMMMMMM0;.',,'..oNMMMMMMMXc. . ,0MM0:..     ......':oOXWMMMWXWMMNl.... .:KMMMMMNl..'dXWMMWx'...'..;,. .cl.'..   ...;kNMMMMMO'....xMMXc....,0MMMMMMk.   .lNMk,......xMWd.....kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMNc .',.;d0WMMMMXc.   ,0MMMMMMWd.   .kMO,....dWMMNd,.....   ..lNMMMK:..    .dWMMMMMMWNX00x,    'xKXNWMMMMMWx,.'''.'lXMMMMMMMNc....,0MMKc..... ...........,lx0NMMMMMK:..,l:  ;OWMMMKc;d0Ol:kWWo..... 'OXx,.oo.'''.  ....c0WMMMMk'....xMMXc....,0MMMMMMO'   .lNMk,.....'xMWd....'kMMMMWo.   .kMMMMMMMMM    //
//    MMMMMMMMWo. ...:kNMMMMMXc. ..,0MWK0WMWd.   .xMO'....dWMMMWO;....    .cOOkkc.       ,OWWWWKxo:'....     ..',cokKWMMNx,....'.cKMMMMMMNl....;0MMKc''..'.:ddl,..........;okXWMO,,xXWk.  .dNMW00Kk:....l0l      '0MMKdko.''''.......'oXMMMk.....xMMXc....,0MMMMM                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LOE is ERC1155Creator {
    constructor() ERC1155Creator("Letterhythm Open Edition", "LOE") {}
}