// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: still too late for you to lea
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//    bring trouble to the forces behind you!"                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//    Present all are successively open, even if Yang Hao is suspected of being a great, they also did not fear, are holy land heirs, themselves have the corresponding cards, the most important thing is, although their teachers elders agreed not to hand, but at the moment are also in the city, really dangerous, absolutely can come in the first time.    //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//    "Let me go. Give me all your weapons, and I will leave at once."                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//    Hear the words of everyone, Yang Hao is a smile, direct mouth way.                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STLFYTL is ERC721Creator {
    constructor() ERC721Creator("still too late for you to lea", "STLFYTL") {}
}