// SPDX-License-Identifier: MIT

// Copyright © 2023 Bams.
// https://bams.monster
// https://x.com/bamsmonster
// https://t.me/bamsmonster

// .-. .-')     ('-.     _   .-')      .-')    
// \  ( OO )   ( OO ).-.( '.( OO )_   ( OO ).  
//  ;-----.\   / . --. / ,--.   ,--.)(_)---\_) 
//  | .-.  |   | \-.  \  |   `.'   | /    _ |  
//  | '-' /_).-'-'  |  | |         | \  :` `.  
//  | .-. `.  \| |_.'  | |  |'.'|  |  '..`''.) 
//  | |  \  |  |  .-.  | |  |   |  | .-._)   \ 
//  | '--'  /  |  | |  | |  |   |  | \       / 
// //  `------'   `--' `--' `--'   `--'  `-----'  


// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXXXNNWWMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0OOOO00KXNWMMMMMMMMWWWNNXXXKKK000OOOOOOOOOOOO00KKKXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0OxddodxxO0KNWMMMMWWWNNXXK00OkkkxxdddoooooooooodddxkkO00KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Oxdolcccloxk0KNWWMWWNXK0Okxxdoollllcccc::::::::::cccclloddxkOKXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNK0Oxol::;;;:coxk0XNWWWNXKOkxolcc::;;;;;;,,,,,,,,,,,,,,,,;;;;::cldxOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0Oxdlc:;,,,,;coxO0KXNNXKOxdolc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:cldkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOxolc:;,,,,,,;coxk0KXXK0kdlc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:cldk0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0Oxoc:;,,,,,,,,;codkO000Okdl:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:coxOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkdlc:;,,,,,,,,,;cldxkkkkxdl:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:coxk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxol:;;,,,,,,,,,,;:lodddddolc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:cldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0koc:;;,,,,,,,,,,,;:cloooolcc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKkdl:;,,,,,,,,,,,,,,;:clllcc::;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:ldkKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxoc;,,,,,,,,,,,,,,,;;::::::;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;coxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kdl:;,,,,,,,,,,,,,,,,;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:ldkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxoc:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdlc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:loxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWXKOxoc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNXOxoc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNKOdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:cldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:cldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWWNKkdc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWWX0koc:;,,,,,,,,,,,,,,,,,,,,,,,;;;;:::::::::::;;;,,,,,,,,,,,,,,,,,,,,,,;;;;:::::::::::::clodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWWX0koc;;,,,,,,,,,,,,,,,,;;;;:::ccllllooooollllccc::;;;;,,,,,,,,,,,;;;::ccllllooollllcccllodxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,,,,,,,,;;;:cclloodxxkkkkOOOkkkxxxxdddoollcc:;;,,,,,;;:cllodxxkkkOOkkxddooooodxkO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,,,,,,,;;:clodxkO00KKXXXXXXKK0OOkkkOOOkkxxdolc:;,,;;:cldxkO0KXXXXXXKOkxddooodxkO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,',,,,;:cloxkOKKXNNNWWWWNXK0Okxdooddxxkkkkkkdoc::::cloxk0KXNWWWWNXK0kdolcccclodxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,',,,;;:coxOKXNWWWWWMWWNKOxdlc;;,,,;:coxkOOOkdolcclldxOKXNWMMWWNX0Oxl:,''..',;coxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,,,,,,;:coxOKXNWWMMMMWNX0xl:,'......';coxkOOkdolcclodxOKNWMMMWWXKOxo:,......',:ldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMWWNX0koc;;,,,,,,,,,,;:coxk0KNNWWWWWNKOdc,.........,:lodxxdoc::::cldk0KNWWMWNX0kdl:'.....';:ldkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWWX0koc;;,,,,,,,,,,,;;cldxO0KXNNNNX0ko:,........',;clloolc:;;;;;:loxO0KNNNNK0kdl:,'''',;:loxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWWX0koc:;,,,,,,,,,,,,,;:clodxkO0000Oxoc:;,,,,,,;;::ccccc::;,,,,,;:cloxkO0000Okxol::;;;;:clodkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWWNKkdc:;,,,,,,,,,,,,,,,;;:cloodxxkkxdolcccccccccccc:::;;,,,,,,,,,;;:clodxxxxxddolcc::::ccldxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNKOdl:;;,,,,,,,,,,,,,,,,,;;:ccllooollccccccccccc::;;;,,,,,,'',,,,,,;::cllloolllccc:::::cloxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc:;,,,,,,,,,,,,,,,,,,,,;;;;:::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;,;;:loxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:ldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWNKkxoc:;,,,,,,,,,,,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''',,,,,;cldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdlc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;coxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxoc:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;coxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kdl:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cdk0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWNNK0koc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:ldk0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKOxl:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:lxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cox0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;cok0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxoc:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:ldOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOxoc;;,,,,,,,,,,,,,,,,;;;,,,,,,,'''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:clxOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxoc:;,,,,,,,,,,,,,;;;:;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:cox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxoc:;,,,,,,,,,,,,;;:::ccccc::::;;;;;;,,,,,,,,,,,,,,,;;;;;;;:::::;;;,,;:cldk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdl:;,,,,,,,,,,,;;::cloodooolllccc:::::;;;;;;;;;;;:::ccclllllcc::;,;;:coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkoc:;,,,,,,,,,,,;;:clooddddddoooolllllllccccccccllllloooolllcc:;;,;;cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxoc;;,,,,,,,,,,,,,;;::cllodddxxxxxxxxxxxxxxxxxxdddddoollc::;,,,,,;:coxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOdlc:;,,,,,,,''''''''',;:cloddxxkkkkkkOOOOkkkkxxxddoolc:;,''...'';:ldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdoc:;,,,,,,'''''.....'',;;:ccclllloooooooollllcc::;;,''......',;cokOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxoc:;,,,,,,''''.............'''''',,,,,,,'''''.............'',:ldOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxoc;,,,,,,,,'''..........................................'',;cok0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0kdl:;,,,,,,,,'''........................................',,;cldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kol:;;,,,,,,,''''..........'''',,,,,,,,,'''''........'',,;:ldk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxolc;;,,,,,,,''''''.''',;;:ccclllllccccc:::;;,,''''''',;:loxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxdlc;,,,,,,,,,,'''',,;:cllooddddddddooollcc:;;,,,''',,:coxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0kdl:;,,,,,,,,,,,,,,,;::ccllloooolllllccc::;;;,,,,,,,;coxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0kdl:;;,,,,,,,,,,,,,,,,;;;;;;:;;;;;;;;;;,,,,,,,,,,,;:ldk0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0kdlc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:lok0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxdlc;;,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,;:cldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0Oxol:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cldkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0kxolc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:coxO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Oxdlc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:coxOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Oxdolc:;;,,,,,,,,,,,,,,,,,,,,,,;;:lodkOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXK0Oxdolc:;;,,,,,,,,,,,,,,,,,;;:codk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXKOkxdollcc::::;;;;;;;:::clloxk0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXK00OkxxddoollllllloodxkO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OOOkkxxxxxkkOO0KXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXXKKKKKKKXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

pragma solidity ^0.8.21;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol";

contract BAMS is ERC20, ERC20Burnable, ERC20Permit {
    constructor() ERC20("BAMS", "BAMS") ERC20Permit("BAMS") {
        _mint(msg.sender, 1_000_000_000 ether);
    }
}