// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Considering the fact that
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    o enhance its origin, it might have had an effect on her, too.                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    Every TIME THE SEA boundary breaks THROUGH a layer, THE SPIRIT grain will be produced, so when the friars practice the SEA boundary, they can refine a device without breaking through a layer. But most of the extraordinary achievements of people, wheel sea secret environment are only refining a device, although it will be a late bloomer, but can break ten thousand method.    //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CTFT is ERC721Creator {
    constructor() ERC721Creator("Considering the fact that", "CTFT") {}
}