// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Gracious Creator
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//    I'm Michael Touchet and love to create new works of art of all kinds. I am a self-taught artist that likes to admire all the beautiful elements this magnificent planet has to offer. I’m not exactly sure why I started making art, but what I can tell you is that I enjoy what I do and I spend a lot of time perfecting my techniques. I make all different types of art work from mosaics,wood/clay sculptures, furniture, and most of all photography. I like to come up with new ideas, which is not always easy. But over time I am able to refine my thoughts and ideas, in the end it’s always fun to create something new.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract GC is ERC721Creator {
    constructor() ERC721Creator("Gracious Creator", "GC") {}
}