// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: FotoGraaGHanneke
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXNWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kkO0OkkXMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxc0MMMMMMWWWWMMMMMMMMN0KWMMMMMMMMMMMMMMMMMMWWWWX0xxxxxdx0XKXXNNNNNNWWMMMMMMMMMMMMMMMMMMMMMN0kkOKNWMNkxXMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKcl0K0OkkxkO0NMMMMMMMWklOXXKK0OOkkxxxxxxxxxxxdoodoodkkxllkO00KXNNNNWWWMMMMMMMMMMMMMMMMMMMNOxkKWMMMW0xkXMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkkxxdc;cdxxkOKXNWWWWNX0Okxo:ldxxxxxkkkkOO00KKKKX0xoxKNWWWN0xkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdkXWMMWXOxxKWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkOO0x:oXWMMMMMMMMMNOdddxdccOXNWWMMMMMMMMMMMMMMWOdkXWMMWXOxxKWMMMWWNXXWMMMMWWMMMMMMMWNNMMMMMXxclk00OkkkkKNN0xONMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdc0MMMMMMMMMMMMWNWWWOlOWMMMMMMWWWMMMMMMMWXxclk00OkkkkKWN0kOOdxxldNMN0OkxxKWMN0kkxokNMW0oxKKOOO0KXNX0dc:xXWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlkWMMMMMMMMMN0OOOXWKoxNMMMMNOdxkkKX0XWW0xoxK0OOOOKXNX0xc:xXK0KxdKNOdk0Occ0W0dd0Kd;dNXxckNMMMMMNOkxl:c;oXMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKldNMMMMMMMMM0o:lkolxlc0MMMWXdcldxclx0NWOlckNMMMMMXOkxl::;oNMMWklk0ocx0xo:cxd:ckkdocldc;xNMMMMMMNKOdd0OlxWMMMMMMMMMMM    //
//    MMMMMMMMMMWNK0OO0O00OO0KNWMMMMMMNolKMMMMMMMMMWkldoclxOdl0WXOxxoodllxKNMW0oxXNMMMMMMNKOddOkckWMMW0dxkkxxk0NXOkOOkk0NWX0kcdNMMMMMMWKxdONWkcOMMMMMMMMMMMM    //
//    MMMMMMMNKkkkkO0KXNNNXK0Okk0WMMMWkckWMWWNXK00KKKOkkOXWMKddxxkKWWKO0XWMMMXodNMMMMMMMWKxdONWkcOMMMMMWWMMMMMMMMMMMMMMMMMMWkc0MMMMMN0xdONMMNdlKMMMMMMMMMMMM    //
//    MMMMMMWk:l0NWMMMMMMMMMWWNOddOK0k::dxkkkOOO0KXWWMMMMMMMMWNNWMMMMMMMMMMMWkc0MMMMMMW0xdONMMNdlKMMMMMMMMMMMMMMMMNKXMMMMMMWxlKMMWXOxx0NMMMMKldNMMMMMMMMMMMM    //
//    MMMMMMWXkddxxxxxxxxxxxxxxxdl:co::xO0XNWWMMMMMMMMMMMK0NMMMMMMMMK0NMMMMMWdlKMMMWXOxx0NMMMMKldNMMMMMMMMMMMMMMMWOl0MMMMMMMKookkxxkKWMMMMMWkc0MMMMMMMMMMMMM    //
//    MMMMMMMMMWNXXKKKKKKKKXXXNWWNkll:xWMMMMMMMMMMMMMMMMNdoXMMMMMMMXodNMMMMMW0ookkkxxkKWMMMMMWxc0MMMMMMMMMMMMMMMMXodNMMMMMMMMNK00XWMMMMMMMW0ldNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'lXMMMMMMMMMMMMMMMMMOlkWMMMMMMWkl0MMMMMMMMN0OO0XNMMMMMMMM0ldNMMMMMMMMMMMMMMMWxlKWNXWMMMMMMMMMMMMMMMMMW0loXMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0x0WMMMMMMMMMMMMMMMMXooXMMMMMMM0lkWMMMMMMMMMMMMMMMMMMMMMW0loXMMMWWMMMMMWX00NM0lx0xdONMWXOxONMWWMMMMMMNklxXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxl0MMMMMMMXooXMMMMWNKOkkOXWMMWK00kkOOldXKkkkxxKMMMXxlcoKXo;ok0NMWXxc:lkNKkKWX00Okdx0WMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWW0lkWMMMMMMWkl0WXK0kdoxOOcc0WWXx;:dkloO0Kk:,lOklOWXkc:okK0ocllONWXkl;:xO0kx0WMNK00KNWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000K0000kcl0NWMMWNXkccxkkOOo:xKko:ckOkc,:kNXolkkd:,dXM0ldxxkdoxkkl:kN0xxxxO0Oxkkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkOO0KXNWWWMWXolkkdxkkkkd:lOXWWMWOdxkOKKkxxkdlOWMWKOOKKxxNMMWXKXNMWNXXNKKNMMWNNWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0clOXNNNNXKK0Oko:oxkxxooOXkl0MMMMMMMWWWMMMMMMMNNWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kxkkkkkkkkkko:xXWWMMWOdxlxWMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNXXXKKKK0000000000KXNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMXoxNMMMMMMNx;cKMMMMMMMMWNXXK0OOkkkxxxxdddxxxxxxkkkkkkkkOOO000KKXXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kXMMMMMMMMO:dWMWX0OkxdddxxxxkkkOO0KKKXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMXkKMMNOxxkO0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract FGH is ERC721Creator {
    constructor() ERC721Creator("FotoGraaGHanneke", "FGH") {}
}