// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Talismans by Anna Judd
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;'.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,:X0,.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.xWWo :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxoOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;.OMMx.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc;,,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0''0MWo.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo:KO,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.,KMK,'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l;'dWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;dWNc:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.,KWo.oWMMMMMMMMMMMMMMMMMWWMMMMMMMMMMXOc.lWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo;0MWo:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.,Kk':XMMMMMMMMMMMMMMMMMXlc0MMMMMMMMMMWo.xMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;cNMWo:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.'l,,0MMMMMMMMMMMMMMMMMWo .OMMMMMMMMMMX;,KMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dWMNllNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0' .,OWMMMMMMMMMMMMMMMMM0, ,KMMMMMMMMMMk'lWMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,kMM0:xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd. ,0MMMMMMMMMMMMMMMMMMMk. :XMMMMMMMMMNc,OMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWo,OMNl:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxo:'.. lNMMMMMMMMMMMMMMMMWWWx. cNMMMMXdcdKO,lNMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWl,0Wk,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;. .cx0l.:NMMMMMMMMMMMMMMWOc;c; .xMMMMK:   .''OMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNl,00;cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0x,.lXWd.;XW0xKMMMWWMMMWXx.     :XMMXd'.;l;. lNMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNc,x:,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.:Xx.;Ox;.dMMXllXNkc'  .;. .xMWO:. :XMO',0MMMMM    //
//    MMMMMWNNWMMMMMMMMMMMMMMMMMMMNc.''xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'dd.;OKo'xMWd.'dc,c, .cl. .xNx,;,.xNO;,OWMMMMM    //
//    MMMWO:',xWMMMMMMMMMMMMMMMMMMNc .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX::l.:NNc.kMO, ..;0O' ....;.';,oKc.,;':0WMMMMMM    //
//    MMNd.'odkWMMMMMMMMMMMMMMMMMMK,.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdkKkd0l;c.:XX:'0X:,:..dWd   .;0Xo;l0WMKoclONMMMMMMMM    //
//    MWk.,0MMMMMMMMMMMMMMMMMMMMMXc ,KMMMMMMMMMMMMMMMMMMXxk0xloKMMMMMMKl.   ..;Oc:o.;XX;'xc'xO,'0Mk. 'dXMMWWMMMMMMMMMMMMMMMMMM    //
//    MX:.xWMMMMMMMMMMMMMMMMMMMMX:. ;KMMMMMMMMMMMMMMMMMWo..';;.lWMMMNk, .;c' .ok,ok.,KX;..'dNW00WMN0OXWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MO';KMMMMMMMMMMMMMMMMMMMMXc.;';XMMMMNO0WMWKk0WMMWk. .oXO'lWWN0:..lKN0,  '':KO.'0X; ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    Wd.lWMMMMMMMMMMMMMMMMMMMXc.lk,:XMMMWd.cXKl'.cNMMO' .xWWd.dNx:'..'OWk'.cc:dXMO.'0WOxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMX00XMMMM    //
//    Wl.dWMMMMMMMMMMMMMMMMMMNl.cXO':NMMM0' :o,;:.oWM0,  :XMNc'xo..:Oc.ol.,kWMMMMMx.,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl..,kWMM    //
//    N:.xMMMMMMMMMMMMMMMMMMNo.:KMk.cNMMNc. ..lKo.xW0,...dWMWl...cOXM0:.,oKMMMMMMNc ;XMMMMWWWWWWWWWWWWWWWWMMMMMWWNX0xc.  .xWMM    //
//    K,.OMMMMMMMMMMMMMMMMMNd.,0MMk.cNMXl':. cXNc.kO,'c.,0MMMKc;xNMMMWKOO00Okkxxdl. .clcc::;;,,,,,,,,,,;;;:::::;,'..  .;dKWMMM    //
//    0''0MMMMMMMMMMMMMMW0o,..;dXWk.cKx;;xd.;KMNc.:',OXxOWMMWX0kdolc:,'...             .......'''''''........'',;:clxOXWMMMMMM    //
//    O.,KMMMMMMMMMMMMMM0,  .xOo:xd..',dX0,.kWMWx'.cKWWXOxl:,..     ..',;::cclloc. 'dO00KKXXXNNNNNNNNNNNXXXNNNNWWMMMMMMMMMMMMM    //
//    O.,KMMMMMMMMMMMMMMK;  ,xkx;.. .oXMMKlxWMMMWKOkdc,.    .';coxkO0XNWWMMMMMMMk. lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    K,'0MMMMMMMMMMMMMMK,.;cc::cc' '0MMMMWMMWXOo:.   .':lxOKNWMMMMMMMMMMMMMMMMNc .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    Wo.dWMMMMMMMMMMMMK:.oNMMWWMMK:.xMMMWXOo;.   .,:cxXWMMMMMMMMMMMMMMMMMMMMMMO. cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MK:'kWMMMMMMMMMW0;.lNMMMMMMMMXOKWKx:.   .;lkK0:';lOWMMMMMMMMMMMMMMMMMMMMXc .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMKc'lKWMMMMMMWk'.dNMMMMMMMMMWXx:.  .;oOXWMMM0''xxxXMMMMMMMMMMMMMMMMMMMWd. lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMNx;,:dk00Ox:.;OWMMMMMMMMMKo'  .cxKWMMMMMMMWd.:KWMMMMMMMMMMMMMMMMMMMWx. :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMNOo:;,,,;ckNMMMMMMMMMNx' .;xXWMMMMMMMMMMMWk,,xXMMMMMMMMMMMMMMMMMNd. :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWNNXNWMMMMMMMMMMMXl. ;kNMMMMMMMMMMMMMMMMXd;;o0NMMMMMMMMMMMWXk;..oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWk..lNMMMMMMMMMMMMMMMMMMMMXkc;:ldO0KKK0Oxl:..'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNd;dNMMMMMMMMMMMMMMMMMMMMMMMWXOoc:;;;,'',;cdONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TALISMANS is ERC721Creator {
    constructor() ERC721Creator("Talismans by Anna Judd", "TALISMANS") {}
}