// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cat Editions
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                        //
//                                                                                                                                                                        //
//    MMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWNXWMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMWK0WMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNOddkXWMMMMMMMMMMMMMWWMMMMMMMMMMMNdl0WMMMMMMMMMMMMMMMMMMMMMMMMNKNMMMMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXd,....'cxKWMMMMMMMMMMMMMMMMMMMMMMMM0;,xNMMMMMMMMMMMMMMMMMMMMMMMOkNMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXc.........'cONMMMMMMMMMMMMMMMMMMMMMMM0;.oNMMMMMMMMMMMMMMMMMMMMMNxxWMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxllxXMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWd....d0x:.....:OWMMMMMMMMMMMMMMMMMMMMMM0;.cKMMMMMMMMMMMMMMMMMMMMXdOMMMMMMMMMMMMMMMMMMMWKKWMMMMMMMMMMMMMMMMMMMMMMMMMWKo,....oWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXc...lNMMW0l.....oXMMMMMMMMMMMMMMMMMMMMMM0;.;0MMMMMMMMMMMMMMMMMMM0lOMMMMMMMMMMMMMMMMMMM0kNMMMMMMMMMMMMMMMMMMMMMMMMMNx'......oWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXc...lNMMMMW0:....;kNMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMOckMMMMMMMMMMMMMMMMMW0xXMMMMMMMMMMMMMMMMMMMMMMMMMKc........oWMMMMMMMMMMMMMMMMM    //
//    MMMMWWWMMMMMMMMMMNl...:XMMMMMMNx'....;dKWMMMMMMMMMMMMMMMMMMM0;.:XMMMMMMMMMMMMMMMMMO:kMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMWNKOo,...',....oWMMMMMMMMMMMMMMMMM    //
//    MMMMMWWWWMMMMMMMMMx....xWMMMMMMWKo'....'cdxO0XWMMMMMMMMMMMMMWk;oNMMMMMMMMMMMMMMMMWd:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0koc:,'.....cOl....xMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWNNMMMMMMMMX:...,0MMMMMMMMWKd;........,:ld0NMMMMMMMMMMWNWMMMMMMMMMMMMMMMWWOckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoc;,'........':o0WK;...;KMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWNNWMMMMMMMk'...cXMMMMMMMMMMNkl,..........,lx0WMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,........,:oxO0XWMMWx....oWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWXNWMMMMMNo....dWMMMMMMMMMMMMNK0kdl:,.......:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.....:oxkOKNWMMMMMMMMX:...,0MMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWNXXWMMMMXl...;0MMMMMMMMMMMMMMMMMMWN0xl;......;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.....;d0WMMMMMMMMMMMMMMMk'...oWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMN0KWMMMMK;...oWMMMMMMMMMMMMMMMMMMMMMMWKko:.....,lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:....:d0NMMMMMMMMMMMMMMMMMNl...'OMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWNWMMMMWd...;KMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:'....':oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:...'l0WMMMMMMMMMMMMMMMMMMMM0,...lNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMO'...xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl;.....':d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;...'oKWMMMMMMMMMMMMMMMMMMMMMWo....kMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMK;...lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xc,.....,lxKWMMMMMMMMMMMMMMMMMMMMMMWKo,...;dXWMMMMMMMMMMMMMMMMMMMMMMM0,...:XMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNl...;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'.....:dKWMMMMMMMMMMMMMMMMMMXo'...:kNMMMMMMMMMMMMMMMMMMMMMMMMMMx....dMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMk'...oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;.....:x0XMMMMMMMMMMMMMNk,...:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...'OMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNo....dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d;.....,oKWMMMMMMMMWO:...,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;...;KMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMWWMMMMMMMMMMMMMMMMMMMXc....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'....'xNMMMMMNk:...'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'...oWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMWNXWMMMMMMMMMMMMMMMMMMK;...'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;....xWMMNk:...'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd....xMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMWXKKWMMMMMMMMMMMMMMMMMO'...;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNd...;KWO:...,dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc...'OMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWK0XWMMMMMMMMMMMMMMMNl....dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;...oo...'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'...:XMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWXKXWMMMMMMMMMMMMMXc....kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.......:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd....oWMMMMMMMMMMMMMMMWKkXMMMM    //
//    MMMMMMMMMMWX0KNMMMMMMMMMMNo....cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'.....oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:...'OMMMMMMMMMMMMMMW0olkNMMMM    //
//    MMMMMMMMMMMMNKOOXMMMMMMMNl....:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo...,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'...:XMMMMMMMMMMNOxxolkNMMMMMM    //
//    MMMMMMMMMMMMMMWXNMMMMMMXl....lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc....dWMMMMMMMMMMW0kOKWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMKc...'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo....:KMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMK:...'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO;....;0MMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMXc....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.....cKMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXl....dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'....,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNl....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'....lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWd....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo....'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMO'...oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl....:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNl...:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl....lXMMMMMMMMMMMMMWNKKKKXXNWMMMMMMMMMMM    //
//    MMMMMWWWWWMMMMMMO'...kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx....;KMMMMMMMMMMMMMMNkllllllllox0WMMMMMMM    //
//    MMMMMMMMWNXWMMMNl...cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc....lXMMMMMMMMMMMMMMMWWWWWNXK0O0NMMMMMMM    //
//    MMMMMMMMMMMMMMMO'..'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl....,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNc...lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'....oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWx...;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;....cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMK;...kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOdl,.....;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:....;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWo...oNMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,...........'dXMMMMMMMMMMMMMMMMMMMMMMMMMWKkdodxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMXl....:XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMM0,..;0MMMMMMMMMMMMMMMMMMMMMMMMMWKo'.....,,........:0WMMMMMMMMMMMMMMMMMMMMWKd;........;cld0NMMMMMMMMMMMMMMMMMMMMMMX:....dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNl...dWMMMMMMMMMMMMMMMMMMMMMMMW0l'.....;xXXk;.......'xWMMMMMMMMMMMMMMMMMW0o'...............;dKWMMMMMMMMMMMMMMMMMMMMO'...'kWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMO'..:KMMMMMMMMMMMMMMMMMMMMMMMKl......,dXMMMMK;........dNMMMMMMMMMMMMMMNk:....................'oKWMMMMMMMMMMMMMMMMMMWd....,0MMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNl...xWMMMMMMMMMMMMMMMMMMMMMNx,.....,oXMMMMMMWx.........xWMMMMMMMMMMM0x:......,oo,....';;.......'dNMMMMMMMMMMMMMMMMMMNl....cXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMM0,..;KMMMMMMMMMMMMMMMMMMMMMXo......oKMMMMMMMMMNkod;.....,0MMMMMMMMMM0;......;xXMWX000KXWNOc.......cXMMMMMMMMMMMMMMMMMMK;....oWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMx...oWMMMMMMMMMMMMMMMMMMMMXl.....'kWMMMMMMMMMMMMMMk'.....lNMMMMMMMMK:......cXMMMMMMMMMMMMMW0:......:KMMMMMMMMMMMMMMMMMMk'...,0MMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWo...xMMMMMMMMMMMMMMMMMMMMNo.....'kWMMMMMMMWKdlcllldc......xWMMMMMMXl......:KMMMMMMMMWNKOddxKXo......:KMMMMMMMMMMMMMMMMMXc....xMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMNc...kMMMMMMMMMMMMMMMMMMMMO,.....dWMMMMMMMNx'.......:'.....;KMMMMMWd......'kMMMMMMXkl:,'....'xXo......oWMMMMMMMMMMMMMMMMWo....lNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMWNXXNWMNc..'OMMMMMMMMMMMMMMMMMMMWd.....,0MMMMMMMWk.................lNMMMMO,......oNMMMMNx,..........cXX:.....;KMMMMMMMMMMMMMMMMMx....:XMMMMMMMMMMMNKKKXWMMMMMM    //
//    MMMWXXNWMXc..'OMMMMMMMMMMMMMMMMMMMNl.....;XMMMMMMMXc.................'OMMMNl......;KMMMMNl............lNWo.....,0MMMMMMMMMMMMMMMMMk....;KMMMMMMMMMMW0ddooodONMMM    //
//    MMMMMMMMMNo...kMMMMMMMMMMMMMMMMMMMNl.....;KMMMMMMMNc..........;l......xMMMO'......dWMMMWx.............kMWl.....,KMMMMMMMMMMMMMMMMMO'...;KMMMMMMMMMMMMMMMWXKKNWMM    //
//    MMMMMMMMMWx...oWMMMMMMMMMMMMMMMMMMWd.....'OMMMMMMMWx.........,kO,.....oWMWd..... ,0MMMMWd............cXMK;.....:XMMMMMMMMMMMMMMMMMk'...;KMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMO'..:XMMMMMMMMMMMMMMMMMMMO'.....lNMMMMMMMNo......'l0W0,.....lWMK:......lNMMMMMXc..........cKMNl......xWMMMMMMMMMMMMMMMMMx....lNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMX:..'OMMMMMMMMMMMMMMMMMMMNl.....'OMMMMMMMMNd;'',oKWMMk......dWMO'.....,kMMMMMMMNx,.......oXMWd......lNMMMMMMMMMMMMMMMMMWo....dWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWo...dWMMMMMMMMMMMMMMMMMMM0;.....cXMMMMMMMMMNXKNMMMW0;.....,0MMd.....,o0MMMMMMMMMXxl::co0WMNd......:KMMMMMMMMMMMMMMMMMMNc....kMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMk...cNMMMMMMMMMMMMMMMMMMMWk'.....oNMMMMMMMMMMMMMMNx'.....'xWMWd.....'lOMMMMMMMMMMMMWWWMMW0c......;0MMMMMMMMMMMMMMMMMMMK;...'OMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMO,..;KMMMMMMMMMMMMMMMMMMMMNo......dNMMMMMMMMMMMWOc......,kWMMMO'......;xKNMMMMMMMMMMWN0x:.......:0WMMMMMMMMMMMMMMMMMMMk....:XMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMK;..,0MMMMMMMMMMMMMMMMMMMMMXc......dNMMMMMMMWKx:.......cKMMMMMNd.........;cldxkOkxol:,........,xNMMMMMMMMMMMMMMMMMMMMNl....dWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMX:..'OMMMMMMMMMMMMMMMMMMMMMMK:......c0NMWXOd:........,xNMMMMMMMNk;..........................;dXMMMMMMMMMMMMMMMMMMMMMWk'...,0MMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNl...kMMMMMMMMMMMMMMMMMMMMMMMXc.......;c:'.........;xXMMMMMMMMMMMNOo;'..................':oONMMMMMMMMMMMMMMMMMMMMMMM0,...'kWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWo...xMMMMMMMMMMMMMMMMMMMMMMMMNd'...............;oONMMMMMMMMMMMMMMMMNXKkdoc:,''.'';:loxOXWMMMMMMMMMMMMMMMMMMMMMMMMMNl....xWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWo...dWMMMMMMMMMMMMMMMMMMMMMMMMWKo;.........,cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd....lNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWo...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kdolloxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx....:XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWo...lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'...:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWNNWx...:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkxdxxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKK0OOO0KNWMMMMMMMMMMMMMMMM0;...,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMWWWNXNMO,...dWMMMMMMMMMMMMMMMMMMMMMMWXOdl:,.........;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc'',,,,,,,.....,:ox0XWMMMMMMMMMMK:...'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNl...,OMMMMMMMMMMMMMMMMMWXOdl:'..............'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOO00KKKKKK0Odl;'....,:lxOXWMMMMNl....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMM0;...;0MMMMMMMMMMWNKOxo:'............,;;:cldKWMMMMMMMMMMMWX00NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOdc;'....':lxO0o....oNMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNd....;odoolllccc:,............;cdk0KXNWWMMMMMMMMMMMMMMMNd'..;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdl;'.........,dO00KXXNNNNXX0Oxdlc::cxXMMMMMMMMMM    //
//    MMMMMMMMMMXkl:'........................,:okKNMMMMMMMMMMMMMMMMMMMMMMMNo.....;KMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMWKOdc'...........'',,,,,'........'cKMMMMMMMMMM    //
//    MMMMMMMMM0:.....................';coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMNk:.......cKWMMMMWXkl::lOWMMMMMMMMMMMMMMMMMMMMMMMMMWk'...:olc;,'..........';:codOKWMMMMMMMMMMM    //
//    MMMMMMMMWd............;clllodxO0XNMMMMMMMMMMMMMMMMMMMMMMMXxcco0NKd;..........,lodooc,.....;KMMMMMMMMMMMMMMMMMMMMMMMMWk'...cXMMWWNXK000OOO00KXNWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMM0:...cO0l....:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.....,.......lo'................dNMMMMMMMMMMMMMMMMMMMMMMMNd....oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNOxOWMMK:....:KMMMMMMMMMMMMMMMMMMWXK0000XWMMMMM0,.........'l0WW0c'...........,l0WMMMMMMMMWNNWMMMMMMMMMMMKc...,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMK:....;OWMMMMMMMMMWNKOxoc;,'....'dNMMMMMKl,....;cxXWMMMMWKxolcccclodONMMMMMMMMMM0c;;:clodxOKNMNk,...lKMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWWMMMMMMMMXl....'dNMMWNKOxoc,.......,:loxk0WMMMMMMWNK00KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxo:.....';l:...,kWMMMMMMMMMMMMMMMMMMMNxox0XWMMMMMMMMMMMMMMM    //
//    MMMMMMMWXxOWMMMMMMMMNx'....;ol:,.......';ldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc,.......;0MMMMMMMMMMMMMMMMMMMMMMWXK0O0KKNMMMMMMMMMMMM    //
//    MMMMMWWX00NMMMMMMMMMWKl...........':ldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.......l0WMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXNWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWKxc'...........:kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:...''....'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMM    //
//    MMMMMMMMMMMMMWKOo:'.......,;.......;lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;...;dKKo'....'oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MWWNNNNXXKOxo:'.......':oOXNOo,........;ldOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc...,lONMMMWKl.....,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    kc;,,,,''.........':okKWMMMMMMN0dc,.........;lx0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXXOd:...,lkXMMMMMMMMWOc.....,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    ..............':oOXWMMMMMMMMMMMMMMN0xl:'........';cldk0KXWMMMMMMMMMMMMMMMMMMMWNK0Okkxddoolc;,''''...:oOXWMMMMMMMMMMMMNk;.....'o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    c'......';cox0XWMMMMMMMMMMMMMMMMMMMMMMWXkoc'............,;clok0KNWWMMWNXK0kdl:,.................;okKWMMMMMMMMMMMMMMMMMMNx;......ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    WXK0OO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxoc;'.............',;:c::;'..............''',;:lodONMMMMMMMMMMMMMMMMMMMMMMMMNx;......;dKWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxol:;'..................';cloxO00KKXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;......'lkXMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKOxolc;,,,,;:codkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc'......,lkKNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;........;cd0WMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM                                                                                                                                         //
//                                                                                                                                                                        //
//                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Catty is ERC1155Creator {
    constructor() ERC1155Creator("Cat Editions", "Catty") {}
}