// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: nothingnesss
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.   .dKNNXXXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..cl:,.',,,,,;:oONMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWXOxxdxxk0XWMMMMMMWx..kWMWN0xxxkkxdl,.:KWO:',;lx0NWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMKl'.',;,,''';o0WMMWk..dWMMMMMMMMMMMMMX: ;l..lxl;'.':d0NMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXx'.c0NWWWNXKxc'.;oo:..dNMMMMMMMMMMMMMMMKl'.;kWMMWX0xc'.,oONMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWO,.;kNMMMMMMMMMWXxc;;cdKWMMMMMMMMMMMMMMMMMWXXNMMMMMMMMWXOl'.,o0WMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK,.lNMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc'.:kNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMk..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd,.:0MMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMx.'0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.'OWMMMMMMMMMM    //
//    MMMMMMMN0dcco0WMMMMMk..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.'kWMMMMMMMMM    //
//    MMMMMXx;.'::..dNMMMMk..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.'OMMMMMMMMM    //
//    MMMNx,.;xXWWO'.c0WMMk..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.,0MMMMMMMM    //
//    MMKc.,kNMMMMMKl'.;cl'.cXMMMMMMWX00KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00KNMMMMMMMMMMMMMMMMMMX: :XMMMMMMM    //
//    MXc.;KMMMMMMMMWXkoc:cxXMMMMWXd;....'cOWMMMMMMMMMMMMMMMMMMMMMMW0o,....,o0WMMMMMMMMMMMMMMMM0,.lXMMMMMM    //
//    Wx.'OMMMMMMMMMMMMMMMMMMMMMWk'        .cKMMMMMMMMMMMMMMMMMMMMXo.        .dNMMMMMMMMMMMMMMMM0,.cXMMMMM    //
//    K,.oWMMMMMMMMMMMMMMMMMMMMWx.           ;KMMMMMMMMMMMMMMMMMMXl           .oNMMMMMMMMMMMMMMMMK:.,OWMMM    //
//    d.'0MMMMMMMMMMMMMMMMMMMMM0,             lNMMMMMMMMMMMMMMMMWd.            .kMMMMMMMMMMMMMMMMMNo..dNMM    //
//    : cNMMMMMMMMMMMMMMMMMMMMWd.             .OMMMMMMMMMMMMMMMMK;              lNMMMMMMMMMMMMMMMMMWO,.cXM    //
//    ..xMMMMMMMMMMMMMMMMMMMMMWl              .xMMMMMMMMMMMMMMMMO.              ;XMMMMMMMMMMMMMMMMMMMK:.:X    //
//    .'0MMMMMMMMMMMMMMMMMMMMMWl              .xMMMMMMMMMMMMMMMMO.              :XMMMMMMMMMMMMMMMMMMMM0,.o    //
//     ,KMMMMMMMMMMMMMMMMMMMMMMx.             .OMMMMMMMMMMMMMMMM0,              oWMMMMMMMMMMMMMMMMMMMMWo.,    //
//     ,KMMMMMMMMMMMMMMMMMMMMMMX:             :XMMMMMMMMMMMMMMMMNo             '0MMMMMMMMMMMMMMMMMMMMMMO..    //
//     ;KMMMMMMMMMMMMMMMMMMMMMMM0,           ,0MMMMMMMMMMMMMMMMMMX:           .kWMMMMMMMMMMMMMMMMMMMMMMK,     //
//     ;XMMMMMMMMMMMMMMMMMMMMMMMW0:.        :0WMMMMMMMMMMMMMMMMMMMXl.        ;OWMMMMMMMMMMMMMMMMMMMMMMMX;     //
//     ;XMMMMMMMMMMMMMMMWWWMMMMMMMNOc'...'ckNMMMMMMMMMMMMMMMMMMMMMMWOl,...':xNMMMMMMMMMMMMMMMMMMMMMMMMMN:     //
//     ;XMMMMMMMWXK0Oxoc;,oXMMMMMMMMMNXKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKKNWMMMMMMW0OKNWMMMMWWMMMMMMMMMN:     //
//     ,KMMMMMM0c,'.. 'coxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'',;::c:;lKMMMMMMMMNc     //
//     '0MMMMMMN0O0O; lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0x, .codONMMMMMMMMN:     //
//    ..OMMMMMMMMMMWk'.:kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc cNMMMMMMMMMMMMN:     //
//    ..kMMMMMMMMMMMWKd,.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; oWMMMMMMMMMMMMX:     //
//    ; lNMMMMMMMMMMMMMNx..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..OMMMMMMMMMMMMMX:     //
//    d.,KMMMMMMMMMMMMMMWo.,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx..dNMMMMMMMMMMMMMX;     //
//    O..OMMMMMMMMMMMMMMMO..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl,.,xNMMMMMMMMMMMMMMX;     //
//    0'.xMMMMMMMMMMMMMMMX: cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..lONMMMMMMMMMMMMMMMMK,     //
//    X; oWMMMMMMMMMMMMMMM0:.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk..kWMMMMMMMMMMMMMMMMMM0'.    //
//    Wd..kWMMMMMMMMMMMMMMMNx;.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.oNMMMMMMMMMMMMMMMMMMMk..    //
//    MNd'.;xNMMMMMMMMMMMMMMMNk'.dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,.lXMMMMMMMMMMMMMMMMMMMWo ,    //
//    MMMXx,.cXMMMMMMMMMMMMMMMWd.,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl..dNMMMMMMMMMMMMMMMMMMMMX; l    //
//    MMMMMK;.lNMMMMMMMMMMMMMMM0,.lKXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.:0WMMMMMMMMMMMMMMMMMMMMMk..O    //
//    MMMMMMx..OMMMMMMMMMMMMMMMWO;.'''',,,:lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.lNMMMMMMMMMMMMMMMMMMMMMMK; lN    //
//    MMMMMM0'.xMMMMMMMMMMMMMMMMMWK0OOOkkxo;.,xNMMMMMMMMMMMMMMMMMMMMMMMMMWo.;KMMMMMMMMMMMMMMMMMMMMMMNl.,KM    //
//    MMMMMMK; oWMMMMMMMMMMMMMMMMMMMMMMMMMMNk,.;xXMMMMMMMMMMMMMMMMMMMMMMM0,.dWMMMMMMMMMMMMMMMMMMMMMXl.'OMM    //
//    MMMMMMNc cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;.'cxKWMMMMMMMMMMMMMMMWKOd;.:XMMMMMMMMMMMMMMMMMMMMMK:.;0WMM    //
//    MMMMMMMO'.lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;..dNMMMMMMMMMMMMWO:.',:dXMMMMMMMMMMMMMMMMMMMMM0,.cXMMMM    //
//    MMMMMMMW0:.'ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'.lKNWMWWNX0Okx:.'dKNWMMMMMMMMMMMMMMMMMMMMMMNc :XMMMMM    //
//    MMMMMMMMMW0o'.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'.',;;;,'',,,:dXMMMMMMMMMMMMMMMMMMMMMMMMMMO..kMMMMMM    //
//    MMMMMMMMMMMMXc.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdoodkOKXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMWo ;KMMMMMM    //
//    MMMMMMMMMMMMMX; lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN: cNMMMMMM    //
//    MMMMMMMMMMMMMMk..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMX; oWMMMMMM    //
//    MMMMMMMMMMMMMMK; oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOoc;;ckNMMMK,.dMMMMMMM    //
//    MMMMMMMMMMMMMMNc :NMMMMMMMWXOk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'.,col..xWMMO..kMMMMMMM    //
//    MMMMMMMMMMMMMMWo ;XMMMMMW0c'.'.'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk..l0NMMNc cNMMx.'0MMMMMMM    //
//    MMMMMMMMMMMMMMWo ;XMMMMMO'.c0Xk'.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMNc cNMMMMNc cNMWd.,KMMMMMMM    //
//    MMMMMMMMMMMMMMWo ,KMMMMX: cNMMMk..OMMMMMMMMMMMMMMMMMMMMMMMMNOo:;;:dKMMMMMX: lWMMMMNc cNMMx.'0MMMMMMM    //
//    MMMMMMMMMMMMMMMk..OMMMM0'.xMMMMO..kMMMMWN000XWMMMMMMMMMMMMXl.'loo:.'kWMMMX: lWMMMMWl :XMMd.,0MMMMMMM    //
//    MMMMMMMMMMMMMMMX: cXMMMk..OMMMWd.'0MMMNd'.''';dXMMMMMMMNKx;.;0MMMWd..kWMMX; oWMMMMMk..oOx,.lNMMMMMMM    //
//    MMMMMMMMMMMMMMMM0:.'col'.lNMMMWl :XMMMO..dKKk,.:XMMMMNx,.';dXMMMMMNo.,KMMX; oWMMMMMWk;''';dXMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNOoc::ckNMMMMNc cNMMMx.'0MMM0'.xWMMMx..dXWMMMMMMMM0,.dWMX; oWMMMMMMMWXXNWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWMMMMMMMMNc cNMMMx.'0MMMN: lWMMWl :XMMMMMMMMMMX: lWMN: lWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.'0MMNo.,KMMMN: cNMMNc cNMMMMMMMMMMX; oWMNl :NMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.'cc;.'xWMMMX; oWMMNc cNMMMMMMMMMMK,.dWMNl :XMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOollokXWMMMM0'.xMMMN: lNMMMMMMMMMMX: ;kOo..dWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.'0MMMX; lWMMMMMMMMMMMKl,'',:kNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl :XMMMK, dWMMMMMMMMMMMMMNXXNWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK; oWMMMO..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO..kMMMMO..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo ;KMMMMK; oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc cNMMMMNl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc :XMMMMNc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.;oooo;.'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.    .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract nothing is ERC1155Creator {
    constructor() ERC1155Creator("nothingnesss", "nothing") {}
}