/**
 *Submitted for verification at Etherscan.io on 2023-04-28
*/

/**

HTTPS://SCHIZO.ARMY HTTPS://SCHIZO.ARMY HTTPS://SCHIZO.ARMY HTTPS://SCHIZO.ARMY HTTPS://SCHIZO.ARMY HTTPS://SCHIZO.ARMY 

&&&&&&&#BBBBBBBBGGGPGGPPPGGGGB#####&&&&&&&&######&@@@@@@@@@&&&&#################B#B####################&&&#########BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGPGGGGGGPGGGGGGPGPPPPPPPPPPGB#&&&&&&@&@@@@@@@@@@@
&&&#####BBBGGGGPPPPPGGGGPPPPP5PPPPGGBBB##B#BBBB#&&&&&&&&&&&&&&&##################BBBBB#######################BBBBBBBBBBBBBBBBBBBBBBBBBGBBBBBBBBBBBBBBGGBBBGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPGPPPPPPGPGPPPPPPPPPPPPPPPPGGPPPPPPPPPPPPPPPB&&&&&&&&&&@@@@@@@@@@@
&&&#&###BBBBBGGPPP5P555PPPPPP555555555PPPGGGGPB&&&######BB#BB####&#########B####BBBBBBBBB#################BBBBBBBBBBBBBBBBBBBBBBBBBBBGGBBBBBBBBGGGGGGGGGGGGGPPGGGGPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPP555555P5PPPPPPPP5PPPPPPG#&&&&&&&&&&&&&&&@@@@@@
@&&&&&&&&##BBGGPPPPP555555Y55555PPPPPP55555555PB###BBBBBBGBGGPG#&&&&&######BB###B#########B###########BBBBBBBBBBBBBBBBGBBBBBBBBBBGGBBBBBBBBBBGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGPGGBBGGGPP5PPPPPPG#&&&&&&&&&&&&&&&&&@@@@
&&&&&&&&&&&&&###BGGPP55PPPP5555555555555P5555PPGBBBBBBGGGGGGGGGGGGB#&&&#####B###B###BBB##BB#######BBBBBBBBBBBBBBBBBBBGBBBBBGGBGBBBBBBBBBBBGGGGGGGGGGGGPGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPP5PPPPPGGGBB###BBBBB#BBBBGPP5PPPGB#&&&&&&&&&&&&&&&@&@@@@
&&&&&#############B#GBGGGPP555555555YYYY5Y55PGGGGPPGGGBBBGGGGGGGGBGGB#&&&######BBBBB#####BBB##BBBBBBBBBBBBBBBBBBBBBGGBBGBBBBGBBBBBBBBGGBGGGGGGGGGGGGGGPGGGPPPPPPPPGPPPPPPPPPPPPPP5PPPPP5PPPPPP55555555PPGBB#############BBBBBGGPPB#&&&&&&&&&&&&&&&&&&@@@@@
&&&&&&&####&&&####&BGGGBBBGPPP5555555555555Y5PGBGGGGGGGBBGGBBGBGGBGBB##&&&&######B###B#B###BBBBBBB#BB#BBBBBBBBBBBBBBBBBBBBBBBBGGBBGBBGGGBBGGGGGGGGGGGGGGPPGPPPPGPGPPPPPPPPPPPPPPP55P5555P5PPPP5555P555PPG####BB#########BBBBBBBBB###&&&&&&&&&&&&&&&&&&@@@@
&&&&&&&&##&&&&&###&BPPP55GGGGGPPPPPP5P55P555PPPGGGGGGGGGGGGGGGGGGGGGGGG###&&&&###B#######BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBGGGBBGGGGGGGGGGGGGGPPGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555555PPPPPPGGB##############BBBB##B####&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&##&&&&&##5PPB##PJJ?JJJJ5BBGGPP55555PPPGGGGGGGGPPGGGGGGGPPGGGGGPPPGGB##&&&##B###BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGGGGGGGGGGGGGGGPPGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55PPPPPPGGGGBBBBB##############BB######&&#&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&#&###P5GBB#5JJJJJ???JPGPP5P5555PPPGPPPPPPPPPPPPPPPPGGPPPPPP55PGGBGGB&&&BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGBBBBBBBBBBGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPP55555PPPGGBBBBBBB#############B#############&&&&&##&&&&&&&&&&&&&&&&
&&&&&&&&#######B55B#&GJ????????YPPP55555555PPPPPPPPPPPP555PPPGGPPPPPP55PGGGGG##&&#BBBBBBBBBBBGBGBBBGBBBBBBGGGBGBBBBBBBBBBBBGGBGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPGGBBB#BBB############BB#############&&&######&&&&&&&&@&&&&&&
&&&&&&###########PYPB#B5???????JBGGGPPP555PPPPPPPPPPPP5555PPPPGPPPP55555PGGGB##&&&&#BBBBBBBBGGGGGGGGBBBBGGGBBBBBBBBGBBBBBBBBBGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPP55PPGBBBBBBBB#############B############&&&&&&######&&&&&&&&&&&&&&
&&&&&&&&###########BPPGGG5PPPY55GGPPPPPPPPPPPPPPPPPPPPPPP555PPPPPP55555P5PGGBBB#&&&#BBBGBBGGGBGBGBBBBBBGGGGBBGBBBBBGBBBBBBBGBGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGBBB##BBBB###BB#B#####BB#B#########&&&&&&&&&#&&#&&&&&&&&&&&&&&
&&&&&&&&&#######&###BG###Y555PJ7?5GGGPP55PPPPPPPPPPPPPPPP5555PPPPP5555PPPPGBBBB#&&@BBBBGGBGGBBBGGBBBGBBGGBGGGBGBBBBBBBBGGBGGBBGGGGGBGGGGBGGGGGGGGGGPGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGBBBBBBBB###B##B#B###B############&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&#######BGGG##&&G?JP55YJJYPGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPP555PGGGB#BBB#&&@#BBBBGGBGGBGGGBGGGGGGBBBBBBBBGBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGGGGGGPGPPPPPPPPPPPPGPPPPPPPPPPPPPPPPPPPPPPPPGBBBB#BBB#############B########&#######&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&#&####BGGGGGGGGGB&57?YY??JY5YJY5PGGGPPPPPPPPGPGGGPGPPPPPPPP55PPGGGBBBBB&&@&BBGGBGGGGGGGGBGGBBGGGGBGGGGGGBGGGGBBBBBBBBBGBBBBGGGGGGGGGGGGGGGGGGGPPPGPPPPPPPPPGPPPPPPPPPPPPPPPPPPPPPPPPGBBBBBBBB#######BB##################&##&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&#&&&###BBBB#&57?YY7!755Y77?JY5PGPPPPPGGPPPGGGGPPPPPPPPPPGGGGBBB#&&@&#GGGGGGGGBBGGGGGGGGBGGGGGGGGBBGBBGGBBBBBGBBBBGGGGGGGGGGGGGGGGGGGGGGGGPGGPPGPGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBBB#######BBB###############&####&&&&&&&&&&&&&&&&&&&&&&&&
@@&&&&&&&&&&&&&&&&&&&&&&####Y7?YY?????777777?JY55PGGGGGGPGPPPP5PPPPPPGBBBBBBBBB&#BBBGGGGGGGGGGGGGGGGGBGGGGGGGGBBBGGBGBBGBBBBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPGBBBBBBB##########BB#############&&&&#&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&##&###BBBGB#B?7?5YYJ?777777777777?JYPGGGPPGPP5PPPPGPPPGBBBBBBGB#BBBGGGGGGGGGGGGGGGGGGGGGBBGGGGBGGGGGGGGGGGBGGGGGGGBGGGGGGGGGGGGGGGGGGPPGGPPGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPGGBBBBBBB##########################&###&&#&&&&&&&&&&&&&&&&&&&&&&
BB####&&&&&&&&&&&######BBBB##B?7J555YJ??7777777777!77?YPPGGGGPPPPGGPPPGGBBBBGB#BBBBGGGGGBGGGGBGGGGGGGGBGGGGGGGGGGGGGP5PGGGPP55PPPGGGGPGGGGGBBGGGGGGGGPGGPPGPGPPPPGGPGPPPPPPPPPPPPPPPPPPPGGBBBBBBB###BB#####################&########&&&&&&&&&&&&&&&&&&&&&&
GGGGB&&&&&######&###BBBBBBBBB#G?7J5P5YJ??77777777777777??Y5GBGPPPPPP5PPGBGBBB##BBBGGGGGGGGGBGGBBGGGBGBBBBGGGGGGGGGGPP55PGG555555Y55PPPP55PGBBGGGGGGPPPPPPPGGPGGGGGPPPPPPPPPGPPPPPPPPPPGGBBBBBBBBBB####B###################&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@@
GGGGGB##&&&&&#######BBBBBBBB##&P77Y5P5YJ???7?77777777777!!7?5GP5PPPP55PPGGGBBB#BBBGGGGGGGGGGGGGGGGGGGGGGGGGGGBBGGPP55PPPPP5YYYYY5555YY555P5PPGGGGGGGGGPGGGGGGGGGGGGPPPPPPPPPPPPPPPPPGGBBBBBBBBBBBBBBB#BB#########&&&&&&#&&&&&&&&@@@@@@@@@@&&&&&&&@@@@@@@@@
GGGGBGGB#&&&&&&#&&&&&&&&########57?YPGP55YJ??77?777777777!!!!?5PPPPP555PPPGBGPG##BGGGGGGGGGGGGGGGGGGGGGGGPGGBBPPGGGPPP5YJY55JJYYYJYYYJJJJYYYY5PGGGGGPGGGGGGGGGGGGGPPPPPPPPGPPPPPPPGGGGBBBBBBBBBBBBBBB######&&&@@@@@@@@@&&@&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
GGGGBGBGGB&&&&&&&##&&&##B#B#BBB##Y7?YGGGGP5YJJ????7????777777!7J5PPPP555P5PGGPPGPGGBGGGGGGGGGGGGGGGGGGGGGGGGBGGGGGBGGGGPYJJYY5YYYJJJJYJYJJJJJJYPPGGGGGPGGGGGGGGGGGGPPPPPPPPPPPPPGGGGBBBBBBBBBBB#########&&@@@@@&@@&@&&&&&&&&&&&########&&&&&@@@@@@@@@@@@@@
GGGBBBBBGBB###&&&&#########BBBB##&Y7J5BBGPPGP55YJJ?????J?????7777JY555555Y5PGPPY7?J5PPYY5P5PP5555PPPGGGPPGBBGBBBBBBPP5PGP5YYYYYYYYJJJYYJJJJJJJJYPPGGGGGGGGGPGPGPPGGPPPPPPPPPPPGPGGGGBGBBBBBB###BBB####&&&&@&#&#&&&&&&#&&&#BBBB##&&&&&&&&&&&@@@@@@@@@@@@@@@
GGGBBBBBGGGGGBBBBBBBBB#####&&&&&&&&J7Y5#&BGPPPPP5YJ?777?????????77777?J5P55PPPPJ7???Y5?7?JY555YYY555555PPGGGBBBBBB##G55PGGP5JJJJYYYJJJJJJJJJJJJJY5PGGGGGGGGGGGPPPPPPPGGPPPPPPGGGGGGGGGBBBBB##BB#####&&&&&&&&&#GPGBBB#######&&#&&&&##&&&&&###&&&&&&&&&&@&@@
GGBBBBBBGGGGGGGGGGGGGGGB###&&&###&&#??J5#&&#BGGPPP5YJJJJ?????J????77??Y5PPYY55P5777?YY?777J5P5555PPP555Y55GBBBBGGB##GPPGGGGP5YYYJJJJYJ???JJ??JJJYY5PPPPPGGGGPPPPPPPPPGGGPPGGPGGPPGGGGGGBBBBBBB##&&&&&##&##BBBBGPPPPPGGBBGGBBB#####BBGGGGGGGPPPGGBBGGBB#&&&
GGGBGBBGGGGGGGGGGGGGGGGB##########&&B??YP####&##BBGPPPP55555YYJJ??JJY5PP55JJJY5GP777J5?777J?J5555YYYYYYYYY55PG#####BGGGGPPPPP5YYYJ????????????JJYJJ5PPPPGGGGGPPPPPPGGGGGPPGPPGPGGGGGGGGBGBBB#&&&&##BBGGGPPPPGGGP5PPPGGGBB#BPPGGGP55Y55555555555PPBBBBB#&&&
GGGGGGBGGGGGGGGGGGGGGGGGB#&&&#&&#&&#&B??JP#####&&&&#GGPPPPGGGPP55555PPP5YYJJ5PBGG57?J5J7!!?J77JPGPP5555YYYYY5PB#&&&&#BBGPPP55PP5YYYJ??77?????JJJJJJJYPPPPPPPGGPPPPGPPPPPPPPPPPGGGGGGGGBBBBB&&&&&#&BP55P5555PPPP5PPPGGBGGBBGPP5555PPP555PPPPGGGPGGGGB#&&&&&
GGGGGGGGGGGGGGGGGGGGGPPG#&&&&&&&&&&##&G7?YG&###B###&&&#BBGPPPGGGPPPPPPYYJJYY55JGGGJJY557777J777JJYPPP5555Y5PB###&&&&&&##BGPP55PPPPPP55YJ?????JJJ??JJYYPPPPPPPGGGGPPPPPPPPPGGGGGGGGGGGBBBB#&&&###BBP5555555555555PPPGGGGGGPP555555PPGPGGGGGGBBBB####&&&&&&&
GGGGGGGGGGGGGGGGGGPPPPPPGB#&&&&&&&&&&&&P7?YG#BBB#####&&&&&&#GPPGGGPPGYJJYYYY5YY5YG5?Y55?7??7???777YPPP5555GB#GB###&&&#GGBBBGGPP5Y5YYJJ??7!!!!!7JJ?JJJY5PPGPPPPPPPPPPPGPPGGGGPGGGGGGBGB#&&&##BGGGP55YYY5555555555PPPPGGGGPP5555555PPP5PPPPPPPPPGGBB###&&&&&
GPGGGGGGGGGGGGGGPPPPPPPPPPG#&&&&&&&&&&&&57JYG###&#####&&&&&&&&BGGGGB5JY55YYJP5YY555YJY55?YY????????YPP555555GPB&&&&&&&P55PP55YJ?JYJ?777777!!!!!7JJJYJY5GGPPPPPPPPPPPPPGGGGGGGGGGGGGB#&&&###BP5555YYYYY555555555PPPGGGGPPPP5P555PPP5PPPGPPPPPGGGGGGBBB#&&&&
PGGGGGGGGGGGGGGPPPPPPPPPPB#&&&&&&&&&&&#&&Y7JYB&############&&&&&#BGPY55P555YBPP5YYYYYYY5P5PP555PP555PP555555PPB##&&&&#GP55YYYJ?775PJ??J?7!!!!777Y5JYY5PGGPPPPPPPPPPPPGGGGGGGGGGGGGG#&&&BBGGP5YYYYY555555555PPGGGGPGPPP5555555555PPPPPPGGGPGGGBBBB##&&&&@@@
GPGPPGGGGPGGPPPPPPPPPPPPPB#&&&&&&&#&&&&&&#J?JY##B#&&#BB#BB#&&&&&&&&555PP555PBGP555GGPPPPPPPGGPPGGGGGGBBGP555555PPB##BGPP5555YJ?7!7YPP5P5J?????7JGYJ55PPPGPPPPPPPPPPPGGGGGGGGGGGGGG#&&#BGGP5YJYYY5555555555PPPPPPPPPPPPPPPP555555555PPPPPGGBGGGGGGB##&&&&&@
GPGPPGPGGGPPPPPPPPPPPPPPPPPBB#&&&&&&&&&&#&BJ?J5###############&&&#G5Y5GPPPGGPPYPGBBBBBGGGGPGGGGGBGB###&&&BGP555PGBGGGPP55555YJ?77777?JJ?7Y5YY55PPYYY5PPPPPPPPPPPPPPGPPPPGGGGGGGBB#&&BBPPP5YYYYY555555555PPPPPPPPPPPPPPPPPPPPPPPPPPPGBBBGGB##BBGGGB##&&&&&&
PPPPGPPPPPPPPPPPPPPPPPPPPPPB&&&&&&&&&&####&BJ?J5&&#######B####&&&PPPGBBGBB#B55GGGGGGBBBBBGGBGBGGBBB#&&&&&&##BBBBGGGPPPP55P5YJJ??777!777!75PPPGP555Y55PPPPPPPPPPPPPPPPPPGGGGGGGGB#&##BG5YYYY5555555555555PPPPPPPPPPPPPPPPPPPPPPGGGGGBBB#########&##&&&&&&&&
GGGPPPPGPPPPPPPPGPPPPPPPGGGB&&&&&&&&&&&&&&&&B??JP&&&&&###BBBBB###BBBBBBB##BBGGB##BBBBBGBBBBBGB###BB#&&&#BGGGGGGGPPPPPPP5555YJJJ??77J?7!7??JPGGGY?Y55PPPPPPGPPPPPPPPPPGPGGGGGGB##&#BP55YYYY555555555555PPPPPPPPGPGGGGGPPPPPGGGGGGGGGGBBBBB######&&&&&&&@&&&
PGPPPPGGPPPPPPPPPPPPPPPPPGGGB##&&&&&&&&&&&&##G??JG&&####BBBBB###BBB######BGB#########BBBBBB##&&BBGG&@#BGGGGGGGPPPPPPPPPP5555YYYY5YJ5PJ?7?YPPGPG5J5PPPPPPPPPPPGPPPPGGGGGGGGG#&&&#GP5JYYYY555555555555PPPPPPPGPPGGGGGGGGGGGGGGGBBBBBBBBBBB##########&&&&&&&&
PPPPPPGPPPPPPPPGGGPPPPPPPPPGGGGG#&&&&&&&#####&P7?YB&########&#&BGB###&&&#B##&&###&&&&######&&&#G#GG&#GGGGGPPPP5PPPPPPPPPPP55YJJY5GG5JJJYY5PPPP55PPPPPPPPPPPPPPPPPGGGGGGGG#&&##G55JJJYYY5555YY55555PPPPPPGPGGPPGGGGGGGGGGGGBGBBBBBB#BB#######&#&&&&&&&&&&&&
GPPPGPPPPGPGPPPPPPPPPPPGPPPGGGGB#&&&&&&###&&&&&P7?5B#&&&#####&&&##&&&&&&&&&&&&&&&&&######&&&&&BGBGPBGGGGGPPPP5PPPPP555PPPGGP55YY5YYY555YYYYY5PPPPPPPPPPPPPPPPPPGGGGGGGBB##BBB5YJJJJYY5555Y5555PPPPPPPPPGGGGGGGGGGGGGGGGGGGGBBBBBB###########&&&&&&&&&&&&&&
PPPPGGGPGGGGGGPPPPPPPPPPPPPGGGGGBB######&&&&&&&&5?J5#&####&&&&&#B#####&&&&&&&&@@@&#######&#&&#BGGGPGPPGGGPPPP5PPP55PPPPPGGGBBGPY7!!?55P55YYYY555PPPPPPPPPPPPPPGGGGGGB###BGP5Y?JJJYY5555555555PPPPPPPPGGGGGGGGGGGGGGGGGGGBGBBBB#############&&&&&&&&&&&&&&&
GGPPGGPPGGGGGGGPPPPPPPPPPPPPGPGPPGGGGGG#&&&&#&&&&Y?JP#&&&&&&&&&#B####&&&&&&&@&&@&############BGPGPPGPPPPPPGP5PGP55PPPPPGPGGGPPY77J5PPPP5Y55YY55YYY5PPPPPPPGGGBBBB#BBBBP55YJJJJJJYY5555555PPPPPPPPGPGGGGGBBGGBBBBBGGGGGGGBGBBBB###&&#####&#&&&&&&&&&&&&&&@@
GGGGGGGPGGGPPPGGPPPPPPPPPPPPGGPPPGPPGG#&&&&&&&&&&#Y?YP&&&&&&&&&&&&&#BB#&&&&&&&&@&#&#####&&&#&#GGPPGGPP5PPPPPPGGPPPPPPPPPPGGP5YJYPPP55?????????JJ5YJJY55PPGBBBBBGGP55JJ????JJJYYY555555PPPPPPPPPPPGGGBGGGBBGGGBBBBBBB#B##BBBGBBBB#&&&@@&&&&&&&&&&&&&&&&&@&@
GGBGGGGGGGGGPPPGPPPPPPPPPPPPPPPPPPPPPPGB#&&&&&&&&&#Y?YG&&&#&&&&&######&&&&&&&@&&&&&#####&&&#&#GPGPG#BGPPPPPPPPPPPPPPPPPPP5P55PGBBPY?77?77!!!!!!!7?J?JJJY5GGPPYY????777???JJJYY555Y555PPPPPPPPPGGGGBBBGGGGBGBBBBBBBBB########BBBBBB&&&&&&@@@@@&&&&&&&&&&@@@
GGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB#&&&##B#&&#Y?YB&&&&&&&&&&##&&##&&&&&&&#&&&######&#&###PPP5B&&BGPPPPPPPPPP55555P5Y5GBBBG5?7!?7777!77!7!!!~!!!?JJJJJJ?7777777???JJYYYY55Y55PPPPPPGPPPPGGGGGGGGGGGBBBBBBBGBB##BBB##&&&&&&&###&&&&&@@@&&@@@@@@@@&&@@@
GGBBBGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGPPGGGPG#&&&&#YJ5B&&##&&##&&#########&&&##&&##BB########BY55P#####BBBGPPP555555555GB##BGY777J77?7!7?7777777!!77??????7?????????7?YY5555555PPPPPPPPPGGPGGGGGGGGGGGBBBBBBBBBB#######BB#&&&&&&&&&#&&&@@&@@&&@@@@@&&&&&
BBBBBGGGBGGGPPPPPPPPPPPPPPPPPPPPPPPPPGGGPPPPGB&&&&&&&BJJ5B##&&####&&#&&###&&&&&#################PY55B####B###BBBBBGGGPPGB#BBB5?!77J?7J?7????77777!!!!!!!777???77!!7?77?7J5555555PPPPPPPPPPGGGGGGGGGGBBBBBBBBBBBB###&&&&&&&##&&&&&&&@@&##&&&&&&&@@@@@@@@&##
BBBBBBGGBGGGGPPPPPPPPPPPPPPPPPPPPPPPGGGGGPGGB&&&&&&&&&BJJ5B&####&&&&&&&&&&&@@&##&###############GPYY5##BGGBBBBBBBBB###GGPBG5J!!77?Y??Y??J???7777!!!!!!!!!!777!!777!777?JJYPP55PPPPGPGGPPPPGBGBGGGBBBBBB##BBBB#######&&&&&@@&&&&&&&&&&&BB######&&&&&&&&&&#&
#BBBBBGGGGGGGPGPPPPPPPPPPPPPPPPPPPPPPGGPPPGG#&&&&&&&&&&BJY5###&&&&&##&@@@@&&&&##&###############BY5YJYPBGGBBB#######BBGPYJ7!777??J5?Y5JJY??JJ?7!7???777???????JYJ???JJYYJ?YPPPPPPPPPPGPPPGBBGGBBBBBBBBBB####B###&&&&###&&&&&@&&&&&&#BBBBBBB#BB###########&
#BBBBBGBGGGGGGGGGGPPPPPPPPPPPPPPPPPGPPPPPPPPG&&&&&&&&&&&GJYP#&&&####&&&&&@&&##&&&############BBBBPYY?!?GBGGGGGGGP5YYJ?77!!!777??JJPJP5JYJYJ???????7????JJJYYJJJ?77YYYYJ?775GGGPPPPPPPPPPGBBBGGBBBBBB##BBB##&&#&&&&&&&&&&&&&&&&@@@&#BBBBBBBBBBB#BB########&
#BBBBBBBBGGGGGGGGGPPPPPPPPPPPPP5PPPGGPPP5PGP#&&&&&&&&&&&&GJYP&&&&&&&&&&&&&@&#####&&#####BBB###BB#G5?J?~7PP5YYYJ??777777!7777777??JP5PPY5YYYY??JJ?????JJJYJJJ???7?JYYJ?77J5BBGGGGPPPPPGGGBBBGBBBBBBBB#######&&&&&&&&&&&@&###&&@@@@&#BBBBBBB##############&&
#BBBBBBBBGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPGBBB#&&&&&&&##PJYP#&&&&&&&&&&@&######&######B#####BBBBPJ777~75J?JJ???777777777?777??JJ5BGGGPG5YY?7Y55555YYYYYJJ?????JJYY???YYYPBBGGGPPPPPGBBBBB#BB###BBBB###&&##&&&&&&&&&#BBGBBBB#####BBBBBBBBBBBBBB#########&
BBBBBBBBBBGGGGGGGGGGGGGPPPPPPPPGP5PPP5555PPPPPPB&&&&&&&#&&&PJYP#&&&&&&&@&&&&&&########B####B#BBBB##Y777!~7YJJJ???77777777??J?JYY5PG#BBBGGGP5?J???Y5PP5PPPP5555J?7J5Y?JPJJ??5BGGGGPPGGB#B#BBB#BB######BB##&&&&&##&&&&&@&BBBBBBBBBBBBBBBBBGGGGGGGBBBB#######
#BBBBBBBBBBBGGGGGGGGGGGGGPGPGGGPPPPPP5555PPPPPB&&&&&&#B#&&&&5JYP&&&&&&&&&&############BBBBBB##BB####J!77!~?YJJJJ???J??77??J5PGBB####B##BBGPG5YJJ???YYY555JJJYJ77?J55J5PY?JJ?PBBGGPGGGBBB##BBB#######&##B##&&&&&&&&&&&&&BGGGGBBBBBBBBBBBGGGGGGBBBBBBB#B###&
#BBBBBBBBBBBGGGGGGBGGGGGGPPPGGPPGGPP555555PPPPB###BBBG#&&&&&#YJYP&&&#####&&##############B#B#####B##BY7??!!JYYYYYJYPYJ7?JJ5GBB#######BB##BPYGGPYJYYJ5YP5?5YYJ777?Y5555G5J?JJYB#BBBBBB##BB###B########&&&&###&&&&&&#BBBBGGBBBBBBBBBBBBBBBBBBBBBBBBBBB######
BBBBBBBBBBBBBBBGGGGGGGGGGPPPGGPGGPPP5YY555PPPPPGPPPPPGBB###B#BYJYP#BBBB#####B#BB################BBBBBBP?7?7!J5PPP555YYJYYJJJYG######BB###BG5GPGBPP5PGGPJ55YJ??JJYYYYYY55YJJYYYP############&#####&#####&&&&###&&&&#GGGGGGGGGGGBBBBBBBBBBBBBBBBBB##########
BBBBBBBBBBBBBBBGGGGGGGGGPGPGGGGPGGPPPP5555PPPPPPPPPPPPPPGGGGGBGYYYPBBBB###############B#########BBBB###PJ7777Y5PPPP5YYJJ?77??YPBBB####&&#BBGBGPPPPPGGG5PG5JJYYYJJJ?JJJY5YY55J?JYPB#########&&&####&&####&&&&&&&BBBGGGGGGGGGBGGGGGBBBBBBBBB##B##B##B#######
BBBBBBBBBBBBBBBGGGBBGGGGGGGPGGGGPGGPPP5555PPPPPP5PPPPPPPPPPPPPGG5YYGBBBB############BBGBB#B#####BGGGGGBBPJ7!!7JJJYYJ??7777?JJYPGBBB##&&##BB##GGGPGGBBGGP5YJJJ??JJ?JYY5P5YYJ???????Y5GB#&#####&&#####&#####&&&&&#GGGGGGGGGGGGGGGGGGBBBBBBBBB##&&###&#######
BBBBBBBBBBBBBBBBBBBBGGGGGGGPGGGGGPGGGPPPPPPPPPPP555PPPPPPPPPPPPPGG5PGGPB#######BBBBBBGGGGBBBBBBBBBP5YY5GBPJ7!!!?JJJJ??????JY55PGB##############BBBGG5YYJJ??JJJJYYYJY555YJJ??????77??JY5PGBB###&&#B####&&&&&#&&#GPGPGGGPGGGGGGGGGBBBBB######&&&&&&&&&&&####
BBBBBBBBBBB#BBBBBBBBBGGGGGGGGGGGP5PPPPPPP5555P555PPPPPPPPPPPPPPPPGP55YYP##BBBB#BBBBBBBBBBBBGGGGGGGG5YYJYPBPJ?7!!7?J??77??JY555GB##########BBGGPPP5YY5PPP555YYYJYYYY5PP555YYYJJ?JYJ??JJYYYY5G#&&&&&####&&&&&#GGPGGGGGGGGGGGGGGBGGBBB##&&&&&&&&&&&&##&#&&##&
############B#BBBBBBBBBBGGGGGGGGP55PPPGP555P55555PPPPPGPPPPPPPP55YYJYYY5####BB##BBBB###BBBBBBBGGGGGGYYJ?YGBPJ77!!!!?JJJJYYYYYPB######BBBBGPP555555PGGGP5YYYYYJYYY5555555555555YYY??JJJY55555P&&&&&#GB##&&&&&BGGGGGGGGGGGGGGBBBBBB###&&&&&&&&&&&&&&###&&&&&
&#&&&&&&&&####BBB#BBBBBBGGGGGGGGPPP55PGPP55P5555PPPPPP55PPPP5YYYYYYYYYY5######BBBBB#B###BBBBBBBBGGGBGP5YY5GGGY77?7!!7JJJYY5PPB#####BBBBGPPPPPPPGGGPP5YYYJJJYJYY5555555YY55YJJJYYJJYYYJY5555PPB&&&&&GGGGGBBBGGGGGGGGGGGGGGBBBBBB###&&&&&&&&&&&&&&&&&####&&&
&&&&&&&&&&&&&&#####BBBBGGGGBBGPGPPP555PGGPPPP5PPPP555PPGGPPP55YYY5YYYY55B####BBBBBBBBB##BBBBBBBBBBGGBGPP5555PGPJ7777!!7YPPGGB##BBBBGGGGPPPPPGGGGP55YYYYYJJJY5PP55YY55YYYYJYYYYYJJYYYYYY5555PPG#&&&#GGGGGGGGGGGGGGGGGGGGGBBBBBBBB###&&&&&&&&&&&&&&#&##&&&&&
#&&&&&&&&&&&&&&&&&##BBBGGGGGGGGGPPPP555GGGPPPPP555PPGGPPPPPP5555YYYYYYY5GBB##BBBBBBBB#B#######BBGGGGPPP5YYYY5PGBPJ?777!!?5B##GPBGGGPPPPGGBBGGPPPP55YYYYYYY5PGP55YYYYYYYYYYYYJJJYYYYYYYYP555PPGGBBGGGGGGGGGGGGGGGGGGGGGGGBBBBBBBB#B##&&&&&&&&&&&&&#&##&&&&&
&&&&&&&&&&&&&&&&&&###BBBGGGGGGGGGGPPP55PGGPPPPPPGGGPP55555PPPPPPP555YYYYPBBBBBGBBBBBBBBBB###BBBBBGBBBGGGG555Y5PGBB5????77?P#GBYPGGGGGGBBBGPPP5P555YYYYYY5PGP55Y5YYYYYYYJJJJJJYYYYYYYY55555PPPGGGGGGGGGGGGGGGGGGGGGGGGGGGBBBBBBBB####&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&###BBBGGGGGGGGGGPPP5PPGGGGPPGBGPPP5555555555555PPPPPP55BGGGGGGGGGGBBBBBBBBGBBGGGGGGGGPP55YYJJYYPGPYJ???JYPGBP5BBBBBBGGGPPP5P555YJYY5PPGP55YYYYYYYJJJJJJJJYYYYY555555555PPGGGGBGGGGGGGGGBGGGGGGGGGGGGGGGBBBBGGGBB#####&&#&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&#####BBBBBGGGGGGGBGGPP5PPPGGGPGBGGPPPP5P555555555PGGGGGGBGBGGGGGGGGGPGGBBB#BBBGGGGPP5555YYYJY??7???JYPPY??JJYPGG5B#BBBP555555PP55555PPGGPP55YYYJJJ????JJYY5YY5555555YYY5PPGBBGGGGGGGGGGGGGGGGGGGGBB#BBBBGGBBGGGBBBBBB########&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&#####BBBBBGGGGPGGBGPPP55PPGGGPGGGPPPPP555555555PGGGGGGBBB###BBBBBBBBBBBB#BBBBBGGGGPYYYYYJ????777777!!!7?YYJY5??YP###G5J??JJYJYPGGGBGGPP55YYJJJJ?JJJYYYY5555Y5555YYY55PGBBGGGBBGGGGGGGGBGGGGGGGB##########BBBBB#####BB#######&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&#####B#BBBBBGGGGGGBGPPPPPPPGGPGGPPPP55555555PPGGGPPGBBBB####B##BBBB##B##BBBBBBPP55YJJJJJJ????77!!!!!!!!!!?YY55YJYB#G5YPP5Y?JJ??YP55YJJJJJJYYYYY5555555555YYY55555PGBBGGGGGGGGGGBGGGBBBGGGGGGBB###&###############&#########&#&&&&&&&&&&&&&&
&&&&&&&&&&&&&&########BBBBGGGGGGGBBP5PPPPPPGGGGPPP5555Y555PGGPPPGGGGBB##BBBBBBBGGGBBGBBBBBBBGP55J??????JJJJ?77!!!!!!!!!!77?Y5PPY5PBPGP5Y???7!!7JP5555555555555555555555PP55PPGGGGGGGPPPPPPGGPPGBBGGGBGGGGGGB#######################B###&#&&#&&&&&&&&&&&&&&
&&&&&&&&&&&####&&&#&###BBBGGGGPPGGGGPPPPPPPGGGGP5P5555555GGGPPPGGBBBBB#BBBBBBBBGGGGGGGGPGGB#P5YJJ??77777?7777!!!!!!!!!!!777?J5GG5Y5G55YYJJJJ??Y5PP55555555555555PPPGGGGPPPPGGGGGGPPPPPPPPPPPP5Y5GGGGBGBGBBB#######################BB########&&&&&&&&&&&&&&
&&&&&&&&&&##&&&&&&##&#BBBBGGGGGP55PPPGPPPP5PGGGP55555555PBPPPPPGGGGB###BBB#BBBBBGBBGPP5J5GB#GPYJ??7!!!!!7!!777!!~~!~~~!!!7777?P5YPGBBBPP555PPGGGGGGGGGGGGGGGGGGGGGPPPPPGB#BGGGGGPPPPPP55P5555Y?7JGGBBBBBB#################################&&&&&&&&&&&&&&&&
&&&&&#&&#&#&&&&&&&#&###BBBGGGPGP555555555PPPGGGGPPPP555GBGGPPPPGGGB##B#BBBBBBBBGGGBGP5YJJ5B#GPYJJ?7!!!!!!!!77!!~~~~~!!77!!!!!?57~??5BG5J??7?YPBBBBBBBGGGGPPPP55555PGBB#&&&#BGGGGGPPP55555555J?777JPGBBBB###########################B#####&&&&&&&&&&&&&&&&&
##&&&&&&#&&#&&##&#######BBGGGPPPPP55555555555PPGGGPPPPGBGPPPPGGGB##BBGGGGGGGGGGGGGGGP5Y?7YPGP5YJJ?7!!!7!!!7777!~!!777!!~~!~~7??!!?J7JYPPP5Y?!?BBGGGGPPPP55555PPGBB##&&##&&&###BGGPPPPP55YYYJJ?7777?PBBBB###########&###############B########&&&&&&&&&&&&&&
##&##&&&&&################BGPPPPPPP555555555YYY555PPBBBGGGPPGBBBB#BBBBGPGGGGGGPGBBBGGPPYJJYP5P55JJ?7777777!!777777!!!~!~~!!!7?!??!!!7YYJ?JY?!5BGPPPP55555PGGB##&&&&&&&###&&#&&#BGGGPPPP5YYYYJ??77!!7YGBBB##################################&&&&&&&&&&&&&&&
&#&&&&&&&&&&&&&###&#&#####BGPPPPPPPP55555555555555YJY5GBBGGGBBBBBBBGGPPP5PPPGGPGBBBBGGGP555GPGGPYYJ????7777777?7!!!!!!!!!~~!?7!!~~!!55??77J7YBGGGGGGGGB##&&&&&&&&&&&&&&###&&&&&#BBGGGGPP55Y5YJ?777!!!?5GBBBBB#############################&#&&&&&&&&&&&&&&
############&&&&&&&&#######GPPP5PPPPP5555555555PPPP5Y??YPPGBBBBBBBBG555P5555PPPGGBGGGGGGPPGBGGGP555YJJJ?7!77??7!!!!!!!~~!77??~~~!!~JGP5J?JYPBGGGGGB####&&&&&&&&&&&&&&&&&&&&#&&###BGGGGGGGGPP5YJ?77!!!!!7YPGGPPPPPPPPG###################&###&###&&&&&#####
#&&&#######BBB###&&&##&&&&#GPPPP555555PP55555555PPPPPY?7?JJYY5GBB#GGPP555P555PPGGGGPGGGGGGBBPGPP5555YYJ?7??J?!~!77!~~~!~!!7!~!!~~!JYY5555PPGGGGGGGBBBBBBB#####BBBBBBBBBB#&&#####BB###BBGGGGGGP5YJ?7!!!77!7777!7777777P##########################&&&#######
&&&&&&&&&&#####BGB#&&&&&&&#GPPPPPPP55PPPP5P5P55555555P5J777?JJJJ5GGGPPPPY5555Y5GPPPPPPGGGGGGGGGPPGPPP55YYJJ?!!777!7!777~!!~!~~~~7JJ?77?JJYYYYYYY5555PPPP55555555555YYY555PB&&#########BBBGGGGGGP5Y?7!!!7!!!!!!777!7!!!Y###################################
&&&&&&&&&&&&&########&&&#&BGPPPPPPPP5555P5555555Y55YY55P5J7!7?77!75GGPP55YY5555PGPPPPPP5PPGGPPGPPPPPGPP5Y?7!7??7!!??7!!~!~~~~~~7?7!~~~^!????????JJJJYJJJJJJJJJJYJJJJJYY555PG#&######B###BBBBBGGBGG5YJ77777!!!!7!!7!7?7!?G#################################
&##&##&&&&&#&&&&#######&&#BPPPPPPP555555555YYYYY5YYJJY55PP5J!!777!!5GPG55PYYY5555PPPPPPPPPPPGGGGGGGGGP5J?77JJ??!!?7!~~7!~~~~~~77!7!~~~~^~7????77???JJJJJJYYYYYYYYJJJYYYY55PGGB&&##########BBBBGGGGBBGP5YJ?77!!7777JGPPY?Y#################################
&&&#&##&#&&&&&&&&#########GPPPPPPP555555YY5555PP5J?77JY5555Y77???7!!YGPPPYJ55YY55555PGPGPPGGGGGGBGGP5YJJYJJY?77?Y7~~~!!!~~~~~!77!!!!~~~~^~!????????7?JYYYYYYYJJJJJJY5YJJ555PG#&&&&&########BBBBBBBGGGGGGP5YJJ???7!?BJYJYG#################################
&&&&&&&&&#&######&&#######GPPPP555P5555555PPPPPY?7!!!7J55YYY???J??7!!5GPPP5PYYYYYY5YYPPPPPPP5PPPP55YYYYYYYJYJY5YJ7~~!!!~~~~^!77777!!!!~^^^~~7????????77???JJJJJJJJJ?7JYYJJYY5B&&&&&##########BBBBBBBBGGGGGGBBGPP55PBY55GB#################################
&&&&&&#####BBBBGG#&###B#&#P5PPPPPPPP55555555P5Y??7!!!7?JJ?YJ????J??7!75G555PYJ?5YYY?555555555P5Y55Y5P55YYYJJ??YJ7?!77!~~~~~~JJ?!!!!!~!!~~~~~~~~!?J?????77777????77!!!!?JJ?????G&&#&##########[email protected]&BBBGG#GGBB###################################
&&#####&&#######B#&#####BBP5PPPP5P555P5555555Y?JJYYYJ?777?YJ???JJ???77?PPYJ55YY5YYJ5PY555555Y5Y55YY55555YJJJJYJ?!J??7!!~~~^7J???!!!!!!!!!77~~~^^~?????7?7???777777777!777777?J#&&&&###BBBBBBBB#BBBBBBBBBBB#&BBBBB##B#B#########################B##########
####&&&#########B#####B###BPPPPPP5555P55555P5?!???J555YJJYY??777!!!!777JG5YJ?JYPPY?PYY55P5YYJ5Y5YYYYYYPYYYPPYJJJ!YY77!!!~^!?!~!!77!!!!!!!!7!~~~~~!!!!!77???JJJJY5YYJ77777777?B&&&&&&GYJYYYY555P####BBBBBBB#&BPG###B#B#########################B###########
##&&&&&###############B##&&B55PPP55555PPPPPP5?77777777????77!!~~!!!!!!77YGPYJ?5PP?7?YYYJGYY55G5555P5YY55YPB5JJJJ7P5!!!~!^^?!!!~~!!~~!!!!!!7!~~~^^~!!!!!!!!!7?77!!?J777777??JP&&&&&#P5Y555555P5YP55PBBBBBBBB&GP&&#BB##########################B############
##&&&&&##&&&&&###&###BB#&###B55PPPPP5P5PPPPPPPYYYYYJJJJJJJYJJJ?777!!77!~!?5P5JBBBJ77?Y5PPPGGGGGGGG5YYYYYPGG5JJYY?GY!!!~^^!J~!!!!!~~~~~!!!!7!^^^^^~!!!!7777777!!~!??777??JY5PG&&&#&BY555PPPPPPJJJJJJYB#BB###BP##&##B###########################BB##########
##&&&&&&&###&&#&&###BBB######B5555P5555PPPPPPGP5YYYYYYYYYYYYYYJ?7777!7!!!~!7JYGGBP777?JY5PPPPPPBP?JJJJ?PBGGPY555YPJ7?!^^~Y?!!!!~~~~~~~~~~~~!~~^~~~~~~!7!7777!7?77???JJJJJY5B&&&&&&&BGPPPPGGGP5YY5P5YP###B#&B5GP#B##########################BB####B########
###&#&&&&#&&&&#####BBBB######&B55555555PPPPPPPGP5YYYYYYYYYYYYYJJ??77!!!!!!~~~!YGBG5????JJYY55P5P?JJ???PGGPGG555PP5!?J~^^?P7?77!~~~~~~~~~~~~~~!!~~~~~~~~!!!!!!77???????JJ5B&&&#&&&&&&&##BBBGGPPPP5555YB####&BG&PB###########################B####BB#B#B#B##
###&&&&##&&&&&####BBB#########&B5PP5PPPPPPPPPPPPGPYYYYYYYYYYJJYYJ?777!!!!!~~~!!JPGP5YYJJYJJ5P5PJ????JPGGG5GGP5PPPJ~!J~~^YP7????7^~~~~!!~~~~~~!!!~~~~~~~~~~~~~~!!!77?J5PB&&&&&&&&&&#GGPP55YYYYYYJJJJJG##GG#BB##BG&#########################BB###BB###BB####
######&&#######BBBBB#&&&&&#####&BP55PPPPPPPPPPPPGGG5YJJYYYYYYJYYYJ?77!!!~~~~!77!?PPPP5JYY5YY5P5J???JPGGPP5PPPPPPG7^!7~^~?5?J5???~~~!!!!~~~~~~~~~~~~~~~!!?7!!!!!7?Y5PGG#######&&#BPPPP555YYYJJJJJY5GB##G5GB####&BBB##########BB############BB##BB#BB#B#####
#BB##B#######BBBBB#&&&&#&&&&&&&&&#PP5PPPPPPPPPPGGGP555YYYJJJYJJYYYJ?7!!~~~~~!77!!JPPPP5YJY55Y5P5?JY5GGGPYY5PPPPPPY^!7!^!?7JYPJJJ~~!!!!!~~~~^^~~~~~~~~~~!JPPPPPPPPPPPPGB#&##&###PPPP555YYJJJY5PGG####&BP#&#####&&#############B#B#########B####BBBB##B#####
&BBBBBBBGBBGBBBB##&&&&&&####&&&&&&##GPPPPPPPGGGP5YYY5555P55YYJJJJJJJ?7!!~~~~!!!!!!?PPPPPYJYJYYY5JYPGGPG5?JYPPGPPPG7~?!~77~JY5YYJ!~!!!!!!~~~~~~~^^^^^^^^~~YGGGGPPPPPPPP5PGB#BB#P55YYYYYYYJJP&&&&######B#&&#####&#########################B###BBBBB#BBB#####
&&&###BBBBB###&&&&&&&&&&&####&&&&&&&&&#BGPGGP5YYYYYY55555555PP55YYYYYYJ??7!~!!!!!!!?P5PPYJJJJJJYYYGGGPYJ??Y5PGGPPPY7?!7~7~!P5Y55?!!!!!!!!~~!~~^^^^^^^^^~~!PGGPPPGBGP5555555PGG5YY55YYJJJJPBBBB#########&#######&B#####BB##############BB###BBBBBB#BBBBB###
&#&&&&&&&&&&&&&&&&&&&&&&&&&&##&&#&&&&&&&&#B5YJJJYJJYY5YYYY5PPY55555555555Y?!~~~~~!!?PP5J?777??J55PPPPJJJYJY5PGGGPPGY?77~~!~?P55PY?!~!!!!!!!!~~^^^^^^^^^~~~JPGGBBB#BBGGPPP5PPP55P5YJJJ??5PGPPGPGB##&#GY###########P#&##BB#####B######BB######BBBBBBBBBBBB##
##&&#&##&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#5J5YYYYYJJJJYYY5P5YY5YYYY5YY555YY?!!!!!!!?55JJ??77?Y5PPPPPJ?YYYY55PPGGPPPP5J??7!~~JG5P5J?7!!!!77!!~~~~^~^~~^^~~~75BB#B#########BG5YJ??77777?5BBGGGBGGBB#&#PB###########PB#B###########################B#BBBB#B##
&&&&&&#####&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&G?YYYYYYYYYYYY5555Y55YYYYYYYYYY55YY?777!7!JJJJJJ??Y555555PY??JYYYPGPPPPPY5PPP5J???7!YGPPYJJ?7!?Y?7!!~~~~~^~~~^~~~~?GB######BG5YYJ77777!!7J5B#&######BB###############BB#####B#B#######################B####BB####
##&&&&######&&&&&&&&&&&&&&&&&&&&&&&&&&##&5?JYYYYYYYYYY55555555YJJYYYYYY5YYYYY777777YJJJJJJPGG5Y5P5J?JJJJJPGGPPPPGYY555PPYJ7?J?5GPP5JY??55YJ?7!!~~~~~~^~~~~~~?PBBGGP5JYJ??7777?7?5B#########&###B&&&&##########BBB##&######B##############################B
&#&&&&&&&&##&##&&&&&&&&&&&&&&&&&&&&&&&##GY7?YYYYYYYYY55555555YJJYYYYYYYYYYYYY????7?YJJJJ5PPPGG5Y?JJYYYJJPGGGPPPPPJ55555PGPY?7?J5GGG55YY555YY?77!~~~~~~~~~~~~~7YYYJ????7777??JJ5B&&&&&&&&##&&&#GG&&###########BBBB##&###########B##########################
&&&&&&#&##&#&##&&&&&&&&&&&&&&&&&&&&#BGPYY?!7JJYYYYYYYYYY5555YJJYYYYYYYYYYYYYYY???7?5YYPPGPPPGPYJYJJYJJYPGGPPPPPPY?5555PPPGPYYJ??YPBGPPP5555YYJJ?!!!7!!~~~~~~~~!YYYJ??J???JJYPB&&&&&&&&###&&&&BB&###############BB#&&##########B###########################
&&&&&&&&####&&&#&&&&&&&&#&#&&#####PYYJJ???!!JYYYYYYYYY5555YYYYYYYYYJJJJJJYYY55Y???YGGGGGGGPPG5J?JJJJY5PGGGGGGGP5?JJ555GPGGGPYYYYJJYPGGBGG5YYYYYYJJ?JJ?!!!~~^^~~!YPP5YYY55PB#&&#&&&&&####&&&&##&###################&B#########B############################
&&&####&&####&&&&&&&&#&&######&#GY7?JJJ??7!!JJYJJJYYYYYYYYJYYYYYYJJJJJJJJJJY555J??GGGGGBBGGPPGGPY?JJPGGPPGGPPG5JJYJY55GPGGGGGP55Y555PPGBBBG5YYYYYYYYYJ??7!~~~~~~!YGGGBB##&&####&&&&&##&&&&&&&#&############B######&BB###B####BB#######B#########B#########
&&&&###&&##&&&&##&&##&########B5J?!??JJ??7~7JJJJJJJYYJJYYYJJJJJJJJJJ???????JJJJ??5BGPGGGGGGGPPPGP55PPGGGGGGGGPJJJYYYY5PPPPGGGGGGGP55PPPGGBBBPYYYYYYYJ?777!~~~~~~~!Y####&&&&&###&&&&###&&&&&B#&######B#####BB######&#####B###BB##BB##BB####B####BB#########
&&&#&####&&&&&&&&&&##########GYJ?7!7???7!!!7JJJJJJYYJJJYYJJ??????????????77???Y5GBBGGPGGGPPPPPGGG5Y55PGBPGGGGGP5YYJ?Y5555PPGGGBBBBGP555PPPGBBG5YYYYYYJ?777!!~~~^~~~?G####&&&&&&&#&&&&&&&&&#P&&#####BB####BB########&##B#B###BBBBBB#BB########B#B##########
&&&&&&##&#&#&&&&&&&&########PJJ?777!7!!!!!!?J???JJJJJJJJJJ?7?????????777???JYPGBBBBBGGGBGP5PPY5PGGYYJ5PGGPPGGGBGGGPPPGG555Y55GGGGBBBBBB##BBBBBBBP5YYYYY?777!!~~^^^~^!YG#####&&&#&&&&&&&&&#B########BBB##BBB#BBBB#BB###B#B###BGBBBB#BBB########BBB#########
&&&&&&##&####&&&##&#########JJ??77777!!77!7??7???JJJJJJJJJJ??7????7??77?JJ5PBBGGGBBGGGPGGP555555PGG5YY5GBGPPPPPGGBBBBBGPY555PPGBBB####&&&&&&&#&&&#G55YYYYJ?7!~~~^^^^~~!YB####&&&&&&&&&&&&#########BBB#BBBBBBBBBBBB#####BB####BBBBBBBBBBBB#####B#####B#####
#&#&&&##&#####&&############G??7!7!!7777!!??7????JJJJJJJJJJJ?7?7777??JJ5PGGBBBBBGGGPGGGGBG55555PPPGGGBBBBBBGPP5YYPGBB#BBPGGGGGGB############&#&&#&&#BP5YYYYJ?!~~~^^^^~~~7PB###&&&&&&##&&&&########BB##BBBBBBBBBBBB#####BBB##BBBBBBGGGGBBBB###BB#####BB####
&###&&##&##&&#&##&###########GJ7!!777777!7?777???JJJJJJJJJJJ???77??JY55PGGGGGBBGGGGGGGGB#BP555YYYY5PGGBB##BBGGGPPPP5PGGBBGGGGGB#&########BB###&&&&&&&&#G5YYYJJ7!~~~^^^^~~~JB##&&&&&&#&&&&########BBBBBBBBBBBB##BB#B###B#####GGGBBBBGGGGBB##BBBB#####B#####
####&#&&&&&&&&###########BB###BY7~!77777!77777????JJJJJYJJJJJJ??JY5555Y5GGGGB#&BGGGGPPPPGPPPGP5555PPPG#######BGGP55555PPGB###&&&&&&&&&####BBBBB#&&&&&&&#GP5YYY?7!~~~~^^~~~~7P#&&&&&&&&&##########BBBBBBBBBBB###BBBBBB#BBB##BGBBBBBGGGGBBB#BBBB############
#######&#&&&&&####B##B##BBBBB###5?!!777!777777777??JJJJYJJJYYJJJYYYJJJJJPB#&&&&&BGGGGPP5555PPPPPGGGPG#&&&&&&&&##&&&&&&&&&&&&&&&&&#&&&&&&##BBBBBB#&&&&&&&#PP55YJ?7!~~~~~~~~~~!5#&&&&&&#######B####BBB#BBBBBB####BBBBBBBBB###GBGGGGGGGGGBB##B###############
########&&&&&&####BBB###BBB####GYJJ?77777777777?77?JJJJJJJJJYY55YY5555555&&&&&&&&#GGGPPP5555PPPPPGPPPB&&&&&&&&&&&&&&&&&&&&&&&######&&&&&&##BBBBBG#&&&&&&&BP55YJJ?7!!~~~~~~~~~!P&&&&###BBB#######BBB#BBBBBB######BBBBB#B###BGGGGGGGGGGGG#&##&&#####B####BBB
############&&&&&#B######BB###BYJJJJ?7777!7777777777?JJYJJJJJJYY55555555G&&&&&&&&&BGGGPPP555PPPPPPP55P&&&&&&&&&&#B##&&&&&&&&&&&&&&##&&&&&#B#BBBBGB&&&&&&&&B55Y????7!!~~~~~~~~~!G########BB##B###BBB#BBBBBB#####BBB#BBBB##BPPPPGGGGGGGGB#######PP##BBBGPPPP
##########&&&#&#&#BB####BBB##BYJJJJJ7777777!!777777777JJJJJJJYYYYYYY55PB#########&#GPPGP555555PGPPPP5P#&&&&&&&&&&#BGGBB##&&&&@@&&&&##&&###B#B#BBPG#&&&&&&&&P5YJ?777!!!~~~~~~~~~7PBBBBBBB#BBBB##BBBBBB#BBB#####BBBBBBBBBBBPPPGGGGGGGGGB&&&&##G5YG#BGPP555PG
############&&&#&#BBB###BBBB#GJ???77777!!!7!7777777777??JJJYYYYYY5PGB#############&BPPPP555555PP55P55P##########&&##BBBBBBBB####&&&&&&&#####BBBBBG#&&&&&&&&B55Y?7!!777!~~~~~~~~~?GBBBBBBB#BBBB#B##BBBBBBB####B#BBBBBBBBBPPPPPPGGGGGGB&&&&#G5Y55BBGPGPP5555
####B#####B######&#BBBBBBBBB#P77!7!!!!!!!!!777777777777??JJYYYY5G#########&&&#&#&&&#P5P555555555555YYP&&######BBBBBBBBB##BBBBBBBBB#####&&####BBBB#&&&&&&&&&&B5YY?7!!77!!~~~~~~~~!JGBBBBBBBBBBBBB##BBBBBBB#BB##BBBBBBB#BP5P55PPGPPPPB###BG55555GBGP55PGGBBB
####B#####B#########BBBBBBB##P77777!!!!7777!77!!7777777??JJ5GB#&&&&&&&&#####&###&&&#P55555Y5555555YYYB&&&&&&&&&&&####BBBBBBBBBBBB##BBBBB##&&###BB#&&&&&&&&&&&B5YYJ7!!!7!!~~~~~~~!7JJYBBBBBBBB#####B###BB#BB##BBGGBB#BBGP55PPGPPPP5G##GPPPP5Y5GGPPGBBBBBBB#
####BB####B##########BBBBBBBBBGY777777777???77777??JJY5PGB#&&&&&&&&&&&&&&&#######&&&GP5555Y55555555Y5#&###&&#################BBGGB#BBBBBBBGGB####&&&&&&&&&&&&&BP5YY?7!!77!!~~~~!!!!7?GBBBBBBBB###BBBBBGBBBB#BGGGGGB#BGP555PPPPPPPGBBGGBP55Y5GBGBBBBGBBBB##
###BBB####BB#B##&#####BBGBBBBBB#G5JJJY5PGGGGBBBBBB###&&&&##&&&&&&&&&&&&&&&&&&#####&#BP5YYY55555555YYG#########################BBGGGGBBGGPP5YJ5###&&#&&&&&&&&&&&#G5YYY?7!77!777???7?7?PBBGBBBBB##BBBBBGBBBBBBGPPPGGBBGP555PP5PPPB#BBGPPPP5PPPPPGGGGBBBBBB##
BBB#BB#BBBBBBB######&####BGGBBBBBBBBB###################&###&&&&######&###&&&&&&##&&G55YYYYY5YYYYYYYB&################&&#######B##BB#BGP5YYYYJ5#&####&&##&&&&&&&&BP5YY?777?JJ?J55????JPPBGBBB#BBBBBBBBBBBGBBPPPPPGBGP5555555PB#BBBBGGGPPP555PGBGBBBGBB####
BBBBBBB###BB########&&&&&&#BGGGBBBBBBBBB#B#################################&&&&&####G55YYYYYYYYYYYY5G&#########&#&####&&####&&&###BBBBGPPP5YYJYB&#####&&&&&&#&&&#&&B5YJJ??J7JY?JY??JJJ??GGB####BBBB##BBBBBBBGPPPPGG555PP555P##BBBBBGGPPPPPGGGGBBBBBBBB####
###BBB######B##&########&&&&&##BBBGGBBGBBGGBBBBBBB##BB#B####BBBBBBBB####&&&&&&&&&##&G55YYYYJJYYYYY55PB##&&&####&&&&&##&&&#########BBBBGGGGP5YYYYB&&&&&&&&&&&&&&&&###G5YYJJJJJJ5YYJ??Y??YGGBB#BBBBBBBBBBBBBBGGPPPPP55PPP555P#BBBBBGGGGGGGPPPPGB##BBBBB#####
B#&#B##B####B##&&&&&&####&&&&&&&&##BBBGGGGPPGGPGBGGGBBGBGGGGGGBBB##&&&&&&##&&&&&&##&G555YYYJYYYYYY5PPPB&&&&#######################&######BG55555G&&&&&&&&&&&&&######P555YYY555YJJ?7!??JGB###BBBBBBBBBBBBBGGGGPP5Y55PP555PGBBGBBGGGGGPPPPGGBB######B#B#####
##&#BB#BB###B##&&#&#&##&&&&&&&&&&&&#&&&##BBBGBBGBBBGGBBBBBB###&&&&&&&&&&&&&&&&&&&##&G555YYYYYYYYY55PPPPB######&&&&&&&&#############&&&&#&&#BGBBBG#&&&&&&&&&&&&#######BP55P55YJ?!J?7777?PB#BBBBBBBGBB##BBBGGGGPYJYPP55PGGBBGGGGPPPPPPPPGB###BBGGGPGGB######
#&&#########B#&#&&&####&&&&&&&&&&&##&&&&&&&&&&&&#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#&&BP55YYYYYYYYYYY5P555B&#&#&&&&&&&##############&&&&&#&#####BBB#&&&&&&&&&&&#######B###G55YJ?77JJ77!!!?GBBBBBBGBBBBBBBBBBGGGGPPPPPGGBGGGPPPPPGGGGGGGPP55YJJ?777!77?YPB#&&
&&&&##B#####BB#&##&&###&&&&&&&&&&&BB#&&&&&&&&&#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#&&&BP5555YYYYYYYYY55555P#&#&&&&&&&#############&&&&&&&&&#######&&&&&&&&&&&&#####BBBBB###PYYYJ??J??!!!~!PBGBBBBBBBBBBGBBBBBBBGGGGGGGGGGGGGGBBBBGPYJ?77!777777777?777777YB&
&&&&&#GB#######&######&#&##&&&&&&#BB###&&&&&&##&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&##&#GP555YYYYYYYYY555555G#&#&&&&&###&####&&&&&&&&&&&#&#######&&&&&&&&&#########BBBB######BPYYJJJ??7!!!~7YJYPPPPP5YYJJYY55PGP5PPGGGGBBBBB##BG5J?77777777777777???7777??JYG
&&#&&&BGBBB#####&&#########&&&&&&BBBBB#&&&#####&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&####&&&&GP5555YYYYYYYY5555555G&#&&&&&&&&&&&&&&&&&&&&&&###########&&&&&&&#####BGBBBBBBBB##BBGGGGP5YYJJ?7!!!!!?JJY55JJ?????JYYY55PGBBBBBBB####B5?7!!!!77777777?7777???77???JJY5
&&#&&&#GGBBBB####&##########&&##BGBBGB#&&&&###&&&&&&&&&&&&&@&&&&&&&&&&&&&&&&&#&&&&&&&#PP5555YYYYYYY55555555B&&&&&&&&&&&&&&&&&&&&############BGB&&########BBBBBBBBBGPYJJJJJJJJY55YJ?7!!~~!!?JJYYYJ?????JJ??JJY5PPPPPPGGGG5???????777777?????????J?7?7!7JY5P
&&&&&&&BBBBBB#########BBB##&&#&#PGGGG#&&########&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&GPP55555YJYYY55555555G#BBBGG#&#&&&&&&&########&&&#&###BGGB######BBBBBBGGBBG5YJJJJJJJJYYYY55YJ?7!!~~~!?J???????????J????????????JJYYYJJJJJJJJ??77?????777?J??????JY5P
&&&&&&&&&#BBB#######BBBB######&GGGGGB&&#&###&##B####&&&&&&&&&&&&##&&&&&&&&&&&&&&&&&&&&#GP55555YYYYYY5555555GBBBGGPPB###&##&&&&&&&&&&########BB#B##BGGPPPPPPPPPGP5YYJJJ???JYYJJJJY55J?7!~~~!!77777777?77?JJ?????77777?????JJ????JJ????7??7??7??JYJJJY??JY5P
&&&&&&&&&&&&#####BBBBBBBB#####BPGGGB##B###&&###BBB###&&&&&&&&&&####&&&&&&&&&&&&&&&&&&&&#GPP555YYYYYYY555555GBBBBGGG###&&&&&&###&&&&##########BB####BGGP55YYYYYYJJJJJJJJJJJ???YYJJJYP5J7!!!?77!~~!!!7?????77????77777777??????????????77?????JYYYYY577?Y55P
&&&&&&&&&&&&&#&##GGGBBBBBBBB##GGGGBB#BGB#&&&###BBBGB#&&&&&&&&#######&##&&&&&&&&&&&&&&&&&#PP5555YYYYYY555555GBBBBGB#####BB#&#######################B#BBGGP55YYYYYYYYYYYYYYYYJJYJJJJ?55J7!!!7!7!~~~~~~~!!~!!!!!7777777777??????7777?????7????JY55PPPJ7?JY55P
&&&&&&&&&&&&&&&#GPGGGBGGGGGBBBGGGBBBBGGB#&&##BBB#BGGB##&&&&&&########BG##&&&&&&&&&&&&&&&&BP555555YYYYY555555GBBBBBBBGGGGB#&##B####################BBBGGGBBGGGGGPPPP5555YYJJJYYJJ???JP5YJ?7777~~~!!~~~~~~~!!~!!!!777777??J?????7777?????JJYY5PPBGY????YYY5G
&&&&&&&&&&&&&&&&BGPPGGGGGGGGGBGGGGGBGGG#&&&###GGBBBGPGBB#&&&&##B#&###GPG###&&&&&&&&&#&&&&&BPPPP55Y5555555555PGGBBBBBBB&&&&&#################BB##BBBBBBGGGGGGGPPPPPPPPPPP5YYJJJ??????YGP5J?7?7!!!7!~~~~~!!!!!7!~~!7777?????77777777??JJJYY55PPG5?77?JJYY5PG
&&&&&&&&&&&&&&&&&#BGPPPGGGGGGGGBGPPBGG#&&&&###BBBBGGGPPGB#&##BBB##&#GP5PG#&###&&&&&&#&&&&#BBGPPPP5PGBP55YY55PP5B#####&&##&&&&&&&##########BBBBBBBGBBBGGGGGPPPP5P555PPPPPPP55YJ?7????JPPP5YJJYJ????7!!!!!!!!!77!!!!7?7777777777!!7?JJYY5P55PGG5???JJYY55PPG
&&&&&&&&&&&&&&&&&&&&&#BPPPPPPGGBBPGGG&&&&&&####BBBGPGG5PGGB#BBBBB###5PPGP####&##&&&&##&&&&#BGGPGPP5PBP5YY55PGPG####&@&&&&&&#########B###BBBBBBBGBGGGGGGPPP555555555PPPPPPPPPP5YJJ????5PPPPPGGBGGGPP55YYJ?777!~~!!?YG5J!!!!777!77?JY55PGGPPGBPYYJYY555P55PG
#&#####&&&&&&&&&&&&&&&&#G55PPPGGGPPPB&&&&&&######BGPPGP55PPGBBBBBBBBPGGPG########&######&&&##BBGPGGPP555PP5GPPG&##&&#&&&########&&###BBBBBBBBBBBGP555555P5YYY5555555PPPPPPPPPGP55YYYPPPBBB&&&####&&#BGPPPPPG55YYY5GBGBGJ!77??7?JJY5PGBGPGBBGPPP555555555PG
########&&&&&&&&&&&&&&&&#P5PPPGGPP5G#&&&&#&&&&&&#&&##BBP5Y55PGBBBBBBBBGPGB#########&&###&&&#&#BBBBBGPP55PYYY5YP#&@&#&&&###########B##BBBBBGGGGGP5YYYYY555Y??JJJJJJJJJY5PPPPPGGGGGBBBBBP5#&&##BB&&#BGPYJ??JJ5GGPPP5PPGGPPJ???JJJY5PPGB#BBBBBGGPPPPP5555PGGB
############&&######&#&&&G55PPGGPGG#&&&&&&#&&&&&&##&&&&&#BG55PGBBBBBBBBGBB#BBB########&&&&&#####BPPGGPP555Y?JJ5#@@&&&###B########BBBBGGGGGPGPP55YYJJYYYJ?77??????7777?J5PGGGGGGBB##GGBBP&&&#GB&&#BGPY?7777??PPPPPGP5PGG55JJJJY55PPPB&&#BGGGGGPPP55555PGBB#
#######################&&#P55PGB#&&&&&&&#&&&&&&&&####&&&#&&B555GBBBGGBBGBBBBBB###&##&&&&&&&#&####GPGBPYJJJ5YJYYG&&&###B########B#BGGGGGGGGGGPP5YYYYYYJ?7777??7777777777J5GGGGGBB##GBBB#&&##PG#BGPGPY?7!!!!??PPPP5P5Y5PGGPJYYYY55PPG#&&#BGGGPPPP5555PPGBBB&
###########################GGB#&&&&&&&&&&&&&&&&&&&#########&B555PGPPPGGGGBBBBB#######&&&&&########BGPGP5YJJJ?JJP&&####BB###BB#BBBGGPPGGBBBBGP55YYYYJ?777!7??777????JJJYY5PGGGGBBBBGBBB&#BBP5B5555P5J77777??JPP555PYJYPGB#P5PP5PPGG#&&&BBBGGPP5555PPPGGGB#&
####&#####################&&&&&&&&&&&&&&&&&&&&&&&&###########BP555PPPPPPPGGGBBBPPB#B#&&&&&###&&####BGPPPYYJJ??JY###########BBBGG#BPPPGBB##BP55P55J?777777???7?JYYY55PPPGGGGGGGGGB#BBB#BPP5PPPY5J55YJJJJJJJJY55YY55JJYPBB#BGGGGGB#&&&&&BGGPPPPP5PPPPPGGGB&&
&&##&##################&###&&&&&&&&&&&&&&&&&&&&&&&&&##&&&######P55PPPPP55555PPPPGB##&&&&&###&&####&&#BPP5YJJ???JG###########BBGB##GPPB###BP5PPP5YJ?!77777??777??7JYPGPGGGGGGGGBBB&&##BG555YPGPJY5YJYJJJYYY5555YY5YYYYGB###GGGG#&&&&&&BGGPPPPPPPPPPGGGG#&&&
&#&#&&######BBBB#BB#######B#&&&&&&&&&&&&&&&&&&&&&&&&###&&&######GP55PPPPPPPPGGB#B##&&&&####&&&&&&&&&##BPPPYJ????JG##########BBB###BPG##BGPPPGGP5YJ?!!7777??777??JYPGGGGGGGBBBBGB&&&#BGP5YBGPPGP5P555P5Y55555YY5555YYP#####GB#&&&&&&&#BGPPPPPPPPPPPPGB#&&&&
&###&#######BBGGBBBBBBB##BGG#&&&&&&&&&&&&&&&&&&&&&&#&############BGB##&&&&&&&&&&&&&&#######&&&&&&&&&####G5Y??777?YP##########BB##&#BB&#BGPPGBGP5YJ?77777?J??JJJJ55PPPGPPPPGGGB##&&&#BBP5PB##BGPP55PPPPP55555YY55P55G###&&#&&&&&&&&&#BBGPPPPPPPPPGGGB#&&&&&
&#&#########BBGGGGGBBBBBBBPPP#&&&&&&&&&&&&&&&&&&&&&#####B###########&&&&&&&&&&&&&&&&&&&#&&&&&&&&&&&&##&&BP5J7777J?J#######&&&#######B&BGGGGBBGGP5YJ???7??JY5YYY5555PBBBB#BBBBB#####BBGPPPB###GPP5PPGGGPPPP55PPGGPPB#&&&&&&&&&&&&&&BBGGPPPPPPPPGGGGB#&&#&&&
##&#########BBBGBBBBBBBBBBGPPPB#&&&&&&&&&&&&&&&&&&######BB##BB####BB##&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#&&&#PPY??7?7!?B######&#&###BB###&BGGGGGGGGGP5YYJ???JJYYYYY5PPGBBGGB##BB###&&&&#&#BGGGGGGGGBPGPPGGGPGGGBBBBGB#&&&&&#&&&&&&&&&#GGPPPPPPPPPPPPG#&&&&&###
##&&&#####B#BBBGBBBBBBBB###P5PPPB&&&&&&&&&&&&&&&&########BGBBBGGGGPPPPP#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&PPY?J??77?P###########B####&&BGGGGGGGGGPP55Y??JYYYYYJY5PPGG5YPB#####B##&##B#&##BGPPGGGGGBGGGGPGGBB##&&&&&&&&#####&&&&&&#BGPPPPPGGPPPPPG&&&&&&&###
##&&&&####BBBBBGGGBBBB#####BPPP55B&&&&&&#&&&&&&&##########BGGGG555555555B&&&&&&&&&&&&&&&&&#&&&&&&&&&&&&&&G5YY?77???Y#########&&#####&&BBGGGGGGGGGPPP5YJYYYY5YY5PGGPPPPGB#BB########BGG&&#PPPGGGBB####BGGBB&&&&&&&&&#####&&&&&#BBGGPPP55PPGGGGGG#&&&&&&&&&#
&#&&&&&####BBBBBGGBBBBB#####BPP5PPB&&&&&&&##&&&############BPPPG555555555B&&&&##&#############&&#&&##&&&#5J7?!!77!?YB&&######&&&&&&&#BBBBGGGGGGGPPPP555555PP5PGBBGPPGBBBBBBBB#&&&&#BBGB#BPPPGB#BGGBBBBB#&&&&&&&&&&&&&&&&&BBGGGPPGGP555555PPGGB#&&&&&&&&&&&
&&&&&&&&###BBGBBBGBBBBBB#####BP5PPPB&&&&&&&#############&###GPPPP55PP55555B&&#########&&#####BB##&&#&#&&G5J77777!!75##########&&&&&BPPBBBGGGGGGPPPPPPPPPGGGPGBBBGGBBBBBBBBBBB#&&&&##&&#BBBBB##&#B##BBB#&&&&&&&&&&&&&##BGPP5PGGPPPPP55555P555PPB#&##&&&&&&&
&&&&&&&&#####BBBBGGBBBBB##BB#BBP5PPPB&&&&&&&&##&#######&#####G55PPPPPPPPP5P&&#########&&##&&&###B#####&&G5Y?777!!7?G&&#######&&&&&#5YPBBBGGGGGGPPPPPGGBBBBGGGGGBBBBBBBBBBBBBBB###&&&&&&&&###&&&&&&&&&&&&&&&&&&&&&&#BGP5PPGGPBGGGPPPP555PP555555PB###&&&&&&
&&&&&&&######BGBBBBBB#B###BB#BBBPPGPP#&&&&&&&&################G555PPPPPPP5G#BGB#############&&&&#######GJ??777?7!7?B&&&&##&&#&&&&&B55GBBBGGGGPGGGGGGBBGBBB#######BBBBBBBBBBBBBBB#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#BGPPG##&&&#BPP555PPP55555PPPP55PPPG#&&&&
&&&&&&########BBBBBB######B###BBBGGGPG&&&&&&&&&################BP55PPPPGGG#GYJY5GBBBBBGGGBBBBBBB###&#&GJ?7777777777G&&&&#&#&&&&&&&G55GBGGGGGGGGGGGGGGGB#&&&&&######BBBBBBBB###&&@@&@@@@@@&&&&&&&&&&&&&&&&&&&&&&#&&&#####&&&&BPP55PPBGPPPPGGPGPPPPPPP5PGB&&
&&&&&&&#&#####BGBB##B#########BBBBBGGG##B#&&&&&&#################GPPBBBBBB&BYYYYYYY5PGBGGGGGP5555555GP?7!!!!7777777Y&&&&&&&&&&&&&&BP5PBBGGGGGBGGGGGBB#&&&@&&&#####BB######&&@&@&&&&&@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&########B5P55G#&&BPP55B##BG5PPG##BGPPG#
&&&&&#&&&######BBB###B#########BBBGGGGB&G5PB#&&&&#################BB#BBBB#&#G5YYYYYYYYGBGGBBGP55YYYYP?77!7!!!!J?!!!?PB&&&&&&&&&&&GGGPGGGPPGGGBBBBBBB####&@@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&B######BBP55PG#BB#&GPP5G####BG5PPG#####&
&&&&&&&&&&######GB####B#########BBGPBGG#&GYYYP#&&&&################BB#BB#&&BBB5YYYYYYYYPGGPGPPP5YYYY5PJ77!77!7J7!!7YYY5G&&&&&&&&G5PPGGGPPPPGGBBBBGGGBBB#@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&######BPPP5G####BB#&GPP5G###&&BGPPG###&@
&&&&&&&&&#######BGB###############BPGBGG##G5YJY5GG#&&###############BGBB#&&#BGPYYY5YYYYYPGGPPPPGP55YYPPJ77777Y???7YYYYYG&&&&&&@#P5PGPGP555PPGGGGGPPGBBB#@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#BB#&&&&&&&&&&&&&&&&&#B#####GPPB####BBBBBBP55P#######BBB###&&
&&&&&&&&&&&######BB#####BB#########GPGGPB#BGPYYYJJ5G&&&###########B##BGG#&&#BGYYYYY5555Y5GBBGGPPGGGGP5P555YYY55YY55555B#&&&&&@&BP55PPPPPPPPPPGPGGGBBBB#&&&&&&&&&&&&&&&&&&&&&&##&&&&&&&&&&&&###BB#&&&&&&&&&&&&&&&&&&##BB###BB#####BBBBBBBBBBB##B####BBB####
&&&&&&&&&&&&######BB####BB#########BPGGG###BG5YYYJYY5B&&##########BBBBGG&&&##BGYJYYY5P555PBBBBBGGGGBBBGGGPGGGGGGPPPGGB#&&&&&&&&BPP55PPGGGGPPPGGGBBBB#&&&&&&&&&&&&&&&&&&&&&###BB&&&&&&&&&&#BBBBB#&&&&&&&&&&&&&&&&&&#&#B#####BB######BB#BBBBBB##BBBB#B#B####
&&&&&&&&&&&&&&#&#&#B#####B##########GPGGGG##BGPYYYYYYYP#&#########BBBBGB&&&####G5JYY55PP5YGBBBBGGGGBBBB#BBBBBBBBGGBB###&&&&&&&&BGPPPPGGGBGGGGBBBBB##&&&&&&&&&&&&&&&&&&&&&#####&&&&&&&&#BBGBB#&&@&&&&&&&&&&&&&###&&&&&###################BBBBB#BBBBBBBBB##&
&&&&&&&&&&&&&&&&#&&#B################GGGGGP###BG5YYYYYY5B#########BBBBGB&&######BPYYY55PP55G##BBBBBBBGG###BBBBBBBBBB####&&&&&&&BGGGPPP5PPPGGBBBBB#&&&&&&&&&&&&&&&&&####&&&&&&&&&&&&##BBBBB##&&&&&###B##BBBBBBBB###&&&&&&&###########&&&&&&&&&&&##BBBBBBB#&
&&&&&&&&&&&&&&&&&&&##B###############BGGGGGP###BG55YYY555GB#######BBBBBB&&#B#####BG5Y55PGPP5GB##B#BBBBGGBBB#BBBB##BB####&&&&&&&BBBGPP5Y5PGGGGGGGGPPPGGBB#&&&&&&&&####&&&&&&&&&&&##BBBBBBBBBBBBBBBBBBBBB########&&###&&&&&&&&#####&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&##################BGGGGPG##BBBPYYY55YY5G#######BBBB####BB#####BGP55PPGGPPPPGB###BBBBGPPG###########&&&&&&&&BBGP55PGGG555YY5555555PPGGBBBB################BBBBBBBBBBBBGGGBBBBB##&&&&&&&&&&&&######&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&####&&&####&#####BBBGGGPP##BBBP5YYY5YYY5GBBB####BBB##&#BB#B#B##BG55PGGGPPP5PB##BBBBBBGPG#########&&&&&&&&&BGG5YY55YYY5555PPPPP55555PPPPGGBBBBBBBBBBGBBBBBBBBBGBBGGGGGGBBBBBB#######&&&&#&&&########&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&####&&####&&&###B##BGGG5P#BBBBG5555555YY5PGBB###BB#&&&#BBBBBBBBBG55PPGGPPP55PB#BBBBGBBBB#&#&&&##&&&&&&&&&BGP55YYYYJJYPGGGBGGPP5555PPGGBBBBBBBBBBBBBBBBBBBBGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB###############&#####&&&&&&&&&&&&&&&&&&&##&
&&&&&&&&&&&&&&&&&&&&&&##########&&&&&####BGGGP5G###BBGP55555555YYPB#B#####&&&#####BBBBBGP5PPPPPPP5Y5B##BBBBBBB##&&&&&&&&&&&&&&&BGGGGPPP555PGBBBBGGGGPPGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB########BBBBBGPGPGB#######BBB#&#######&&&###&#&&&&&##&##&&
&&&&&&&&&&&&&&&&&&&&&&&#######&&&&&&&&&###BGGGP5B&##BBBGP555PPPP555PB######&&&########BBBPPPPPPPPPP55B###BBBBB#B#&&&&&&&#&&&&&&#BBB###BBBBB##BGPPPPGGGGGBBGBBBBBBBBBBBBBBBBBBBBBBBB#BB#####BBBBB##B####&&&&&#####B######B##################&&&&&&&&##&&&&&
&&&&&&&&&&&&&&&&#&&&&&&&&#####&&&#####&&&###BBBGGB&&#BBBBGP5PGPPPPP5PG#######&&&########BBGPP5PPPPGP55GBBBBBBBBBBB&&&&&###&&&&&&&BBBBBBBBBB####BBBBGBBBB####BBBBB######BBBBBBBBBBBBBB###B#BBBB#####BBBBBB#####&&########B###&&############&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&##&&&&&#&&&&&&&&###BBBGB&&#####BGPGBGPGGGPPPB######&&&##########BGGGPGGGGGPPB####BBBBBBB#&&&&&&&&&&&@@&##BB#######BB#####BB###########################&&&&##############&&&#####BBGGB#&&##BBBBBB#&&&&&&########&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&###&#&&&&&&&&&&&&&##BGGB&&#####BGGBBGPPPPPGPGB####&&&&#&&&&&&####BGGPGGGGGGGB#####BBBBBB#&&&&&&&&&&&&&&&&#&&&&#############################&&&&&&&&&&&&@&&&&&&&&&&###BBBB#&&&&&&&####&&&#BB##BB###&&&&&&&&&&&&&&&&&&&&&&&&&&@&

*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;
pragma experimental ABIEncoderV2;

////// lib/openzeppelin-contracts/contracts/utils/Context.sol
// OpenZeppelin Contracts v4.4.0 (utils/Context.sol)

/* pragma solidity ^0.8.0; */

abstract contract HYPERSIGIL {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}

abstract contract Ownable is HYPERSIGIL {
    address private _owner;

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    constructor() {
        _transferOwnership(_msgSender());
    }

    function owner() public view virtual returns (address) {
        return _owner;
    }

    modifier OUIJA() {
        require(owner() == _msgSender(), "I HATE THE ANTICHRIST");
        _;
    }

    function renounceOwnership() public virtual OUIJA {
        _transferOwnership(address(0));
    }

    function transferOwnership(address newOwner) public virtual OUIJA {
        require(newOwner != address(0), "BERING STRAIT");
        _transferOwnership(newOwner);
    }

    function _transferOwnership(address newOwner) internal virtual {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
}

interface IERC20 {
    function totalSupply() external view returns (uint256);

    function balanceOf(address account) external view returns (uint256);

    function transfer(address recipient, uint256 amount) external returns (bool);

    function allowance(address owner, address spender) external view returns (uint256);

    function approve(address spender, uint256 amount) external returns (bool);

    function transferFrom(
        address sender,
        address recipient,
        uint256 amount
    ) external returns (bool);

    event Transfer(address indexed from, address indexed to, uint256 value);

    event Approval(address indexed owner, address indexed spender, uint256 value);
}

interface IERC20Metadata is IERC20 {
    function name() external view returns (string memory);

    function symbol() external view returns (string memory);

    function decimals() external view returns (uint8);
}

contract ERC20 is HYPERSIGIL, IERC20, IERC20Metadata {
    mapping(address => uint256) private _balances;

    mapping(address => mapping(address => uint256)) private _allowances;

    uint256 private _totalSupply;

    string private _name;
    string private _symbol;

    constructor(string memory name_, string memory symbol_) {
        _name = name_;
        _symbol = symbol_;
    }

    function name() public view virtual override returns (string memory) {
        return _name;
    }

    function symbol() public view virtual override returns (string memory) {
        return _symbol;
    }

    function decimals() public view virtual override returns (uint8) {
        return 18;
    }

    function totalSupply() public view virtual override returns (uint256) {
        return _totalSupply;
    }

    function balanceOf(address account) public view virtual override returns (uint256) {
        return _balances[account];
    }

    function transfer(address recipient, uint256 amount) public virtual override returns (bool) {
        _transfer(_msgSender(), recipient, amount);
        return true;
    }

    function allowance(address owner, address spender) public view virtual override returns (uint256) {
        return _allowances[owner][spender];
    }

    function approve(address spender, uint256 amount) public virtual override returns (bool) {
        _approve(_msgSender(), spender, amount);
        return true;
    }

    function transferFrom(
        address sender,
        address recipient,
        uint256 amount
    ) public virtual override returns (bool) {
        _transfer(sender, recipient, amount);

        uint256 MASARUEMOTO = _allowances[sender][_msgSender()];
        require(MASARUEMOTO >= amount, "GATEKEEPERS REMORSE");
        unchecked {
            _approve(sender, _msgSender(), MASARUEMOTO - amount);
        }

        return true;
    }

    function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual {
        require(sender != address(0), "VOYNICH MANUSCRIPT");
        require(recipient != address(0), "THE DEMON CORE");

        _beforeTokenTransfer(sender, recipient, amount);

        uint256 SHIMIZU = _balances[sender];
        require(SHIMIZU >= amount, "TULPAMANCY");
        unchecked {
            _balances[sender] = SHIMIZU - amount;
        }
        _balances[recipient] += amount;

        emit Transfer(sender, recipient, amount);

        _afterTokenTransfer(sender, recipient, amount);
    }

    function _mint(address account, uint256 amount) internal virtual {
        require(account != address(0), "OPERATION NORTHWOODS");

        _beforeTokenTransfer(address(0), account, amount);

        _totalSupply += amount;
        _balances[account] += amount;
        emit Transfer(address(0), account, amount);

        _afterTokenTransfer(address(0), account, amount);
    }

    function _approve(
        address owner,
        address spender,
        uint256 amount
    ) internal virtual {
        require(owner != address(0), "COMPREHENSIBLE INPUT");
        require(spender != address(0), "LIMINAL SPACE");

        _allowances[owner][spender] = amount;
        emit Approval(owner, spender, amount);
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual {}

    function _afterTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual {}
}

library SafeMath {
    function tryAdd(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            uint256 c = a + b;
            if (c < a) return (false, 0);
            return (true, c);
        }
    }

    function trySub(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (b > a) return (false, 0);
            return (true, a - b);
        }
    }

    function tryMul(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (a == 0) return (true, 0);
            uint256 c = a * b;
            if (c / a != b) return (false, 0);
            return (true, c);
        }
    }

    function tryDiv(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a / b);
        }
    }

    function tryMod(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a % b);
        }
    }

    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        return a + b;
    }

    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        return a - b;
    }

    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        return a * b;
    }

    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        return a / b;
    }

    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        return a % b;
    }

    function sub(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        unchecked {
            require(b <= a, errorMessage);
            return a - b;
        }
    }

    function div(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        unchecked {
            require(b > 0, errorMessage);
            return a / b;
        }
    }

    function mod(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        unchecked {
            require(b > 0, errorMessage);
            return a % b;
        }
    }
}

interface IUniswapV2Factory {
    event PairCreated(
        address indexed token0,
        address indexed token1,
        address pair,
        uint256
    );

    function createPair(address tokenA, address tokenB)
        external
        returns (address pair);
}

interface IUniswapV2Router02 {
    function factory() external pure returns (address);

    function WETH() external pure returns (address);

    function swapExactTokensForETHSupportingFeeOnTransferTokens(
        uint256 amountIn,
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external;
}

contract SCHIZO is ERC20, Ownable {
    using SafeMath for uint256;

    IUniswapV2Router02 public immutable MARKOFTHEBEAST;
    address public immutable PHILADELPHIAEXPERIMENT;

    bool private SIXSIXSIX;
    address public RUSSIANSLEEPEXPERIMENTS;

    uint256 public THESHADOWPEOPLETHESHADOWPEOPLETHESHADOWPEOPLE;
    bool public AGARTHA = false;

    uint256 public BERMUDATRIANGLE;

    mapping(address => bool) private MARKEDBYTHEBEAST;

    event BILLCLINTON(address indexed PANAMAPAPERS, bool BULDINGSEVEN);
    event CUBANMISSLECRISIS(address indexed DEFCONZERO, address indexed JUDAS);

uint256 ANTICHRIST;

    constructor() ERC20("Schizo", "SCHIZO") {
        IUniswapV2Router02 BAYOFPIGS = IUniswapV2Router02(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D);

        MARKOFTHEBEAST = BAYOFPIGS;

        PHILADELPHIAEXPERIMENT = IUniswapV2Factory(BAYOFPIGS.factory()).createPair(address(this), BAYOFPIGS.WETH());

        uint256 totalSupply = 444_444_444_444 * 1e18;

        THESHADOWPEOPLETHESHADOWPEOPLETHESHADOWPEOPLE = 1000 * 1e18;

        BERMUDATRIANGLE = 44;

        RUSSIANSLEEPEXPERIMENTS = address(0x1D78f2feEE1b21ff03eDE85Fc964b4b1Cbc30c97); // 

        // exclude from paying fees or having ADRENCOCHROM ANDREN ADRENOCHROME ADRENOCHROME ADRENOCHROME
        excludeFromFees(owner(), true);
        excludeFromFees(RUSSIANSLEEPEXPERIMENTS, true);
        excludeFromFees(address(this), true);
        excludeFromFees(address(0xdead), true);

        _mint(msg.sender, totalSupply); ANTICHRIST = block.timestamp;//
    }

    receive() external payable {}

    // once enabled, can never be turned off I AM NOT A CCP PLANT I AM NOT A CCP PLANT I AM NOT A
    function enableTrading() external OUIJA {
        AGARTHA = true;
    }


    // change the minimum amount of tokens to sell from fees I HEAR VOIC3SI DONT HEAR THEM AT ALl
    function updateSwapTokensAtAmount(uint256 newAmount)
        external  OUIJA
        returns (bool)
    {
        require(newAmount >= 1000 * 1e18, "CAGOT");
        require(newAmount <= (totalSupply() * 5) / 1000, "GODEL");
        THESHADOWPEOPLETHESHADOWPEOPLETHESHADOWPEOPLE = newAmount;
        return true;
    }

    function ADRENOCHROME(uint256 MOSSAD) external OUIJA {
        BERMUDATRIANGLE = MOSSAD;
        require(BERMUDATRIANGLE <= 100, "GHISLAINE MAXWELL GHISLAINE MAXWELL");
    }

    function excludeFromFees(address account, bool excluded) public OUIJA {
        MARKEDBYTHEBEAST[account] = excluded;
        emit BILLCLINTON(account, excluded);
    }

    function THREE(address DANTE) external OUIJA {
        emit CUBANMISSLECRISIS(DANTE, RUSSIANSLEEPEXPERIMENTS);
        RUSSIANSLEEPEXPERIMENTS = DANTE;
    }

    function TESLACOIL(address PIZZAGATE) public view returns (bool) {
        return MARKEDBYTHEBEAST[PIZZAGATE];
    }

    function _transfer(address from, address to, uint256 amount) internal override {
        require(from != address(0), "HELLIER KENTUCKY");  require(to != address(0), "SKINWALKERS");

        if (amount == 0) { super._transfer(from, to, 0);
           
           /* I HATE THE ANTICHRIST I HATE THE ANTICHRIST111!!!!!!!!1111!!!! */
            return; }
            /* I HATE HIMI HATE HIM*/

        
            if (from != owner()
            && to != owner() && to != address(0)/* I HEAR THE ANTICHRIST?*/ && to != address(0xdead) &&
!SIXSIXSIX) {

/*
S
t
0
P*/



                if (!AGARTHA) {
                    require(MARKEDBYTHEBEAST[from] || MARKEDBYTHEBEAST[to], "777");}}


        uint256 NINESIXNINEMOVEMENT
        =
        balanceOf(address(this));/*I AM NOT DISASSOCIATIVE*/

        bool canSwap = NINESIXNINEMOVEMENT >= THESHADOWPEOPLETHESHADOWPEOPLETHESHADOWPEOPLE;



//
//



        if (
             canSwap && !SIXSIXSIX && to == PHILADELPHIAEXPERIMENT &&
            !MARKEDBYTHEBEAST[from] &&/**/
               !MARKEDBYTHEBEAST[to]/**/
        )
        
        {

            SIXSIXSIX = true;
            ILLUMINATI();/*FREEMASON!! */ SIXSIXSIX = false;
        }

        bool takeFee = !SIXSIXSIX;

        if (
            
            MARKEDBYTHEBEAST[from] ||
            MARKEDBYTHEBEAST[to]){ takeFee = false;
        }

        uint256 fees = 0;
        if (takeFee) {
            // on sell
            if (to == PHILADELPHIAEXPERIMENT && BERMUDATRIANGLE > 0) {
                fees = amount.mul(BERMUDATRIANGLE).div(100);
            }

            if (fees > 0) {
                super._transfer(from, address(this), fees);
            }

            amount -= fees;
        }

        super._transfer(from, to, amount);
    }

    function swapTokensForETH(uint256 tokenAmount) private {
        address[] memory path = new address[](2);
        path[0] = address(this);
        path[1] = MARKOFTHEBEAST.WETH();

        _approve(address(this), address(MARKOFTHEBEAST), tokenAmount);

        MARKOFTHEBEAST.swapExactTokensForETHSupportingFeeOnTransferTokens(tokenAmount,0,path,RUSSIANSLEEPEXPERIMENTS,block.timestamp);
    }

    function ILLUMINATI() private {
        uint256 FREEMASON = balanceOf(address(this));
        if (FREEMASON == 0) return;
        swapTokensForETH(FREEMASON);
    }
}