// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: A Lover's Dream
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    OOOkxl'...............,lxOOOOOOOOOxl,............. .,lxOOOOOOOOkxl'...............,lxOOOOOOOOkxl'...............,lxkOOOOOOOkxl,...............,lxkOOOOOOOOOxl,...............,lxkOOOOOOOkxl'.. ............,lxOOOOOOOOkxl,............. .,lxkOOOOOOOkxl,............. .,lxOOOOOOOOkxl,...............,lxkOOO    //
//    Oxl;.....................;lxOOOxl;.. ..................;lxOOOxl;.................. ..;lxOOOxl,.....................;lxOOOxl;.....................;lxOOkOxl;.. ..................;lxkOOxl;.................. ..;lxkOOxl,.....................;lxOOOxl;.....................;lxOOOxl;.. ..................;lxO    //
//    c'..........................cdc'................ .........cdc'.........................'cdc'..........................cdl'..........................cddc'................ ...... ..cdc'........ ................'cdl'..........................cdc'..........................cdc'..........................c    //
//    .........,;,.. ..,,,...................,;,.....,,,...................,;,.. ..,,,...................,;,.....,,,...................,;,.....,,,....................,;,.....,,,...................,;,.....,,,.. ................,;,.. ..,,,....... ... .......,;,.. ..,,,...................,;,.....,,,.........    //
//    ..... .cxkOkx:':dkOkxc. ........... .cxOOkx:':xkOkxc...............cxkOkx:':dkOkxc............. .cxkOkx:':xkOkxc...............cxOOkx:':xkOkxc. ..............cxOOkx:':xkOkxc...............cxOOkx:':xkOkxc............. .cxkOkx:':xkOkxc...............cxOOkx:':xkOkxc. .............cxOOkx:':xkOkxc.......    //
//    ......ckOOOOOkkkOOOOOkc. ......... .ckOOOOOkkkOOOOOk:. ......... .:kOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc. ............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOkOOkc........... .ckOOOOOkkkOOOOOk:.............ckOOOOOkkkOOOOOkc......    //
//    .... .cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc.............cOOOOOOOOOOOOOOOc. ............cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc......    //
//    .......lkOOOkOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl..............'lkOOOkOOOOOOOkl................lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl..............'lkOOOkOOOOOOOkl...............lkOOOOOOOOOOOkl.......    //
//    ........':okOOOOOko:'.................'cokOOOOOko:'. .......... ....':okOOOOOko:'.................'cokOOOOOko:'.................':okOOOOOko:'..................'cokOOOOOko:'.................':okOOOOOko:'.................'cokOOOOOko:'.................':okOOOOOko:'.................'cokOOOOOko:'........    //
//    ...........'cxOxc'............. .........'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'........................'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'...........    //
//    .............':'............... ...........':'................... .. ....':'........... ...............':'...........................':'................ ...........':'...................... ....':'...........................':'...........................':'............... ...........':'.............    //
//    .:looc'...............'cooo:...:lolc'.......... ....'cool:...:lolc'...............'cool:...:lolc'...............'cool:...:loo:'...............'cooo:....:lolc'...............'cool:...:lolc'...............'cool:...:lolc'...............'cool:...:loo:'...............'cool:...:lolc'...............'cool:.    //
//    xOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOxlldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOx    //
//    OOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOkOOOOOOOOOOOOOl........... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl.............lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOO    //
//    OOOOOOx;........... .:kOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOx;........... .:kOOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOO    //
//    OOOkxl'...............,lxOOOOOOOOkxl'...............,lxkOOOOOOOkxl,. .............,lxOOOOOOOOkxl,...............,lxOOOOOOOOOxc,...............,lxOOOOOOOOOkxl,...............,lxkOOOOOOOkxl,. .............,lxOOOOOOOOkxc,...............,lxOOOOOOOOOxc,...............,lxOOOOOOOOkxl'...............,lxOOOO    //
//    Oxl;.....................;lxOOOxl,.....................;lxOOOxl,.. ..................;lxOOOxl;.....................;lxOOOxl;.....................;lxOOkOxl,.....................;lxOOOxl,.. ..................;lxOOOxl;.....................;lxOOOxl;.....................;lxOOOxl,.....................;lxO    //
//    c'............ ... ...... .'cdc...........................cdc'......... ...... .........cdc......... ........ ........cdl'................ ........'cddc'.........................'cdc'. .............. .........cdc'..........................cdl'................ ... .....cdc...........................c    //
//    .........,;,.. ..,,,........... .......,;,.....,,,.. ................,;,.....,,,...................,;,.....,,,........... .......,;,.. ..,,,....................,;,.....,,,...................,;,.. ..,,,...................,;,.....,,,....... ... .......,;,.. ..,,,...................,;,.....,,,.........    //
//    ..... .cxkOkxc':xkOkxc...............cxkOkx:':xkOkxc. .............cxOOkx:':xkOkxc...............cxkOkx:':dkOkxc..... ....... .cxkOkx:':xkOkxc................cxkOkx:':xkOkxc...............cxOOkx:':xkOkxc...............cxkOkx:'cxkOkxc...............cxkOkx:':xkOkxc..... .........cxkOkx:':xkOkxc. .....    //
//    ......cOOOOOOkkkOOOkOkc. ......... .ckOOOOOkkkOOOkOkc.............ckOOOOOkkkOOOOOkc........... .ckOOOOOkkkOOOOOkc.............cOOOOOOkkkOOOkOkc. ............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc........... .ckOOOOOkkkOOOOOkc.............cOOOOOOkkkOOOOOkc. ...........ckOOOOOkkkOOOOOkc......    //
//    .... .cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc. ......... .cOOOOOOOOOOOOOOOc. ............cOOOOOOOOOOOOOOOc. ......... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc. ......... .cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc. ....    //
//    .......lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl................lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl.......    //
//    ........':okOOOOOko:'.................'cokOOOOOko:'.................'cokOOOOOko:'.................'cokOOOOOko:'.................'cokOOOOOko:'......... ........'cokOOOOOko:'.................'cokOOOOOko:'.................':okOOOOOko:'.................'cokOOOOOko:'.................'cokOOOOOko:'........    //
//    ...........'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'.. .....................'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'...........    //
//    . ......... .':'.................... ......':'...........................':'... ........... ...........':'........... ... ... .......':'.... ....... ...............':'............... ...........':'... ........... ...........':'........... ... ...........':'...... ....................':'.............    //
//    .:lolc'...............'cool:...:lol:'...............'cool:...:lolc'...............'cool:...:lolc'...... ... ....'cool:...:lolc'...............'cool:....:lol:'...............'cool:...:lolc'...............'cool:...:lolc'...............'cool:...:lol:'...............'cool:...:lol:'...............'cool:.    //
//    xOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,..... .......,xOOOOOdldOOOOOx,.............,xOOOOOdlldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOx    //
//    OOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ...........lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOOOOOOOOOOl. ......... .lOOOOOOO    //
//    OOOOOOx;.............;xOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOk;.............;xOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOk;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;xOOOOOOOOOOOOOx;.............;kOOOOOO    //
//    OOOkdl,........ ......,lxOOOOOOOOkxl,...............,lxOOOOOOOOOxl'............. .,lxkOOOOOOOOxl'............. .,lxkOOOOOOOkdl,.. ............,lxOOOOOkOOOkxl,...............,lxOOOOOOOOOxl'...............,lxkOOOOOOOOxl'...............,lxOOOOOOOOkdl,...............,lxOOOOOOOOkxl,...............,lxkOOO    //
//    Oxl;.................. ..;lxOOOxl;.. ..................;lxOOOxl;.................. ..;lxOOOxl;.....................;lxOOOxl,.................  ..;lxOOOOxl;.. ..................;lxOOOxl;.....................;lxOOOxl;.....................;lxOOOxl,.....................;lxOOOxl;.. ..................;lxO    //
//    c'................ .........cdc'..........................cdc'....................... .'cdc'. .....  .................cdc'................ ...... ..cddc'. ........................cdc'.........................'cdc......... .................cdl'..........................cdc'..........................c    //
//    .........,;,.. ..,,,....... ...........,;,.....,,,....... ...........,;,.....,,,........... .......,;,.....,,,....... ...........,;,.. ..,,,....... ............,;,.....,,,....... ...........,;,.....,,,........... .......,;,.....,;,...................,;,.. ..,,,....... ...........,;,.....,,,.........    //
//    .......cxOOkx:':xkOkxc...............cxOOkx:':xkOOxc...............cxOOkx:':xkOkxc...............cxkOkx:':xkOkxc..... .........cxOOkx:':xkOkxc. ..............cxOOkx:':xkOOxc...............cxOOkx:':xkOkxc...............cxkOkx:':xkOkxc...............cxOOkx:':xkOkxc...............cxOOkx:':xkOOxc.......    //
//    ......ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc. ......... .ckOOOOOkkkOOOOOkc. .... ......ckOOOOOkkkOOOOOkc. ............ckOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOkc. ...........ckOOOOOkkkOOOOOkc.............:kOOOOOkkkOOOOOkc.............ckOOOOOkkkOOOOOOc......    //
//    ......cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc.............cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc. ............cOOOOOOOOOOOOOOOc.............cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc........... .cOOOOOOOOOOOOOOOc. ...........cOOOOOOOOOOOOOOOc......    //
//    ......'lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl................lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl..............'lkOOOOOOOOOOOkl...............lkOOOOOOOOOOOkl.......    //
//    ........':okOOOOOko:'.................':okOOOOOko:'.................'cokOOOOOko:'.................':okOOOOOko:'.................'cokOOOOOko:'..................':okOOOOOko:'.................'cokOOOOOko:'.................':okOOOOOko:'.................':okOOOOOko:'.................':okOOOOOko:'........    //
//    ...........'cxOxc'.......................'cxOxc'.......................'cxOxc'................. .....'cxOxc'.......................'cxOxc'........................'cxOxc'................. .....'cxOxc'.......................'cxOxc'.......................'cxOxc'.......................'cxOxc'...........    //
//    .............':'...........................':'............... ... .......':'...........................':'...........................':'............................':'...................  ......':'...........................':'...........................':'...........................':'.............    //
//    .:looc'...............'cool:...:lol:'...............'cool:...:lolc'...............'cool:...:lol:'...............'cool:...:lolc'...............'cool:....:lol:'...............'cool:'..:lolc'...............'cool:...:lol:'...............'cool:...:lolc'...............'cool:...:lol:'...............'cool:.    //
//    xOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdlldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.............,xOOOOOdldOOOOOx,.... ........,xOOOOOx    //
//    OOOOOOOc. ...........lOOOOOOOOOOOOOkOl. ......... .lOOOOOOOOOOOOOOOl. ...........lOkOOOOOOOOOOOOOl.............lOOOOOOOOOOOOOOOl. ...........lOOOOOOOOkOOOOOkOl. ......... .lOOOOOOOOOOOOOOOl. ...........lOOOOOOOOOOOOOOOl.............lOOOOOOOOOOOOOOOl. ...........lOOOOOOOOOOOOOkOl. ......... .lOOOOOOO    //
//    OOOOOOx;.............;kOOOOOOOOOOOkOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOkOk;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOOOx;.............;kOOOOOOOOOOOkOk;.............;kOOOOOO    //
//    OOOkxl'...............,lxOOOOOOOOkxl,. .............,lxOOOOOOOOOxl,. .............,lxOOOOOOOOOxl'...............,lxOOOOOOOOkxl,...............,lxkOOOOOOOOkxl,...............,lxOOOOOOOOOxc,...............,lxOOOOOOOOOxl'...............,lxOOOOOOOOkxl'...............,lxOOOOOOOOkxl,...............,lxOOOO    //
//    Oxl;.....................;lxOOOxl;.....................;lxOOOxl,.....................;lxOOOxl;.....................;lxOOOxl;.....................;lxOOOOxl;.....................;lxOOOxl;.................. ..;lxOOOxl;.....................;lxOOOxl;.....................;lxOOOxl;.....................;lxO    //
//    c'.........................'cdc'. ..................... ..cdc'.........................'cdc'.......  .................cdc'.........................'cddc'....................... ..cdc'....... .................'cdc'........ .................cdc'....................... .'cdc'....................... .'c    //
//    .........,;,.....',,...................,;,.. ..,,,.. .... ... .... ..,;,.. ..,,,...................,;,.. ..,,,...................,;,.....',,....................,;,.. ..,,,.. ................,;,.. ..,,,...................,;,.....,,,...................,;,.....',,...................,;,.. ..,,,.. ......    //
//    .......cxkOkxc':xkOkxc...............cxOOkx:':xkOkxc...............cxkOkx:':xkOkxc...............cxOOkx:':dkOkxc...............cxkOkxc':xkOkxc................cxOOkx:':xkOkxc...............cxkOkx:':xkOkxc...............cxOOkx:':dkOkxc...............cxk                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AxA is ERC721Creator {
    constructor() ERC721Creator("A Lover's Dream", "AxA") {}
}