/*KNWNXXWWWNK0XXK0KXXXXNNX00K00XNNNNXK00KK0000KOxddOkk0OkOOxddoxkkdxO0xdkkookkoddxOOOkxxdoooldxo:col::oxxk00dokOkOXWMMMM
Kl;clc;:cll:;,;:;,;:::::c:,,,,,;:::c:;,,;;,,,,;,'.','',,'','...''''',,'.''..,'...',,,''''.....'........''',,'.',''lXMMMM
x'..'',;,,',,''',;;,,;;;;,',;:::;;,,,::;,;::;,,;,',,,,,,,''''',,,'',;,,;:::;;;::;;;:,',;;,;,',;:c:;,,;:::;;,;;;'..:KMMMM
k,.;xO0K0OO00OOO0KK00KKK0OO0KKKKKK000KK000KKK00K0O0000000OOOOO000OO00O0KKKKK0KXKKKKK0O0KK000O0KXXK000KKXKK000Kk;..;k0KXW
O;.:0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0:....',;d
0;.c0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;.......;
0;.c0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:.......:
0;.:OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKl.......:
0:.;kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c.......c
0:.;kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO;.......c
O;.:OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0l.......:
k,.:OXXXXXXXXXXK0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOdoddkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;.......l
x'.;OXXXXXXXXXKd:dOkxddkO00KXXXXXXXXXXXXXXXXXXKx;....'cOXXXXXXXXXXXKXXXXXXXXX0kOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO;.......c
x,.;kXXXXXXX0d:,.'''..''',,;coxOKXXXXXXXXXXXXXO:..:dc'.,dKXXXXXXXXkcxXXXXXXXOc,oKXXXXXXXXKKKXXXXXXXXXXXXXXXXXXx,.......c
O,.;kXXXXXXXX0x;.,oxxkkxoc::;'.';:okOKXXXXXXXXx,..oK0o'.,xXXXXXXXKo'c0XXXXKx;':OXXXXXXXXKo:xXXXXXXXXXXXXXXXXXXO;.......l
O,.:OXXXXXXXXX0c.:OXXXXXXXXK0kdlc:,',;cxKXXXX0l'.,xXXKl..c0XXXXXXKl.;OXXXKd,.;kXXXXXXXXXk;.oKXXXXXXXXXXXXXXXXXO:.......o
k,.:OXXXXXXXXXO:.:OXXXXXXXXXXXXXXKOxl,.'lOXXKo'..c0XXXO;..l0XXXXX0c.,xXX0o,.'dKXXXXXXXXXk,.c0XXXXXXKKXXXXXXXXXk;......'d
x'.;kXXXXXXXXXk;.:OXXXXXXXXXXXXKOxol;'.'cOXXXd'..c0XXK0l'.,d0KXXXx,.,xXKo'.'oKXXXXXXXXXXk;.,oxxdocc:ckXXXXXXXXx,.......l
k,.;kXXXXXXXXXk;.:OXXXXXXK00kdc;,..,:lxOKXXXKo'..ckdl:,'...ck0XXXd'.'dOl'.'lKXXXXXKK0kdo:'...'',;;;,:kXXXXXXXXd'.......:
x'.;kXXXXXXXXXx,.;OXK0Oko:;,'.',cox0XXXXXXXXk;...','';cloox0XXXXXd'.,xd'..cOXXXX0olc:;:c;...cxkO0KK00XXXXXXXXXk,.......c
k,.;OXXXXXXXXXx,.'co:,,'',:ldxk0XXXXXXXXXXXXO:..'lkOOKXXXXXXXXXXXd,.'lc..:OXXXXXK0OOO0KXO;.'oKXXXXXXXXXXXXXXXXO;.......:
O;.;OXXXXXXX0xc'....':odk0KXXXXXXXXXXXXXXXXXO;..;kXXXXXXXXXXXXXXXx,..'..:kXXXXXXXXXXXXXXKl..lKXXXXXXXXXXXXXXXXk;.......l
O,.:OXXXXXXXOc'.....,cdxO0KXXXXXXXXXXXXXXXXXO:..,xXXXXXXXXXXXXXXXk;...,o0XXXXXXXXXXXXXXXKo'.c0XXXXXXXXXXXXXXXX0:.......l
d'.:OXXXXXXXXKo'.';:,'..',;cloxk0KKKXXXXXXXXKo'..oKXXXXXXXXXXXXXX0c..'oKXXXXXXXXXXXXXXXXXx'.;OXXXXXXXXXXXXXXXX0c.......o
o..:OXXXXXXXXXo'.;kK0kxdoc;,'..',;::loxxOKXXXx,..:0XXXXXXXXXXXXXX0c...:dxk0KXXXXXXXXXXXXXO;.;kXXXXXXXXXXXXXXXXO:......'x
x'.lKXXXXXXXXXd,.,kXXXXXXXK0kxdl:,''....,dKXXk,..;kXXXXXXX0kxk0XXKl....'.',;clccooodOXXXX0c.'dXXXXXXXXXXXXXXXXO;......'x
k,'oXXXXXXXXXXk;.'dXXXXXXXXXXXXXKOOOkdl:;dKXXO:..'dKXXKkdc,..'oKXKl...lkxl:,''......c0XXXKo..lKXXXXXXXXXXXXXXXO:......'x
d''dXXXXXXXXXXk;..lKXXXXXXXXXXXXXXXXXXXKKXXXXKo'..ckdl:'..':ld0XXKo'..c0XXKOkOkxxxddOKXXXXk;.,kXXXXXXXXXXXXXXXO:......,k
l..lKXXXXXXXXXO;..:OXXXXXXXXXXXXXXXXXXXXXXXXXX0c..''..';ldkKXXXXXXd'..'dXXXXXXXXXKK00XXXXXKl':OXXXXXXXXXXXXXXXk;......'d
o..lKXXXXXXXXX0c..:OXXXXXXXXXXXXXXXXXXXXXXXXXXXOc..';lk0XXXXXXXXXXO:...lKXXXXXXKOxOkkkOKXXX0k0XXXXXXXXXXXXXXXXk;......'d
d'.lKXXXXXXXXXXOddOXXX0xdx0XXXXXXXXXXXXXXXXXXXXX0xxOKXXXXXXXXXXXXXX0o:lOXXXXXK0xodlokxkXXXXXXXXXXXXXXXXXXXXXXXO;......'d
l.'dXXXXXXXXXXXXXXXXXO:...:kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOdolcllccdOOKXXXXXXXXXXXXXXXXXXXXXXXO;......'x
d''dXXXXXXXXXXXXXXXX0l.....;kXXXXX0kxddoodOKXXXXXX00XXXXXOod0KXXXXXK0kxdol,..,xXKKXX0OO0XXXXXXXXXXXXXXXXXXXXXXk;......'x
d''dXXXXXXXXXXXXXXXXk;.''...c0XXXx;;cccc:';xKXXXX0l:OXXXXOdx0KXXXKkc,';cl;...:kXXXKd;'';dKXXXXXXXXXXXXXXXXXXXXx,......'k
o.'dXXXXXXXXXXXXXXXXx,.:c'..:OXOd:',:::::,.,cxKXXO;'dXXXKxcok0XXKd,..cO0o,..'lKXX0l'.,,.:OXXXXXXXXXXXXXXXXXXXXO;......'d
o.'dXXXXXXXXXXXXXXXXd',x0l..c0Kl..;:'...,l:..:0XKd''dXXXk;.,ckXXk;..;O0l'....;kXKl..:kOdxKXXXXXXXXXXXXXXXXXXXXk,......'d
:.'dXXXXXXXXXXXXXXXKl.;OXd'.lKXk;.;;':xo,''..c0NKl.,xXX0c..,cxXXx'..'c:'.....,xX0c..;oodk0KXXXXXXXXXXXXXXXXXXKd'......,k
:..oKXXXXXXXXXXXXXXKl.,xX0doOXX0c...'oX0:....lKX0:.;kXX0:..,cxXXk;...........:OXXkc,''...,oKXXXXXXXXXXXXXXXXXXx,......'x
:..oKXXXXXXXXXXXXXXKo''lxOKXXXXKo'...:kx;...'oKXk;.;kXXKd;';:dKXKx;........':kXXXX0l;lo;..;kXXXXXXXXXXXXXXXXXKd'......,k
:.'dXXXXXXXXXXXXXXKd;...',dKXXXXd'....,,'',,ckXKd'.:OXXXKOkO0KXXXX0xl:;;;cox0XXXXX0c.co;.'oKXXXXXXXXXXXXXXXXXXx,......,k
l..oKXXXXXXXXXXXXXKOxc':xk0XXXXX0xxxxxxkkOO0KXX0c..:xxlcc::ldOXXXXXXXKKKKXXXXXXXXXXd,...'oKXXXXXXXXXXXXXXXXXXXO:......,k
:.'dXXXXXXXXXXXXXXXXXx;oXXXXXXXXXXXXXXXXXXXXXXXk;..''.....',;dKXXXXXXXXXXXXXXXXXXXXKklclkKXXXXXXXXXXXXXXXXXXXXO:......'x
c.,xXXXXXXXXXXXXXXXXX0xkXXXXXXXXXXXXXXXXXXXXXXXOl;,;:lodxxO00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;......,k
o.,xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk,......,k
c.'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx,......,O
l.'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx,......,k
d.'dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx,......;0
c..oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk,......;O
;..lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:......,k
;.'dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:......;0
c.'dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;......cK
:.'lOOO000kkOOkxkkkxxO00OOOOOOOOkxxxkkkxdxxkOkkkxkkkxxkOkkxdddxddkkkkkxdxxxkkdxdxxxxkxxxxxxxxooooooxxkxoxooxoox,......:K
c..'''',,,'''''..'...',,,''''''''...'''....'''''..'...'''.........''''.....'..........................................:0
Kdlcodoc;.............................................................................................................:K
MMWWWMMNo.............................................................................................................lX
MMMMMMMNd'.'....................................................................''.....................''....''..'''',dN
MMMMMMMMKxoxoooooolllll::cclxoxc:cccc::c:;xox:;cxlll:;;;cocxooxllcxoox::cc;;:cxoxxooxc:;;:odoccxdoxc:cxxxoxoxxxxxxxxkk*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.14;

import "../erc721a/contracts/ERC721A.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

contract Rektfolios is ERC721A, Ownable {
  using Strings for uint256;
  string private _baseTokenURI;
  uint256 public constant maxSupply = 10000;
  uint256 public mintLimit = 1;
  bool public minting = false;

  mapping(address => uint256) private _minted;

  constructor() ERC721A("rektfolios", "REKTFOLIOS") {}

  function mint(uint256 qty) external payable {
    require(minting);
    require(qty > 0 && qty <= mintLimit);
    require(totalSupply() + qty <= maxSupply);
    require(_minted[_msgSender()] + qty <= mintLimit);
    require(msg.sender == tx.origin);
    _minted[_msgSender()] += qty;
    _safeMint(msg.sender, qty);
  }

  function reserve(address creator, uint256 qty) external onlyOwner {
    require(!minting);
    require(totalSupply() + qty <= maxSupply);
    _safeMint(creator, qty);
  }

  function toggleMinting() external onlyOwner {
    minting = !minting;
  }

  function setMintLimit(uint256 qty) external onlyOwner {
    mintLimit = qty;
  }

  function setBaseURI(string calldata baseURI) external onlyOwner {
    _baseTokenURI = baseURI;
  }

  function _baseURI() internal view virtual override returns (string memory) {
    return _baseTokenURI;
  }
}