// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dreamy Isles
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//    A dreamy isle is a place of pure magic and wonder. Nestled in the azure waters of the ocean, this paradise is a true escape from the hustle and bustle of the modern world.                                                                                                                   //
//                                                                                                                                                                                                                                                                                                  //
//    As you step off the boat onto the sandy shores, you are immediately enveloped in the sweet scent of tropical flowers and the gentle sound of waves crashing against the shore. The air is warm and the sun shines brightly, casting a golden glow over everything.                            //
//                                                                                                                                                                                                                                                                                                  //
//    The landscape of the dreamy isle is like something out of a fairytale. Verdant forests, dotted with palm trees and exotic flowers, stretch out as far as the eye can see. Lush green fields, filled with all manner of fruit trees, stretch out between the forests and the sandy beaches.    //
//                                                                                                                                                                                                                                                                                                  //
//    As you wander through the dreamy isle, you are struck by the sheer beauty of it all. The air is filled with the sound of singing birds and the rustling of leaves in the gentle breeze. Every turn brings new wonders to behold, from sparkling waterfalls to hidden coves and lagoons.       //
//                                                                                                                                                                                                                                                                                                  //
//    At night, the dreamy isle comes alive with the sound of music and the glow of lanterns. Bonfires light up the beach and locals gather to dance and sing under the stars. It is a place where time seems to stand still and all your worries are left behind.                                  //
//                                                                                                                                                                                                                                                                                                  //
//    Whether you are seeking adventure or simply want to relax and unwind, the dreamy isle is the perfect place to find peace and tranquility. So come, let yourself be whisked away to this magical paradise and leave all your troubles behind.                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                    \||/                                                                                                                                                                                                                                                                          //
//                    |  @___oo                                                                                                                                                                                                                                                                     //
//          /\  /\   / (__,,,,|                                                                                                                                                                                                                                                                     //
//         ) /^\) ^\/ _)                                                                                                                                                                                                                                                                            //
//         )   /^\/   _)                                                                                                                                                                                                                                                                            //
//         )   _ /  / _)                                                                                                                                                                                                                                                                            //
//     /\  )/\/ ||  | )_)                                                                                                                                                                                                                                                                           //
//    <  >      |(,,) )__)                                                                                                                                                                                                                                                                          //
//     ||      /    \)___)\                                                                                                                                                                                                                                                                         //
//     | \____(      )___) )___                                                                                                                                                                                                                                                                     //
//      \______(_______;;; __;;;                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//    DDDDDDDDDDDDD                                                                                                                    IIIIIIIIII                 lllllll                                                                                                                           //
//    D::::::::::::DDD                                                                                                                 I::::::::I                 l:::::l                                                                                                                           //
//    D:::::::::::::::DD                                                                                                               I::::::::I                 l:::::l                                                                                                                           //
//    DDD:::::DDDDD:::::D                                                                                                              II::::::II                 l:::::l                                                                                                                           //
//      D:::::D    D:::::D rrrrr   rrrrrrrrr       eeeeeeeeeeee    aaaaaaaaaaaaa      mmmmmmm    mmmmmmm yyyyyyy           yyyyyyy       I::::I      ssssssssss    l::::l     eeeeeeeeeeee                                                                                                          //
//      D:::::D     D:::::Dr::::rrr:::::::::r    ee::::::::::::ee  a::::::::::::a   mm:::::::m  m:::::::mmy:::::y         y:::::y        I::::I    ss::::::::::s   l::::l   ee::::::::::::ee                                                                                                        //
//      D:::::D     D:::::Dr:::::::::::::::::r  e::::::eeeee:::::eeaaaaaaaaa:::::a m::::::::::mm::::::::::my:::::y       y:::::y         I::::I  ss:::::::::::::s  l::::l  e::::::eeeee:::::ee                                                                                                      //
//      D:::::D     D:::::Drr::::::rrrrr::::::re::::::e     e:::::e         a::::a m::::::::::::::::::::::m y:::::y     y:::::y          I::::I  s::::::ssss:::::s l::::l e::::::e     e:::::e                                                                                                      //
//      D:::::D     D:::::D r:::::r     r:::::re:::::::eeeee::::::e  aaaaaaa:::::a m:::::mmm::::::mmm:::::m  y:::::y   y:::::y           I::::I   s:::::s  ssssss  l::::l e:::::::eeeee::::::e                                                                                                      //
//      D:::::D     D:::::D r:::::r     rrrrrrre:::::::::::::::::e aa::::::::::::a m::::m   m::::m   m::::m   y:::::y y:::::y            I::::I     s::::::s       l::::l e:::::::::::::::::e                                                                                                       //
//      D:::::D     D:::::D r:::::r            e::::::eeeeeeeeeee a::::aaaa::::::a m::::m   m::::m   m::::m    y:::::y:::::y             I::::I        s::::::s    l::::l e::::::eeeeeeeeeee                                                                                                        //
//      D:::::D    D:::::D  r:::::r            e:::::::e         a::::a    a:::::a m::::m   m::::m   m::::m     y:::::::::y              I::::I  ssssss   s:::::s  l::::l e:::::::e                                                                                                                 //
//    DDD:::::DDDDD:::::D   r:::::r            e::::::::e        a::::a    a:::::a m::::m   m::::m   m::::m      y:::::::y             II::::::IIs:::::ssss::::::sl::::::le::::::::e                                                                                                                //
//    D:::::::::::::::DD    r:::::r             e::::::::eeeeeeeea:::::aaaa::::::a m::::m   m::::m   m::::m       y:::::y              I::::::::Is::::::::::::::s l::::::l e::::::::eeeeeeee                                                                                                        //
//    D::::::::::::DDD      r:::::r              ee:::::::::::::e a::::::::::aa:::am::::m   m::::m   m::::m      y:::::y               I::::::::I s:::::::::::ss  l::::::l  ee:::::::::::::e                                                                                                        //
//    DDDDDDDDDDDDD         rrrrrrr                eeeeeeeeeeeeee  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm     y:::::y                IIIIIIIIII  sssssssssss    llllllll    eeeeeeeeeeeeee                                                                                                        //
//                                                                                                             y:::::y                                                                                                                                                                              //
//                                                                                                            y:::::y                                                                                                                                                                               //
//                                                                                                           y:::::y                                                                                                                                                                                //
//                                                                                                          y:::::y                                                                                                                                                                                 //
//                                                                                                         yyyyyyy                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//    bbbbbbbb                                                                                                                                              bbbbbbbb                                                                                                                                //
//    b::::::b                                       hhhhhhh                                                                                                b::::::b                                                                                                                                //
//    b::::::b                                       h:::::h                                                                                                b::::::b                                                                                                                                //
//    b::::::b                                       h:::::h                                                                                                b::::::b                                                                                                                                //
//     b:::::b                                       h:::::h                                                                                                 b:::::b                                                                                                                                //
//     b:::::bbbbbbbbb yyyyyyy           yyyyyyy      h::::h hhhhh          ooooooooooo   nnnn  nnnnnnnn        eeeeeeeeeeee  yyyyyyy           yyyyyyy      b:::::bbbbbbbbb                                                                                                                        //
//     b::::::::::::::bby:::::y         y:::::y       h::::hh:::::hhh     oo:::::::::::oo n:::nn::::::::nn    ee::::::::::::ee y:::::y         y:::::y       b::::::::::::::bb                                                                                                                      //
//     b::::::::::::::::by:::::y       y:::::y        h::::::::::::::hh  o:::::::::::::::on::::::::::::::nn  e::::::eeeee:::::eey:::::y       y:::::y        b::::::::::::::::b                                                                                                                     //
//     b:::::bbbbb:::::::by:::::y     y:::::y         h:::::::hhh::::::h o:::::ooooo:::::onn:::::::::::::::ne::::::e     e:::::e y:::::y     y:::::y         b:::::bbbbb:::::::b                                                                                                                    //
//     b:::::b    b::::::b y:::::y   y:::::y          h::::::h   h::::::ho::::o     o::::o  n:::::nnnn:::::ne:::::::eeeee::::::e  y:::::y   y:::::y          b:::::b    b::::::b                                                                                                                    //
//     b:::::b     b:::::b  y:::::y y:::::y           h:::::h     h:::::ho::::o     o::::o  n::::n    n::::ne:::::::::::::::::e    y:::::y y:::::y           b:::::b     b:::::b                                                                                                                    //
//     b:::::b     b:::::b   y:::::y:::::y            h:::::h     h:::::ho::::o     o::::o  n::::n    n::::ne::::::eeeeeeeeeee      y:::::y:::::y            b:::::b     b:::::b                                                                                                                    //
//     b:::::b     b:::::b    y:::::::::y             h:::::h     h:::::ho::::o     o::::o  n::::n    n::::ne:::::::e                y:::::::::y             b:::::b     b:::::b                                                                                                                    //
//     b:::::bbbbbb::::::b     y:::::::y              h:::::h     h:::::ho:::::ooooo:::::o  n::::n    n::::ne::::::::e                y:::::::y              b:::::bbbbbb::::::b                                                                                                                    //
//     b::::::::::::::::b       y:::::y               h:::::h     h:::::ho:::::::::::::::o  n::::n    n::::n e::::::::eeeeeeee         y:::::y               b::::::::::::::::b  ......                                                                                                             //
//     b:::::::::::::::b       y:::::y                h:::::h     h:::::h oo:::::::::::oo   n::::n    n::::n  ee:::::::::::::e        y:::::y                b:::::::::::::::b   .::::.                                                                                                             //
//     bbbbbbbbbbbbbbbb       y:::::y                 hhhhhhh     hhhhhhh   ooooooooooo     nnnnnn    nnnnnn    eeeeeeeeeeeeee       y:::::y                 bbbbbbbbbbbbbbbb    ......                                                                                                             //
//                           y:::::y                                                                                                y:::::y                                                                                                                                                         //
//                          y:::::y                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DREAM is ERC721Creator {
    constructor() ERC721Creator("Dreamy Isles", "DREAM") {}
}