// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: TRIPS
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                          ..                                                                                                                                                                                                               ....               ........                              //
//                                          ..                                                                                                                                                                                                                    ....             .........                          //
//                                        ...                                                                                                                                                                                                                       ....            .........                         //
//                                                                                                                                                                                                                                                                    ....            ........                        //
//                                    ..                                                                                                                                                                                                                                ....           .........                      //
//                                                                                                                                                                                                                                                                        ....          .........                     //
//                               ..                                                                                                                                                                                                                                         ....         .........                    //
//                              .                                                                                                                                                                                                                                             ....        ..........                  //
//                           ..                                                                                                                                                                                                                                                 ....       ..........                 //
//                          .                                                                                                                                                                                                                                                     ....     ...........                //
//                                                                                                                                                                                                                                                                                  ....    ...........               //
//                                                                                                                                                       ............                                                                                                                 .....  ...........              //
//                                                                                                                                                  ...';clooooollllc::,..                                                                                                              .................             //
//                                                                                                                                           .....,;:cloooooooooooooooool:'.                                                                                                             .................            //
//                                                                                                                                  ........',;cllooooooooooooooollllllloll:'.                                                                                                             ................           //
//                                                                                                                       ...'.''',,;::cclllloooooooooooollllllllccccllllllllc:,..                                                                                                            ...............          //
//                                                                                                                ...',;:ccllllooooodddooooooooollllllllllccccccccc::::::ccclollc:;;,,'.............                                                                                            .............         //
//                                                                                                        ...',,;:clooooddddddddddddddoooooolllllllccccccc:::::::::::::::ccclooooooooollllllcccc:::;;,,''....                                                                                    .............        //
//                                                                                                   ...';:cclooooddddddddddddddddoooolllllccllccccccccccc::::::::;;::cclllloodooodoooooooooooooollllllccc::;,,'....                                                                               ...........        //
//                                                                                           ....',;;:cllooooooooooooooooooodooooolllcclcc::::::ccccc::cccccccccccccccccllllloooooooddddooooooooollllllllllllccc::;,''....                                                                           ..........       //
//                                                                                        ..,;:cccllloooooooooooooooooooooooollllccccccc::::::;;:cc::cccc:::ccc::cllccccllllllloooooodddoooooooooooooolllllllllcccccc:::;,,'...                                                                       ..........      //
//                                                                                      .',;clllllllooooolllloooooooooolllllcccccccc:cc:::;;;;::::::::::::cc:ccccclllccllllllllllllloooooooodoooooooooolllllllllllcccccccc::;;,'...                                                                     .........     //
//                                                                                   .';:ccclllllllooooooooloolllooollclccccc:c::::::;::::;;;;;;;;::::::::::ccccclllllllllllllllllllooooooooooooooooooollolllllllllllccccccc:::;;,''..                                                                   ........     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TRIPS is ERC1155Creator {
    constructor() ERC1155Creator("TRIPS", "TRIPS") {}
}