// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Meet Me on Film
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    N0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX    //
//    x:ooooooooooolllllllllllllllllllllllll'.;oooooooooooooollllllllllllllllllllllc' 'looooooooooooooooooollllllllllllllll;.d    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.o    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.o    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.o    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.o    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.d    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.d    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.d    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx'd    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'd    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'd    //
//    xxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'd    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'x    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,x    //
//    xxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,x    //
//    kxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,x    //
//    kxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,k    //
//    kxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;k    //
//    kdKKKKKKKKKKKKKKKXXXXXKKKKKKKKKKKKKKKK: lKKKXXXXKKKKKKKKKKKKKKKKXXKXXKKXXXXXXKc ,OKKKKKKKKKKKKKKKKXXKKKKKKKKKKKKKKKKKo,k    //
//    0oooooooooooooooodxdddoooooooooooooodol:loodxkxddddddddddddddddddddddddxkxxxddlclododddodoooooooooxkxddddddddddddddddooK    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MFILM is ERC721Creator {
    constructor() ERC721Creator("Meet Me on Film", "MFILM") {}
}