// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Provenance
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    Honestly guys, I've had enough of this crap. Where’s the transparency from the team I mean the floor is dropping and not a single word. Just rug me already. I can’t stand losing my money any longer. If this persists I will take legal action. Id like to inform you that my dad is a lawyer, and a good one at that. Top 10 in the country. You don’t want trouble devs. The SEC is already  taking a peek at this project. I can stop this as long as devs do something    //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Reacting to messages with a clown (🤡), a skull (💀), or a nerd face (🤓) isn't funny. It's not cool, it's not interesting, it's annoying.                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    These 3 emojis in particular aren't funny, they're RUDE. We as staff work hard to keep this place safe, and to have you all constantly react to our messages with mean emojis makes me FURIOUS.                                                                                                                                                                                                                                                                                 //
//    STOP reacting to our messages with rude emojis. They do NOTHING but make you look really, really stupid.                                                                                                                                                                                                                                                                                                                                                                        //
//    It shows you have no rebuttals to our arguments, so you have to use juvenile tactics paramount to terrorism in order to stop us from being able to speak our truth.                                                                                                                                                                                                                                                                                                             //
//    FROM NOW ON, IF YOU REACT WITH ANY MEAN EMOJIS, I AM WRITING YOUR NAME DOWN.                                                                                                                                                                                                                                                                                                                                                                                                    //
//    IF YOU ARE A SERIAL REACTOR, YOUR USERNAME IS GOING TO A GOOGLE DOC. AT THE END OF THE MONTH, I WILL TAKE THIS DOC TO THE APPROPIATE AUTHORITIES FOR THEM TO INVESTIGATE AND ARREST YOU.                                                                                                                                                                                                                                                                                        //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    This has been quite hectic for the past 24 hours, trying to run a project and blow up way out of proportion. None of us has ever had any web3 experience in terms of running a project and therefore it's quite hard to get used to new circumstances.                                                                                                                                                                                                                          //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Can I just say we are glad to everybody who didn’t meant because the price was too high but now we have to listen to you cry when all we want to do is just say goodbye but yeah you are sticking around like a bad smell and we don’t know why                                                                                                                                                                                                                                 //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    hi. i dont wanna sound like a fudder its just i want to ask how the floor is so cheap compared where it was. i didnt really follow the project but i was following the minting process and i remember how hyped it was. now that the floor is not that high I'm thinking about buying in. Ofc I will do my own research but I would like to hear some feedback how things are and how the floor turned this low.                                                                //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    You belittle my success and achievement over the past two years, scratch that my entire life, and then tell me to stop talking about it with you or anyone else???  My OWN family can’t handle who I am, let alone the degens on social media. -Anon                                                                                                                                                                                                                            //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Thanks to the team for making sure the ones with BOTS steal my transaction!! How come I got the message “Transaction complete”, party confetti, view on OS and seconds later it said transaction failed?! Can you please explain that to me??? I was so excited, ready to view it and nothing! What a disappointment!! I posted the screenshots on my Twitter                                                                                                                   //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    I am not yet sure of how my account was compromised. I have two prevailing theories, both are, to my mind, highly unlikely. One is an insider at Twitter being involved; this was my immediate reaction, and while still possible, I don’t consider it an especially high likelihood. The other is a phishing attack on me where I gave access to an attacker to the extent that they could bypass my Google Authenticator 2FA. -Zeneca                                         //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    I’ve decided to make a pivotal investment towards my future. I’m ready to be the change throughout multimedia, entertainment, and Web3. BUT I promise it’s not for the profit. This is about securing a feeling of ownership, that what we build together will also define my legacy. -Anon                                                                                                                                                                                     //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Hey mate, i just searched your ERC20 address on etherscan, I saw your trading history and was wondering if you are trying to be the first on-chain clown or something                                                                                                                                                                                                                                                                                                           //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    This Moonbirds CC0 announcement has single-handedly ruined my life. I had just negotiated a deal for $1 million, and now the deal is canceled and my wife has left me. I expect compensation                                                                                                                                                                                                                                                                                    //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    If everyone had to package up and ship 📦 every Doodle or Cryptodickbutt they sold, then NFTs would never last. The incredible ease & blockchain verification makes the MP work                                                                                                                                                                                                                                                                                                 //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Actually not even joking when I say I probably have a similar picture in a similarly dumb shirt with a similar stature at that point in my life. I, however, grew up to be a desk jockey just like you'd expect that kid to                                                                                                                                                                                                                                                     //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    Honestly guys, I've had enough of this crap. Where’s the transparency from the team I mean the floor is dropping and not a single word. Just rug me already. I can’t stand losing my money any longer. If this persists I will take legal action. Id like to inform you that my dad is a lawyer, and a good one at that. Top 10 in the country. You don’t want trouble devs. The SEC is already  taking a peek at this project. I can stop this as long as devs do something    //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    If you are rocking a PFP under $100k plz don’t @ me or share your opinion on my wall.  I don’t care what you have to say. Reality is you need to Work harder, move out of your moms basement, stack eth/sol, buy a few real PFP then share your opinion.                                                                                                                                                                                                                        //
//    --------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    gm you stupid fucks pls quit crypto for good                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Final is ERC721Creator {
    constructor() ERC721Creator("Provenance", "Final") {}
}