// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: moment of earth and stone
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//    bronze ancient coffin "clang" sound hit the top of Mount Tai, immediately the mountain are a shaking, as if an earthquake, a lot of rocks rolling down, a loud noise.                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//    On Yuhuangding, countless people are running down the mountain.                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//    "Brush!"                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//    Golden figure flashing, Yang Hao look excited, he directly rushed to the top of the mountain, the body of the golden horn giant animal suspended in the air, broken golden eyes staring at the bottom of the nine dragon corpse and open a corner of the ancient bronze coffin, revealing the color of joy.    //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MOEA is ERC721Creator {
    constructor() ERC721Creator("moment of earth and stone", "MOEA") {}
}