// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: LUCY EIGHTOWLS
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
//                                                                                             ~G#J.                                                                                          //
//                                                                                         .Y&@@B#@@B~                                                                                        //
//                                                                                      [email protected]@@&5 .~5&@&7                                                                                      //
//                                                                                    [email protected]@@&GJ7! .:[email protected]&^                                                                                    //
//                                                                                  [email protected]@&B5?P!P^ .!#5 :[email protected]&!                                                                                   //
//                                                                                [email protected]@&YJ5B&B#P    [email protected]@^                                                                                  //
//                                                                               [email protected]@&?!JGG&#B#G?7~^?5B#[email protected]                                                                                  //
//                                           .^                                ^@@&Y??P5!~:::::^~~~^[email protected]&&#&@:                                                                                 //
//                                          !&@&#BBBGGY^.                     ^G&J^J?~.:7YG&&@&@@&#B~:~PBGG&&~                                                                                //
//                                         [email protected]@&&#&@@&&&&&&&BY:              [email protected]@? J~^[email protected]@@@@@@@@@@@@@@P:!?7G&#                  ..:~!~!!7777777!^.                                            //
//                                         [email protected]&J:^5!!7!PGYY5B&&&G~          [email protected]@[email protected]@@@@@@@@@@@@@@@@@@@?!:Y?&             .!5B##&&#####GB&&&&&@@@#G.                                         //
//                                        [email protected]@#^ :5PG&#&&#P7!7!?G&&J.       [email protected][email protected]@@@@&P7JY5Y?#@@@@@@@B!~:[email protected]?         :!P&&&&5PGPBBG#&7JBGGB&BJ&@@P                                         //
//                                        &@&J..~JP#@@@&#BYJGGJ?YJYGG~    ^@P ?~7#&&@@&!.   ... .~&@@@@@@5: !#&     :YB##&&B55BGJ7JPPB&###BGG&@B [email protected]@G                                         //
//                                       [email protected]@B~.~YGB&&BY7~.^JY!!??~:.~JB~  [email protected]&[email protected]&~..: .!77~. [email protected]@@@@@&. ^7&   ^B#BGP55G:.^::^^:..!YJPG!^?#@[email protected]@P                                         //
//                                       [email protected]&J .!P&P!::!G#&@@@@@@#B#5~  ^~7&..!Y#&&&&&^.?!7   7J?^  [email protected]@@@@&. .^# .?PG?7^:?&@&&@@@@@@#!~~. 5Y7##Y!JG&@B                                         //
//                                       [email protected]&~  ^#B :[email protected]@@@@@@@@@@@@@@#P! ~#Y ^[email protected]@&&&@G .^5&^::[email protected]  J#@@@@P.  :&J~.7?G&#[email protected]@@@@@@@@@@@@@@~ ~P#&Y!?P#@@!                                        //
//                                      [email protected]@#^  7B.~&@@@@@@&GPB&@@@@@@@@Y     &@@&#&@G  G&&JJY&@&. .&@@@@@P   .?. [email protected]@@@@@@@@@@@@@@@@@@@&7 :[email protected]@~                                        //
//                                      [email protected]@G..:J~^@@@@@@&Y!    [email protected]@@@@@&Y    [email protected]@G5&&#  5#@@@@@&: :?#B#&@@: .:: ^Y&@@@@@@&GGBBPJ?J&@@@@@@@@5 BJ:~5Y&@Y                                         //
//                                       [email protected] ^[email protected]@@&5!~J7:.~:  !GG&@@@@Y ~. [email protected]@##&&?:!7:^~~^J~!~PJ7#@@~ :~: [email protected]@@@@@@B~  ...    [email protected]@@@@@@@[email protected]@^                                         //
//                                       [email protected]?#[email protected]~: .YPY#PGYG. JG&@@@@# .J: J&GJP&#G5~~!^^^~!??!?#@&! 7&Y ~&@@@@@&!   ..^!..:  ^&@@@@@@@P:B5!^[email protected]@:                                         //
//                                       [email protected]&?G5^&@@B.  Y#Y..~P7B7 ~Y&@@@@5 [email protected]~ [email protected]#BGP#B&&&&[email protected]@7 [email protected]:@@@&@@@? :77G5~   .^:[email protected]@@@@@@&B!.:[email protected]@?                                          //
//                                       [email protected]#?G:[email protected]@@@. .B&@7 :?.#&:[email protected]@@@@J :J&&[email protected]&Y77!!G#BY~5&#&G^..:[email protected]? [email protected]&&&#^.&@@@Y   ~5Y! [email protected]@@@@@&?G:^[email protected]@P                                           //
//                                       .&&!P~#@&&@J ^Y5BGGBJG&&57B#G&@@: :[email protected]^ ..^P#BG#&&#PYB#?^^[email protected]#. [email protected]&&&&^[email protected]@G:..!#Y?  [email protected]@@@@@GPP7Y&@B                                            //
//                                        [email protected][email protected]@@@@J.:5GGBG7^.:7#@[email protected]@!  [email protected] .^^::::~7~:.:~^^YGJ?&@#J~~ [email protected]@@&&&B::^5B5!JG&B~7..J&@@@@&G!:?#@@:                                            //
//                                         [email protected]!^J&@@@@&J~^^^:!~^[email protected]! :J:[email protected]@@^ :G&Y!^^:^~!5&##[email protected]@@^.P~:7#&&&B&&^.^  .~!??!~~??5&&@@&G^.!#@#.                                             //
//                                          #@7:[email protected]&&@&#BB##GY&&G##P&&5^[email protected]@B.^[email protected]&P7!?J#&&#[email protected]#: 7GP7^JB#7Y&&&7:^7#&P.:!5BP5GB&@#Y::[email protected]                                               //
//                                          [email protected]~7~Y&#B&@@@@&@@B!7#@@5. ~5^[email protected]&^[email protected]@@@&&&&@@@@&&~^@&:!.~&#!:?P&Y?5#&&BG&@@@#GYGBGG&@&Y^.^[email protected]@#                                                //
//                             .^!5GGGGP555YYBJ.   :5B&@#[email protected]&[email protected]@#~.:^~~Y#&#Y^#@#[email protected]@@@@@@@@@@@G.#&[email protected]&JGG5!:~YG&P&@&&&&&&#&&@@&@@&Y:.~:!BBB#&&&&&&&##B!^:.                                  //
//                           ^[email protected]@@BJJ~:::. .^7?~ .... .?PY5J?!!^!JJPGBGB&@@@@@&~#&[email protected]@@@@@@@@@@@@5!P^&@@@@@@@&G?7^YPP5JB&&&##&&&#5!^. .~!:....:~~!!7777Y#&@@@&G7:                              //
//                       .?G&@&5!^::7Y5!:7J~:.:.  .57&BBP^   .^YPY&@@@@@@@@@@@@#J5#@@@@&@@@@@@@@Y7!&@@@@@@@@@@@#J^::!?7??!^.....~YPY^.^!JGBBBG5J7~~^^^~!J55PB&&@&GY!:.                        //
//                      [email protected]@@#J:  .^[email protected]@&&@@&#[email protected]@@&J~:. :[email protected]@@@@P5&@@&GY&&@@@@&[email protected]@@@&&#@&#@@@@@@@@##&@@@&5?!?~^~?YGPG#&@#!..~5&@@@@@@@@@@@&P!7Y!!?5B###B#&&@@&#!                      //
//                    7&@@B~....!GP~J&&@@@@@@@@@@@&5^ ~JPPG??#B^.^[email protected]@@@@@#&@@PPBGP#[email protected]@@@@@@[email protected]@GB#@@@@@@&@@@@@@@@&P!~Y&@[email protected]@@&7 .J&&&&&&&&@@@@@@@@@PYY!!?YP&&#PYPGB#B&&Y.                    //
//                 [email protected]@@&?^~^:^PG^J#@@@@@@@@@@@@@@@@@B  ^[email protected]@@[email protected]@@@@@@B5&@@@@&B&&&@@@&B&@@&[email protected]@@@@@@@@@@@@@&P!5&@@@#GY: [email protected]&&BP#&&@@@@@@@@@@@@@@[email protected]@&P#&&#P?G&&G.                  //
//               [email protected]@&P!77J&#5J#[email protected]@@#J~::^^^~7P#&@@&@B. ^~B#&@@@@@[email protected]@@@&@@@P&@@@@@@@#~BG&@@@@@G^[email protected]@@#&B#[email protected]@@@&#&&&&BGYY?~.7&@&J?GGJ7^^:.....~5&@@@@@@&. J5&@@&@@7:~7GG#@&!                 //
//               [email protected]@B~.  :~^[email protected]@&!...:!5~7G? .7G&&@@#: ^^...7JYG&B5#@5B#[email protected]@&@BPY7:::[email protected]@@@BB&#&&@[email protected]@P!7~J~. :!^::::.  [email protected]@@@@B .5B&&&&5~5#G?^^&@@G.               //
//                [email protected]@GJ:.~77JB5 [email protected]@&!  .?PG&[email protected]#..?P&[email protected]#::^^~:7?:5G5PP#B5?Y#BG&P!:           .:!7~G##@@@@@&[email protected]@&&&@@@@&#G!::P&^[email protected]^~ [email protected]@&#BGG5^.  [email protected]@@@@B~:BY7YG5GBB5!:7&@@@Y               //
//                 [email protected]@@[email protected]@@[email protected]@@@J .PY5JJYBG&[email protected]@J.7?~^B&B&@@&Y#[email protected]@@@#BJ?:               . !#&&@@@&Y&@@@@@@@@@&B#P!7&&GG#B7:[email protected]@@?J:   .... [email protected]@@@@@G7#?~!PG55GB##@@@@&.               //
//                                                                                                                                                                                            //
//                            '||'      '||'  '|'   ..|'''.| '||' '|'    '||''''|  '||'  ..|'''.|  '||'  '||' |''||''|  ..|''||   '|| '||'  '|' '||'       .|'''.|                            //
//                             ||        ||    |  .|'     '    || |       ||  .     ||  .|'     '   ||    ||     ||    .|'    ||   '|. '|.  .'   ||        ||..  '                            //
//                             ||        ||    |  ||            ||        ||''|     ||  ||    ....  ||''''||     ||    ||      ||   ||  ||  |    ||         ''|||.                            //
//                             ||        ||    |  '|.      .    ||        ||        ||  '|.    ||   ||    ||     ||    '|.     ||    ||| |||     ||       .     '||                           //
//                            .||.....|   '|..'    ''|....'    .||.      .||.....| .||.  ''|...'|  .||.  .||.   .||.    ''|...|'      |   |     .||.....| |'....|'                            //
//                                                                                                                                                                                            //
//                           [email protected]@&?5JYJY&@@@@@@@@&&B?^~.~^5#&&&&&@@&GJB&@@@@@@@&J~J~:.         ~JP5Y^!Y75B&&@&@&Y#@&@@@@@@@@@&7. .. ......:...:^^~~~!^^?G&@@@#5!.                              //
//                            [email protected]@BY7J?:~Y?PPBP7^..^75!:[email protected]@@@&#P5P5B&@@@@@@@@@@@5!P#GP?!^. :^~~:&#[email protected]@@@@@&&@@&&&&#Y5PG##&@@&&#&&&BY~.   :^::^^~J5PG&@@@#!                                   //
//                             .^!?#@&?:       :[email protected]@BYPYJJ~.  [email protected]@&#&@@@@@@@##7B&&&&B55575?G##G#@&#@@&&@@@@@PY&@@&&Y::^^:~?JYYJ7!~~^.     [email protected]@@&#GY7^                                      //
//                                  .J&&P7:  .::~^^^::.      :!&JP&@@P##&@@@@@@Y&[email protected]@@@@@@@@&[email protected]@@@@@&B#@GB&@@@@@@@@BJPY5!....Y#B#&#BP?^:.  .^..7BY                                            //
//                                     [email protected]@7 ..    ~P#&&B?7^ .~!5J:[email protected]@P~7&@[email protected]@@@@[email protected]@@@@[email protected]@@@[email protected]@@@&?~JPBGGB&&&###&&&@@@@@&5^.    ^57                                          //
//                                     [email protected]~~~^:!#&@@@@@@@@@&&GJ^[email protected]@&G&@@@@@@@@P&@@@@#@@&#&@@@@@@@@@@@@@@@@@@@&GPYG&&GJP55&&##&&&&@@@@@@@@&P^  .:7G!                                        //
//                                   .J#?!7^:5&@@@@@&&&&&@@@@@&#@BJ7&@@@@@@@@@@G&[email protected]@@@@@@@G#@@G&&55G&@@@@@@@&&@[email protected]@&P77YBPGG#&&&&&@@@@@@@@@@@@B^^BP~JG:                                      //
//                                  [email protected]&J.:~^[email protected]@@@@&@&&###&G&@@&[email protected]&GY5Y5B&[email protected]&[email protected]@@@@@@@@@@@@@@&[email protected]&G&@@@@&&&[email protected][email protected]@@@@@@@@Y:!&G.:P5.                                    //
//                                 .&@#^[email protected]@@@@@@B7.:^::^[email protected]@&???!~7^!:7&@&Y&@@@@@[email protected]@@@@[email protected]#!#@@@@&[email protected]#~J~!?!^~7?&&&@@@!   .Y&@@@@@@@#[email protected]::[email protected]^                                   //
//                                 [email protected]@5:[email protected]@@@@&^  ^5#J.   ^?.5&&&@&?!^7?^^[email protected]@Y^#&@@@@@@&@@@@@@@@[email protected]~!JYY?^[email protected]~B&Y.  [email protected]?5G#@J7 .. :&@@@@@@@?5#&&.^!&&:                                  //
//                                .#@&:!BY [email protected]@&#&^   J##B57!!?Y!7B&&@@5  !J [email protected]@@@:[email protected]&&@@@@@@@@@@@@@@@^[email protected]@5^^~^!&#^5#&B~ .BP^5J^ .^?P:   :&@@@@@@@^YY~B7 JJ&@^                                 //
//                                [email protected]@&7?PG [email protected]@@@#.  ~!#@5YJYGB!^~!P?Y&&:   .&@@@Y !Y&&&&&@@&&&&##&@@@^:@@##~  [email protected]!&B#B: .#B#&@G.  .:.    [email protected]@@@@@@:PY..7:[email protected]@.                                //
//                                 #@&~75G:[email protected]@@@&^ ^G^7:   7&G. :[email protected]@&@@@?  [email protected]@@B  ^7Y7!!?YJPGBBP5YBG5~ 7&&@@^ [email protected]&G&#&#G7 [email protected]@@@@BG^.:.   [email protected]@#??B5^&?  ^[email protected]@G                                //
//                                [email protected]@B!?5#~:@@@@@#7:Y5:  .Y&&&#..7&@@@@@P .&@@@^  ~~J5PB#55##PPY#@@&&Y! :#@@&: [email protected]&&&&&&@5 :PBG7GG!..^^~J&@@@&BG!?PB~..~JBBP&@@:                               //
//                                [email protected]@BJB#B^ [email protected]@@@@G^... ~~Y5&@@:.~#@@@@@B !&@&:  .G&@#G5GJ77?J7~P##&&&@#..!Y#&  #@PB&&##&&J!BBP&P?JP&@@@@@@@@B7?BY~:::~7P#[email protected]@~                               //
//                                [email protected]@#PB&[email protected]@@@@Y:   !!J^5G~ [email protected]@@@@& [email protected]@B   [email protected]&?J#&&P!?7~7Y#&&&&#&&&#J..J~ .G&&&&&&&@@@@@@@@@@@@@@@@@&&G7!#B7.   :^[email protected]@J                               //
//                                [email protected]@&YG&[email protected]@@@@@P7~::J5^.?&@#&@@@@@! 7&#7 [email protected]&BGB5GB~...::!YPB#@&&#&@@B: .   ^P#BB&@@@@@@@@@@@@@@#G#&##BBY5G5!:~~!!:  [email protected]@&                               //
//                                [email protected]@#5P&@&&[email protected]@@@@@@@@@@&&@@@@@@@@@@?  YG^  [email protected]&&5.!^ Y!~?JB5G?7B&&&&@@@@~    .^5P?GG&&@@&&&&#&&5^:7BG!~~!??YGPP#@@@&Y:^[email protected]@!                              //
//                                [email protected]@#5.^&@@B5P!^[email protected]@@@@@@@@@@@@@@@@@@G   7.. [email protected]@P!B#Y5P ~GBG???#@&[email protected]@@@@@@&   .B&&&&B!.^!7JY5GGGBBB##BY~..^7PBB#&&&@&@@@&&@@&                              //
//                                [email protected]@@&~.YG7  !PP7.~BB&@@@@@@@@@@@@@B~   .. . [email protected]@@GY&#57~5BBY :!&BP!  &@@@@@@@~  [email protected]@@@@@@#J77~7JPGB#&&&&&##GG##&&&&@@@@@@@@@@@@@.                             //
//                                :[email protected]@@5^.  :5P^~5PJ?~:5G&&&&#&@@@&Y^..^J#...:[email protected]@#[email protected] :[email protected]&5  :@7 ^  [email protected]#Y7JG&7 :J&:  ~PGB#&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&BPY?                              //
//                                  [email protected]  :~5Y^[email protected]@&5G??5JYJJYY?: ^J#BG&. [email protected]@&#@:   5&JJ  ^B~    ~7~75G57^.7?G          ..:~~~!!!~~~~7JPGGP5Y5Y!^....                                    //
//                                  &@PY7~?~:...!Y?5#PBY!YBJ!77!^^7#@B!  &: Y&.JP#@@@P^  ^J5!  !5.  .^~PBBGP5P5^^P&.                                                                          //
//                                 [email protected]@@@@&#GJJ5BBPYP#5!7YJ!!5B#&&B~.    &B~55 [email protected]@@@@#?!:.   .  ?BJ#B#BBG?~G&[email protected]@:                                                                          //
//                                   .~7?5&@@&@@@@@@@@@@@@@@&PY?^        [email protected]?Y:  :[email protected]@@@@&J.75!^.G&[email protected]@#5B&@@&&@G                                                                           //
//                                         ..  ^~~~~~~??7~~:              [email protected]&.  ^BBY55#@@&@&#&@&##5?YP#BJ#&@@@#[email protected]@.                                                                           //
//                                                                        !&@G?:~Y7.5GJ!?JY&BG57Y57YYJGB&@@@@#~#@^                                                                            //
//                                                                          [email protected]@&#P:.!GGBP5GBGBBPGY?Y#@@@@&@@JP&@~                                                                             //
//                                                                           ^#@@&^.7#!?J^B&PY?J!:#@@@@@@@@[email protected]@J                                                                              //
//                                                                             ^[email protected]@GGG.^[email protected]@#J~:..B&@@@@@&[email protected]@5                                                                               //
//                                                                               [email protected]@@@G7:7P#B!:.. [email protected]@G                                                                                //
//                                                                                ^Y#@@@&&5B7  [email protected]@@?                                                                                 //
//                                                                                   .5&@@@@#J!^.  [email protected]@@#.                                                                                  //
//                                                                                      .?#@@@@&[email protected]@@@P                                                                                    //
//                                                                                         .7B&@@@@@@@@B^                                                                                     //
//                                                                                             :P&&&#Y.                                                                                       //
//                                                                                                                                                                                            //
//                                                                 .|,   .__..__ .___.  .  .._..   .     .__ ._. __..___  .|,                                                                 //
//                                                                 -*-   [__][__)  |    |  | | |   |     [__) | (__ [__   -*-                                                                 //
//                                                                 '|`   |  ||  \  |    |/\|_|_|___|___  |  \_|_.__)[___  '|`                                                                 //
//                                                                                                                                                                                            //
//                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract EIGHTOWLS is ERC721Creator {
    constructor() ERC721Creator("LUCY EIGHTOWLS", "EIGHTOWLS") {}
}