// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Lindos Editions
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMWWNKK00000KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:;;;;;;;;;;;;;cokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc,,;ldk0KXNNNNXXK0koc;,;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc',ckKWMMMMWWWWWWWWWMMMWN0d;';dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.;xXWMMMMMMMMMMMMMMMMMMMMWMMW0l',xNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.;kNMWMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMW0,.oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNx.,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWO'.xWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWMK,.xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.:XMWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWMWl.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMK,.kMWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWM0'.OMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.oWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWMk.;XMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.cNMWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWMk.;XMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.lWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWMK,.OMWMMMWMMMMMMMMMMMMMMMMWXOdooxKWMMMMMMWMX;.xMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWl.lWMMMWNWMMMMMMMMMMMMMKko,,:cc''dNMWMMMMWx.;KMWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMd.:NMXd;,:OWMMMMMMMMMMWkc:ldc;x0,.kMWMMWM0,.kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMW0,.kWMO.   :XMWMMMMMMMMMWW0:.;xXNc.dMMMMW0,.dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWO,.xWWMNkc:l0WMMMMMMMMMMMMWk,.:KM0'.OMWMNk'.xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMO''kWMMMMMMWMMMMMMMMMMMMMMMMWNOkXO,.dWMW0:.;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWx.;KMMMMMMMMMMMMMMMMMMMMMMNK0O0xc.,kNMNd.'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWMXo',clxXMWMMWMWXNMMMMMMMWMKkl;;;ckNMWMWd.;KMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWXo..cKWWMMW0c'dWMMMMMMMMMMWNNWWMMMMWMNl.:XMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWMO..kXXKOo:',xNMMMMMMMMMMMMWWMMMMMMMWMNl.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNx;''',;:oONMMMMMMMMMMMMMMMMMMMMMMMMMMNd.,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWNo.,kKXWMWMMMMMMMWMWK0XNMMMMMMMMMMMMMWk''xNMWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',,'xWMWWWWMMWNkc.:OXMWMMMMMMMMMMMMW0;.cKWWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0d'.o0XXXKOxc,',.:kKMWMMMMMMMMMMMMMMNd''lKWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWKo;,;;;;;:lxKXl..lNMWMMMMMMMMMMMMMMWXd,.oXMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK00KNWMMWM0, .OMWMMMMMMMMMMMMMMMWMXo.,kWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWMMMMMWl..oWMMMMMMMMMMMMMMMMMMMWO,.dNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd..cNMWMMMMMMMMMMMMMMMMMMMK;.dNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx'.:NMWMMMMMMMMMMMMMMMMMMWM0,.kWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNl..oWMMMMMMMMMMMMMMMMMMMMMMWk.,KMWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk. '0MWMMMMMWWWWMMMMMMMMMMMMMNc.oWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'':kWMMMMMWMXlcKMWMMMMMMMMMMWMO.,KMWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNo.;0WWMMMMMMWMNl.lNMMMMMMMMMMMWMX:.xMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNl.:XMWWMMMMMMMWM0'.OMWMMMMMMMMMMMWd.cNMWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.;KMWMMMMMMMMMWMNc.dMMMMMMMMMMMMWMO.,KMWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMK;.kMWMMMMMMMMMMMMWl.oWMMMMMMMMMMMWMK,.OMWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWM0''0MWMMMMMMMMMMMMWl.oWMMMMMMMMMMMWMX;.xMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMK,.OMWMMMMMMMMMMWMNc.dWMMMMMMMMMMMWMNc.dMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMK,.OMWMMMMMMMMMMWMWl.oWMMMMMMMMMMMWMNc.dWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMK,.kMWMMMMMMMMMMMMWo.cNMWMMMMMMMMMWMNc.dWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMX;.kMWMMMMMMMMMMMMMk.;XMWMMMMMMMMMWMNc.dMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LME is ERC721Creator {
    constructor() ERC721Creator("Lindos Editions", "LME") {}
}