// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: lul
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//         ______      __           __                                                                                                                          //
//        / ____/___ _/ /_____     / /   ____  _________                                                                                                        //
//       / / __/ __ `/ __/ __ \   / /   / __ \/ ___/ __ \                                                                                                       //
//      / /_/ / /_/ / /_/ /_/ /  / /___/ /_/ / /__/ /_/ /                                                                                                       //
//      \____/\__,_/\__/\____/  /_____/\____/\___/\____/                                                                                                        //
//    0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK00KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'...;lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,'.lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  .   ..,cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOd:'       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    ...    .'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl,.           cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d;.            .:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc'.....          'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o,.            .ckXMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.  .........       .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKd,              ,dKWMMMMN00000000KKXNNWWNOc.       ........      .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxl:;,'..                 .cONMMKo'.........',;:,.           ........    .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,                          .;xXMWO:.                          ........  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;                             ,xNMNkl;.                            .. . 'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc                               ;kNMMNd'                                ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                               .:ONWWKl.                              :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'                                 .,lKMWO;.                           .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'                                    'xNMNd.                          .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                                      .cKWW0:.                         'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.                                         'xWMNkoddolc;..                 .cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;                                           ,kNMMMMMMMMMWXOo;.                :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                                          .dXMMMMMMMMMMMMMMMW0l.               :XMMMMMMMMMWX0kxKMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.                                         .dWMMMMMMMMMMMMMMMMMMW0c.             .oWMMWN0kdc;'. .oWMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,                                          ;XMMMMMMMMMMMMMMMMMMMMMNx.             'dxl;'.    ..';dNMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMO.                       .,::c:,.           :XMMMMMMMMMMMMMMMMMMMMMMWx.             ...';cloxO0KNWWMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMWx::lodxO0KXNWMMMk.                    .:xKNWMMWN0l.         ,0MMMMMMMMMMMMMMMMMMMMMMMNc            .l0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMK;       ...';:co:.                   ;0WMMMMMMMMMNl          oNMMMMMMMMMMMMMMMMMMMMMMMx.           .kWWNNNNNXXKK000K0XWMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMKc''.........                        ;KMMMMMMMMMMMNl          .dNMMMMMMMMMMMMMMMMMMMMMMx.            ',,,''''.........dWMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMWWNNNXXXKKK000OOOkd'                 cNMMMMMMMMMMNd.           .cKWMMMMMMMMMMMMMMMMMMMXc           .;:;;,,''......   ,0MMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNd.                .dXMMMMMMWKx;      .......  .oKWMMMMMMMMMMMMMMMMXl.          .xWWWWWNNNXXKK00OOOKWMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMN0xxdoolc:;;,'.                   'coddoc;.      'd0KXXXXKk'  .cxKWMMMMMMMMMMMXx,            :OXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMXc         ..,:co:.                              .oXMMMMMXo.     .;cdkO0000XMNo.           .....',:codxOKXNWMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMM0;..,:coxOKXWWMMNk;                               'lk00d,             ....:KMO'         'dKX0koc;..    ..,xNMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMXKXWWMMMMMMMMMMMMNk;.                               .                     :XWd.      'dXWMMMMMMWNKOdl:'.;OMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'                                                   .oNX:   .:kXMMMMMMMMMMMMMMMMNXXWMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'.                                                .kWk;:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOd:'.                                            .oNWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;'.                                 ..;cdOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxol:;'....           ....',:codkKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK0OOkxxxxxkkO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl:,'',;oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlccoONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc         oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'      .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:         :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xxx:         ,ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.          lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.              .,cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkl'          .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc                    .':oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;.             .;xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                        .;lkKNMMMMMMMMMMMMMMMMMMMMMMMMNKko:'.                    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.    .,d0ko:,..            .,cx0NWMMMMMMMMMMMMMMWXOdc,.            .''.         cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoloONMMMMWNX0kdl:,..         .':dOXWMMMMMMMNOl;.           .':ldkKNNk,      .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKkdl;..        .;odkKNMMWKxl;.   ..,:ldOKNWMMMMMMMXx;'':dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:'.        .,cx0XWMWKkdxOKNWMMMMMMMMMMMMMMMWXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;.        .':okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkkKNMMMWKkoc:..      ..;lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl:'.   .,lkXWMMMMWXOo:..       ..;lx0NWMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdllxKWMMMWX0xl;..         .'l0WMMMMMMMMWXOo;..        .':lxkO0KKXXX0xl:,;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc,.     'dOxl;..          .,cd0NWMMMMMMMMMMMMMMWKkl,.          .....','..     ,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc           .          ..;okKNMMMMMMMMMMMMMMMMMMMMMMMN0d:'.      ...........     ,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc                  .,cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,................   .;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:.             .lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d,............,:cokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxdd:.        :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo............oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.        .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   ........,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.        .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.  ........'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'.     ..lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;........'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract zaa is ERC721Creator {
    constructor() ERC721Creator("lul", "zaa") {}
}