// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Les Grossman
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKK0000KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkkxddooooodkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxdxxxxxxkkkxxdolldONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;,lxxxxkkOOOOkxdolc;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.;oxxxkOO000Okkxdol;.cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..:dxkkkO0000OOkxxdl;..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo..cxkkkOO000OOkxxxdc,..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, 'coxkOO00000OOkxdl:. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.....,;:ldkkdoolc:;,. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;'......:d:.... ....'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMWX0kx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlclllccclxkl,,'.....,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMWXOxkkdxKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdlxkOOkkkOkolddol:,;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMKkxxxdloxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:lxkkkxolccxOOkdc':ONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MNkdxdodxxdxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOo,,:cloolccllodl:,.:OXXNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMM    //
//    W0dddxxxdoo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOl;,',:cllcccc:;,''.:OXXKkxOXXXXXNNNXXXNMMMMMMMMMMMMMMMMM    //
//    XxloddddxdONMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKX0dlo:,,,;;;;;,'.',,;lOXXXx;:o0NNNNNNXK00KNWMMMMMMMMMMMMMM    //
//    KoloodxdlckWMMMMMMMMMMMMMMMMMMMMMWWWXkc,ck0KOdddc,'.''....',,;:l0NX0l..,:kNNNNXNX0K0kk0NMMMMMMMMMMMM    //
//    Xocoool,.'c0MMMMMMMMMMMMMMWWWWNNNNXXd. .c,.:dxkkdc:,.....,;,',;lKWWKkd,.'c0WWNNNNK00kxdd0NMMMMMMMMMM    //
//    Wd;cllc;,;oKMMMMMMMMMMMMWNXNNWWWWWWNd. ,c..;xO0X0xol,...',,..,,lKWMWNXO;..:0WNXNN0OOOkxdoxKWMMMMMMMM    //
//    Wx',:lllcl0WMMMMMMMMMMWNNNNWWWWWWWWNd..,;..oXNNXNK0x;.......,;'cKWWWklOO;..oXNNNX0000OkdlcxKXNMMMMMM    //
//    Nl.';:ccckNMMMMMMMMWWNNNNWWWWWWWWWWNo..'. .lXWNNNNXXk:,''',;::;lKWN0l.;Od'.,ONNNXX0kkxdolco0XKKWMMMM    //
//    Xl,;;::::dXMMMMMMMWNNNNWWWWWWWWWWWWNo...   ,ONNNWNNNN0xc::cccc:oXNK00c.:x:..lKNXKkdddddolld0XKOKWMMM    //
//    No',,;:cclOWMMMMWNNNNNWWWWWWWWWWWWWNd..    .lXNNNNWWNNXOo:,;:clxKK0XXd. :o,.;kOxdoxkkxxdodOKKK0O0NWM    //
//    Xc.',;:cccxXWMWWNNWWWWWWWWWWWWWWWWWNd.      ,ONNNNNNWNNNXd;,':okXXXXKl.  :l''ldl:codxxdox00000OkOOXM    //
//    No.';:cllloOXNNNWWWWWWWWWWWWWWWWWWWWx.      ,ONNWNNNNNWWWNk:;loxXNXK0c   .::.;oolccloddkOkkOK0000kOW    //
//    Wx'';cloollx0XXWWWWWWWWWWNNWWWWWWWWWO,     .lKNNNNNNNWNWWMWKxddx0KKKKo.   'c,;ONWN0occlloxOKKXXKKkxK    //
//    Wx'';coooookKKKNWWWWWWWNNNNNNWWWWWWWK:.    ;ONNNNNWNNWNNWWWW0xOKKXXXKx,   .l;,OWMMXo;;:ld0KXXXXX0kdk    //
//    Mk,':looodxKNKKXNWWNNNNXXXXKKXNWWWWWXo..  .oXNNNNNWNNNNNNWWWNXNWNXK000x'  .c:,kWMMWXOxxO0KXXNNXK0Oxk    //
//    M0;.;clodOXNNXKKNWWNNXXXK0xk0KKXXNNWWx'.   c0XXNNNNNNNNNNWWMMMMMNKKXXXKd. .lc,kWMMMMMWNK0O0KXXXKOdd0    //
//    MNx,,:lx0NWWNXKKXNWNNXXK0kkKNK0KKKXNW0:.   .oXNNNNNNNNNNNNWMMMWWNKKKXXXKc .cc'xWMMMMMMMMWKdldxxdl;:0    //
//    MMXo;cdKWWWWNK00KXNWNNXX0OXWWKO00KKKNXl.    'ONNNNWNNNNNNNWWMWWWN0KXXXXKl  ;:'oNMMMMMMMMMWkccllll:c0    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LG is ERC721Creator {
    constructor() ERC721Creator("Les Grossman", "LG") {}
}