// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The Album
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    '..''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..'    //
//    ..lO00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000Ol..    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMW0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMMMMMMMMMMMMMMMWx'.    //
//    .'xWMXl''''''''''''''''''''''....'''''''''''''''''''''''''''''''''''''''''''...'kMMMMMMMMMMMMMMMWx'.    //
//    .'xWMWX000000000000000000000x,.,d00000000000000000000000000000000000000000Oo'..cKMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;..lXMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.'oXMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'.,xNMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'.;kWMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl..:OWMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c..c0WMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:..lKMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;.'oXMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.'dNMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'.;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMWKc..:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMMW0:..cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMMWO;.'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMMNx,.'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMMNd'.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMMXo'.;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMMMKl..:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMMW0:..c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMMMWO:..lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMMWNk;.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMMNx:,.'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMMNd'..,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMMXl...;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMMMKc..:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMMW0:..cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMMWO;.'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMMNx,.'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMMNd'.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMMXo'.;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMMMKc..:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMMW0:..c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MMWO:..lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MWk,..c0XNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNWMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMK:.;0MK:...';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oXMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMXdcdXMNkoooooooooooooooooooooooooooooooooooooooooooooooookNMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.    //
//    .'xWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWx'.    //
//    ..;cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;..    //
//    '..................................................................................................'    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Editions is ERC1155Creator {
    constructor() ERC1155Creator("The Album", "Editions") {}
}