// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dungeon (1 of 1) by Lxrd_Ox
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    ~!!J555555555555555555555555555555555555555555Y!!!!!!Y555555555555555555555555555555555555555555J!!~    //
//    ~!!YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJJ?7!75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5JJ7    //
//    ~!!YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7!75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY    //
//    ~!!YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGGPPP7!75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGPPPY    //
//    ~!!YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGGPPP7!75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGPPPY    //
//    ~!!YP5555555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGGPPP7!7555555555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGPPPY    //
//    ~!!!7777777!?PPPPPPPPPPPPPPPPPPPPPPPPPGGPPPPPPPPPP7!!!7777777!YPPPPPPPPPPPPPPPPPPPPPPPPPGGPPPPPPPPPY    //
//    ?YYYYYYYYYYY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ?JYYYYYYYYYYYY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?J7    //
//    5GGPPPPPPPGGPPPPPPPPPPPPPPPPPPPPPPPGGPPPPPPP55Y777GGGPPPPPPGGGPPPPPPPPPPPPPPPPPPPPPPPGGPPPPPPP55Y77!    //
//    5GGJ!!!!!JGGPPPPPPPPPPPPPPPPPPPPGGPPPPPPPPP5!!7PPPGGG7!!!!!5GGPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPY!!?PPY    //
//    5GG5Y555YPGGPPPPPPPPPPPPPPPPPPPPPPPPPPPP5???YYYPPPGGG5YYYYYPGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPY??JYY5PPY    //
//    YGGGGGGGGGGGPPPPPPPPPPPPPPGGP555555PP5Y5J77?PPPPPPGGGGGBBBB#####BGPPPPPPPPPGGP555555PPP555J77JPPPPPY    //
//    YPPPPPPPPPPPPPPPPPPPPPPPPPPP7!!!!!JPPY7?YGBBB###&&&&@@@@@@@@@@@@@@&#BGPPPPPPPP7!!!!!5PP?!!JPPPPPPPPY    //
//    YPPPPPPPPPPPPGGGGGPPPPPPPPPGGGGGGB#&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&#GPPPPPYYY7!!7?7JYY5PPPPPPPPY    //
//    J55PPPPPPPPPPGGGGGGPPPPPPB&&#&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&&&&&&&&&&&&&&BPPPPPP7!!7?75PPPPPPPPPPPY    //
//    [email protected]@@@&BGB#@@@@@@@@@&&&&##[email protected]@@@@@@@@@#PPPPPP7!!5PPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@&&&#[email protected]@@@@@@@@@#PPP?77Y55PPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@BYYY???5PPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@#[email protected]@@@@@@@@@B!!7PPPPPPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@#[email protected]@@@@@@@@@G555PPPPPPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@#[email protected]@@@@@@@@@GJYYYYYPPPPPPPPPPPP5JJJJY?    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@B!!!!!!5PPPPPPPPPPPJ!!!!!~    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@B!!!!!!5PPPPPPPPPPPJ!!!!!~    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@BJJJJJJ5PPPPPPPPPPP5JJ?!!~    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@#PPPPPPPPPPPPPPPPPPPPPY77!    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@#PPPPPPPPPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@#PPPPPPPPPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@#PPPPPPPPPPPPPPPPGGGGGPPPY    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@#PPPPPPPPPPPPPPPPGGGGGPPPY    //
//    [email protected]@@@@@@@@@[email protected]@@@@@@@@@BPPPPPPPPPPPPPPPPPPPPPPPPY    //
//    [email protected]@@@@@@@@@BPBBBGGGGGGP55JJJJJJJ??JJYP#&&@@@@@@@@BPPPPPPPPPPPPPGGPPPPPPP55J    //
//    5GGGGGGGGGGGPPPPPPPPPPPPP#@@@@@@@@@@#PGGGGGGGGG55P#&&&&&@@@@@@@@@&##&&@@@@BPPPPPPPPPGGGPPPPPPPPPY!!~    //
//    [email protected]@@@@@@@@@B#&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&#&&BPPPPPPPGGPPPPPPPPPY7??YYJ    //
//    5GGY?????YGGPPPPPPPPPPPPPPGB#&@@@@@@B&@@@@@@@@@@@@@@@@@@@@@@@@@&&&&####BGPPPPPPPPPGGPPPPPP5YYJ77JPPY    //
//    5GGGGGGGGGGGPPPPPPPPPPPPPGGGGGGB#&@@B&@@@@@@@@@@&&&&&####BBBBGGPPPPPPPPPPPPGGGGGGPPPPPPPPPJ!!JPPPPPY    //
//    YPPPPPPPPPPPPPPPPPPPPPPPPPPPJ777775BGBP5PBBGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP?777775PPJ77J555PPPPPY    //
//    YPPPPPPPPPPPPPPPPPPPPPPPPPPPJ??7!!?YYJ?7JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP???!!!JYYJ??YPPPPPPPPY    //
//    YPPPPPPPPPPPPGGGGGGPPPPPPPPPPPP?!!!!!JPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGPPPPPPPPPPPPP7!!!!!YPPPPPPPPPPPY    //
//    ?YY5PPPPPPPPPPPPGGGPPPPPPPPPPPP?!!J555PPPPPPPPPPPPYYYPPPPPPPPPPPPPGGPPPPPPPPPPPPP7!!Y55PPPPPPPPPPPPY    //
//    JYY5555PPPPPPPPPPPPPPPPPPPPPYJYJ??YPPPPPPPPPPPPPPPYYY555PPPPPPPPPPPPPPPPPPPPPPYJJJ??5PPPPPPPPPPPPPPY    //
//    YPPYJJ5PPPPPPPPPPPPPPPPPPPPP?!!YPPPPPPPPPPPPPPPPPPPPPYJJ5PPPPPPPPPPPPPPPPPPPP57!!5PPPPPPPPPPPPPPPPPY    //
//    YPPPPPYJJ5PPPPPPPPPPPPPPP7!!Y55PPPPPPPPPPPPPPPPPPPPPPPPPYJJ5PPPPPPPPPPPPPP57!7555PPPPPPPPPPPPPPPPPPY    //
//    YPPPPP5Y55555PPPPPPPPPJJJJJJ5PPPPPPPPPPPPPPPPPPPPPPPPPPP5Y55555PPPPPPPP5JJJJJJPPPPPPPPPPPPPPPPPPPPPY    //
//    YPPPPPPPP5JJYPPPPPP5557!75PP555PPPPPPPPPPPPP555555PPPPPPPPPYJJ5PPPPPP5PY!!75PP555PPPPPPPPPPPPP5555PY    //
//    YPPPPPPPPPPP5JJYPP57!75P57!777!YPPPPPPPPPPP5!!77!75PPPPPPPPPPPYJJ5PPY!!?PP57777775PPPPPPPPPPPY!7777!    //
//    YPPPPPPPPPPPP55YJJJJJYPPP7!!!!!YPPPPPPPPPPP5!!!!!7PPPPPPPPPPPP555YJJJJJYPP5!!!!!!5PPPPPPPPPPPJ!!!!!~    //
//    J55555555555555Y!!!5555557!!!!!J55555555555Y!!!!!!555555555555555J!!7P5555Y!!!!!!Y55555555555J!!!!!~    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DUN is ERC721Creator {
    constructor() ERC721Creator("Dungeon (1 of 1) by Lxrd_Ox", "DUN") {}
}