// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Super Burn
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                       bbbbbbbb                                                                                                                                       dddddddd                                            //
//                                                                                                       b::::::b                                                                                                                                       d::::::d                                            //
//                                                                                                       b::::::b                                                                                                                                       d::::::d                                            //
//                                                                                                       b::::::b                                                                                                                                       d::::::d                                            //
//                                                                                                        b:::::b                                                                                                                                       d:::::d                                             //
//        ssssssssss   uuuuuu    uuuuuu ppppp   ppppppppp       eeeeeeeeeeee    rrrrr   rrrrrrrrr         b:::::bbbbbbbbb    uuuuuu    uuuuuu rrrrr   rrrrrrrrr   nnnn  nnnnnnnn             ssssssssss   uuuuuu    uuuuuunnnn  nnnnnnnn        ddddddddd:::::d   aaaaaaaaaaaaayyyyyyy           yyyyyyy    //
//      ss::::::::::s  u::::u    u::::u p::::ppp:::::::::p    ee::::::::::::ee  r::::rrr:::::::::r        b::::::::::::::bb  u::::u    u::::u r::::rrr:::::::::r  n:::nn::::::::nn         ss::::::::::s  u::::u    u::::un:::nn::::::::nn    dd::::::::::::::d   a::::::::::::ay:::::y         y:::::y     //
//    ss:::::::::::::s u::::u    u::::u p:::::::::::::::::p  e::::::eeeee:::::eer:::::::::::::::::r       b::::::::::::::::b u::::u    u::::u r:::::::::::::::::r n::::::::::::::nn      ss:::::::::::::s u::::u    u::::un::::::::::::::nn  d::::::::::::::::d   aaaaaaaaa:::::ay:::::y       y:::::y      //
//    s::::::ssss:::::su::::u    u::::u pp::::::ppppp::::::pe::::::e     e:::::err::::::rrrrr::::::r      b:::::bbbbb:::::::bu::::u    u::::u rr::::::rrrrr::::::rnn:::::::::::::::n     s::::::ssss:::::su::::u    u::::unn:::::::::::::::nd:::::::ddddd:::::d            a::::a y:::::y     y:::::y       //
//     s:::::s  ssssss u::::u    u::::u  p:::::p     p:::::pe:::::::eeeee::::::e r:::::r     r:::::r      b:::::b    b::::::bu::::u    u::::u  r:::::r     r:::::r  n:::::nnnn:::::n      s:::::s  ssssss u::::u    u::::u  n:::::nnnn:::::nd::::::d    d:::::d     aaaaaaa:::::a  y:::::y   y:::::y        //
//       s::::::s      u::::u    u::::u  p:::::p     p:::::pe:::::::::::::::::e  r:::::r     rrrrrrr      b:::::b     b:::::bu::::u    u::::u  r:::::r     rrrrrrr  n::::n    n::::n        s::::::s      u::::u    u::::u  n::::n    n::::nd:::::d     d:::::d   aa::::::::::::a   y:::::y y:::::y         //
//          s::::::s   u::::u    u::::u  p:::::p     p:::::pe::::::eeeeeeeeeee   r:::::r                  b:::::b     b:::::bu::::u    u::::u  r:::::r              n::::n    n::::n           s::::::s   u::::u    u::::u  n::::n    n::::nd:::::d     d:::::d  a::::aaaa::::::a    y:::::y:::::y          //
//    ssssss   s:::::s u:::::uuuu:::::u  p:::::p    p::::::pe:::::::e            r:::::r                  b:::::b     b:::::bu:::::uuuu:::::u  r:::::r              n::::n    n::::n     ssssss   s:::::s u:::::uuuu:::::u  n::::n    n::::nd:::::d     d:::::d a::::a    a:::::a     y:::::::::y           //
//    s:::::ssss::::::su:::::::::::::::uup:::::ppppp:::::::pe::::::::e           r:::::r                  b:::::bbbbbb::::::bu:::::::::::::::uur:::::r              n::::n    n::::n     s:::::ssss::::::su:::::::::::::::uun::::n    n::::nd::::::ddddd::::::dda::::a    a:::::a      y:::::::y            //
//    s::::::::::::::s  u:::::::::::::::up::::::::::::::::p  e::::::::eeeeeeee   r:::::r                  b::::::::::::::::b  u:::::::::::::::ur:::::r              n::::n    n::::n     s::::::::::::::s  u:::::::::::::::un::::n    n::::n d:::::::::::::::::da:::::aaaa::::::a       y:::::y             //
//     s:::::::::::ss    uu::::::::uu:::up::::::::::::::pp    ee:::::::::::::e   r:::::r                  b:::::::::::::::b    uu::::::::uu:::ur:::::r              n::::n    n::::n      s:::::::::::ss    uu::::::::uu:::un::::n    n::::n  d:::::::::ddd::::d a::::::::::aa:::a     y:::::y              //
//      sssssssssss        uuuuuuuu  uuuup::::::pppppppp        eeeeeeeeeeeeee   rrrrrrr                  bbbbbbbbbbbbbbbb       uuuuuuuu  uuuurrrrrrr              nnnnnn    nnnnnn       sssssssssss        uuuuuuuu  uuuunnnnnn    nnnnnn   ddddddddd   ddddd  aaaaaaaaaa  aaaa    y:::::y               //
//                                       p:::::p                                                                                                                                                                                                                                     y:::::y                //
//                                       p:::::p                                                                                                                                                                                                                                    y:::::y                 //
//                                      p:::::::p                                                                                                                                                                                                                                  y:::::y                  //
//                                      p:::::::p                                                                                                                                                                                                                                 y:::::y                   //
//                                      p:::::::p                                                                                                                                                                                                                                yyyyyyy                    //
//                                      ppppppppp                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                          //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract burn is ERC1155Creator {
    constructor() ERC1155Creator("Super Burn", "burn") {}
}