// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: MAYC#33
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMWX0kddoooooddddkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkddddk0KXXKOdc::lxOKKXXXKK0kdloONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcokOxdoooooolcclddddOXNNNNNNNXKdcoKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0co0xc;.'o0KK0dc;;cdOOdd0NNNNNNNNX0olo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNocOx:;'  ;OXK0o'   .c00ddKNNNNNNNNNX0o:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMWXOxdddxKWMMMMMMMMMWNK0O0XWN0ddddx0NMMMW0xdxxkOOkkkkkkkxxkkkkkkk0NMMWNXKKXNMMMMMMWXOkkO0NMMMMMWXOkkkkkkxdxxkkkkkOkkxxxxx0WMMW0cox:,.   c0dlx;     .dXxlONNNNNNNNNNNKolKMWNKOkkkOOKNMMMMMWX0OkkkO0XWMM    //
//    MMMKl:dkOklckNMMMMMMWKdlloolcdo:dOOkl:OMMWO:lkkxlcldxxxxxxxxxxxddxo:xNKdlooollOWMMMMKlcodollkNMMWOccddxxoldkkxxxxxxdddxxkxccKMMNocdc;,   .x0lcc.     .oXxckXNNNNNNNNNN0loK0xddxkOkkxooONWXOdddxkOkxxodON    //
//    MMMO:dXNNNXo:OWMMMMW0cckKXNKc,,lKNNXd:kWMNd:ONNNXKXNNNNNNNNNNNNNNNO:oOclOKXX0o:OWMMWO:oXNNXxcdXMNd:kNNNNNXNNNNNNNNNNNNNNNXlc0WXdcx0dc;,;lkXXo;,      .dXxlONNNNNNNNNNXdlkdlkKK0OkOKXXOldOooOKK0OkOKXKklx    //
//    MMNx:kNNNNN0clKMMMNkco0NNNN0:';dXNN0cc0MMKll0NNXkldk000XNNNNXK00Okl:lcl0NNNNN0clXMMWx:xNNNNXkcoXNoc0NNNXOddxkOXNNNNNXKOkkd:oXKockKOxxk0XNNNNKxc.  . .:0Nxl0NNNNNNNNNN0ldKolxdddxkxlxXXdlxolddddxkdlkXXdl    //
//    MM0cl0NNNNNXd:OWWKocxXNNNNXd,':ONNXx:xWMXo:kXNN0c,lol:;xXNNXxclddddo:l0XK0XNNXoc0WMKll0NNNNNXxcxOcoXNNNOccodo:oKNNN0ocooc:oXXdckXd;'..'lOXNNNN0: .coo0NNOlx0XNNNNNNNXdcOWXOkOKXK0xlxXKloXXOO0KKKOdlkX0ld    //
//    MWx:xXNNNNNNOcoK0llONNNNNN0c',oXNNKoc0MMKclKNNXx:xNWNd;xXNN0clXWWXx:dKNO:;kXNXd:OWWk:xXNNNNNNKd;,:ONNNXd:kWWKclKNNXd:xWWNNWMNxcx0c;'   .lKNNNN0:.:ONXNNNKkddxkO0XNNKdcxNMMW0xddddx0K0ol0WMNOddddxk0X0do0    //
//    MXlc0NNNNNNNXx:c:oKNNNNNNXO:';xXNN0llKMWKclKNNXoc0WMNdcONNNk:dNMXd:dXNKl''l0NNk:dNNdcONNNNNNNNKdcxXNXNXo:0MWOcdXNNKlc0MMMMMMNk:oo:;.  .;kXNNNNXK0KNNNXOl:;;cldxOKXxclONMMM0loOKXNNNOcc0WMWOldKKXNNXkclKW    //
//    MKcl0NNNXKKXNXkdkKNXKXNNNXk:':xXNN0coXMM0coKNNXdcOWMXocONNNk:xNNd;dXNXd;:;,xXNKlc0XocONNNXXXNNNNXXNNNNXd:xWNx;dXNN0llKMMMMNOocxOo,. .,d0NNNNNNNNNNNX0c.    .ldlo0XxoKWMMMMXxodddkKNKxlkNMW0llxodkKNKxlkW    //
//    MKll0NNNO:;kXNNNNN0l,oXNNXx;':ONNN0coXMNd:kXNNKo:OWMKll0NNNd:kNO:lKNNXOoodkKNNNO:oOll0NNXx;cOXNNNNNNNN0c:OWNo;xNNN0coXMMMKo:d0XNKxodOKNNNNNNNNNNNNKo'     'xKxc:xXOdKWMMMMMWNX0xco0NXdlKWMWKkkOkoo0NKooX    //
//    Wk:dXNNXo,,:OXNNXOc''oXNNKo:;cONNNKd:lxlcxXNNKd:xNMMOcdKNNXlc0Ocl0NNNNNNNNNNNNNXoco:dKNN0c;:cONNNNNNNNx:xNMXlc0NNNk:xWMWO;,coddkOO0XNNNNNNNNNNNNNXd.     .dX0clxONOo0NKkxxONMMMWk:dNXo;oxxONMMMWkckNXdo0    //
//    K::0NNN0:lklcdxkococ:OXNNO:locOXNNNXOxdkKXNNKo:kWMMNdcONNNk:okcl0NNNNNXXXXXXNNNNx,.;ONNXx:xOcl0NNNNNNKlc0MWk:dXNNKoc0MWO;':cccoolddloxOOOOOOOOOkOOo.     ;0N0coOxkdxX0loOOooO00kod0NXxcx0kodO00xldKNKdl0    //
//    KclKNNNO:dNKdc;;lOXlcKNNXx:xx;o0NNNNNNNNNNXOc,oNMMMKll0NNXd:ocl0NNX0xoooollxKNNN0;.:KNNXo:0W0cl0NNNNN0clXMNx:kNNN0llKMWk;',;;:cclxdlcdkoldoolc:,clc,''. .lKN0cdNNXXWW0ldXNKkxxxk0XXKxclkXNKOxxxk0XN0ocdX    //
//    KclO0KKd:OWMWNXXNWK:,dKNKlcOd..cxk0XXXX0OOd,'oKWMMM0cl0XX0:',cOXNXxcokO00KkcoKNNXo,o0XX0ccXWW0clOXXKKx;lXMXockKKKOl:0MMXl.,coldko:okdkkc;::ccc:,:coOK0:  :KNOcdNMMMMMWOlxK00XXX000dlcccd00KNXXXKOkkockNM    //
//    Wkc;;cc,c0MMMMMMMMXo.;ool;oXXx;,''x0o:o:.;;;kWMMMMMKlcdcc:,,,:dkdl;oNMMMMMXo;lxxkkl::oo;'oNMMWKo:::co;;kWMXl;;co:''cKMMW0:,ododdlxX0l;codc:ollddxOXNNKl.,dXKocOMMMMMMMNkllc:cOk:,c:ckKkdl:oOo:kd:clokXMM    //
//    MWKl;;;l0WMMMMMMMMMXo:::cdKMMWKx:;k0:.;coddONMMMMMMXo:::cd0Kd,',,;l0WMMMMMNk;.,;';;;,:::dKWMMMMNOollloOWMMNOl,;c,,dXMMMMWOco0X0kxkOkdodxkxdxkOKXNNNNNNX0KXKockWMMMMMMMMWK0KOloocok0NMMWN0old:,llxXNNWMMM    //
//    MMMNOkKWMMMMMMMMMMMMNKKNWWMMMMMM0lclcdKNWWWMMMMMMMMMX00XWWMMWX0k0XWWMMMMMMMN0occokKX0xkKWMMMMMMMMWWWWWMMMMMMW0oldKWMMMMMMWOllOXNXXXKXNXXKXXXNNNNK0kk0XNXKkod0WMMMMMMMMMMMMMWXOOKWMMMMMMMWKxdkKXXWMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMWXxoxKOxO0KXNNNXOxONKkxkkxlxX0od0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxd0klx0xkKNX0dlxXOdKWMXodXOokWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkokkcxWXddKXkxxkOxkNMMWOxxdkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OkkKWWOo0N0dkK0KNMMMMMNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWko0NXdoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOloxdcdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dlokXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MAYC33 is ERC721Creator {
    constructor() ERC721Creator("MAYC#33", "MAYC33") {}
}