// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Chen Feng run true
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//    the true gas in the body flow, did not dry up, this is relieved.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//    "Yes, I'd like to see what progress you've made in the past few days. Don't think that you can get rid of the name of waste by breaking through one day. Today I'll wake you up again and let you know that waste will always be waste." Wang cold track, first, fast moving, arrived Chen Feng in front, his hands together, like hook like substance caught, directly to the scratching, Chen Feng shoulder waved and catch the wind with a sharp between, more powerful than just two bailiffs, this moves like Chen Feng rolled over the shoulder, any malicious, although look down upon each other, but at first is the     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CFRT is ERC721Creator {
    constructor() ERC721Creator("Chen Feng run true", "CFRT") {}
}