// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The PhotoGrabber
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                 bbbbbbbb          bbbbbbbb                                                        //
//    TTTTTTTTTTTTTTTTTTTTTTThhhhhhh                                      PPPPPPPPPPPPPPPPP   hhhhhhh                                       tttt                                   GGGGGGGGGGGGG                                   b::::::b          b::::::b                                                        //
//    T:::::::::::::::::::::Th:::::h                                      P::::::::::::::::P  h:::::h                                    ttt:::t                                GGG::::::::::::G                                   b::::::b          b::::::b                                                        //
//    T:::::::::::::::::::::Th:::::h                                      P::::::PPPPPP:::::P h:::::h                                    t:::::t                              GG:::::::::::::::G                                   b::::::b          b::::::b                                                        //
//    T:::::TT:::::::TT:::::Th:::::h                                      PP:::::P     P:::::Ph:::::h                                    t:::::t                             G:::::GGGGGGGG::::G                                    b:::::b           b:::::b                                                        //
//    TTTTTT  T:::::T  TTTTTT h::::h hhhhh           eeeeeeeeeeee           P::::P     P:::::P h::::h hhhhh          ooooooooooo   ttttttt:::::ttttttt       ooooooooooo    G:::::G       GGGGGGrrrrr   rrrrrrrrr   aaaaaaaaaaaaa   b:::::bbbbbbbbb   b:::::bbbbbbbbb        eeeeeeeeeeee    rrrrr   rrrrrrrrr       //
//            T:::::T         h::::hh:::::hhh      ee::::::::::::ee         P::::P     P:::::P h::::hh:::::hhh     oo:::::::::::oo t:::::::::::::::::t     oo:::::::::::oo G:::::G              r::::rrr:::::::::r  a::::::::::::a  b::::::::::::::bb b::::::::::::::bb    ee::::::::::::ee  r::::rrr:::::::::r      //
//            T:::::T         h::::::::::::::hh   e::::::eeeee:::::ee       P::::PPPPPP:::::P  h::::::::::::::hh  o:::::::::::::::ot:::::::::::::::::t    o:::::::::::::::oG:::::G              r:::::::::::::::::r aaaaaaaaa:::::a b::::::::::::::::bb::::::::::::::::b  e::::::eeeee:::::eer:::::::::::::::::r     //
//            T:::::T         h:::::::hhh::::::h e::::::e     e:::::e       P:::::::::::::PP   h:::::::hhh::::::h o:::::ooooo:::::otttttt:::::::tttttt    o:::::ooooo:::::oG:::::G    GGGGGGGGGGrr::::::rrrrr::::::r         a::::a b:::::bbbbb:::::::b:::::bbbbb:::::::be::::::e     e:::::err::::::rrrrr::::::r    //
//            T:::::T         h::::::h   h::::::he:::::::eeeee::::::e       P::::PPPPPPPPP     h::::::h   h::::::ho::::o     o::::o      t:::::t          o::::o     o::::oG:::::G    G::::::::G r:::::r     r:::::r  aaaaaaa:::::a b:::::b    b::::::b:::::b    b::::::be:::::::eeeee::::::e r:::::r     r:::::r    //
//            T:::::T         h:::::h     h:::::he:::::::::::::::::e        P::::P             h:::::h     h:::::ho::::o     o::::o      t:::::t          o::::o     o::::oG:::::G    GGGGG::::G r:::::r     rrrrrrraa::::::::::::a b:::::b     b:::::b:::::b     b:::::be:::::::::::::::::e  r:::::r     rrrrrrr    //
//            T:::::T         h:::::h     h:::::he::::::eeeeeeeeeee         P::::P             h:::::h     h:::::ho::::o     o::::o      t:::::t          o::::o     o::::oG:::::G        G::::G r:::::r           a::::aaaa::::::a b:::::b     b:::::b:::::b     b:::::be::::::eeeeeeeeeee   r:::::r                //
//            T:::::T         h:::::h     h:::::he:::::::e                  P::::P             h:::::h     h:::::ho::::o     o::::o      t:::::t    tttttto::::o     o::::o G:::::G       G::::G r:::::r          a::::a    a:::::a b:::::b     b:::::b:::::b     b:::::be:::::::e            r:::::r                //
//          TT:::::::TT       h:::::h     h:::::he::::::::e               PP::::::PP           h:::::h     h:::::ho:::::ooooo:::::o      t::::::tttt:::::to:::::ooooo:::::o  G:::::GGGGGGGG::::G r:::::r          a::::a    a:::::a b:::::bbbbbb::::::b:::::bbbbbb::::::be::::::::e           r:::::r                //
//          T:::::::::T       h:::::h     h:::::h e::::::::eeeeeeee       P::::::::P           h:::::h     h:::::ho:::::::::::::::o      tt::::::::::::::to:::::::::::::::o   GG:::::::::::::::G r:::::r          a:::::aaaa::::::a b::::::::::::::::bb::::::::::::::::b  e::::::::eeeeeeee   r:::::r                //
//          T:::::::::T       h:::::h     h:::::h  ee:::::::::::::e       P::::::::P           h:::::h     h:::::h oo:::::::::::oo         tt:::::::::::tt oo:::::::::::oo      GGG::::::GGG:::G r:::::r           a::::::::::aa:::ab:::::::::::::::b b:::::::::::::::b    ee:::::::::::::e   r:::::r                //
//          TTTTTTTTTTT       hhhhhhh     hhhhhhh    eeeeeeeeeeeeee       PPPPPPPPPP           hhhhhhh     hhhhhhh   ooooooooooo             ttttttttttt     ooooooooooo           GGGGGG   GGGG rrrrrrr            aaaaaaaaaa  aaaabbbbbbbbbbbbbbbb  bbbbbbbbbbbbbbbb       eeeeeeeeeeeeee   rrrrrrr                //
//                     NNNNNNNN        NNNNNNNNFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTT                    ///////                    AAA               RRRRRRRRRRRRRRRRR   TTTTTTTTTTTTTTTTTTTTTTT                                                                                                             //
//                     N:::::::N       N::::::NF::::::::::::::::::::FT:::::::::::::::::::::T                   /:::::/                    A:::A              R::::::::::::::::R  T:::::::::::::::::::::T                                                                                                             //
//                     N::::::::N      N::::::NF::::::::::::::::::::FT:::::::::::::::::::::T                  /:::::/                    A:::::A             R::::::RRRRRR:::::R T:::::::::::::::::::::T                                                                                                             //
//                     N:::::::::N     N::::::NFF::::::FFFFFFFFF::::FT:::::TT:::::::TT:::::T                 /:::::/                    A:::::::A            RR:::::R     R:::::RT:::::TT:::::::TT:::::T                                                                                                             //
//                     N::::::::::N    N::::::N  F:::::F       FFFFFFTTTTTT  T:::::T  TTTTTT                /:::::/                    A:::::::::A             R::::R     R:::::RTTTTTT  T:::::T  TTTTTT                                                                                                             //
//                     N:::::::::::N   N::::::N  F:::::F                     T:::::T                       /:::::/                    A:::::A:::::A            R::::R     R:::::R        T:::::T                                                                                                                     //
//                     N:::::::N::::N  N::::::N  F::::::FFFFFFFFFF           T:::::T                      /:::::/                    A:::::A A:::::A           R::::RRRRRR:::::R         T:::::T                                                                                                                     //
//                     N::::::N N::::N N::::::N  F:::::::::::::::F           T:::::T                     /:::::/                    A:::::A   A:::::A          R:::::::::::::RR          T:::::T                                                                                                                     //
//                     N::::::N  N::::N:::::::N  F:::::::::::::::F           T:::::T                    /:::::/                    A:::::A     A:::::A         R::::RRRRRR:::::R         T:::::T                                                                                                                     //
//                     N::::::N   N:::::::::::N  F::::::FFFFFFFFFF           T:::::T                   /:::::/                    A:::::AAAAAAAAA:::::A        R::::R     R:::::R        T:::::T                                                                                                                     //
//                     N::::::N    N::::::::::N  F:::::F                     T:::::T                  /:::::/                    A:::::::::::::::::::::A       R::::R     R:::::R        T:::::T                                                                                                                     //
//                     N::::::N     N:::::::::N  F:::::F                     T:::::T                 /:::::/                    A:::::AAAAAAAAAAAAA:::::A      R::::R     R:::::R        T:::::T                                                                                                                     //
//                     N::::::N      N::::::::NFF:::::::FF                 TT:::::::TT              /:::::/                    A:::::A             A:::::A   RR:::::R     R:::::R      TT:::::::TT                                                                                                                   //
//                     N::::::N       N:::::::NF::::::::FF                 T:::::::::T             /:::::/                    A:::::A               A:::::A  R::::::R     R:::::R      T:::::::::T                                                                                                                   //
//                     N::::::N        N::::::NF::::::::FF                 T:::::::::T            /:::::/                    A:::::A                 A:::::A R::::::R     R:::::R      T:::::::::T                                                                                                                   //
//                     NNNNNNNN         NNNNNNNFFFFFFFFFFF                 TTTTTTTTTTT           ///////                    AAAAAAA                   AAAAAAARRRRRRRR     RRRRRRR      TTTTTTTTTTT                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                             www.ThePhotoGrabber.com                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TPG69 is ERC721Creator {
    constructor() ERC721Creator("The PhotoGrabber", "TPG69") {}
}