// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: THOMAS
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                            ....            ......................                                                                                                                                                  //
//                                                                                                             .............................................................                                                                       .........................................................          //
//                 .. .......                                                                           ..........................................................................                                                ................................................................................    //
//    ......................................................       ......                         ......................................................................................                            ..............................................................................................    //
//    ..................................................................................................''.''.............'.......................'''''''..''''...'..........'.'''''..............................................................................................................................    //
//    .............................................................................................''''''''''..'....'..'...'''''''','''''''..'''''','',,,''',''''','','''''.'',,'''',,''..........................................................................................................................    //
//    .........................................................................................'''',,,''''''..''''.''''''....',,,,,,;;,,,'''',,,,,,;;,,,,,,,,,,,,,,,,;;,'''''','''''',,,,''...............................................................................''''''''''''''''''''''''''''''''........    //
//    .......................................................................................',,,;,,,,,,'''''..',''''''''''..'',;;;,,,,'',''',,,'',;:;;;;;,,,,;;,,,;,,,,'',,',,,,''',,;;;;,,'''....................................................''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,'''''''''''''''    //
//    ..............................................................................''''',,,,,;;,,,,,,,,''''''..',,,'....',,',,;;;:;',,,'',,',,;,,,;;;;;;;;;;;,,;;,,,,,,,,'.',,',''',;,,;;;;;:;;,,,,'..................................'''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''    //
//    .............................................'''.....................''''''''',,,,;;:::;;;;;,,,'''..''''''',,,'..'',;;;;;;::::;,,'',;;,,,,;;,;;;:;,;:cc::;;;,,;;;,,,,',;,,,,,;;,',;;;:::ccc::;,,,,'''........................'''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,    //
//    ....''''''''''''''''''''''''''''''''''''''''''''''''''''...........''''',,,,;;;;;;;;::;;,',;;,'''''''',,,'',,,,''',,,,;;:;;;;;;;'',;;,,,,;;,;;;;:;,;:::::;;;;:;;;;;;,,;;,,,;;,;;,,,,,;:;::cccccccc::;,''''...........'''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,    //
//    '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,;::::::;;;;;;,,''..'''''',,,'',;,,,,,,,,'',,,;,,;;;,;,,,,',,',;;;;;,,::,;;;,;::::;;;::;;;,,,,,,,,,;;,',;;,,,,;:;;;:ccclllccc::;,,'''''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;::::::;;;;;;;;;;;;;;;;;;    //
//    '''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''',,,,;;;;;;;,;:::;;;;,'''''',,,,,'...',,,'',,,,,,,;;;;;,,;:cc:;,,,,;::,,;;;;;;;:cc:;::cc:;;::;;;;:;,'''',::;,,'''''',;;:::::ccccc:;,,;;;,,''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::;;;;;;;;;;    //
//    ''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:;''',;;;;;;,;,,''''''''''''','',;,,''',;,',;;;:::;,;;:cc;;,,,,;:;;cc:::::::::::::cc;;::::::;;,,;,,,::;,,'',,',;,;;;;:ccc:ccc:;,;;;,,'''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::;;;;    //
//    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,;;;;:::;'.',,;::;,,''''.....'''...',;,'',,,,,,,'',;;;;:c:;;:::::::;;;,c::lc:clccc:cllcccc:;:cc::::::,,,,,,;;,,,',,;;;;;;;;;;:cc:clc:;::;;,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::c::::::::::::::::::    //
//    ,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;::::,'',;;::;:;,''.........''.',,,'',,,,,,,,',;;;:ccccc:::::::::::ccllccllccccccllllc::::::::ccc;,,;;;::,'',;;,,,,;:;,;::cc:cll::c::;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::ccccccccccccc::::::::::    //
//    ,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;:::::::::::::::::;;;;;;;;;;;:;;::::cc:,,,;:;;::;;,''''.............'',,,;;,,,,,;;::::::cloc:c::;:ccc::cccccccccccclllllllcccccccc:;:c:;;;;,,;,,'''',;;;,;:;;::clolllc:;;,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::ccccccccccccccccccc:::::    //
//    ;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::cclllc;,,,;;,;;;,'''......''''...........',,,',,,,;:cllllc:::::::clol:;,;cc;::lllccclllllllllooc;;:;;;,',;;,;;,,;,',;;;;::::;:cccllllcc::;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::cccccccccccccccccccccccccc:    //
//    ;;;;;;;;;;;;;;;::::::::::::::::::::::::::::cccccc::::::::::::::cccllllc,'',;;;,...'''''',,'...'..........'''';;,'''',;::cccccc:;;;:c:;,,,':c;;:clc::ccccllllcllc:;;::c:,',,;,,;;;,''',:;,;::::;::::c:::c::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccc    //
//    ;;;;;;;;;;;;:::::::::::cccccccccccccccccccccccccccccccccccccccccllooooc;,',,,',,,''......''..,,'..',''...,,,,;::;,'',,,;:colllc::;,;;,,;;,;;,';cc;;cccllc:::::llcccc:::;,;;;,;:::;;,,;:;,;;:c:;;:;;;;:cc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccc    //
//    ;;;;;;::::::::::ccccccccccccccccccccccccccccccclllllcccccccccccllloodoc;'......'''...''',''..''...','...,;:;,',;;;;;:ccc:::ccclc;;,',,,;;;;,,;;,;;;:;::;;cllllllcc::;'',;;;;:;;;::cc:::;:c:::,,,,,;;;::c:;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccllllllcccccccccc    //
//    :::::::::::cccccccccccccccccccccccllllllllllllllllllllllllllllllooddolc,.............',;;;'''''..',,,,;;::::;,,;:::::cccc::clllc,'',;,''..',,,,,,,,,,;;:coddddoooc:::;;:::ccccc::clcllc::c:;;,,,;:c::;:c::;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccclllcccccccccc    //
//    ::::::::::ccccccccccccccccccccclllllllllllllllllllllllllllllllloodddoc;'.............',;;,,,,,,',;;,,;;;;;,;;,,:lc:cllllcc:;;,,;,,,;:;','..,,,,,,;;,,,';clloooodoc::clllccllooc;;:clc;,,'''',,;:clc::;:cc:;;::::::::;;;;;::;;;:::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccccccccccllllllllllllllllllllllllllllllooooool:;,'....'''''......',;;;;,,''...''',;c::cc::cllcclcccc;;,,''',;,;;,,'....'',;,,,,,;;;;:lccccccc::::looc::;,,,,,,,'...''',,,;clc:::clcc:::;;::::::::;;:;;;;;;:::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccccllllllllllllllllllllllllllllllllllooooooddc,.......',;;;;,'......'';;;,,,'''..';cccccllllc::::cc:,,,,,'''''''''.   ..''''.','',,,,;;::::::clccccc;'...........',;:::::llcc::cddolc::;;::;;;::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccclllllllllllllllllllllllllllllllllloooollool:,'..'....',:c:;,'...................''''..''..'''..''.......   ......  .......        .....'',''''..............',;;::::coooccc::lxkdlc::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccclllllllllllllllllllllllllllllllooooloolllllc:,',;;...',,;;:::;,,'''''........                                      ...              ..                ...',,;:cccc::cclooolccoxxdolc::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::ccccccccccccclllllllllllllllllllllllllllllllolllllloolllolc;,;c:,..';;;,;;;:::;;;;;;,,'.....                     ...                              ....          ....',;::cclllccccccllloolldxkxdoc:::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccllllllllllllllllllllllllllllloolllodxdolloollc:,;cc:'.';::;;;;,;:::;;,,;;;;;,'...                  ....              ... ...   .... .... ...........',;::cccllllllccllolclddlldkOkdlc::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccclllllllllllllllllllllllllloooollooddollooooodl;,;:;,..,::,,'',;;;;,'',;;;;;,,,'....    .....  ..........    .     .........   ............',;,'''',,;:c:ccccclllcccclollloolloxkxdlcc:::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccccccllllllllllllllllllllllllllooddllodocclldxxddkkdc,,;;;,,,;;;;,',;,,,,,,,,,,,;;:;,'''........'.....'..'....    .......',,,''...'.........''',:::;,',,,,;::::cllccllccccclooloolloxxxxolc::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::ccccccccccccclllllllllllllllllllllllllllllllloolccldxkkkkkko:;;;;;;::;;:::;;;;;,,,,;,',,,,;,'''''.......'''.....''...............,;;;;,,'',,,,,,,,',;;:::;;;;;;;;;;:clccclc:cccllloooooodoloxkkxdoc::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::ccccccccccccllllllllllllllllllllllllllcc::codl:clodxOOOOOOxocc:;,,,,;::clcccc:;;;;;,,,,;;;;,,;;;,''''''...',,,''''..'''''...''.'';:;;;;:;;;;;;;:;;;;;;,,;;;;;;;;;;;:ccccccc:ccloccllllloddodxxxxdolc::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::cccccccccclllllllllllllllllllllllllllcc::cloolcoxkOOO0000Oxoll:,,;;;;;::;,;:;,,;;:;;;;;;;;;;;;;;,,,,',,''....'',,,,,,,''..''''',;::::;;;:::::::::;;;,,;;::::::::::cllcc:::::::cc::::coodxkxxxxxxdlcc::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccc    //
//    :::::::::ccccccccclllllllllllllllllllllllolllcc::cclolloxkkO00OOOOOxdool:;,;:c:::;,',,;;::cc:;,,,,,,;;,;,,,,,,,,;,,'.''.'',,,,''''''''',;:cllc::;;;;;::::::::::::ccc:ccc:::cclllccccc:;;:llc:clooxxxxxxdollcc::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccc    //
//    ::::::::::cccccllllllllllllllllllllllllllllcc::::cclllodxkkO000OOOkxddooc;'';:ccl:,''',;:;;;;,,;;;,,,,,,;;;:;,,;:;;;,,,,''''''''''',,,;;:cllollcc:;;;;;;;;;:::::ccclccccc:::cccllccllc;;;ccllccclxkxxxddolc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccc    //
//    ::::::::::cccclllllllllllllllllllllllllccc::;;;;;:cclodxkO000OOkkxxdddooc;,,,:cldolc;,','',;;;:c:;,'',,,;;;:;;;;;;;;;;,,,,'''''''',,,;;:cclooolllc:::;;;,,,;::::cccccccccc:::cclll::lolcc::cooooxOOxooodolcc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccc:::ccccccccccccccccccccccc    //
//    ::::::::::cccclllllllllllllllllllllllc::;;:::::::::clxkkxxO000Okkkkxdddol:;;,,,:ldol:;;;,,;;,,::;'',,;;;:::::;;;;;:::;;;,,,,''''',,,,;::cloodoooolc:::;;;,,,;:ccccc:::::cc:c::::clc:cllllc::ldddxkxoccloolc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccc:::::c:ccccccccccccccccccc    //
//    ::::::::::ccccclllllllllllllllllllllc:;;;;;:::::::ccoxkkkxkOOOkxkkkxxxddolc:;,',:odolccc::;,,;:;,,,;::::;;:::;;;:;;::;:;;;,,,'''',,;;::cloddddddollc::::;;;,,;:ccc:;::::ccclllc;;;:cloollcccodddxxdlclodocc::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccc::::::::::cccccccccccccc    //
//    ::::::::::cccccllllllllllllllllllllc:;;;;;;;;,,;ccclodkOO000OkkOOkkkkkxdool:,'.',:clllclllc::::;;::::;::::cc:;:;;;;;;;;::;,,,,,,,,,;;:ccloddddddollcccc:::;;,;;::::::;::ccclccc;;;;:cc::::;:clldxxdlldddlcc::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccc:::::::::::ccccccccccccc    //
//    :::::::::ccccccllllllllllllllllllcc:;;,,,;:;;;;:cclddxkkkkOkkxkOOkkkkxxddolc:,'''',:lddoolllccccccc:;;:::;;;;;,,;;,,,,,;;,,,,',,,,;;;::clodxxxxxdoollc:::::;;;;;::c:::::::::ccc::clcc:;;;::;;:oxdlclxkkdolc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccc::::::::::::cccccccccccc    //
//    ::::::::ccccccclllllllllllllllllc:;;;,,,,;;;,;:::ldddxxkkOOkkkxxxxddxxxxxdlc::,'''',:loollccllc:cc:;::;;;::;,,,,;;;,'',,,,'',,,,,,;;;;:coodxxkkxddddlccc::;;;;;:::::;:::ccc:cclccodollcccc::coddoooxOOkxoc:::::::::::::::::::::ccccccc:::::::::::::::::::::::::::::::ccccccccccccccccccc::::::::cccccccccccc    //
//    :::::ccccccccclllllllllllllllllc:,,,,,,',;,,,:c::ldxxxkOOOkkkkxkkkxxxxxxxxdol::;''''',:ldolcc:;;,;;:c:;:::;;;:;,,,,,'',,,,,,',,,,;;;;:ccloddxxxxddooolcc::;;;;;::::;;;;;:::::c::cllllllllc::oxxdoodkOkxoc:::::::::::::::::::cccccccccccc:::::::::::::::::::::::::::cccccccccccccccccccccccc:::::::::cccccccc    //
//    ::::ccccccccccllllllllllloooolc:;,;;;,,,,,'',:::coxkkxxkxdxkxkkkkkkxxxdddddoollc;'....':oddlc:;;;;;;;;::;;:::;,,',,,,,',,,'''',,,,;;;::clodddddxxxdlcllc::;;;:;:::;;;;,,;::;:::::c:::ccc::clxkxocldkOOxolc::::::::::::::::cccccccccccccccccccccccccccccc:::::cccccccccccccccccccccccccccccccccccc::ccccccccc    //
//    ::::cccccccccclllllllllooooolc:;,,;,,,,,,,,,;;;:cloxkkkkxkOOOOOOOOOkkkxxxdoooolc:;,'....,col:;;,,;::;:::::;;,,,,;;;,,''''''',,,,,;;;;;'',:coodxxoc:::clcc:;;;:;:::;;;,,,,;;;;::;;:c:;;::;:cllolcldk0K0kdlc::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    ::::cccccccccclllllllloooooll:;,,,,''''',,,,,,;:clldkOOkkO000OkkOOOkkkkkxxdddoolc::;'....;loc;;:::ccc:::,'',;;,;;,,''''''',,,,,,,,,;;,,'...':dxo:;:cccccc:::;;;;;:;;;;;,,;;;;::cccc:::::::cccllldO0KK0kolc:::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::cccccccccllllllllloooooolc:;,,,''..'''''',,:looooxkkkkkkO00OkOO00OOkkkkxxddllc:::,''..';clllc::cc;,,,,',;,'',,....'''',,,,,,,,,,;;,,,,,'';loolcc::::::::::::::::;;,,,;;;,;;,;:lccc:;;;;clolloxO00K0kdlc::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    :::ccccccclllllllllooooooolc:;;,,'''..''''.',;:cooooodddxkxxxxxkOO00OOkkkkxxddoolcc:;,,'..',:clc;;;;,,,,,,,,''''.......'',,;;;,,,,,;;;;;;;;;;clollc:::::::;::::::::;;,,,,;;;;;;;;ccccc:clllccloxO00KK0xocc:::::::::ccccccccccccccccccccccccccccccccccccccccccc                                                  //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MKF is ERC1155Creator {
    constructor() ERC1155Creator("THOMAS", "MKF") {}
}