// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Bad Dog Outliers
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKNWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo,..;dXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc,..,lONMMMMMMMMMMMMMMMMMMMMMMMMNx,.    .cXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.      .:dOWMMMMMMMMMMMMMMMMMMMMKl.       .oNMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.         ..c0WMMMMMMMMMMMMMMMMWO;.         .xWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMKc.    ....      .oKMMMMMMMMMMMMMMNx'.    ...    ;KMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMXd:co0WMMMMMMMMMMMMMMMW0;.    .cOOo,.     .;kWMMMMMMMMMMMXo.    .,do.    .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMXo.  ..lKWMMMMMMMMMMMMWk,.    .oKXXX0l...    .oNMMMMMMMMMKc.    .:OX0:.    ;KMMMMMMMMMMMM    //
//    MMMMMMMMMMWx.     .'oXMMMMMMMMMMWx'    .,xKXXXXXXko;.    .cKMMMMMMW0;.    .l0XXXx'    .dWMMMMMMMMMMM    //
//    MMMMMMMMMMNo.       .,kNMMMMMMMNx.    .,kXXXXXXXXXX0c.    .;0WMMMWk,.    .oKXXXX0c.    ;KMMMMMMMMMMM    //
//    MMMMMMMMMMXc.         .cKWMMMMNx.    .;OXXXXXXXXXXXXKo.     'xNMNx'    .'xKXXXXXXx.    .xWMMMMMMMMMM    //
//    MMMMMMMMMMX:    .'.    .,kWMMWx.    .:OXXXXXXXXXXXXXXKx'.    .lkl.    .;kXXXXXXXX0;    .cXMMMMMMMMMM    //
//    MMMMMMMMMMK:   .:ko'     .lKWk'    .:OXXXXXXXXXXXXXXXXXk:.    ...    .cOXXXXXXXXXKl.    ,0MMMMMMMMMM    //
//    MMMMMMMMMMX:   .cKXk;.    .,l,.   .;OXXXXXXXXXXXXXXXXXXX0o.         .l0XXXXXXXXXXXx.    .xWMMMMMMMMM    //
//    MMMMMMMMMMXc   .cKXX0l.     .     'xXXXXXXXXXXXXXXXXXXXXXXk;.     .'dKXXXXXXXXXXXXO,    .oNMMMMMMMMM    //
//    MMMMMMMMMMNl.  .lKXXXKk;.        .lKXXXXXXXXXXXXXXXXXXXXXXXKxc'..'cOXXXXXXXXXXXXXX0:.    :XMMMMMMMMM    //
//    MMMMMMMMMMWo.  .oXXXXXXKd;..    .:OXXXXXXXXXXXXXXXXXXXXXXXXXXX0OO0XXXXXXXXXXXXXXXXKl.    ;KMMMMMMMMM    //
//    MMMMMMMMMMWx.  .oXXXXXXXXKxc,'';o0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXd.    'OMMMMMMMMM    //
//    MMMMMMMMMMMO'  .dXXXXXXXXXXXK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'    .kMMMMMMMMM    //
//    MMMMMMMMMMM0,  .dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0Okl.    .xWMMMMMMMM    //
//    MMMMMMMMMMMX:  .oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0kxdoc:;'....     .xWMMMMMMMM    //
//    MMMMMMMMMMMNl. .oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0kxdlc:,....             .;0MMMMMMMMM    //
//    MMMMMMMMMMMWd. .lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0Oxdlc;,....                ...';o0WMMMMMMMMM    //
//    MMMMMMMMMMMMk. .cKXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0kxdoc:,'...               ...',:cldxO0XNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMK;  :0XXXXXXXXXXXXXXXXXXXXXXKOxdl:,'....             ....';cldxO0XNWWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNl. :0XXXXXXXXXXXXXXXXK0kdl:,...              ...';:ldkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMK:.oKXXXXXXXXXXXK0kdl;'..            ....,:loxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMX0KXXXXXXXX0kdc;'..        ....';cldxk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWNNXKOdl:'..   ....',:cldxO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWNOl:;;;:ccodxk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BDO is ERC1155Creator {
    constructor() ERC1155Creator("Bad Dog Outliers", "BDO") {}
}