// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cody A Banks
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMWNNNKxld0NNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNWMMMMMMMMWNNNXd;,:ONNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWNNXxlo0NNNWMMMMWWWNNXOllk0KNNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWNNKo,,lKNNNWWWNNNNNKd:lkOOOOO00KXXNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWNNNXKkll0NNNNNX0kdo:,,:;;,,'',,;:cloxOKNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWWWNNNKolONKko:;;,.';;,,,,;;;;:::,...';lx0XNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWWNNNKo:l;'..,;'',,;;:ccccccc:,........,cxKNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWWNNNNNXkc'..',,'',;:ccccccccccc:'.....,cc;'';d0NNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWWNNNXKOkxc,,,',,'...,;;;::cccccccc:,....;kXXXOo:;:xKNNNWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWWNNN0dl:;;;;,,'.....',,;;,,,,;:cccccc:;'..'ckXNNX0o:,l0NNNWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWWNNNXx:;::cccccc:,'.,;:cccccc:;,,;ccccccc:;,,,:oOKNNKxc,:kNNNWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWNNKxc,;:cccccccc;,',:cccccccccc:,',;:ccccccccccccok0Kkl:,:kNNNWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWNNN0:',;;;;;;;;;,'',,;;;;;;;;;;;;,'',;ccccccccccccccloxOkl,:0NNNWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWNNNO::dxxxx:......,oxxxxxl'....,:,,::;,,,,;:cccccccccxXKo,'oXNNWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWNNNNxckXNNNKxlccddcoKNNNNXklccodc,;:,......;cccccc:;',::'..;ONNNWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWWWNNNNNNNKxcoOXNNNNXX0d,'ckKNNNNNXKkc,;:;,......,:cccc:,........'xNNNWWWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWWNNNX0kdolllc;',codddoc,....';loddol;'';:cc:,'.'';:ccccc;'........'oXNNNNNNNWWWWMMMMMMMMMMMM    //
//    MMMMMMWNNNKdc;,,;;;;:;',:;'..................',:ccccc::::ccccccc;'.........;lddxk0KXNNNNWWMMMMMMMMMM    //
//    MMMMMWNNXk:,;:::;;,,;:,',:;,................,;::ccccc::::::::::c:;'.......';;;,,;;:lokKNNNNWMMMMMMMM    //
//    MMMMWNNNO:,::::,,,,;;::;,''''.............'',,,,,,,,,,,,,,,,,,,,,,'......,;::::::::;;;:oOXNNWWMMMMMM    //
//    MMMMWNNNx,;:::;',::::::::;,''........''',,,,;;;;;;;;:::::::::;;;;;;;;,,,,,,,,,;;::::::;,;oKNNNWMMMMM    //
//    MMMMWNNNk;,:::;;::::::::::;,'''',,;;;;::::::::::::::::::::;;;;;;::::::::::;;;,,,,,;;::::;,lKNNWWMMMM    //
//    MMMMMWNNXo,;::::::::::;;,,,,;;;:::::::::::::::::::::::::;,,,,,,,,,,,,;::::::::::;,,,;::::,;xNNNWMMMM    //
//    MMMMMWNNNKo,;:::::::;,,,,;:::::::::::::::::::::::::::::::::::::::;;,,;:::::::::::::::::::,,xNNNWMMMM    //
//    MMMMMMWWNNXx:,;:::::;,;:::::::::::::::::::::::::::::::::::::::::;,,,,;::::::::::::::::::;,c0NNNWMMMM    //
//    MMMMMMMWWNNN0o;;::::::::::::::::::::::::::::::::::::::::::::::::;;;,,;::::::;;;,;;;;;;;,;l0NNNWMMMMM    //
//    MMMMMMMMMWWNNXkc,;::::::::::::::::::;;;;;:::::::::::::::::::::::::::::::;,;:loddddollloxOXNNNWMMMMMM    //
//    MMMMMMMMMMWWNNNKo;;::::::::::;;,;;:cclllcc:;,,;;:::::::::::::::::::::;,;cdOKNNNNNNNNNNNNNNNWWMMMMMMM    //
//    MMMMMMMMMMMMWNNNXd,;:::::::;;:ldk0KXXNNXXXKOkdlc;,,;;:::::::::::::;,;:oOXNNNNWWWWWWWWWWWWWMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWNNKo,;:::::;,oKNNNNNNNWWWWNNNNNNX0xdoc:;;;;;;;;;;,;cokKNNNNWWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWNNN0c,;::::;,oXNNNWMMMMMMMMWWWWWNNNNNXKOxdollllodx0XNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWNNN0l,;:::;,cKNNWWMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWNNNKxc;;;;lONNNWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWNNNX0OO0XNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWWWNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CAB is ERC721Creator {
    constructor() ERC721Creator("Cody A Banks", "CAB") {}
}