// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: SeptaPaboy
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdoxkkkkkkkkkdodkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddkkkkkkkxxxddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdoxkkkkkxxxxxkkkkkkkkkkkxxxxdxxxxxddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkOO00OOOkkkkkkkkkkkkkkkkOOOOOOOOOOkkO0000OOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdoxkkkkkkkkkkkkkkkkxxxkkxxddxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkxxdooodxkkkkOO0000OOOOO000000000OOOkkkxxxkkkkkkOO00000Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdoxkkkkkkxxddddxxdxxddxxddxkkkkxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkkxxxxxkkkxdooooodk0XNXNWWWNNWWWWNNNNNWWWWWWWNNNNXXK00OkkkkkOO00KK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxooodxxxdoddddoooodddxooxkkkxdoddxxxdddddddxxkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkkkkO0KXXXXKKK0kdoodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWX0kxddxxkO00KKK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddddooxkkxdxdodxxdxkkkxodddxdxxxkkkkkxdddddxkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkOO0KNWWMWWWWNXK00Okkxook0NWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNWWWMWWWXOxoooolooxkO0KKKK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddkkkkdoxkkkkxdxkkkkkkkkxxdxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkOO0XWMMWWWNXXKK00Oxddddxkkxxk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNNNX0kdooooooooodkO0KKK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkddddddddkkkkxdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOO00XNWMMMMMWNNX0OkdoooooooooxO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXXK0kddoooooooooooodxO0KKK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkkkkkkddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOO00KNWMMMWWNNNNNNXXXKOdooooooodx0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkdooooooooooooooooxO0KXK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOO0KKNMMMMMMMMWWWNNXXK000kdoooooooox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMWNXNNWMWXXK0kxoooooooooooooooooodk0KXK0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKKKNWMMMMMMWWNNNXXK00OOOO0KKKOkxdoodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXNWWWNXKKKOkxxdooooooooooooooooooooloooxOKXX0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKNWWMMMMMWNNXKKKKXXKKXXXKK0OOOOO0KXK00KNMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMWNXXKK00KNWNK0kxoloooooooooooooooooooooooooox0XXKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMWWNWNXK0OOkxddoodxO0XNWMWX00KXWMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNWWMMMMMMMMMMMMWX0OkO0KNNNX0kdoooooddooodxkkxdoooooooooodkKXX0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMMWWNNXKOxddooooolldkKNNWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNXKKKXNWWMMNXK00OxoodxkOXNNKOxoooxOO0KXNNNXK0OkkxddoooooxOXX0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO00KXNNMMMMMMMWNX0kxxkxxdooooooooooxKNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKK0OkkO0KKOxdoooolooloxOKNWX0kddOXWMMMMMMMWNNXKOkxddooodOXX0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO0XNWWMWNNWMMMMMMWNX00OkkdollooooooooookXWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMWMWNKOxddxdoooooooooooooxOXWWX0O0KNWMMMMMMMMMMWXXKOOkdoodOXXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO0XNWWNXKKXNWWMMMMMMWWNXKKKKK0kxxdolooxkxxk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXNWWMMWNNWMMMMMMMWNX0kdooooloooooooooodkKWWMMWNWMMMMMMMMMMMMWWWNXKkdloxKX0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKNWNX0O0KXNWWWNXXKKXXNNNXK0OxxxddxxkOOOKXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKXWWNK0KWMMWXKKK0KKK0kdoooooooloooooodx0NWMMMMMMMMMMMMMMMMMMMWWWKkoookXKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKNNX0Ok0XNWMMMMWWNNXXK000OkxxdddooooodOKNMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKKXWX0OO0NN0kxxxddk0K0xooooooooooooddddOXWMMMMMMMMMMMMMMMMMMMMMW0xooxKXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKNXKOkO0XWMMMMMMMMMMMWWWWMWNK0OkdoooodxxxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKKNXKOxkOkdodddoodOKKOxooooooooodOK0kxONMMMMMMMMMMMMMMMMMMMMMMNOdooOX0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKX0OkOKNWMMMMMMMMWWWNNXK0O00K0kkxxdoloxKNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMWKOO0KKxddxdooooooodkKXKkdoooooxxdONWKkkKWMMMMMMMMMMMMMMMMMMMMMWXkookK0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0K0OkOKNWMMMMMMMMMNX0OOOOxxxdoodddddooood0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWMMMNOddk0OdooooooooooodOXNXOdoxkkkOkk0NWX0XWMMMMMMMMMMMMMMMMMMMMMMW0dox0KOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk00OkOKNWMMMMMMMMWKOOO0KXNNKOxoooooodkOkdxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMNXKNWMNXX0xoxkdoooooooooooodONWXOdx00OO0OkKWWWWMMMMMMMMMMMMMMMMMMMMMMMWXkod0Kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO0Okk0NWMMMMMMMMWKkkKNWMMMMMMMNKkooooooxO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMWWMMWXOOXNX0K0xoooooooooooooooooxXWWXkdkXNXNXOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMNOodO0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO0OkOXWMMMMMMMMWXkkKWMMMMMMMMMMMMWKxdxxddox0NMMMMMMMMMMMMMWNXXXWWWMMMMMMMMMMMMMMMMMMWXKXWWNWMMN0xOXNKkxooooooooooooodkkkddONMW0xONMWWWX0KNMMMMMMMMMMMMMMMMMMMMMMMMMMW0ddO0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkk0NWMMMMMMMMN0kKWMMMMMMMMMMMMMMMMN0kOKXKkk0NMMMMMMMMMWXKKKXNWNNNNWWWMMMMMMMMMMMMMMMMNK0XNKXWMWKxxkOkdoooooooddoooodx0NXkoONMMXkkXWMMMWXKNWMMMMMMMMMMMMMMMMMMMMMMMMMWKxx0Okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMMW0k0WMMMMMMMMMMMMMMMMMMMMXO0NMWNXNWMMMMMMN0O0KWMMMMNKXXXWNNMMMMMMMMMMMMMMMMWXOKXKKNMMNkddxxoooooxxkOkxdodkkKWNOOXMMMW0kKWMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMXxkKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NWMMMMMMMWXkkXWMMMMMMMMMMMMWNNWWMMMMMWK0NMMMMMMMMWXOO0NMMMMMMMWXO0KXNKXWMMMMMMMMMMMMWWWMN0OXKOXWWXOxodoooodk0XXXXKOdx00KWWNNMMMMMX0KWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWKxOKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWMMMMMMMMW0xONMMMMMMMMMMMMMMNK0kkkO0XWWWXKNMMMMMWXOkKNWMMMMMMMMMMKxkOKN00NMMMMMMMMMMMMNXNWWKO0Ok0XNNKxooodxddOXWWMWWXOkXXXWMMMMMMMMWXNMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d00kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWMMMMMMMMNOxKWMMMMMMMMMMMMMMMWNKOxoookXWWMNXWMMMNOkKWMMMMMMMMMMMMMW0ddx00k0NWMMMMMMWNWWWWXXWWXkxkkxk0XNOooodOkdkXMMMMMWK0XWWMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOkK0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMMNkxXWMMMMMMMMMMMMMMWXKKOxdoox0WMMMMMWWW0x0NMMMMMMMMMMMMMMMMWOooodddk0KXXNWWN00X0O0K0KXKkdddooxKN0doodO0kONMMMMMMNKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkOKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMMXxxXWMMMMMMMMMMMMMMMWN0kdoooookXWMMMMMMKOXWMMMMMMMMMMMMMMMMMMNOoooooooddddkOOkxk0kodkxkOOxooooodONKxookKWXXWMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxKKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMMMMMMMMMXxxXMMMMMMMMMMMMMMMWX00KKXKKOkdokXWMMMMWNNMMMMMMMMMMMMMMMMMMMMMW0dooooddoooooooodkkxoooooddooooolokXXkoo0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkX0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMMXxxXMMMMMMMMMMMMMMMNOkKWMMMMMMWN0O0XWMMMMWMMMMMMMMMMMMMMMMMWNNWMMW0dooodO0kdddxxdodkxoooooloooooooooxKN0ddKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWW0x0XOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOKWMMMMMMMMNkdXMMMMMMMMMMMMMMWKk0NMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMNK0kxooOWMMW0ddxxkXNXK0OOOkxxkkooooloolooooooodKWXxxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWMMMMMMMMMMMMMMMMMMMMMMMNXXkxXKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWMMWWWMMMWOdKWMMMMMMMMMMMMMNOkXWMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMWN0kolccccco0WMMW0ddO0KNWMWNXKKK0kOOxooooooodxdoodkOXMNOkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMWKKKxOXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMWNXWMMMW0d0WMMMMMMMMMMMMMXO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNWXOdllllllllccdXMMWNKkxOXWWMMMWWWNNNKO0OdlooodxkOkxx0XXWMWXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMXOKOxXKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkXWMXKNMMMMXxOWMMMMMMMMMMMMMXOKWMMMMMMMMMMMMWNXKKKK00XWMWNKOddxd:,,,,'',,,;:clOWMWKKKOkKNMMMMMMMMMMMNKKKkdoodxOKXXXNWWMMMMWNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWMMMMMMMMWWMMMMMMMMMW0k0xON0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NWX0XWMMMWkkNMMMMMMMMMMMMMX0XWMMMMMMMMWNKOxdolcccccco0Xx:,....             ..:0MWXkOKOOXWMMMMMMMMMMMMWNWXkoookNNWWWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMWNNMMMMMMMMMXxkkkXXkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWN00WMMMMKxKMMMMMMMMMMMMMX0XWMMMMMMMWKkocccccccccccll;'.                      cNWWXxx00OXWMMMMMMMMMMMMMMMWXkddkNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNMMMMMMMWXNMMMMMMMWNOoOO0N0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXW0OXMMMMNOOWMMMMMMMMMMMMN0KWMMMMMMWXxlccccccccccccll'                         .kWMWXdoO0O0WMMMMMMMMMMMMMMMMWNXOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNWMMMMMMNXNMMMMMMWX0ddkOXXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NXO0WMMMMKONMMMMMMMMMMMMWKKWMMMMMMW0occcccccccccccol.                          .cXNWWKdcd000XMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMNKNMMMMMMW0dodx0N0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKN0kXMMMMWKKMMMMMMMMMMMMMXKNMMMMMMWOlccccccccccccclo'                            'kKOXWXdclx00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKNMMMMMMXXWMMMMMMXxlooxXXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXXO0NMMMMNKNMMMMMMMMMMMMNKXMMMMMMWOlcccccccccccccco:.                            .cOkd0NXxcclk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0NMMMMMWKXWMMMMMWOooodKW0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NKkKWMMMWXXMMMMMMMMMMMMMKKWMMMMMW0lcccccccccccccclo'                             .,oOocd0XOoccokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKOXMMMMMNKXWMMMMMXdlooONXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKN0kKWMMMWXNMMMMMMMMMMMMNKXMMMMMMXocccccccccccccccol.                             .,;dx::;oK0dlccokKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNKkKWMMMMX0KWMMMWNOoolxXN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKXOOXMMMMNNWMMMMMMMMMMMMXKWMMMMMWOlcccccccccccccccoc.                             .,;;xo;:.,xklllcclxKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKX0kKWMMMWK0KNMMNX0doooKWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk    //
//    kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKXkONMMMMNNMMMMMMMMMMMMWKXMMMMMMWOcccccccccccccccco:                               .:':k:;:..ox:,cloclx0XNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO00k0WMMMN0O0NMNKKxlooOWXOkkkkkkkkkkkkkkkk                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SPOP is ERC721Creator {
    constructor() ERC721Creator("SeptaPaboy", "SPOP") {}
}