// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The Puppet Workshop Customs
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#################################################################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#######&&&&&#####################################################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&##BGPPY5???!?!77!?7JJYPPBB###################################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&##GP5YJ??7!!!!!!!!!!~~^^::.:.^^?J5GB##############################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&##GPYYJ??JJYY5P5PGPPPPGPP5PP55Y?7~^:..:~?YB###########################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&&&&#BGPYYJYYYP5YY5YYPYJ5YJY7J7J7?Y7?5Y?YPPY?~:..^!5G########################                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&&&##BP5YYYYPP5Y5BY???J?J5?755J?7?7?7??7~!7JYJYPPY7^..:75B##################&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&&&##GP5555PP55P5JJYPYJJPJ!YY!J?YY?Y!???7~^~?YJ7!J?J5P5?:.:~YB################&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&&##BP555PPPPP5YY5555YG5??J?Y5?5?~YYJJJ7~~!!?77?!!~77!?Y5PJ~..^YB############&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&&#BGPPPPPP55YY5GP5YJYJ5PYYJ7YP??Y?!7YJ77???!7^...  .~??77?PGY~:.~5B#########&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&&#BPPPPPP555PGGPP55YJ7~^~7JJ5J?JJJ?7?J!??J?!^..::^^^::!77!7?J5GY^.:?G######&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&&#GGPPGGGGGPPGBGPPPP55YJ!^..:7YJ7JJJJ57?JJ?!~~~~!!!!!!!~!!~~7??J5P?^:!P#####&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&&BGPPPGGPPGB##BBGGGGGGGGGP5J!: .7JYJ7Y5?YYY?????JYY555YYJ?JJ7~~!??YG5~:~P####&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&BGGPPGPGPPPB#BBBBGGGGGGGGGGPP5?^.^J5J?JJP5YYY5PGP555G#Y7?Y?!7???7??JGG!^~P###&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&#GGGGGBGGPPG#BBBBBBB####BBBB#BBP5?^^5PJ?YGPPGBPY7~^:::JBJ:^JJ?77!!!!!?5G7~7G###&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&#BGGGGGPGGBBBBB####GBBP5YYJJJJ5G#BPJ!!GP?5BB#GY?7!~~~^^~5#J!7J?!!!!!~~^~YP7!?B&#&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&BGGGGGBGGBBBGGPB#BGGBPP55YYYJJ??JP##P?YB5Y##BPYY55Y77777YB5JY?777?JJ???JJPP775#&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&#BGGGBBBBBGGGGGP##BGBBGGPPGGBGYYJJJYG&B5#G55PGPPPBPPYJJJYPGPPJ?JJJJ??JJ?JY5BY7JB&&&&&&&&                                                                                                                                                                                                            //
//    @&&&&&&&&&&&BBGGGBBBBBBBBBBG###GGBBGGGBBBBP5YYYY5B&BGG5J7?JYY55YYYYY5GG5??J55J?????J77?PGJ?5#&&&&&&&                                                                                                                                                                                                            //
//    @&&&&&&&&&&#BBBGBBBBBBBGGBBG#&##PGBBBBBBBGPPPPPPGBGPJJ7~^::^~!!!7?J5YY5J!^:~J5YJ??JYYYJYBYJY#&&&&&&&                                                                                                                                                                                                            //
//    @&&&&&&&&&&#BBBGBBBB#BBBBB#GB#&&#GPPGBBBBGGGGGGBGP5YJJJ?7!~^^~~^^::^^?777J55Y5GP5YJYYYYYGPJJB&&&&&&&                                                                                                                                                                                                            //
//    @&&&&&&&&&&BBBBGBBBB##BBGB#BBBGB#&&#BGGGBBBBBBBGPP55555YYJJ?777?7777?!~7P#&&B5P555YYJJJJPGYYG&&&&&&&                                                                                                                                                                                                            //
//    @@&&&&&&&&&#BBGGB#####BBB#BBBBBGGBBGPPP5555GBGGGGGGGPPPPP555YYYYYJJJJYPB&&&&B55PP5YJY555PB55G&&&&&&&                                                                                                                                                                                                            //
//    @@@&&&&&&&&BBBBGBBB#B##B#BB#B###BBGBGGGP5YYY5GBBBBBGGGGGGGGGGGGGPPPGB#&&#B#&#55PGGGPP555PB55G&&&&&&&                                                                                                                                                                                                            //
//    @@@@&&&&&&&#BBBGB#####B#BBB########&&&&&&##BBGBBBBBBBBBB#BBBB######&&&##BBB##55GP5555555GG55B&&&&&&&                                                                                                                                                                                                            //
//    @@@@@&&&&&&#BBBGBBB##BB#BBBB&&##&&@@@@@&&&&&&&&########BB######&&&&&##BGBB###5YPP555P555GGPPB&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@&&&&#BB#GBBB#&######&&#B#@@@@@@@@&#BB###&&&&&&&&&&&&&&&&&&&###B#P5PPGBYYJY5PP5PP5BP5P#&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@@&&&&#BBBGBB###BBB##&&BG&&&&&&&@@@&BPGGB&@@@@@@&&&&&&&&#######B#&#GPP5YY55PGBBPPGGPPB&&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@@&&&&###BGB######&#&&&BP#&&&&&&&&&@&###&&&&&&&&&&&&&&###########&@@&##&&&&BPPPPPGGGG#&&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@@@&&&&#B#BGB#####&#&&&#GB&&&&&&&&&@@&&&&&&&&&&&&&#P5G############BPYY5G##BGGGPPGGGG#&&&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@@@@&&&##BBBGBBBBB##&&&&BP#&&&&&&&&&&&&&&&&&&##BBBPY77P#########BPYYPGBBBBBGPPPGGGGB&&&&&&&&&&                                                                                                                                                                                                            //
//    @@@@@@@@@&&&&&##BBBGBBB####&&&#GP#&&&&&&&&&&&&&&&#BG5J?5GGPJJG######BP5PGB#####BGBGPGGGGB&&&&&&&&&&&                                                                                                                                                                                                            //
//    &&&&&&&&&&&&&&&####BG#####B&&&&&GPB&&&&&&&&&&&&&&#BBGPYJYGBPYYB&&#BGGB##BB##BBBBGPGGGGGBBB##########                                                                                                                                                                                                            //
//    &&&&&&&######&&&####BGB&&&##&&#&&#P5PB&&&&&&&&&&&&&&##BPYJ5GG5PGGGB###BB###BBBGGGGGGGGGPPPGGGGGGGBBB                                                                                                                                                                                                            //
//    ###############&&####BBB####&&###&&#PYY5PB##&&&&@@@@@&&&#G55GG5PB##BBBB##BBBBGGGGBBGGPYYY5555PPPPPGG                                                                                                                                                                                                            //
//    ##############B#&&&####BBB##&&&&####&&#G5YYYYY5PPGB##&&&&&&#GGG##BBBB###BBGBBGGGBBBPYJJJYYYY55555PPP                                                                                                                                                                                                            //
//    ###############BB#&&#####BBB##&&&&##B###&&&##BGGGGGGBB#&&&&&&&#BB#####BBBBBGGGBBBG5???J?JYJYYYY555PP                                                                                                                                                                                                            //
//    #############B###BB##&&####BBB##&&&&&&#######&&&&&###BBB##&&&&###&##BBBBBBBGBBBG5J???J??JJJJYYY55555                                                                                                                                                                                                            //
//    ################B#BB#########BBBB#&&&&&&&&#####&&&&&&&&#&&&&&&#####BBBBBGGBBBG5J?7?J???JJJJYYYYYY55P                                                                                                                                                                                                            //
//    ##################BB#BGBB#######BBBBB###&&&&&&&&&####&########BBBBBBGGBBBBBPYJ?????J????JYYYYYY5P5Y5                                                                                                                                                                                                            //
//    ####&&####B#######BB#BBBGBBB########BBBBBB#######&&##&&####BBBBGGGGBB###GPYJ??J?J?JJJJYJJYJYYYY55Y5P                                                                                                                                                                                                            //
//    #&&&&&####&###&######BBBGB#GGBB###&#####BBBBBGGGGBBBGGBBGGGGGBB#########GPP5YJJJJJJJYJJJY5JJY5YY5GG5                                                                                                                                                                                                            //
//    &&&&&##&&&###&&##&###B##BB&BG#BGG##&&&&&&&############################BBBBBGPP5YY5YJJYY5Y5YY5555PPPP                                                                                                                                                                                                            //
//    &&##&##&&&&#&##&#&#######B&###&#&&&@@@@@@&&&&&&&&############BBBBBBBBBBBBBBBBBGGPP5YY5555Y555P555PPP                                                                                                                                                                                                            //
//    &&##&&&###&####&##&&##&##&###&&&&#####################B###BB#BBBBBB#BBBBBBBBBBBBBGGPPPP55P5Y555PPP5P                                                                                                                                                                                                            //
//    ##############B######B##########################B########BB#####BBBBBBBBBBBBBBBBBBGGGGGGPP55P5555PGG                                                                                                                                                                                                            //
//    ##########B###B###############################################B#BB#BBBBBBBBBBBBBBBBBGGGGGP5PP55PPGGP                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TPWC is ERC721Creator {
    constructor() ERC721Creator("The Puppet Workshop Customs", "TPWC") {}
}