// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Mouth {
  using Strings for uint256;
  string constant MOUTH_MOUTH___ANXIOUS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAP0lEQVR42uzRMQoAMAgEsPP/n+7QxaW02DUHTkJUTH0mAAAAAHgCdi/JeIO0mp1wme6NAAAAAAAAAIBTlgADAK4vD/cR1jg5AAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___BABY_TOOTH_SMILE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA////////c3ilYwAAAAN0Uk5T//8A18oNQQAAADpJREFUeNrs0TEKADAIBMEz/390wD5gsJ1tlQExZ1kAAAAAMAMy33lNu+UJ5Y0AAAAAAAAAgP+uAAMAa4of8AL3yZMAAAAASUVORK5CYII=";

  string constant MOUTH_MOUTH___BLUE_LIPSTICK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFUGv/S2Le////rt5oUQAAAAN0Uk5T//8A18oNQQAAADtJREFUeNrs0cEJACEQBMH28g9aAxBO2G91AMXA9A0LAAAAAM9AjYDWqcmC+pvgRgAAAAAAAADArS3AAE2zH+2klLMNAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___FULL_MOUTH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFNTU1AAAA////0A2dowAAAAN0Uk5T//8A18oNQQAAAEBJREFUeNrs0iEOACAMA8DC/x8NjpBgBpKrmWhzaumPCQAAAPwBJPutAqmuTlWbuQZWF38AAAAAAAAAAChmCDAAHnkf6fOp8jgAAAAASUVORK5CYII=";

  string constant MOUTH_MOUTH___MISSING_BOTTOM_TOOTH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA////////c3ilYwAAAAN0Uk5T//8A18oNQQAAADhJREFUeNrs0cEJACAQA8HE/ov2YwN64Gu2gCGQrGEBAAAAwCcgp/cFadN4AQAAAAAAAABw3RZgABpJH+jnE47kAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___NERVOUS_MOUTH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAN0lEQVR42uzRsQkAIAADwXf/pQVxARWs7iHtNWk8FgAAAAA+AdXaPbAJLwAAAAAAAAAATpsCDACa4Q/1sglxFAAAAABJRU5ErkJggg==";

  string constant MOUTH_MOUTH___OPEN_MOUTH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAOElEQVR42uzRsQkAMAwDQWX/pQOuDSkEqe57HwLnlAUAAAAAv4BMzYLnvS8AAAAAAAAAANauAAMAr3QP90EGRPYAAAAASUVORK5CYII=";

  string constant MOUTH_MOUTH___PINK_LIPSTICK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF4GDl////yw5CGAAAAAJ0Uk5T/wDltzBKAAAAOUlEQVR42uzRsQkAMAwDQXn/pQOpAw6ove99CJwpCwAAAAC+gaQCcmsWrPfeCAAAAAAAAAB4dgQYAJnfD/XVqKI6AAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___RED_LIPSTICK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZ3ktT////91YocAAAAAN0Uk5T//8A18oNQQAAADtJREFUeNrs0cEJACEQBMH28g9aAxBO2G91AMXA9A0LAAAAAM9AjYDWqcmC+pvgRgAAAAAAAADArS3AAE2zH+2klLMNAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___SAD_FROWN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAOElEQVR42uzRsQkAMAwDQXn/pQPp0pkYXN3X4hqlhgUAAAAAW0Bu/0D6Gy8AAAAAAAAAAJ6OAAMAxAUP+bDZ4t4AAAAASUVORK5CYII=";

  string constant MOUTH_MOUTH___SMILE_WITH_BUCK_TEETH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA////////c3ilYwAAAAN0Uk5T//8A18oNQQAAADpJREFUeNrs0TEKADAIBMEz/390IH1AtJ1tlQExZ1kAAAAA0APS3/lNX6sTqrwRAAAAAAAAADDoCjAAYUAf7yk/D1EAAAAASUVORK5CYII=";

  string constant MOUTH_MOUTH___SMILE_WITH_PIPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFzs7OiW8+AAAA////Igr54gAAAAR0Uk5T////AEAqqfQAAABYSURBVHja7NNLCsAgEATRGr3/nYMLdxpCGiKB6o2recwH6WEQEPgfABlABrBs4DkA4Q44fQXCDsiBbIR9/T3Q5lP1coltpEb8zgICAgICAgICAt8ClwADAGw7L7BSiUgtAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___SMILE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAN0lEQVR42uzRMQoAMAgDwPj/TwvdC4LgdFkTbklqmQAAAABgBmS++bUvXgAAAAAAAAAA3AMtwADDAQ/5B23EaQAAAABJRU5ErkJggg==";

  string constant MOUTH_MOUTH___SMIRK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAPElEQVR42uzRwQkAIAADsXP/pcUNREEQ0nebTxuXCQAAAP4C6hBoo9bGvgugFTcCAAAAAAAAAN4DU4ABAIuXD/QMyW3bAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___TINY_FROWN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAN0lEQVR42uzRsQkAMAwDQWX/peMBDCkEqe5rcY1yygIAAACAj0CmDnhsvAAAAAAAAAAA2LoCDADZJA/7BAcUuAAAAABJRU5ErkJggg==";

  string constant MOUTH_MOUTH___TINY_SMILE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAN0lEQVR42uzRsQ0AMAgDQbP/0skEERES1X1rdA2pYQEAAADAGpDOxXO++QIAAAAAAAAA4L8jwADZmg/7DSgAAAAAAABJRU5ErkJggg==";

  string constant MOUTH_MOUTH___TONGUE_OUT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA4GDl////7QoSFwAAAAN0Uk5T//8A18oNQQAAADhJREFUeNrs0YEJACAMA8G0+w8tzlCwCPcDHIGkhwUAAAAAz4DcZguqehlwIwAAAAAAAMCPwBFgAI13H/PplSVCAAAAAElFTkSuQmCC";

  string constant MOUTH_MOUTH___TOOTHY_SMILE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA////////c3ilYwAAAAN0Uk5T//8A18oNQQAAAD1JREFUeNrs0TEKADAIA8C0/390oUO3guJ6GVwMB2L2MAEAAABADUi989veDE5Yb3gjAAAAAAAAAKCVI8AAYUAf76VMPZsAAAAASUVORK5CYII=";

  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 0) {
      return MOUTH_MOUTH___ANXIOUS;
    } else if (assetNum == 1) {
      return MOUTH_MOUTH___BABY_TOOTH_SMILE;
    } else if (assetNum == 2) {
      return MOUTH_MOUTH___BLUE_LIPSTICK;
    } else if (assetNum == 3) {
      return MOUTH_MOUTH___FULL_MOUTH;
    } else if (assetNum == 4) {
      return MOUTH_MOUTH___MISSING_BOTTOM_TOOTH;
    } else if (assetNum == 5) {
      return MOUTH_MOUTH___NERVOUS_MOUTH;
    } else if (assetNum == 6) {
      return MOUTH_MOUTH___OPEN_MOUTH;
    } else if (assetNum == 7) {
      return MOUTH_MOUTH___PINK_LIPSTICK;
    } else if (assetNum == 8) {
      return MOUTH_MOUTH___RED_LIPSTICK;
    } else if (assetNum == 9) {
      return MOUTH_MOUTH___SAD_FROWN;
    } else if (assetNum == 10) {
      return MOUTH_MOUTH___SMILE_WITH_BUCK_TEETH;
    } else if (assetNum == 11) {
      return MOUTH_MOUTH___SMILE_WITH_PIPE;
    } else if (assetNum == 12) {
      return MOUTH_MOUTH___SMILE;
    } else if (assetNum == 13) {
      return MOUTH_MOUTH___SMIRK;
    } else if (assetNum == 14) {
      return MOUTH_MOUTH___TINY_FROWN;
    } else if (assetNum == 15) {
      return MOUTH_MOUTH___TINY_SMILE;
    } else if (assetNum == 16) {
      return MOUTH_MOUTH___TONGUE_OUT;
    } else if (assetNum == 17) {
      return MOUTH_MOUTH___TOOTHY_SMILE;
    }
    return MOUTH_MOUTH___ANXIOUS;
  }
}