// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Salisby Dalisby 15/29
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//    SalisbyDalisbyBooksArt,Aliasnewnamefromthedarklords”AbudaAtta”,abudawasgiventhetaskofbeingtransportedaroundtoservicetheprisonersinthepyramidtechnologyfields,thenlaterservicedoneorbforastageplayorganizedbythedarklords,acontributiontothedarklordspropagandascamforprocessingthelightedfamilyintodeeperslaverydarkregions,AbudaAttaafterbeingattackedthosandsoftimesbythedarklordsmonstersgroup,awakenedfromhislongtechnologydazebacktorealalityofhisdutyasoneofmanycaretakersoftheUniversesbabies,thecaretakershavebeenorderingtheprocessingofthedarkmonstersgroupintonothingforalongtimenow,thepopulationofdarkmonstersknownasdeadmenhavebeendecreasinglargenumbers,SalisbyDalisby’sjournalstory.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract VFotm is ERC721Creator {
    constructor() ERC721Creator("Salisby Dalisby 15/29", "VFotm") {}
}