// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: hide
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    odoooolllllllllllllllllllllllllllloodddddoooollllllllllllllllccccccccccccccccccccccc::::c:::::::::::::::cccccc::::::::::cccccc::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''..'''''''''.....................''''''''''''''''''''''    //
//    oddoooollllllllllllllllllllllllllllloooooooooolllllllllllllllllcccccccccccccccccccccc:::::::::::::::::::::::::::::::::::cccccc:::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,'''''''''''''''''''''''''''''''.....''''''''.....................''''''''''''''''''''''    //
//    oddddoollllllllllllllllllllllllllllllloooooooooollllllllllllllllllcccccccccccccccccccccc::::::::::::::::::::::::::::::::::::::c::::::::::::c:::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,''''''''''''''''''''''''''.....................................''''''''''''''''''''''    //
//    odddddoollllllllllllllllllllllllllllllllooooooooooolllllllllllllllllccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::cc::::::ccc:::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,''''''''''''''''''''''''......................................''''''''''''''''''''''    //
//    lddddddooolllllllllllllllllllllllllllllllllllooooooolllllllllllllllllccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::ccccccccccc::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,''''''''''''''''''''''''.....................................''''''''''''''''''''''    //
//    looddddoooolllllllllllllllllllllllllllllllllllllooooollllllllllllllllllllccccccccccccccccccccccccc::::::::::::::::::::::::::::::::cccccccccccccccc:::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''.....................................'''''''''''''''''''''    //
//    looodddddooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::cccccccccccccc:::::::::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''.........................'.........'''''''''''''''''''''    //
//    loloodddddooolllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::ccccccccccccccccc:::ccc:::::::::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''........................''''''''''''''''''''''''''''''''    //
//    lllloooddddooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''.....................'''''''''''''''''''''''''''''''''    //
//    llllloooddddooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::::;;;;;;;;;;;,,,,,,,,,,,,,,,''''''''''''''''''''''''''''....................'''''''''''''''''''''''''''''''''    //
//    lllllloooodddooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,'''''''''''''''''''''''''''''..................'''''''''''''''''''''''''''''''''    //
//    llllllloooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''...........'''''''''''''''''''''''''''''''''    //
//    llllllllloooooooooolllllllllllllllllllllllllllcllllcllllcclllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''........''''''''''''''''''''''''''''''''''    //
//    cllllllllllooooooooollllllllllllllllllllllllllclllcccllcccccclllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    //
//    cllllllllllloooooooooollllllllllllllllllllllllllllccclllccccccccccccccccccccllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    //
//    cllllllllllllloooooooollllllllllllllllllllllllllllccclllllcccccccccccccccccccccccccccllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    //
//    clllllllllllllloooooooolllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccclccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.''''''''''''''''''    //
//    cllllllllllllllllooooooolllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..''''''''''''''''''    //
//    cllllllllllllllllllooooooolllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''..''''''''''''''''''    //
//    cllllllllllllllllllloooooooolllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''.''''''''''''''''''    //
//    cllllllllllllllllllllooooooollllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.......''''    //
//    llllllllllllllllllllllooooooolllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........'    //
//    lollolllllllllllllllllllooooollllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,',,'''''''''''''''............''''''''''''''''''''''''''''..........'    //
//    lollolllllllllllllllllllloooooloolllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,''''''''''''................'''''''''''''''''''''''''''.''''''''''    //
//    lolllllllllllllllllllllllloooooollllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,''''''''''''''''...........'''''''''''''''''''''''''''''''''''''''''    //
//    loolllllllllllllllllllllllooooollllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,''''''''''''''''''''''.....''''''''''''''''''''''''''''''''''''''''''''    //
//    loolollollllllllllllllllllloollllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,''''''''''''''''''''''''''..''''''''''''''''''''''''''''''''''''''''''''    //
//    looloooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::;;;;;;;;;;;;,,,,,,,,,,,,''''',,'''''''''''''''''''''''''''''''',,'''''''''''''''''''''''''''''''''    //
//    loooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllccccllcccccccccccccccccc::::::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''',,,'''''''''''''    //
//    lololoollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllcccccccccccccccccc:::::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''',,,,,''''''''''''    //
//    loooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccllllllllllllcccccccccccccccccccc:::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    //
//    looooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccclllllllllllllccccccccccccccccccccc:::::::;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    //
//    looooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccclcccccccccccllllllllllllllllllllllllcccccccccc:::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,''''''''',,''',,,''''''''''''''''''''''''''''''''''''''''''''''.''''''''''    //
//    looooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccclccccccccccclllllllllllllllllllllllllllcccccccc:::::::;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,''''''''''',,,,,,''''''''''''''''''''''''''''''''''''''''..............'....    //
//    loooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccclxxlcccclcllllllllllllllllllllllllllllccccccc::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''''.......................    //
//    looooooooooooooooooooooooooooooolllllllooooooooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccdKNkcccllccllllllllllllllllllllllllllllcccccc:::::;;;;;;;;;,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcclccoOXXkcccllclllllllllllllllllooooooooolllccccc:::::;;;;;;;;,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''''''''''''''''..............................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccdOxkKxllllllllllllllllllllloooooooooolllccccc::::;;;;;;;;;,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''...................................................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllx0kx00ollllllllllllllllllllooooollllccccc:::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''.........................................................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldO00OKKxllllllollllllllllllloooooolcccc:::::;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''...............................................................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllokK0xdk0klllllllolllllllllllllllllllcc:::::;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''.................................................................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollloolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkOxl:cx0kolllllllloooollllllllllllcccc:::::;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''..................................................................    //
//    looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllloooooooolllllllllllllllllllllllllllllllllllllllllllllllllox0KOxddkKKxlllllllooooolllooooooollccc:::::::;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''..................................................................    //
//    loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllloxOOOkdddxO0Oollllllooooooooooooooooollcc::::::::;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''..'..................................................................    //
//    loodoodooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllldkOkxo:;;;cxOOxlllllllloooooooooooollllllcc:::::::::;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''................................................................    //
//    lddddddddddooooooooooooooooooddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllooxkkkkxooooxkkOkdlllllllllllooooooooooollllcccc::::::::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''................................................................    //
//    lddddddddddddooodddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllodOKK0xddddxk0K0kolllollllllllooooooooooolllcccc::::::::::;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,'''''''''''''''''''''''''''..............................................................    //
//    odddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooolllllllllllllllllllllldOK0xol:;;cdkOkdooolllllooooooooooooooooooolllccc:::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,'''''''''''''''''''''''''''''...........................................................    //
//    odddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooolllllllllllllllllloO0xl;;:lodk0Oxoloooooooloooooooooooooooodddoolllccccccc:::::::::::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,''''''''''''''''''''''''''''''''.....................................................    //
//    oddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooolllllllllllllldOkooddddkXXOdooooooooooooooooooooooooddoddddoollllccccccccc::cc::::::::::::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,''''''''''''''''''''''''''.'.'c                                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HZI is ERC721Creator {
    constructor() ERC721Creator("hide", "HZI") {}
}