// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Bridge To Consciousness
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    ::::::::::::::::::::::::::::::::::::::::::::::::::~?5GPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5GG5?~:::::::::::.:^~7Y5PPP5YJJJJJJJJJJJJJJJJJJJJJJJJJ5PG5?~::::::::::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::::::::::::^75PPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPP5J!::::::^!?Y5PP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPGY!::::::::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::::::::::!YGPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPJ~!J5PP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5G5!::::::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::::::::!5G5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5BBPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5GY^::::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::::::7PG5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPGYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPG!:::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::::!5G5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B7::::::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::::::^YG5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYYYYYJJJJJJJJJJJJJJJJJJJJJJ5B5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B?:::::::::::::::::::::::::::::::::::    //
//    ::::::::::::::::::::::::::::::::::::?GPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY55PPPPPPPPPPPPPPPPPPPPPP55YYJJJJJJJJJJJJJ5B5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B!::::::::::::::::::::::::::::::::::    //
//    ::::::::::::::::::::::::::::::::::^5BYJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPPP55YJJJJJJJJJJJJJJJJJJJYY55PPPPP5YJJJJJJJJJ5BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPG~:::::::::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::::::!GPJJJJJJJJJJJJJJJJJJJJJJJY5PPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPPP5YJJJJJPGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJBJ:::::::::::::::::::::::::::::::::    //
//    ::::::::::::::::::::::::::::::::JB5JJJJJJJJJJJJJJJJJJJJJYPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPPPPYJJYB5JJJYYY555PPPPPPPPPPPPPPPPPPPPPPPPPPPPP555555YYJJJ5B~::::::::::::::::::::::::::::::::    //
//    ::::::::::::::::::::::::::::::^YBYJJJJJJJJJJJJJJJJJJJJPGP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5PGPPBBPPPPP5555YYYJJJJJJJJJJJJJJJJJJJJJJJJJY5555555PPPPPBPYJ7!^:::::::::::::::::::::::::::    //
//    :::::::::::::::::::::::::::::^5GJJJJJJJJJJJJJJJJJJJJJJYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPBPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55PP5YJ!^::::::::::::::::::::::    //
//    ::::::::::::::::::::::::::::^PGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5GPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PP5J~:::::::::::::::::::    //
//    :::::::::::::::::::::::::::^PGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYYYYYYYYYYJJJJJ5PP5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPJ~::::::::::::::::    //
//    ::::::::::::::::::::::::::^PGJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY55PPPPPPPPPPPP5555PPPPPPPPPPPPPG##GYJJJJJJJJJJJJJJJJJJJJJJJJJYYYYY55555PPPP555555YYYYYJJJJJJJY5P57^:::::::::::::    //
//    ::::::::::::::::::::::::::5BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPPPP55YYYJJJJJJJJJJJJJJJJJJJJJJJJJYYY55PPGPYJJJJJJJJJJJJJJYY55PPPPPP555555YYYYYYYY5555555PPPPPPPPP55YP#J:::::::::::::    //
//    :::::::::::::::::::::::::?BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPPPP55YYJJ?JJJYY55PPPPPPPPPPPPPPPPPP55YYYJJJJJJJJ5PGPJJJJJYY5PPPPP55YYJJJJJJJJYYYYY55555YYYYYYYYJJJJJJJYY555PGPYJ!^:::::::::    //
//    :::::::::::::::::::.::^^7B5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPGP5YJJJJJJY5PPPPP55YYYYYYJYYYJJJYJYYYY555PPPPPP55YJJJJGB55PPP55YJJJJJYY55PPPPPPPPP55555555555555PPPPPPPPP55YYJJJJY5PPY~:::::::    //
//    :::::::::::::::::^~?Y55P#BJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PGP5JJJJJY5PPPP5YYYYJYYYYYJJJJJJYYY5Y55YYYYYJJJJJJY55PPPP5GG5YYYYY55PPPPPP555YYJJJJJJJJYYYYYYYYYYYYYYYYYJJYYYY55PPPPP5YJJPB?::::::    //
//    :::::::::::::::!YPP5YYJYB5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPP5YJJJJJYPGP5YYY55YJ???JJJJJ7777!^:....:^^^~!7Y555555YYJJJY55JYPPPPP55YYJJJJJJJJYYY5Y5YYY55PPPGGGBBPYJ????YY5P5YYYJJJYY5PGP5B5:.::::    //
//    ::::::::::::^?PG5JJJJJJPBJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5PPPPPP55YJJJJJY5PPP5YY55JJ7~^[email protected]@@@@@@@&#GJ^         .::^!7JY5PPP5YJYYJJJJJJJJJJJYY55YJ?!~!JPB#GP#@@@@@@@@@&BJ^  ..:^~!?JPP5JJJJY5GGY7::::    //
//    :::::::::::7GGYJJJJJJJJGPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYJJJJJJJY55PPP5YY5YJ!^:. [email protected]@@?..?&@@@@@@@@@@&P^               .:^!?J5GPJJJJJJJJ55Y?7!:.  .J#@@@5. :[email protected]@@@@@@@@@@&Y.        :JPGP555YJJ5PP7::    //
//    :::::::::^YB5JJJJJJJJJYBYJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYYYY55PPPP5YYJY5Y7^.     ^[email protected]@@@@[email protected]@@@#GG#@@@@@#!                    .^JGYJJJ5YJ7^.      :[email protected]@@@@&[email protected]@@&B5J5B&@@@@P:          .::~!?YPPYGG^:    //
//    ::::::::~PGJJJJJJJJJJJ5BJJJJJJJJJJJJJJJJJJJJJJJJJJ5GP5PPPP55555YYJJJJYYJ!:        [email protected]@@@@@@@@@@@@5.  .?&@@@@#~                      ?B5PY!:          [email protected]@@@@@@@@@@@@B^   :[email protected]@@@@5.                :!G#!^:    //
//    :::::::7BPJJJJJJJJJJJJGGJJJJJJJJJJJJJJJJJJJJJJJJJJBPJJJJJJJJJJJJJJY5Y7:           ^#@@@@@@&[email protected]@@#?::[email protected]@@@@@Y                      ~#Y~.           [email protected]@@@@@@BTC&@@@[email protected]@@@@@#^                  :PP!:    //
//    :::~::JBYJJJJJJJJJJJJJG5JJJJJJJJJJJJJJJJJJJJJJJJJJYGP5555555YYYYY5J~.             !&@@@@@@&?^[email protected]@@@@&&@@@@@@@@G.                    .5?              :[email protected]@@@@@@BTC&@@@@@@@@@@@@@@&!                   ^#J.    //
//    :::~^JBYJJJJJJJJJJJJJJYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYY55555PB#?                [email protected]@@@@@@@@@@@@@@@@@@@@@@@@@P.                    75.              ^#@@@@@@@@@@@@@@@@@@@@@@@@@#^                   7#?.    //
//    :::~5BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5P5?^.            !&@@@@@@@@@@@@@@@@@@@@@@@@@?                    :P~               [email protected]@@@@@@@@@@@@@@@@@@@@@@@@Y.                .7PG?~:    //
//    :::5BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55YJ!^.        [email protected]@@@@@@@@@@@@@@@@@@@@@@#?.                 .:!GY                 ~#@@@@@@@@@@@@@@@@@@@@@@B?.            .^~?YP5J~:::    //
//    ::5BJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY555J!^.     .?#@@@@@@@@@@@@@@@@@@@B?:               .~7Y5PPGG?~:.              :J&@@@@@@@@@@@@@@@@@&G7.     ..:^!?JY5PPP5GB^^~:::    //
//    :YBJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ55YJJJJJJY5P5YJ7~:  :?P#&&@@@@@@@@@&#G57.         .::~7??J5P5YJJJJ#BPP55YJJ?7!~^^::..  :?5GB#&@@&&&@@&&BPJ77?JJYYY5PPP55YYJJJY5PP^^~:::    //
//    YBYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPPPP5YJJJJJJYY5P55Y?!~~7?JYYYJJJ?7!^:::::^~~!7?Y55PPP55YYJJJJJJ5GPJJJJJYYY55555555555YJ???YPGGGGPGBGPP5555555YYYJJJJJJJY5PPPY?~::^~:::    //
//    BYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPPP5YYJJJJJJYY555PP5555PPPPPGGGP555555555YYJJJJJJJJJJJY5GPYJJJJJJJJJJJJJJJJJJJJJJJJJJJYJJJJJJJJJJJJJJJJJJJJJJJJJ5BJ!~::.::::::::    //
//    YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY55PGPP55YYJJJJJJJJJJJJJJJJJJJJJJJ?JJJJJJJJJY5PPPPPGP5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B?::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY55PPPPPPPPPPPPPPPPPPPPP55555555PPPPPP5YYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5GP!:::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYYYYYYYYYYYYYYYYYYYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5PGY!:::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY5PP5JJJJJJJJJJJJJJJJJJYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYJYPY7^:::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPP5YYJJJJJJJJJJJJJJJJJJJJJYPPPP5YJJJJJJJJJJJJJJJJJJJJJJYY55PGGY?!^^:::::::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55PPPPPPP55555PPPPPPPPPPPPP555PGY!::::::::::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPPP55YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PBBG55555YYYYYJJJJJJJJJJJ5G57::::::::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPPPPP5YYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55YJJJJJJJJJJJJJJJJJJJJJ5GP7::::::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYGP!::::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5GY^::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGG~:::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPG~::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPG~:::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG5^::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYB7::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG5^:::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5G~.::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55PPGGPPPPPPPPGGGGGPPP555YYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYP#PJ!:::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPGGP5YYYYYYYJJJJJYYYYYYY555PPPPGGGPPP555YYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY55PGGP5555BY^:::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPGPYYJJJJJYYYYYYYYJJJJJJJJJJJJJJJYYYY555PPPPGGGPPP5555YYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY55PPGGP55YYJJJJJYB?:::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5BPYJYYYYYYYJYYJJJJJJJJJJJYYYYYYYYJYYYYJJJJJJYYYYYY5555PPPGGGGPPPP555YYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY55PPPGGPP55YYJJJJJYYYYYJYBJ:::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPB5JYYYYYYYYYY55555555555YYYYYJJJJJJJYYYYJJYYYYJYYYYJJJJJJJJYYYYY55555PPPPGGGGGPPPPPPP5555555555555555PPPPPGGGPPP555YYYYJJJJJYYYYYYYYJJY5GY^:::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B5JYYYYYYJYYYPPPPPPPPPPPPPGGGPPPP555YYYYJJJJJJJJJYYYYYYYJJJYYYYJJJJJJJJJJYYYYYYYYYY5555555555555555555555YYYYYJJJJJJJJYYYYJJYYYYYYJJY5PG5!:::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGGJYYYYYYYJJYJJJJJJJJJJJJJJJYYYY555PPGGGPPPPP555YYYYJJJJJJJJJJJYJYYYYYJYJJJJJYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYJJYJJJJJJJJJJJJY5PP5?~:::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGGJJYYYYYYYYYYYYYYYYYYYYYYYYYYJJJJJJJJYYYY5555PPPGGGGPPPPP5555YYYYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYY55555PPGBY7^::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYGGYJJJJJJJJYJJJJJJJJJJJYJYYYYJYYYYJYYYYYYJJJJJJJYYYYYY5555PPPPGGGGGPPPPPPPPPPP55555555555555555555555555PPPPPPPPPPPPGGGPPPPP555YP#7::::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ55JJJJJJJJPGP555555555555555555YYYYYYYYJJJJJJJJYYYYYYYYYYJJYYYYJJJJJJJJJYYYYYYYY55555555555PPPPPPPPPPPPPPPPPP5555555555YYYYYYYYYYJJJJJJJJJ5B7:::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B5JJJJJJJJJY5PPPPPPPPPPPPPPPPPPPPPGGPPPPPP555YYYYJJJJJJJJJJYYYYYYYYYYYYYYJJYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYJJJYYYYJJJY#?:::::::::::::::::    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5B5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY55PPPGGPPPPP555YYYYJJJJJJJJJJYYYJYYYYYYYYYYYYYYYYYYYYJYYYYYYYYYJJYYYYYYYYYYYYYYYYJJJYYJJJYYYJJY5BJ::::::::::::::::::    //
//    5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYGPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY55PPPPGPPPPPP555YYYYYYYYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYYYYYYYYYYYJJJJJJJJJJY5PGP7:::::::::::::::::::    //
//    YPYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5PPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYY555PPPPPPPPPPPPPPPPPPPPPP555555555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY55PPPP5J!:::::::::::::::::::::    //
//    :7P5JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYY5PPPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYYYYY5555555PPPPPPPPPPPPPPPPGPPPPGPPPPPGBBP555YYJ?7~^::::::::::::::::::::::::    //
//    :.~PG5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYPG57:::::::::::::::::::::::::::::::::::    //
//    JJPB55PPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPJ~:::::::::::::::::::::::::::::::::::::    //
//    GGGGGG5YY5PPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPJ!::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPGGBGPYJYY5PPPP5YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PP5J!^::::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPPPPGGGGP5YJJJY5PPPPP5YYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PP5Y7~::::::::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPPPPPPPPGGBGG5YJJJJYY5PPPPPP55YYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPPYJ7~::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPPPPPPPPPPPPGGGGGP5YJJJJJJYY55PPPPPPPP555YYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY555PP5YJ7~^::::::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPPPPPPPPPPPPPPPPPGGGGGP5YJJJJJJJJJJYYY555PPPPPPPPPPP55555YYYYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYJJJ5G5J?7!~^:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::    //
//    PPPPPPPPPPPPPPPPPPPPPPPPPGGGBGGPP5YJJJJJJJJJJJJJJJJJJJYYYY5555PPPPPPPPPPPPPPPPP5555555YYYYYYYYYYYYYYYYYYYYYYYYYYYY55555PPPPPPP                                                                              //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BTCB is ERC1155Creator {
    constructor() ERC1155Creator("Bridge To Consciousness", "BTCB") {}
}