/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMx                     ,MMMMMMMMMMMMMMMMMMMMMMMMMM#^                  .MMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMk.                     TMMMMMMMMMMMMMMMMMMMMMMM$                  .dMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN,                     JMMMMMMMMMMMMMMMMMMMMM'                  .MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMe                     .HMMMMMMMMMMMMMMMMMD        .gggggggggggMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMh.                     TMMMMMMMMMMMMMMM3        (M""""""""YMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMN,                     (MMMMMMMMMMMM#!       .MD        .MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMp                      WMMMMMMMMMF        .M3        (MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMN.                     7MMMMMMM^        J#!       .MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM,                     ,MMMM#`       .MF        .MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb                     .MMD        .M^        JMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,                  (MM^       .d#`       .MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,               [email protected]        .MD        .MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm             .MM"        .M^       .dMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,          JMM'       [email protected]        .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMe       .MMD        .M"        .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.   `.MMNggggggggkM'       .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  .dM#"""""""""""        .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#` .MMF                   (MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD  .MM=                  .MDTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM^ .dM#`                  .Mt  ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
[email protected]  .MMD                   J#!     WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD  (MM^                  .MF        ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' [email protected]`                  .M=          ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD  .MMD                  .d#`             UMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMt  JMM^                  .MD                ?MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMM#! [email protected]                   .M^                  .MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMF  .MM$                  .dN.                     TMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMM= .gM#!                  .MMMN,                     (MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM#` .MMF                   (MMMMMMp                     .HMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMD  .MM=                  .MMMMMMMMMN.                     TMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM^ .dM#`                  .MMMMMMMMMMMN,                     ,MMMMMMMMMMMMMMMMMM
[email protected]` .MMF                   JMMMMMMMMMMMMMMp                      WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMD  .MM^                  .MMMMMMMMMMMMMMMMMN.                     ?MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM^ .MMB`                  .MMMMMMMMMMMMMMMMMMMM,                     ,MMMMMMMMMMMMMM
[email protected]  .MMD                  .JMMMMMMMMMMMMMMMMMMMMMMm                      UMMMMMMMMMMMM
MMMMMMMMMMMMMMNNNMMMNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMH"""""""WMM"""""""MMMMM#""WMMMMM#"""HMMMMMMM""""HMMH"""""""WMMH""""""HMMMM#""""""WMMMM
MMMMMMMMMMMMM^  ......MF  .....  .MMD  .MMMMM=  .  ?MMMMM#   .MM'  ......MM^  ....   dMD  .......MMM
[email protected]   (MMMMMM=  .MMM3  .MM^  .MMMM#`  .Mp  ,MMMD   JMD   [email protected]   ([email protected]   (M^  .MMMMMMMMMM
MMMMMMMMMMN.  ?777WM#`  .MM#`  [email protected]   JMMMMD  .dMMD  .dMt  .MMt   ?771MMM"   ?77^  .MM,  .777TMMMMMMM
MMMMMMMMMMMMN#'  .MF  .dMMF  .dM$  .MMMMM^  .MMM^  .M#!  .M#!  .NNNNMMM'  .N\  .gNMMMMMN%  .dMMMMMMM
MMMMMMMMMMMMB`  .M^  .MMM^  .MH'  [email protected]   ([email protected]`  -MF  .dMF  .dMMMMMMD   JM'  .MMMMMMMM^  .MMMMMMMMM
MMMD          .MM]          MM[     .dD         .MM3  .MM3        .Mt  .MM]  .MF         .MMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "./MGYERC721A.sol";

contract XSOLERC721A is MGYERC721A{
  constructor (
      string memory _name,
      string memory _symbol
  ) MGYERC721A (_name,_symbol) {
    _extension = ".json";
  }
  //disabled
  function setSBTMode(bool) external virtual override onlyOwner {
    isSBTEnabled = false;
  }
  //widraw ETH from this contract.only owner.  
  function withdraw() external payable override virtual onlyOwner nonReentrant {
    // This will payout the owner 100% of the contract balance.
    // Do not remove this otherwise you will not be able to withdraw the funds.
    // =============================================================================
    address wallet = payable(0x52a911BC7Ed9876a31a4891dA72Eb3c52CC7c4Ab);
    bool os;
    (os, ) = payable(wallet).call{value: address(this).balance}("");
    require(os);
    // =============================================================================
  }

}