// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: z0z
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWNXXNWWMMMMMMMMMMMMMMMMMMMMMWNXXXXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN0kkxxxxkkOXWMMMMMMMMMMMMMMMNOo;'....,ckXMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMN0xxkOOkkOOkxdkNMMMMMMMMMMMMW0:.          ,kWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWkdkOkl;'',cxOkoxNMMMMMMMMMMMO'    .:cc:.   .kWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMKdxOkc.     ;xOxo0MMMMMMMMMMNl    ;xOOOOd'   cNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMM0dxOk:      ,xOkodOOOOOkddddl.   .cOOOOOx,   cNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNxdkOx:....;dOOkkkxxxxd:          .:odoc'   .kWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXkdxkOkxxkkOOOOOOOOOkkc                   ,kWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWKOkxxdxkOOOOOOOOOOOkc              ..'cxXMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWNX0xdOOOxlcldOOkkc    .,'.    .dKXNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMKdxOk:',.;kOkk:   .dkx:    oNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWOdkkdc:cdkOdc'    ':;.   ;KMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdkOOOOOOx,            'OMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxdkOOOOx,            .kWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdxOOOk;            .oNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dxOOkl;;;'        cXMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdkOOOOOkl.      :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWNXXXXNNWWMMMMMMMMMNkdkOOOdc'      ,0MMMMMMMMMMWWWNXXXXXNMMMMMMMMMM    //
//    MMMMMMMMMMMMMWNXXKKKKKKKK0000KKXXKdokOOo:.     .kNNXXKK0000KKK0KKKXXNWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWWWWWWWWWWNNXKK000O0kccodl:.    .lO00O00KKXXNWWWWWWWWMMWWMMMMMMMMM    //
//    MMMMMMMMMMWNXXXXKKKKKKKKKKKKKKKKKK0x::lox:.   :k0KKKKKKKKKKKKKKKKKXXXXXXWMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWWNXXXKKKKKK0xclll,   :OKKKKKKKXXXNNWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWWNXXKKKKKKKKKKXXXNWWMWO,     5XMMMWWNXXXKKKKKKKKKKXNNWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWNNXXNNWWMMMMMMMMMMMMMMWx.   ;KMMMMMMMMMMMMMMMMWWNNNNNWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract z0z is ERC721Creator {
    constructor() ERC721Creator("z0z", "z0z") {}
}