// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: You Get What You Pay For
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    .    . .        .  .     .   .    .      .  .        .   .     . . ..X8%:8:[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] t:[email protected]   .     . .      .   .       .           .   .  .    .   .     .  .  .         //
//         .     . .  .       .        .    . .       .  . .       .      .8tS:  [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected];:%8.X..   .      . .       . .      .  .  .       .   .       .  .   .     .     //
//      .    .          . . .   .  . .   .      . .           . .    .  . 8t: [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@t %S;   .    .  .     . .      .  .   .    .  . .      .  . .      .   . .       //
//        .    .  . . .           .    .   .  .     .  . .  .     .   ..St %;[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]:%:8:.   .       .      .  .   .  .   .    .     . .         . .          .    //
//      .   .   .        .  . .      .      . . .. .  .       .     . .X.;; @[email protected]@[email protected]888888888888888888888888888888888888: XSS8;.     .  .   .  .      .         .      .       . .  .      . .  .       //
//        .   .    .  .         .  .    . .. [email protected] .    . ..... .  . 88t% [email protected]@[email protected][email protected] ;. SS8 .. .   .     .   . .     .  . .   .  .   .  .      .   .          .     //
//      .        .      . .  .   .    .  . t Xt;S8.S%. . . %888;. . :8:%8 88X88888888888888[email protected]8888888888[email protected]8  .8t.t      .   . .         .  .          .   .      .  .   .   . .  . .       //
//         . .  .   . .        .    .   . 88 %;:;[email protected]%: . X S%;[email protected] ;tSX8X8X8888888888888888888[email protected]888888888888888888888888888888888888888888888888888888888888888888888888 @8.;.:8              . .  .      .  .  .    .    . .                .     .    //
//      .     .   .      . . .    .    . @%8S . .: [email protected] X%[email protected];:X [email protected]@S%S:SS888[email protected][email protected]88888888888888888888888888 S;.%;:8X  . . .  .          . .      .   .     .     . . .  . . .      .       //
//        .          .          .    . . 88S8 .   .%.8X tX .   [email protected]%8S [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] 8; :;8 :      .  . .  . .     . .    .   .     .         .      .  .   .     //
//      .   .  . .  .  .  .  .    .    . ;.8  .   . :8%X;8X     . [email protected]%[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] ;[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] :. .;;..   .        .     .      .    .   . .   .  .  .    .  .     .       //
//        .   .    .    .      .   .. ....88X .   . %[email protected]    .. .8%:[email protected]@[email protected] :: @@[email protected]@[email protected]@8 ;. @[email protected]@8%t88X%88 [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@8888 t. :8:.... .    .  .     .    .  .   .             .       .      . .    .    //
//      .   .    .    .    . .   ..8;.;8: %@%@ .   ..S888X;X . . 8S8;@[email protected]@[email protected]; % [email protected]@888888888;XS:@@[email protected]@[email protected]@888888888888888888888888888888888888888888888888888888:;8t8. X::    .      .  .  .       .   .  . .  . .    .  .   . .       .      //
//             .    .    .     . 8 @t:[email protected]:@@X. .  . [email protected] 8: .   [email protected]@[email protected]@8 :::.. [email protected] .  [email protected]@[email protected] %XS8.8 88 : .     . .         . . .                  .   .        .  .         //
//      . .  .    .    .   .  . t:8 %.:%88 8S8S .  . ;:X:%XX . . [email protected]@[email protected]@@[email protected]%  [email protected]@@8888888888888888888888888t%;8;@[email protected]@[email protected] .. .. ;8S8 t:8 [email protected];X;.:.%t88:.   .       . .  .         . . . .  . .  .   .   .  .        . .     //
//          .   .    .   .    . ;8S8 .. [email protected] ..   . %8 :8     . @[email protected]@[email protected]@[email protected]@8:[email protected]@[email protected]@[email protected] [email protected]: .    .%;8X ;8S ;: [email protected]@8888888888.X:8:.%;[email protected]   .  .      .  .  .  .         .       .       .  . . .          //
//      .     .    .        . . S8      .X @  @8 . . .; [email protected];% . . :@[email protected]@[email protected]@[email protected]@[email protected] 8S8888888888888888%8; . .  ..X8   :  %8 [email protected]@[email protected]@888.Xt tX8; .      .  .            .  .  .    . .     . .           .  .     //
//        .      .   . .  .   . 88.: .  . 8SS :88 .. . S8 X88 . . [email protected]@[email protected]@[email protected]@[email protected];8  .    . t8.  .   8;%:[email protected]@88  XS888S . .         .  . . .           .     .  .    .  .  .  .         //
//      .   .  .   .     .   .. [email protected]% .   . t8: @@[email protected]: X ;t%XS%8.. [email protected]:[email protected]@[email protected]@[email protected]@[email protected] . .  . 8X%8.   : @8: @[email protected] [email protected] .  . . .          . .  .  .    .    .   .     .      .  .    //
//        .   .       .    .   [email protected] % .   ..88. %S8Xt ..::;:%@t  .. [email protected] 88:;S8::[email protected]@[email protected]@[email protected]:[email protected]@@888888888.%@; .    . S%88 .  . t8;[email protected]@8888 . ;t8% .       . .  .       .     .    .    .    .    . .          //
//      .   .   . .     .      . 8S8S . .   : X%@ % .      . .   . [email protected]@X [email protected] ;%[email protected]@[email protected]@[email protected]@[email protected]@88888888888888;X88t . .  . SS88 . .  S ;[email protected]@@XtS%t8..   .         .  .    . .   .    .     .   .      . .      //
//                  . .   .  .  . %8%S .  .. ;8 S  .   . .     . . 8StS8.;@t .  %;[email protected]%[email protected]@888.88 %;8:888888.;8X8888888888888888888888888X:[email protected] .    . @[email protected] . .. 8;. [email protected]@[email protected]@[email protected];St8:.    .  . .   .   .      .   .    .     .   .  .     .    //
//      . .  . .  .         .    . [email protected] .  . .:  .   .     . .    .. 8 8....    . t:[email protected]:t 8;.  [email protected]@[email protected]@: . .  . X8:8%.:%8t.%:8 [email protected]@[email protected]@[email protected]@8X8.88:XX .         .      .  .        .    . .           .       //
//          .       .  . .    .   . S8t8.     .         . .    . . X8;t .    .   [email protected]@%@88888888888888888888888888888888X8:88. 8;::. ;[email protected]@[email protected]@@%8  .  . . [email protected]:[email protected]@[email protected]@[email protected] %t   . .  .     . .      .  . .   .       . . .  .   .     //
//      .      . .         .    .  .S 8 ; . .  .  .  .. . 8S8 .  . @S8 .    .   . %[email protected]@[email protected]@8888888X88:8 St. :@[email protected]@888888888888888888: S.%.;@S8X .    . 88XX.t%:X.SS8;8;[email protected]@[email protected]@[email protected];[email protected];.       . .      . .        .   .  .        .          //
//        .  .     . . .     .     . % XS:.   .    . [email protected] S. .    .;:    ..  ...%;:8S [email protected]@[email protected]@@ .8 ..   [email protected]@[email protected]  . SS88 . . . ; 8X ..  . %XX% 8 [email protected]@[email protected]@[email protected]@[email protected]: @@..  .       .  .     . .     .      .  .     . .      //
//      .   .   .        . .   . .  . 8S8. .    . . [email protected] .   .   .  ..   X:8.X888  [email protected]@[email protected]@@ @::8  8 88888888888888888888. S: . . 88S8 .   . @8%8.    . ::88.%[email protected]@[email protected]@[email protected]@888X8.8.8t .   .  .   .    .      .     . .   .   .       .    //
//        .   .   .  .       .       . %8 ;. .     .St888: .  .   .   . t;[email protected]@8:88 [email protected]@[email protected]@[email protected]@[email protected]@ .8  [email protected]@888888888888888 8X%S . . S8tt .   . X8    .  . X%@[email protected]@[email protected]@[email protected]@[email protected] :[email protected] .   .   .    .   .  .   .       .      . .  .      //
//      .       .      . .      .  .  ..X8% .  .  .  . @X% .    .   . .SXSS8t 8X [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]  [email protected]@[email protected]@:X888 .  . 8;% .  . . [email protected]      . ;8t8;[email protected]@[email protected]@[email protected]@[email protected]@. St%8t.     .   .      .   .   .  .     . .             //
//         . .     . .     .  .       ..;[email protected] .       . S:..  .      . ;@X%@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@ t:[email protected]: .   ..:   .   . tX   . . . X8  : @[email protected]@[email protected]@[email protected]@[email protected]:;:[email protected] .  .       . .        .   .  .        . . .      //
//      .      .  .    .    .    .  .  .; 8% .  .  .   .       .  .  . % [email protected]@[email protected]  8  [email protected]@[email protected]@[email protected]@[email protected]@8X8X8  @[email protected]@[email protected]@[email protected] t8t. 8; . .   . .   .            . %S8  [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@8 tX8t%8      . .      . . .    .      . .  .       .    //
//        .  .       .   .    .   .    . @XSS .   .  .   .  .    .  . 8 [email protected] [email protected]  [email protected]@[email protected]@[email protected]@[email protected]@[email protected]  @[email protected]@[email protected]@[email protected] SS  Xt88 .   .     .    .  . .  .   .     . [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@ X8; S8S . .     .  .       .     .  .       .  .       //
//      .      . .        .     .   .   . 88;@ .       .     .    .. 8SXX [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] . 8XX8 . .    .     .   .    .  .     . : @[email protected]@[email protected]@[email protected]@[email protected] :X8.t     .        .  .    .  .      . .       .     //
//        . .      .  . .   . .      .  ..tX8.8... .     . .   .. [email protected]  88X8X8  @[email protected]@[email protected]@[email protected] [email protected]@[email protected]@8t;S::. SSX8 .    .   . .   .    .      . . . @@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] SX8;X%8;    . . . .      .   .   .  .     . .  .      //
//      .     .  .   .    .      . .      . .;8 ;8t. ...     . @;Xt8 ::8%[email protected]  @[email protected]@[email protected] %;8 ... : 8% .  .  ;.    .    .     .       . [email protected]@[email protected]@[email protected]@[email protected]: %;t8..           .  .  .       .   .      .       //
//         .       .    .    .  .     .    ..%8S88S @X;8 .   . @S.88. [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] t  .   . @8% . .  ;;; : . :. .t  .   . .  .  [email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] S::X8;[email protected]:.  .  .  .   .       . .    .   .  .    .    //
//      .    . .      .    .       .   .      .SX8 X   X. .    .:.... 88;[email protected]@[email protected]@ 8  @[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@8 .8%.   . . .8.t . . 88S . %8X .8SX .         . @8t:[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@ X88t8: S8            .    .  .     .    .       .      //
//        .      . .     .    . .    .   .  . . 8X:8  .     .   .  [email protected] [email protected]@[email protected]@ X [email protected]@[email protected]@[email protected]@[email protected]@8X t:8 .  .   . :S88 .   ; tX  [email protected]% . ;X  . .  . .. ;[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@8t88 :X8. .. . . . .    .      .     .     . .         //
//      .   .  .     . .    .     .    .       . X8;% . ....... . 8 [email protected]@;@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] @8X [email protected] t88       .  . 8S8  .   :S.  :X:  ;@            t:[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected]@[email protected] ;% StSt 8..          .   . .    . .   .  .    .  .    //
//        .      .  .     .   .     .    . .   . ..t8 %;@[email protected];8 [email protected]@ @[email protected]@[email protected]@[email protected]@[email protected]@[email protected] @ [email protected] X8X      .    .. .XS:..  .   . .    .  .  . . ..S [email protected]@[email protected]@8X8X8X8X8X8X8X8X888X8X8X8X8X8X8X8X8 8:8; t. ;S.   .    .  .        .              .         //
//      .    . .       .    .   . .   .      .   ..;[email protected] [email protected] [email protected]@888X  @8  [email protected] @8X @[email protected] X ::;::.X8X8X [email protected] X8X X8X8X8 @8 [email protected]@S          .   . 8 @ X.. .      .      . . ..t;;@8;[email protected]@[email protected]@[email protected]@8X [email protected] [email protected] X8888::..tX   .  .      . .  .   .  . .  .  .    .      //
//         .     . .     .    .     .   .  .   .    .. @8:%@[email protected]@[email protected] @[email protected] 8  [email protected]  @ [email protected];SS8; %:X8X8X X8X8X8X8X8X @ 8  [email protected]  %88  .    .  .      .  [email protected] 8. .....   . .  .   ;;[email protected] 88888888X @8X [email protected] X8X8X X8X8X @8X @8X @8X X8X8X [email protected]@8X X @8;88: %;:.8  .      .          .        .     .   .     //
//      .    .       . .   .     .           .        t;[email protected] X88X8X88  @ t [email protected] [email protected]@%   :%@. t: @8X8X X8X X  @  @ 8  @.X88%.        .   . .   .  [email protected]:@;;8%:      . 8%8 [email protected]:[email protected] X8X8X X8X8X8X8X8X8X8X8X X8X8X X8X X  @  @ .;%::.8   t    .  .   .  . .     . .  .   . .   .       //
//        .    .  .      .   .  .   . . . .     . . ..8:[email protected]@SS%;8S8XXS8S8 [email protected] [email protected]@ 8X ;%88   :.  ..  .8S :@8  % [email protected]  8 .8 .% 8 8;8Xt. .  .  .   .     . :8%;8:88S8%: 8 . . ..Xt8t8X:@[email protected]@X X8  @8  @8  S  @8 @ X8  @8  @8  @8 .S  @8 @[email protected]  8  X8%8%t.t;: @          .       .                    .     //
//      .   .   .   .  .          .         .  .   . %.8t .;@SSSSSS8XSS%S8SSXX88 S @8  @[email protected] S @88;..   .  . .   88;;@[email protected] :@ 8S88 :8 ;%:% .       .       .  . 8.%8 ;S %%@@  ....   ..S8% 8888 [email protected] X8X88 S :8 .8.888  8 X  88888 S :8  8.8 8 .8 [email protected] 8..8X.88:X::%.:[email protected]    . .     .  .   . .  . . . .  . .         //
//        .   .      .    . . .      .  .          . ::;:[email protected] @ : [email protected] .%[email protected] .  .  .      . 88;8X .%.8X8:.X .8 [email protected] ;t     .  .   .  .   . t;;X8.SS8;8%@X  tSS%.%S:@88.888X8 S88X  @8  t:[email protected]  88888 [email protected]@  @  S :8X @..88S 8 :[email protected]@ :8S88.888.tX8%8: ;.      .    .   .                   .       //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract YGWYPF is ERC1155Creator {
    constructor() ERC1155Creator() {}
}