// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The Collector
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                                                                                 //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM0dkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxOMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMW0xdONMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMMNc  .kMMMMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMXk;   ;kXWMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMWl       'OMMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMWc        cWMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMN:        ;XMMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMX:        .dNMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdXMMMMMMMMMMMMMMMMMMMMMo        .lXMMMMMMMMMMMMMMMMMMNdkMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOdNMMMMMMMMMMMMMMMMMMMMMd       :KWMMMMMMMMMMMMMMMMMMMNxOMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMOoxkkkkkkkkkkkkkkkkkkkkk:       :kkkkkkkkkkkkkkkkkkkkkxoOMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWK0000000000000000000000x'     .o0000000000000000000000KWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;     cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:     dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl    .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo     oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..';xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                 //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////


contract VMCO is ERC1155Creator {
    constructor() ERC1155Creator("The Collector", "VMCO") {}
}