// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: 0xRodo - Special Edition
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoccccccccccccccccccccccccccccccccoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWO;................................;OWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMM0olc:,'''''''''''''''''''''''''''''''',:llo0MMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWk,...''''''''''''''''''''''''''''''''''...,kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0ool:''''''''''''''''''''''''''''''''''''''...,kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWd'...''''''''''''''''''''''''''''''''''''''...,kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMXkddddddddddddddo;....'''''..............''''''''''''''''....  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMM0:'''....''''.........''''................''''''''''''''....   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMXkxxo;.''''.......   'cll;. ...............................    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc'''........    ,xOOl.                                    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc'''....:ool'   .;::;''.',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'.'':ood0WMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc'''...'xWMWl       .coodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdool.   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc'',:llo0MMWl    ...;oxxolc:cccccccccccccccccccccccc::coddo'   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKc'':OWWMMMMWl   .loodkOOo.                            .ckOx'   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXxlldKMMWKkkx,   .loodkOOo.                            .ckOx'   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWWWWMMMNc       .loodkOOo.                            .ckOx'   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMX:    ...';::lxkko,............................'lkkd'   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMX:   ,xkx:   .loodxxxxxxxxxxxxxxxxxkkxkkxxxxxxxxdool.   lWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMX:   'odo:....;cccooooooooooooooooooooooooooooooc:c:,..'dWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMX:       ,dxxc.                                    .oXXXWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNl...    ,xOOl................           ......    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNKK0:   ,xOOkxddddddddddddddo,        .lddddddl.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOk:..      ,dOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOxddooooddxkOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOkkkkkkkkkkkkkOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOkc'...........:xOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOx,            'dOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOkoccccccccccccokOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOx:,,;coodKMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo.  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOkl;;;;;;;;;;;;;;;;;;;;:clldKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.                    'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.   'ccccccccccccccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.   dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWl   ,xOOOOOOOOOOd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract RODO is ERC721Creator {
    constructor() ERC721Creator("0xRodo - Special Edition", "RODO") {}
}