// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: AIVERSE BOUNDARIES
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                   AAA               IIIIIIIIIIVVVVVVVV           VVVVVVVVEEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRR      SSSSSSSSSSSSSSS EEEEEEEEEEEEEEEEEEEEEE     BBBBBBBBBBBBBBBBB        OOOOOOOOO     UUUUUUUU     UUUUUUUUNNNNNNNN        NNNNNNNNDDDDDDDDDDDDD                  AAA               RRRRRRRRRRRRRRRRR   IIIIIIIIIIEEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS     //
//                  A:::A              I::::::::IV::::::V           V::::::VE::::::::::::::::::::ER::::::::::::::::R   SS:::::::::::::::SE::::::::::::::::::::E     B::::::::::::::::B     OO:::::::::OO   U::::::U     U::::::UN:::::::N       N::::::ND::::::::::::DDD              A:::A              R::::::::::::::::R  I::::::::IE::::::::::::::::::::E SS:::::::::::::::S    //
//                 A:::::A             I::::::::IV::::::V           V::::::VE::::::::::::::::::::ER::::::RRRRRR:::::R S:::::SSSSSS::::::SE::::::::::::::::::::E     B::::::BBBBBB:::::B  OO:::::::::::::OO U::::::U     U::::::UN::::::::N      N::::::ND:::::::::::::::DD           A:::::A             R::::::RRRRRR:::::R I::::::::IE::::::::::::::::::::ES:::::SSSSSS::::::S    //
//                A:::::::A            II::::::IIV::::::V           V::::::VEE::::::EEEEEEEEE::::ERR:::::R     R:::::RS:::::S     SSSSSSSEE::::::EEEEEEEEE::::E     BB:::::B     B:::::BO:::::::OOO:::::::OUU:::::U     U:::::UUN:::::::::N     N::::::NDDD:::::DDDDD:::::D         A:::::::A            RR:::::R     R:::::RII::::::IIEE::::::EEEEEEEEE::::ES:::::S     SSSSSSS    //
//               A:::::::::A             I::::I   V:::::V           V:::::V   E:::::E       EEEEEE  R::::R     R:::::RS:::::S              E:::::E       EEEEEE       B::::B     B:::::BO::::::O   O::::::O U:::::U     U:::::U N::::::::::N    N::::::N  D:::::D    D:::::D       A:::::::::A             R::::R     R:::::R  I::::I    E:::::E       EEEEEES:::::S                //
//              A:::::A:::::A            I::::I    V:::::V         V:::::V    E:::::E               R::::R     R:::::RS:::::S              E:::::E                    B::::B     B:::::BO:::::O     O:::::O U:::::D     D:::::U N:::::::::::N   N::::::N  D:::::D     D:::::D     A:::::A:::::A            R::::R     R:::::R  I::::I    E:::::E             S:::::S                //
//             A:::::A A:::::A           I::::I     V:::::V       V:::::V     E::::::EEEEEEEEEE     R::::RRRRRR:::::R  S::::SSSS           E::::::EEEEEEEEEE          B::::BBBBBB:::::B O:::::O     O:::::O U:::::D     D:::::U N:::::::N::::N  N::::::N  D:::::D     D:::::D    A:::::A A:::::A           R::::RRRRRR:::::R   I::::I    E::::::EEEEEEEEEE    S::::SSSS             //
//            A:::::A   A:::::A          I::::I      V:::::V     V:::::V      E:::::::::::::::E     R:::::::::::::RR    SS::::::SSSSS      E:::::::::::::::E          B:::::::::::::BB  O:::::O     O:::::O U:::::D     D:::::U N::::::N N::::N N::::::N  D:::::D     D:::::D   A:::::A   A:::::A          R:::::::::::::RR    I::::I    E:::::::::::::::E     SS::::::SSSSS        //
//           A:::::A     A:::::A         I::::I       V:::::V   V:::::V       E:::::::::::::::E     R::::RRRRRR:::::R     SSS::::::::SS    E:::::::::::::::E          B::::BBBBBB:::::B O:::::O     O:::::O U:::::D     D:::::U N::::::N  N::::N:::::::N  D:::::D     D:::::D  A:::::A     A:::::A         R::::RRRRRR:::::R   I::::I    E:::::::::::::::E       SSS::::::::SS      //
//          A:::::AAAAAAAAA:::::A        I::::I        V:::::V V:::::V        E::::::EEEEEEEEEE     R::::R     R:::::R       SSSSSS::::S   E::::::EEEEEEEEEE          B::::B     B:::::BO:::::O     O:::::O U:::::D     D:::::U N::::::N   N:::::::::::N  D:::::D     D:::::D A:::::AAAAAAAAA:::::A        R::::R     R:::::R  I::::I    E::::::EEEEEEEEEE          SSSSSS::::S     //
//         A:::::::::::::::::::::A       I::::I         V:::::V:::::V         E:::::E               R::::R     R:::::R            S:::::S  E:::::E                    B::::B     B:::::BO:::::O     O:::::O U:::::D     D:::::U N::::::N    N::::::::::N  D:::::D     D:::::DA:::::::::::::::::::::A       R::::R     R:::::R  I::::I    E:::::E                         S:::::S    //
//        A:::::AAAAAAAAAAAAA:::::A      I::::I          V:::::::::V          E:::::E       EEEEEE  R::::R     R:::::R            S:::::S  E:::::E       EEEEEE       B::::B     B:::::BO::::::O   O::::::O U::::::U   U::::::U N::::::N     N:::::::::N  D:::::D    D:::::DA:::::AAAAAAAAAAAAA:::::A      R::::R     R:::::R  I::::I    E:::::E       EEEEEE            S:::::S    //
//       A:::::A             A:::::A   II::::::II         V:::::::V         EE::::::EEEEEEEE:::::ERR:::::R     R:::::RSSSSSSS     S:::::SEE::::::EEEEEEEE:::::E     BB:::::BBBBBB::::::BO:::::::OOO:::::::O U:::::::UUU:::::::U N::::::N      N::::::::NDDD:::::DDDDD:::::DA:::::A             A:::::A   RR:::::R     R:::::RII::::::IIEE::::::EEEEEEEE:::::ESSSSSSS     S:::::S    //
//      A:::::A               A:::::A  I::::::::I          V:::::V          E::::::::::::::::::::ER::::::R     R:::::RS::::::SSSSSS:::::SE::::::::::::::::::::E     B:::::::::::::::::B  OO:::::::::::::OO   UU:::::::::::::UU  N::::::N       N:::::::ND:::::::::::::::DDA:::::A               A:::::A  R::::::R     R:::::RI::::::::IE::::::::::::::::::::ES::::::SSSSSS:::::S    //
//     A:::::A                 A:::::A I::::::::I           V:::V           E::::::::::::::::::::ER::::::R     R:::::RS:::::::::::::::SS E::::::::::::::::::::E     B::::::::::::::::B     OO:::::::::OO       UU:::::::::UU    N::::::N        N::::::ND::::::::::::DDD A:::::A                 A:::::A R::::::R     R:::::RI::::::::IE::::::::::::::::::::ES:::::::::::::::SS     //
//    AAAAAAA                   AAAAAAAIIIIIIIIII            VVV            EEEEEEEEEEEEEEEEEEEEEERRRRRRRR     RRRRRRR SSSSSSSSSSSSSSS   EEEEEEEEEEEEEEEEEEEEEE     BBBBBBBBBBBBBBBBB        OOOOOOOOO           UUUUUUUUU      NNNNNNNN         NNNNNNNDDDDDDDDDDDDD   AAAAAAA                   AAAAAAARRRRRRRR     RRRRRRRIIIIIIIIIIEEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS       //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract EXART is ERC1155Creator {
    constructor() ERC1155Creator("AIVERSE BOUNDARIES", "EXART") {}
}