// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cyber nonno
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                         //
//    On 24 Dec 2022, my dear grandpa Vinicio left this world, after a long life.                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                         //
//    Like every human being he was special and unique, driven by strong values and passions.                                                                                                                                                                                              //
//    I have learnt a lot from him, and he’s one of the core contributors to my passion for technological advancement.                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                         //
//    I’d like to share a few memories and learnings here, to recall some skills and values:                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                         //
//    Passion for technology                                                                                                                                                                                                                                                               //
//    - When I was in primary school, and he was already 65 years old, my school friends used to call him “cyber-grandpa”, to recognize his amazing ability to adopt new tech otherwise typically inaccessible to people of his generation                                                 //
//    - He didn’t have any high school degree (forget university), yet when I was studying electronics in my engineering school he would fix any electronic board accessible to human hands with his own practical knowledge, and I used to be mindblown by that                           //
//    - He understood the power of the internet when most people in Italy had no clue about it. He learnt to use Skype way before my dad did.                                                                                                                                              //
//    - He used to tell me: “when I met your grandma parents I told them: the world will change with technology. One day you’ll walk to a door and it will open magically in front of you without handles or buttons. Your grandma parents told her she was about to marry a crazy man”    //
//                                                                                                                                                                                                                                                                                         //
//    Selflessness                                                                                                                                                                                                                                                                         //
//    - “when you cut slices of salame for guests always cut them in various level of thickness, as some people like them thin, others like them thick”                                                                                                                                    //
//    - “when I see a woman not too good looking in the street, I smile at her, so maybe I’ll make her day slightly better”                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                         //
//    Content                                                                                                                                                                                                                                                                              //
//    - “every morning I wake up, go out of the house, see our garden, and am grateful that I get to live another day in this paradise “                                                                                                                                                   //
//    - “we have no money but we are the richest. You know why? Because we have happiness and love, and no money can buy that.”                                                                                                                                                            //
//    - “don’t ever come to my funeral: just come and visit me once more when I’m alive, so I can enjoy your company”                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                         //
//    Merit                                                                                                                                                                                                                                                                                //
//    - if you ever buy something using debt, remember you are not buying, you’re giving up you’re freedom to get something you cannot afford yet                                                                                                                                          //
//                                                                                                                                                                                                                                                                                         //
//    This list is just a random sample and could be way longer - dear Nonno all these learning will stay with me for my life. Thank you for this beautiful 38 years long gift.                                                                                                            //
//                                                                                                                                                                                                                                                                                         //
//    My last gift to you is to bring you on-chain, you would have loved be part of web3!                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract ICIO is ERC721Creator {
    constructor() ERC721Creator("Cyber nonno", "ICIO") {}
}