// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

/*---------- SALE PHASE ERRORS -----------*/
error INVALID_SALE_PHASE();
error INVALID_START_TIME();
error INVALID_END_TIME();
error INVALID_PRICE();
error INVALID_PRICE_AFTER_24_HOURS();
error INVALID_MAX_AMOUNT_USER_CAN_BUY();
error NOT_IN_SALE_PHASE();
error TREASURY_ADDRESS_NOT_SET();
error WRONG_CANDIDATE();
error LAUNCH_PRICE_NOT_SET();
error INVALID_MINIMUM_GALACTIX_TOKEN_REQUIRE();
error INVALID_LAUNCH_PRICE();
error CURRENT_SALE_PHASE_NOT_ENDED();

/*---------- SIGNATURE ERRORS -----------*/
error INVALID_SIGNATURE();

/*---------- BUY ERRORS -----------*/
error CANNOT_BUY();

/*---------- BALANCE ERRORS -----------*/
error INSUFFICIENT_BUSD();
error INSUFFICIENT_BNB();

/*---------- RESCUE ERRORS -----------*/
error ALL_TOKENS_ARE_SOLD_OR_RESCUED();
error NOT_YET_RESCUE_TIME();
error NOT_OWNER_OF_KEY();
error KEY_IS_USED_THIS_MONTH();
error INVALID_NUMBER_OF_NFTS();

/*---------- CLAIM ERRORS -----------*/
error INSUFFICIENT_CLAIMABLE_AMOUNT();
error NOT_CLAIMABLE_TIME();

/*---------- MERGE ERRORS -----------*/
error INVALID_TIMESTAMP();
error SESSION_ID_IS_USED();
error NOT_OWNER_OF_TOKEN();
error TOKEN_IS_LOCKED();
error INVALID_SESSION_ID();
error MERGE_SET_NOT_FOUND();
error CANNOT_CANCEL_TEMP_MERGE();
error TOKEN_IS_NOT_LOCKED();
error NOT_OWNER_OF_TOKEN_OR_TOKEN_IS_LOCKED();
error UN_AUTHORIZED();
error SESSION_ID_NOT_FOUND();
error CANNOT_EXECUTE_TEMP_MERGE();
error INVALID_TOKEN_IDS_OR_SESSION_ID();

/*---------- KEY ERRORS -----------*/
error KEY_PRICE_NOT_SET();
error NOT_YET_OPEN_FOR_SALE();
error INVALID_KEY_PRICE();
error INVALID_BUY_TIME();

/*---------- PRICE FEED ERRORS -----------*/
error INVALID_PRICE_FROM_PRICE_FEED();

/*---------- RATE ERRORS -----------*/
error INVALID_ROYALTY_FEE_RATE();

/*---------- ADDRESS ERRORS -----------*/
error ZERO_ADDRESS();