// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Pixel Fighter Guild Villains
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOkkkkkkkkkkkkkkkkkl::::::::::::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,cxkkkkkkkkkkkkkkkkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;,,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',cdddddddddddddddddolccccccccccccccccc:;;;,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;,;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;,;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,;;,;;;;;;;;,,,;;,,;;,,;;;;,;;;,;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'''''''''''''''',ldddddddddddddddddolccccccccccccccccc:;,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,;;;;;;;;;;,,,,;;,,;,,;;;;,,;;,;;,''''''''''''''''',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXXXXXXXXXXXXXd;,,,,,,,,,,,,,,,,;ldddddddddddddddddollllllllllllllllllc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::;;;;;;;;;;;;;;;;;;,,'''''''''''''''',dXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l:::::::::::::::::cooooooooooooooooooddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooooodxOOOOOOOOOOOOOOOOOxlccccccccccccccccc:;,,,,,,,,,,,,,,,,,;:::::::::::::::::l0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,;;;;;;;;;;;;;;;,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,;;;;;;;;;;;;;;;,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,;;;;;;;;;;;;;;;,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,,;;;;;;;;;;;;;;,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,,,,,,,,,,,,,,,,,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,,,,,,,,,,,,,,,,,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,,,,,,,,,,,,,,,,,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000Ooccccccccccccccccc:;,;;;;;;;;;;;;;;;,,''''''''''''''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWOdddddddddddddddddkNMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddooooooooooooooooooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddxkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxoc:::::::::::::::::;''''''''''''''''';OMMMMMMMMMMMMMMMMMNkdddddddddddddddddOWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxOKK0000000000KKKK0klccccccccccccccccc;,'''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO000000000000K0000klccccccccccccccccc;''''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;''''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;''''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;,'''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;,'''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;,'''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo'''''''''''''''''cKMMMMMMMMMMMMMMMMMO;'''''''''''''''',cddddddddddddddddddlcccccccccccccccccloddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxO00000000000000000klccccccccccccccccc;''''''''''''''''';OMMMMMMMMMMMMMMMMMKc'''''''''''''''''oNMMMMMMMMMMMMMMMMM    //
//    00000000000000000kc.................;x00000000000000000d;'''''''''''''''',cddddddddddddddddddolllllllllllllllllodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxkOOOOOOOOOOOOOOOOOxc:::::::::::::::::;''''''''''''''''';d00000000000000000x;.................cO00000000000000000    //
//    ,,,,,,,,,,,,,,,,,,...................',,,,,,,,,,,,,,,,,,''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;;;;;;;;;;;;;;;;;;,'''''''''''''''''',,,,,,,,,,,,,,,,,,'...................,,,,,,,,,,,,,,,,,,    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''...................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''....................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,;;;;;;;;;;;;;;;,,''''''''''''''''''''''''''''''''''''....................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,;;;;;;;;;;;;;;;,,''''''''''''''''''''''''''''''''''''....................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,,;;;;;;;;;;;;;;,,''''''''''''''''''''''''''''''''''''....................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;,;;;;;;;;;;;;;;;,,''''''''''''''''''''''''''''''''''''....................''''''''''''''''''    //
//    ''''''''''''''''''...................'''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl;;;;;;;;;;;;;;;;;,,'''''''''''''''''''''''''''''''''''''...................''''''''''''''''''    //
//    ''''''''''''''''''....................''''''''''''''''''''''''''''''''''',cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddl:;;;;;;;;;;;;;;;;;,'''''''''''''''''''''''''''''''''''''...................''''''''''''''''''    //
//    '''''''''''''''''',,,,,,,,,,,,,,,,,,'...................''''''''''''''''',cddddddddddddddddddc::::::::::::::::::::::::::::::::::::cdddddddddddddddddddddddddddddddddddddoc:::::;::::::::::::::::::::::::::::::clooooooooooooooool:,'''''''''''''''''..................':lcclllllllllllccl:,'''''''''''''''''    //
//    '''''''''''''''''',;;;;;;;;;;;;;;;;;,...................''''''''''''''''',cdddddddddddddddddo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:oddddddddddddddddddddddddddddddddddddo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:odddddddddddddddddc,'''''''''''''''''..................'ldddddddddddddddddl,'''''''''''''''''    //
//    '''''''''''''''''',;;;;;;;;;;;;;;;;;,...................''''''''''''''''',cdddddddddddddddddo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:oddddddddddddddddddddddddddddddddddddo:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:odddddddddddddddddc,'''''''''''''''''......                                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PFGV is ERC721Creator {
    constructor() ERC721Creator("Pixel Fighter Guild Villains", "PFGV") {}
}