// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.17;

error AssetNotReceived();
error ApprovalFailed();
error ContractIsPaused();
error DepositIsZero();
error ExpiredTransaction();
error FunctionAlreadyExists();
error FunctionIsImmutable();
error InitializationFunctionReverted(address _initializationContractAddress, bytes _calldata);
error InsufficientOutputAmount();
error InvalidAmm();
error InvalidAmountIn();
error InvalidBridgeType();
error InvalidDataTransferType();
error InvalidFacetAddress();
error InvalidSelectors();
error InvalidAmountOutMin();
error InvalidFromAssetAddress();
error InvalidFromToAddress();
error InvalidMagpieAggregatorAddress();
error InvalidPayload();
error InvalidPath();
error InvalidProtocol();
error InvalidProtocolList();
error InvalidTransfer();
error InvalidSender();
error InvalidToAddress();
error InvalidToAssetAddress();
error InvalidTokenSequence();
error InvalidTransferKey();
error NoSelectorsToCut();
error ReentrantCall();
error SequenceHasPayload();
error SequenceIsUsed();
error SwapFailed();
error TransferFailed();
error TransferFromFailed();