// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Maqueda_diversidad_1
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                     .,'                                                                                                                                                                                                                                            //
//                                                                        .lKMNo.                                                                                                                                                                                                                                     //
//                                                                     .:xXMWMWk.                                                                                                                                                                                                                                     //
//                                                                   ,oKWMMMKo:.      .cxd'                                                                                                                                                                       ..                                                  //
//                                                                .l0NWWWKd:.      .,lKMMMK,                                                                                                                                                                    .oKKl.                                                //
//                                                             .:dKWWWWKl.      .'l0WMWWWKo.                                                                                                                                                                 .lkXWMMd.                                                //
//                                                          .,l0WMWMNx:.      .l0NWWMMKdc.                                                                                                                                                                .lkXMWWXOo.                                                 //
//                                                       .,o0WWMMXkl'      .:dKWMMMNOl.                                                                                                                                                                .:dKMMMWKl.                                                    //
//                                                    .;o0NWMMNOl.      .ckXMMWMWKo,                                                                                                                                                                .;lKMWMMNOl.                                                      //
//                                                 .cdKWWMWXOl'.     .,lKMMMMWXkc.                                                                                                                                                               .:oKWMWWW0l'                                                         //
//                                              .cdKWWMMKxl'       .l0WWMMWN0l.                                                                                                                                                               .'lKWMMMMKl,.       .,,;;;,,,.                                          //
//                                           .lxKMMMWWKl.      .;oOXWWWN0xc'                                                                                                                                                               .'l0NMWMMKo;.      .:dOKWMMMMWMWK:                                         //
//                                       .,lkXMMMMMXd:.     .:oKMWMMNOl,.           .,;cdxxxdc.   ..                .,,;coxxxxkl.     .,okx;           .,;'                                  .,,;cl.                      .,;:oxkkl.   .:oxONMMWWKo;.       .lKMMMMWWWWWMMWWx.                                        //
//                        .,;,,.      .:o0WWWWMMMXd'   .,;oOXMMMWXOl'          .,cdOXMMMMWWMWWl .dXXd.        .;:ldkKMMMMMMMMMMMK,  .l0WMMMl        .lxKWMX:       .'.                  .:oxOXMMWWMl            .,;;;cdxkOXWMMMMWWMk;lOXWMMMMMKd:.      .;cxKWMMMKko:ld0WMWWo   .,,;,,;,,,;;::::cldkkkkkxxd,          //
//                     .:d0NMWWX; .,cxKMMMMMMMMXx' .;lkKWWWWWMMKl.         .;okKWMMMMW0kkdkWWWKkKMMMN:   .;oxkXWWWWWWMWN0xxdxKMMMx;oKMMMMXk,    .:dkXWMMMKo.  .':okKNO'              .lOXMMMMMMMWWK;   .,;,:oxkOXWMMWWMMMMMMWWMMMWMMWWMWWMMWKl.   .,;lxOXMMWWM0odlcdkKWWWWWWKkkOXWMMMMMMMMMMMMMMWWMMMMWWW0x:          //
//                  .lkXWMMWKxOXOdKWMMMMMWWMMMk::lkKWMMMMMWMMKl.     .,,;okKMMMMMMKdc'. .;xWMMMMMWXkd:cdOXWMMMMMMMMWXkl'.   .lXMMWWMMMKo:.   .:xXWMMMMXOl'':od0WWMMMMMl   .',,,;;;;:oKMMWMMMMMMKoc::oxk0NMMWMMMMMMMMWKdlloxxd0MMMWMMKkXWMMMWKkxkkkXWMMMNOxd0WMK0NMMMW0x0NMMMMMMMWWNKOkkkkkkkxdddl:;;;,,,'.            //
//               .cxXMMWKkddooOXWMMWKkxKMMMMMWXXMMMMWKo:dNMMXc',,;ldkKWMMMWMMMMXo::,,lxOXMMWWMMMWWX0NMMMMW0kooKMMWNk:;;;:okk0WWWMMWXxc.   ':dKMMMMMMMW0xxONMMMMWWWMMMMKkkk0NMMMMMMMMMMMMMMMMMMMKkOXWMMMMMMWKOxONWMMWWKkkOXMWWWMMNOo;.;XMMMMWWMMMWWN0xl;'   .dXMN0kd:,. .,c:;:;,;,''.                                  //
//             .lKWWMMXkdd0NWMMWWKxc. cWMMMWWWMW0kxl,.  'OWMMWNWMMMMMMWXkx0WMMWXOONWWWMMMKKWWMMMMMMMWKkxc,.  lMMMWWXXWWMMWMMMMWWXx:.  .:oONMMMMMMMMMMMWWWWMX0OkKWWMMMMMMWMMWMMMMMMWWWMMMMMMMMMMMMWWNOkxo:;,.  .kWMMMWMMMMMMWKOo:'    .lkkxkxooddc;'.         ','                                                      //
//            ;XMMWWMMNNWMWWMKxc;.    'kNWKkxl,,.        'xXMMMMWXOkxl,.  ;KWMWWWWMXOkd:;..l00kkxxl;,.       ,KMMMMMNKKNMMMMWWKl. .,cxKMMWXkOXWWMMMWXOkxo:,..  'xkkkxxxxxo:,,;;;;;,,,,;;,:lodxdxkl,'.          .;:loolol:;;,.                                                                                         //
//            cNMMMWMMMWXko;,.          .,.                .,,,,,.         .,:odl;;.                          .,,;,,,;xNMMMKo;,;cxKWMMN0o;.  ;ddc;,,.                                                                                                                                                                 //
//            .cOXXOdl;;.                                                                                         .lOXWMXdollxKMMWWKkl'.                                                                                                                                                                              //
//              ...                                                                                            .:dKWWMWMXOKWMMMXko;.                                                                                                                                                                                  //
//                                                                                                           'lKMMMMMMMMMMMKkl;.                                                                                                                                                                                      //
//                                                                                                        .ckNMMMWMMMMWKko;.                                                                                                                                                                                          //
//                                                                                                     .'lKWWMMMWWMW0xc.                                                                                                                                                                                              //
//                                                                                                   'lONMMMWMMWXkl,.                                                                                                                                                                                                 //
//                                                                                                .lONMWWMMWWKd:.                                                                                                                                                                                                     //
//                                                                                             .:oKWMMMMWN0l;.                                                                                                                                                                                                        //
//                                                                                           .lKMMWWWMN0l'                                                                                                                                                                                                            //
//                                                                                         .lKWWWMMWKd;.                                                                                                                                                                                                              //
//                                                                                      .;oKMMMWWKo:.                                                                                                                                                                                                                 //
//                                                                                     ,0WMMMWKdc.                                                                                                                                                                                                                    //
//                                                                                     lMMWKo;.                                                                                                                                                                                                                       //
//                                                                                     .odc.                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CMU is ERC721Creator {
    constructor() ERC721Creator("Maqueda_diversidad_1", "CMU") {}
}