// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Coast To Coast
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                    tttt               tttt                                                                                                           tttt              //
//                                                                                 ttt:::t            ttt:::t                                                                                                        ttt:::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//        cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::tttttttttttttt:::::ttttttt       ooooooooooo       cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::ttttttt        //
//      cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::tt:::::::::::::::::t     oo:::::::::::oo   cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::t        //
//     c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::tt:::::::::::::::::t    o:::::::::::::::o c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::t        //
//    c:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttttttttt:::::::tttttt    o:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttt        //
//    c::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t            t:::::t          o::::o     o::::oc::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t              //
//    c:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t              //
//    c:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t              //
//    c::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt  t:::::t    tttttto::::o     o::::oc::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt    //
//    c:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t  t::::::tttt:::::to:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t    //
//     c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t  tt::::::::::::::to:::::::::::::::o c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t    //
//      cc:::::::::::::::c oo:::::::::::oo  a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt    tt:::::::::::tt oo:::::::::::oo   cc:::::::::::::::c oo:::::::::::oo  a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt    //
//        cccccccccccccccc   ooooooooooo     aaaaaaaaaa  aaaa sssssssssss              ttttttttttt        ttttttttttt     ooooooooooo       cccccccccccccccc   ooooooooooo     aaaaaaaaaa  aaaa sssssssssss              ttttttttttt      //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                    tttt               tttt                                                                                                           tttt              //
//                                                                                 ttt:::t            ttt:::t                                                                                                        ttt:::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//        cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::tttttttttttttt:::::ttttttt       ooooooooooo       cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::ttttttt        //
//      cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::tt:::::::::::::::::t     oo:::::::::::oo   cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::t        //
//     c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::tt:::::::::::::::::t    o:::::::::::::::o c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::t        //
//    c:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttttttttt:::::::tttttt    o:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttt        //
//    c::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t            t:::::t          o::::o     o::::oc::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t              //
//    c:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t              //
//    c:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t              //
//    c::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt  t:::::t    tttttto::::o     o::::oc::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt    //
//    c:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t  t::::::tttt:::::to:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t    //
//     c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t  tt::::::::::::::to:::::::::::::::o c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t    //
//      cc:::::::::::::::c oo:::::::::::oo  a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt    tt:::::::::::tt oo:::::::::::oo   cc:::::::::::::::c oo:::::::::::oo  a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt    //
//        cccccccccccccccc   ooooooooooo     aaaaaaaaaa  aaaa sssssssssss              ttttttttttt        ttttttttttt     ooooooooooo       cccccccccccccccc   ooooooooooo     aaaaaaaaaa  aaaa sssssssssss              ttttttttttt      //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
//                                                                                    tttt               tttt                                                                                                           tttt              //
//                                                                                 ttt:::t            ttt:::t                                                                                                        ttt:::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//                                                                                 t:::::t            t:::::t                                                                                                        t:::::t              //
//        cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::tttttttttttttt:::::ttttttt       ooooooooooo       cccccccccccccccc   ooooooooooo     aaaaaaaaaaaaa      ssssssssss   ttttttt:::::ttttttt        //
//      cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::tt:::::::::::::::::t     oo:::::::::::oo   cc:::::::::::::::c oo:::::::::::oo   a::::::::::::a   ss::::::::::s  t:::::::::::::::::t        //
//     c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::tt:::::::::::::::::t    o:::::::::::::::o c:::::::::::::::::co:::::::::::::::o  aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::t        //
//    c:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttttttttt:::::::tttttt    o:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::o           a::::as::::::ssss:::::stttttt:::::::tttttt        //
//    c::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t            t:::::t          o::::o     o::::oc::::::c     ccccccco::::o     o::::o    aaaaaaa:::::a s:::::s  ssssss       t:::::t              //
//    c:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o  aa::::::::::::a   s::::::s            t:::::t              //
//    c:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t            t:::::t          o::::o     o::::oc:::::c             o::::o     o::::o a::::aaaa::::::a      s::::::s         t:::::t              //
//    c::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt  t:::::t    tttttto::::o     o::::oc::::::c     ccccccco::::o     o::::oa::::a    a:::::assssss   s:::::s       t:::::t    tttttt    //
//    c:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t  t::::::tttt:::::to:::::ooooo:::::oc:::::::cccccc:::::co:::::ooooo:::::oa::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::t    //
//     c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t  tt::::::::::::::to:::::::::::::::o c:::::::::::::::::co:::::::::::::::oa:::::aaaa::::::as::::::::::::::s       tt::::::::::::::t    //
//      cc:::::::::::::::c oo:::::::::::oo  a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt    tt:::::::::::tt oo:::::::::::oo   cc:::::::::::::                                                                                 //
//                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract COAST is ERC721Creator {
    constructor() ERC721Creator("Coast To Coast", "COAST") {}
}