// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Money Shitters
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                               ..',,,,''..                                                                                                                                                                          //
//                                                                                                                             'lxO000000OOkdoc;'.                                                                                                                                                                    //
//                                                                                                                            ,k0000000000000000Okdl;..                                                                                                                                                               //
//                                                                                                                           .l00000OOOOOOO0000000000Oxl:'.                                                                                                                                                           //
//                                                                                                                            ;k0000OkkkkkkkkkOO000000000Oxl:,.                                                                                                                                                       //
//                                                                                                                             ;k0000OOkkkkkkkkkkkOO0000000000ko:.                                                                                                                                                    //
//                                                                                                                              ,x0000OkkkkkkkkkkkkkkkOO000000000kd:.                                                                                                                                                 //
//                                                                                                                               ,x0000OkkkkkkkkkkkkkkkkOOO000000000Oo;.                                                                                                                                              //
//                                                                                                                               .o0000OOOOOOOOOOOOOOOOOOkkOOOO00000000kl'.                                                                                                                                           //
//                                                                                                                               .d0000OOOOOOOOOOOOOOOOOOOOOOOOOOO0000000Od;.                                                                                                                                         //
//                                                                                                                              .lO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000kc.                                                                                                                                       //
//                                                                                                                             .lO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000kl'                                                                                                                                     //
//                                                                                                                            'd00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000Ol'                                                                                                                                   //
//                                                                                                                           ;k00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000kl.                                                                                                                                 //
//                                                                                                                         .cO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000kc.                                                                                                                               //
//                                                                                                                        .lO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000x;                                                                                                                              //
//                                                                                                                       .lO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000Ol.                                                                                                                            //
//                                                                                                                       cO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000x;                                                                                                                           //
//                                                                                                                      ,k0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000Oc.                                                                                                                         //
//                                                                                                                     .l0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000Oo.                                                                                                                        //
//                                                                                                                     .x0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000d.                                                                                                                       //
//                                                                                                                     ,k0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000o.                                                                                                                      //
//                                                                                                                     'x0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000l.                                                                                                                     //
//                                                                                                                     .o00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000Oc                                                                                                                     //
//                                                                                                                     .lO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000x'                                                                                                                    //
//                                                                                                                  .':dO0000000OOOOOOOOOOOOOOOOkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000Oc                                                                                                                    //
//                                                                                                              .':oxO0000000OOOkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000o.                                                                                                                   //
//                                                                                                           .;lxO000000OOkkxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000d.                                                                                                                   //
//                                                                                                        .;ok000000OOkxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000o.                                                                                                                   //
//                                                                                                      .:x000000OkkxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000Oc                                                                                                                    //
//                                                                                                    .ck00000OkkxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000Ol,..                                                                                                                 //
//                                                                                                  .:x00000OkxxxxxxxxxkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000OOkxoc;'.                                                                                                           //
//                                                                                                 'oO0000OkxxxxxxxkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000Okdc'.                                                                                                       //
//                                                                                                ;k0000OkkxxxxkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkOOOOO00000000Oxl,.                                                                                                    //
//                                                                                              .cO0000OkxkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxxxxkkkkkkkkkOOO0000000Ox:.                                                                                                  //
//                                                                                              :O0000OkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxkkkkkkkkkkkkkOOOOO0000000kc.                                                                                                //
//                                                                                             ;k0000OkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxkkkkkkkkkkkkkkOOOOOOOOO000000x,                                                                                               //
//                                                                                            .d0000OkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOO00000Oc.                                                                                             //
//                                                                                            cO0000OkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOO00000Oc.                                                                                            //
//                                                                                           .d0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxxxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOO0000O:                                                                                            //
//                                                                                           'k0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOO0000x'                                                                                           //
//                                                                                           ,k0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOO00000c                                                                                           //
//                                                                                           ,k0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000d.                                                                                          //
//                                                                                           'x0000OOOOOOOOOOOOOOOkxdoolllcclloodkOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxxxxxkkkkkkkkkkkkkOOOOkxdoollcclllodxkkOOOOOOOOOOOOOO0000x'                                                                                          //
//                                                                                           .l00000OOOOOOOOOOOxdlc:;;,,,,,,,,,;;:codkOOOOOOOOOOOOOOOOkkxxxxxxxxxxxxkkkkkkkkkkkkkOOkxdlc:;;,,,,,,,,,;;:codkOOOOOOOOOOO0000x.                                                                                          //
//                                                                                            'x00000OOOOOOOkdl:;,,'''''......'''',,;:oxOOOOOOOOOkkxxxxxxxxxxxxxkkkkkkkkkkkkkkOOOkdl:;,,'''''......'''',,;:oxOOOOOOOO00000o.                                                                                          //
//                                                                                             ;k00000OOOOOdc;,,''..................'',;lxOOkkxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOkdc;,,''..................'',;lxOOOOOO0000k,                                                                                           //
//                                                                                            .,d000000OOxl;,''...........  ...........',;lxkxxxxxxxxxkkkkkkkkkkkkkkkkkkkOOOOOxl;,''........... ............',;okOO000000kl,..                                                                                        //
//                                                                                        .;coxO0000000Od:,''......               .......',cdkkxxxxkkkkkkkkkkkkkkkkkkkOOOOOOOd:,''.......','.           ......',ck0000000000Oxl;..                                                                                    //
//                                                                                    .,cdO00000000000Od:,'.....         .:oo'       ......':dkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOd:,'.....   ,kK0:              .....':dkkkOOO0000000Odc'                                                                                  //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract shit is ERC721Creator {
    constructor() ERC721Creator("Money Shitters", "shit") {}
}