// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Badteeth
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    BADTE.ETHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMWX0Okxdx0NWNXXWWMMMMWNKO0KXNWMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWX0xollox0Oxoccccc:::::::;:::c:;,. ..,,;coxOKNWMMMNXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWXkddddoc:;,...                                 .o0KKXWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWKdc:cc;..    .                                   'lxOXWMWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWWMMMN0kOXXkl;.                                                 .:dKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMN0Ok00d,                .;:,. .,::;,''.';::;;;:;,..             .;xKWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNXWMW0l.     ..       .;cc:.                 ..,:clc:'.            .l0WMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWNWMMMMMXd,.  .,:;'..                                   .',,..     .,.    .:OWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0ONN0xdxkd,  .;oxo,                                                           .:OWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMN0ko,.     .:xK0l.  .':;.                                                        .c0WMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWWMW0c.      ,dKWMO;.'cdOK0:                                                           .c0WMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMX0XNd'.;.   ,xNWNNWX0KNWKd;.                                                              .xWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWNKKOlcx0d..;kXNOc:xNMWXx:.                      .',;::,.                                 .. :NMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMK0Kxd0Xk;.,xOdl:.,xNNOc.                     .cxOXNWWMMN0xxkOOc.                          'dc'xWMMMMWXNMMMMMMMM    //
//    MMMMMMMMMN0x0N0:..oko,..;kNNk;.                      :0WMMMMMMMMMMMMMMMNo.                          'dc'dWMMMWKO0NMMMMMM    //
//    MMMMMMMMNxoKXo..cOxlk000XXk;                       'dNMMMMMMMMMMMMMMMMMMXc                           .o;'kMMMMMNKXWMMMMM    //
//    MMMMMMWXdoKXc.'xNXOXMNOdo;.                       lXMMMMMMMMMMMMMMMMMMMMM0,                           'l,:KMMMMMMMMMMMMM    //
//    MMMMMMNkOXXl.;0KXWWW0l:;.                'cdkOOkol0MMMMMMMMMMMMMMMMMMMMMMWk,..                         ;c'dWMMMMMMMMMMMM    //
//    MMMMMWOONXl.cKx;xWNx:c;.               ;kNMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMWNXK0ko:.                    .:.'0MMMMMMMMMMMM    //
//    MMMMMW0dx:.oKd'lXNxcl'               .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd'                      :XMMMMMMMMMMM    //
//    MMMMMMXx,.oXd,lXW0ko.               'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                      oNMMMMMMMMMM    //
//    MMMMXOXXodXXdkNMWKl.               .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                     .dWMMMMMMMMM    //
//    WMMXlcKKOXMMWMWWWd.                ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl                      .xWMMMMMMMM    //
//    NMNo.cOk0MMMMMNN0'                 cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                       .kWMMMMMMM    //
//    MMO,;olxNMMMMMMWo                  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0x:.                         ,0MMMMMMM    //
//    MM0kkll0WWWMWNWK;                   lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO0K0kc.                           :XMMWWMM    //
//    MMMM0:oX0KMMWWMk.                   .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWMMMWd.                          .xWMK0WM    //
//    MWNNKdkXOXMMWWWd.                     .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.                           ,KM0d0N    //
//    W0OOxdKK0WMMMMNl                       cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                           .dWXdxN    //
//    NKXNxxNNWMMMMMX;                       cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.                             ;KWKKW    //
//    MMWKokMMMMMWMW0'                       .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.                         .'   .kNWMM    //
//    MWMO:OMMMMMMMWO.                        .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:.                   .       .dc  .dWMMM    //
//    K0Xo;0MMMMWMNKd.                         .c0K00000OXMMMMMMMMMMMMMMMMMMMMMMMMNx,.                    .:,      .OX:  lWMMM    //
//    kdXo:KMMMMMM0oc.                           ...    .kMMMMMMMMMMMMMMMMMMMMMMMMK,      '.              .l;      'OWx. cNMMM    //
//    doXxlKMMMMMM0oc.                                  ,KMMMMMMMMMMMMMMMMMMMMMMMMNc     ,;               .l,      ,KWXc cNMMM    //
//    KKWOoKMMMMMMXoc'                                  cNMMMMMMMMMMMMMMMMMMMMMMMMMK;    '.               .c,.   ''cXKXO'lWMMM    //
//    MMMNOKMMMMMMWko,                                 .xWMMMMMMMMMMMMMMMMMMMMMMMMMMO.     '.             'cld' 'ocxNXNKcdWMMM    //
//    MMMWWWMMMMMMMXOc                                 .lKMMMMMMMMMMMMMMMMMMMMMMMMMMNc    ':'             ,okK;.xxoKNKN0lOMMMM    //
//    MMMMMMMMMMMMMN0o.                                 .dWMMMMMMMMMMMMMMMMMMMMMMMMMWl  'dl'            '.;xKNkOXdxWMWNOkNMMMM    //
//    MWNNWKKMMMMMMWX0c                                  dWMMMMMMMMMMMMMMMMMMMMMMMMMK;  'dl.           :o;:OWMWWOo0MMWWXNMMMMM    //
//    WXk0WOxNMMMMWWMMO'                                .xMMMMMMMMMMMMMMMMMMMMMMMMMMNOdoldOc          ,0Kk0NMMMNooNMMMMMMMMMMM    //
//    WWXKWNKNMMMMMMMWNd.                               .kMMMMMMMMMMMMNKKKKKKXXKK0KXWMMMMMWx.        .xWMMMMMMMXOKWWWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMN0c                               '0MMMMMMMMMMMWx.............,:clodo,         ;KMWOd0WMMMMMWXNMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNOd;                             .dNMMMMMMMMMMMMO.                             lNMk. .xWMMMMMMMMMMMMMMMM    //
//    MMMMWWMMMMMMMMMNK0kd:                          .;OWMMMMMMMMMMMMMW0o'                           cNNc   'OMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWMMMMMWkdkxxc.                     .,oONMMMMMMMMMMMMMMMMMWKo'                         '00,  ';oNMMMMMWNWMMMMMMM    //
//    MMMMMMNNWWWMMMMMWOoxKXd.                 .:d0NMMMMMMMMMMMMMMMMMMMMMMMNOxl.                    .lKo.  ':kWMMMMMMWMMMMMMMM    //
//    MMMMMMWWMMMMMMMWWWXXWMWO,            .,lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o.                  'l:.   'kWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWWKxc.         ;ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;                 .;.  .cKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNKXO:      .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.             .;dKKc'cONMMMMWXKWMMMMMMMMMMM    //
//    MMMMMMMMMWXNMWWMMMMMMMMWXXNNx'    cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:     ..'...,o0X0kxOXWMMMMWKdlOWMMMMMMMMMMM    //
//    MMMMMMMMMWNWMMMMMMMMMMMMWXOOXKo. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOccoxkOxdoxO0Oxxk0NMMMMMMNkoxXWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMN0xk00dxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXXX0xoox0NMWXKNMMN0kOXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMXxlo0WMMMMMNXXKOOKNWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNKkdxOXWMMMWXklldOXWWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00XWMWXXWXx;,lONMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMNOxdookXWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM$$$$$$$$\MMMMMMMMMMMMMMMMMMM$$\MMMMM$$\MMMMMMMMMMMMMMMMM$$\MMMMMMMMMMMMMMMMMMMMMMM$$\MMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM\__$$  __|MMMMMMMMMMMMMMMMMM$$ |MMMM$$ |MMMMMMMMMMMMMMMM$$ |MMMMMMMMMMMMMMMMMMMMMM$$ |MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM$$ | $$$$$$\MMM$$$$$$\M$$$$$$\MMM$$$$$$$\MMMMMMMMMMMM$$$$$$$\MMM$$$$$$\MMM$$$$$$$ |MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM$$ |$$  __$$\M$$  __$$\\_$$  _|MM$$  __$$\MMMMMMMMMMM$$  __$$\MM\____$$\M$$  __$$ |MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM$$ |$$$$$$$$ |$$$$$$$$ |M$$ |MMMM$$ |MM$$ |MMMMMMMMMM$$ |MM$$ |M$$$$$$$ |$$ /MM$$ |MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM$$ |$$   ____|$$   ____|M$$ |$$\M$$ |MM$$ |MMMMMMMMMM$$ |MM$$ |$$  __$$ |$$ |MM$$ |MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM$$ |\$$$$$$$\ \$$$$$$$\MM\$$$$  |$$ |MM$$ |$$\MMMMMMM$$$$$$$  |\$$$$$$$ |\$$$$$$$ |$$\MMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM\__| \_______| \_______|MM\____/M\__|MM\__|$  |MMMMMM\_______/  \_______| \_______|\__|MMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\_/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBADTE.ETH    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BDTH is ERC721Creator {
    constructor() ERC721Creator("Badteeth", "BDTH") {}
}