// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: NARISOFKA editions
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                          //
//                                                                                                                                          //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.    'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo::coxOKNWMMMMWKc.  'c'  ;KMWNKkol::ckNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO:       .';coxkl.  .dXWk.  ;o:'.      .xWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOc.  lOkoc;..      .lKWMMNl      .;ll'  .xMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;. .kMMMMWNKOxolldKWMMMMMXo;;cdOXWWx.  :XMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;. ;KMMMMMMWWNXK0OOkkxxxxxxxxkOOOOd'  ,0MMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdKWNKkdlc;,....                    'OMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXd;..,dXMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:'.    ...',;:cclllllll:,',,;:;:dKWMMMN0OXMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNx'      ,xX0o,ckOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,..,coxk0KXNWNKXWMMMMMMXc....;kNMMMMMMNl. :KMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMN0x0WXc.  .cc.   .. ':. .kMMMMMMMMMMMMMMMMMMMMMWWWW0odXMMMWK0XWMMMMMMMWO;.:KKdldXMNkc;'';kWMMMMMMNl  .xMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWo. :k;   'kWW0l'. .lKd.  cOkk0NMMMMMMMMMMMMMMMNd,o0c .dWMMMMMMMMMMMMMMWk;;dd.  .OMMMMWNN0xKMMMMMMMk.  lWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMWOlod'   ,0WMMWNX00XWMk.   .  .lNMMMMMMMMMMMMMMNl ;Oc  cNMMMMMMMMMMMMMMMWNKl.  .xWWXkoloOK0NMMMMMMMK,  :XMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWk'   :KWXkl;,:xXMMMNx:'.   .xWMMMMMMMMMMMMMMMXOKNl  ;XMMMWNMMMMMMMMMMW0;   ,OXOl.    .lXMMMMMMWNXc  '0MMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMXo.  .lKOl'      :XMMMWO;   ;OWWX0kxxxk0XWMMMN0k0NWx. .d0KXdlKMMMMMMMMWx.   ;do,.  .'.   oWMMMMXl'ol  .oK0KWMMMMMMMMMMMMM    //
//    MMMMMMMMK:   .:c,.  .,c'   oWWKc.  .lxdc,..      .:kNNo. .'co:........cxOKNWMMMk.   ...   'l0Nd.  ,KMMMM0' 'c.  ....lXMWXKWMMMMMMM    //
//    MMMMMMMWo         'lONWo   ;KO'    ..   .';lodoc.  .c0l      .',;;;'   ....;cd0d.     .,oONMMMk.  '0MMMMX: ,o'      .xWk'.:0MMWWMM    //
//    MMMMMMMWx.    .;oONMMMMd.  ,0o      .,cx0XK0NMMWK:   oO'  .:l;.   ..  ';;,.   .,cc;:cx0NMMMMMMk.  ,KMMMMWKxOXo..:l.  lKc   cNMWWMM    //
//    MMMMMMNKKOxodkKWMMMMMMWo   :XXxc:cdkKWW0o:..;0MMMk.  ;Kd.  :XWXOxol.   ....   .;0WWMMMMMMMMMMWo   :XMNOo:;;:ldkKWK,  ;Ko   '0MMMMM    //
//    MMMMMXc..xWMMMWWMMMMMMX:   oWMMMMMMMMMMO;.;:;kWMMx.  ;XXc  .oNMMMMNl .lOkkxkkOKNMMMNkookKWMMM0'  .xW0:   .,'..'OMX;  '0k.  .kMMMMM    //
//    MMMMMNk::OWMKl;:okKXNXo.  ,0MMMMMWNWMMMMNXNWWWMMX:  .dWM0,  .xWMMMX: .xMMMMMMMMMMMM0,   .,:c:.  .oNK;  .dXWNXkdKMN:  .O0'  .xMMMMM    //
//    MMMMMMMWWMMMO,    ..'.   ,OWMMMNd,':d0WMMMMMMMW0:   cXMMM0,  .kWMMK, .kMMMMMMMMWXkOKOc.      ..:kNMk.  cNMMMMMMMMX:  'OX:  .xMMMMM    //
//    MMMMMMMMNkloOKd,     .':xXMMMMMNl    .;ok0KK0kc.  .lXMMMMW0,  .kWMO. .OMMMMMMMMXc  'oOOl.   'xXWMMMk.  ;XMMMMMMMMK,  ,KWd  .kMMMMM    //
//    MMMMMMMMK;  .:dko,   ;0WMMMMMMMMNo.      ....   .cOWMMMMMMM0;  .dKo. ,KMMMMMMMMWO;   .':;.   oWMMMMX:  .lXWMMMMMWd.  oWM0' ;KMMMMM    //
//    MMMMMMMMMKc.   .''   .xWMMMMMMMMMWO,  .cc:;;:cokXWMMMMMMMMMMKc  ...  cNMMMMMMMMMMXo.       .;OWMMMMMKc   'lk0K0kc.  :KMMW0kKWMMMMM    //
//    MMMMMMMMMMNx'  ....';dXMMMMMMMMMMMMXo. ,kNWWWMMMMMMMMMMMMMMMMNd'    ;0MMMMMMMMMMMMW0: 'xOOOKWMMMMMMMMNk:.   ...   'dXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMKl'lKNXNWMMMMMMMMMMMMMMMW0c..cXMMMMMMMMMMMMMMMMMMMWXOkkONMMMMMMMMMMMMMMMNO0WMMMMMMMMMMMMMMMWKkoc::cldONWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMWXkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                          //
//                                                                                                                                          //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract narisofka is ERC1155Creator {
    constructor() ERC1155Creator() {}
}