// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: one of the five mountains,
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//    Tai has been a place of historic interest since ancient times.                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//    At this moment, it is a holiday, Mount Tai is bustling with people, people, tourists coming and going.                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//    Hundreds of meters away from the main mountain road of Mount Tai, a diameter of more than ten meters, showing a gray brown rock, standing in a dense forest.                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//    On the stone, a length of about six meters, the shape of a lizard ferocious beast is quietly lying down, it is covered with golden skin spread with black lines, the first born a golden horn, behind the growth of a pair of meat wings and giant tail, broken golden eyes calmly watching the walkers on the mountain, exhaling the light of wisdom.    //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract OOTFM is ERC721Creator {
    constructor() ERC721Creator("one of the five mountains,", "OOTFM") {}
}