// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Pili ā nai kealoha
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//    This is my first poem on Ethereum blockchain. I wrote this for my wife as a gift on Mother's Day 2022 in hopes that it would convey the depths of my love for her and our relationship. My hope is that my children and their children will be able to experience the love we have for one another throughout time.                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//    This picture was taken on our wedding day on July 31, 2019. The half-circle was arranged by my cousin and closed after my wife joined me inside for our ceremony and to complete the circle as we made our vows to each other. We were married at sundown as the day came to end. One of my favorite parts of this photo is that you can see Kanaloa (Kaho'olawe) as witness to our bond.    //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//    Even in death I hope to find new beginnings with my best friend if there is an opportunity in the next life.                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//    Hipsey Nussle                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract nAvA is ERC721Creator {
    constructor() ERC721Creator(unicode"Pili ā nai kealoha", "nAvA") {}
}