// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Untitled
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    cccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;clodxkkOO00KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNXXXXNNNXXNNNNXNNNNXXNXXNNXXXXXXXXXXNNNNNNNNXNNXNNNNXXNNNNNNNNNNNNNNNNNXNXXNNXNNXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    ccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:codxxkOO00KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNXNNNNNNNXXNNXNXXXXXXXNXNNNNNNXNNNNXNNNXNNXNNNXNNNNNXXXXNNXNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    cccccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:codxkOO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNXNNXNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXNNNNNNXNNNXNNXXNXNXXXXNNNNXXXXXNNXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    ccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;codxkOO0KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNXNNXNNXXXXXXXXXXXXXXXXXXXXXNXXXXXNNXXXXXXNXXXXXXNXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    cccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkOO0KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNXXNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    ccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;codxkO0KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNXNNNNXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    cccccccccccccccccccccccccccccccccccccccccccc::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNXXNXXXNNNXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK    //
//    ccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK    //
//    ccccccccccccccccccccccccccccccccccccccccc::::::::::::::::::::::::::::;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:coxkOO0KKXXNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNXXNXNXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK    //
//    cccccccccccccccccccccccccccccccccccccc::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;coxkOO0KKXXNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKK0    //
//    ccccccccccccccccccccccccccccc::cc:ccc::::::c::::ccc:::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;coxkkO0KKXNNNNNNNNNNNNNNNNNNNNNXXXXXNXNNXNXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKK0000    //
//    ccccccccccccccccccccccc:::::c:::::::::::::cc::cccc:::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;coxkOO0KKXNNNNNNNNNNNNNNNNNNXXNXXXXXNXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK0000000    //
//    cccccccccccccccccc::;;;;;;;;;::::::::::::::c:ccccccccccc:::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:coxkO00KKXNNNNNNNNNNNNNNNNNXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXXXXXXKXKKXXXXXXXXXKXXXXXXKKKKKKKKKKKKKKKK0000000OOOO    //
//    ccccccccccc:::;,,'.............',;;:;;;;;,;;;:::::::cc:::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkO0KKXXNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKXXXXXKXXKXXKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000OOOOOOk    //
//    ccccccc::;,,'.................................'',,,,;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;codkOO0KKXNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000OOOOOOkkkkk    //
//    cc:::;,'.............................................'''',,,,,,,,;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkO00KXXNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000OOOOOOOkkkkkxxx    //
//    :;,,'.......   .....................................'''''''',,;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:codkOO0KXXNNNNNNNNNNNXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXKKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000OOOOOOkkkkkxxxxddd    //
//    ;,'.......   ............................      .....'',;;;,,,,''','';:;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxkO0KKXNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000OOOOOOOOkkkkxxxxdddoool    //
//    '........  ...................................    ...'';:::;;;,''''',,;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cdxkO00KXNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000OOOOOOkkkkkkxxxxdddooollcc    //
//    ........  ...................................       ...';:ccc::::;;;;,;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::coxkO00KXNNNNNNNNNNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000OOOOOOOkkkkkxxxxxddooolllccccc    //
//      .....   .............................................,;;:cllccllcccc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::coxkO00KXNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000OOOOOOOOkkkkxxxxxdddooolllcccccc::    //
//      .....  ................'''''''''''''''''''.......'...;:cccloooooooooolc::;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;::::coxkO00KXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000OOOOOOOOkkkkkxxxxdddooolllcccccccccccc    //
//      ....  ........''.'''''''''''''''''',,,,,,,,,''''';;.';clllooooooolllollc::;:::::;::;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::cdxkO0KKXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000OOOOOOOkkkkkxxxxdddooolllcccccccccccccccc    //
//      ...    ........'''''',,,,,,,,,,,,,,,,;;;;;;,,,,',;:;,',;cclooddodollc::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::ldkOO0KXXNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKK0KKKK000000000000OOOOOOOOOkkkkkxxxxxdddooolllccccccccccccccccccc    //
//            .........''''',,,,,,,,,,,,;;;;;;;;;;;;;;,,,;::;,'',;:clooooollc:;;,;;:clc::;;;::;;;;;;;;;;;;;;;;;;;::::::::coxkO00KXXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KK0000K00000000000000OOOOOOOOkkkkkkxxxxdddooolllccccccccccccccccccccccc    //
//            .........''''',,,,,,,,;;;;;;;;;;;;;;;;;;;;;;:cc:,'',;;;;:llllcc:;;,,,;coolc::::::;;;;;;;;;;;;;;;;;::::::::ldxkO0KXXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000OOOOOOOkkkkkkxxxxdddooollllcccccccccccccccccccccccccc    //
//            ........''''',,,,,,,,;;;;;;;;;;;;;;;::::::::clllc:;,,,,,,,;ccccc:;,,,,;coolc::;::;;:;;;;;;;;;;;;;:::::::coxkO00KXXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000OOOOOOOkkkkkkxxxxddddoollllcccccccccccccccccccccccccccccc    //
//          ........''''',,,,,,,,,,,;;;;;;;;;;;;;::::cclllooddddlc;,,,,,'',;:cccc:;,,,:lolc::::::::::;;;;;;::::::::::ldkOO0KXXNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000OOOOOOOkkkkkkxxxxddddooolllcccccccccccccccccccccccccccccccccc    //
//         ........'''''',,,,,,,,,;;;;;;;;;;;;;;::::cloooddxxxxkkdl:;;;;,,,'''',;:::;;;:lllc::::::::;;::;::::::::::coxkO0KKXNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000OOOOOOOOkkkkkkxxxxdddooolllcccccccccccccccccccccccccccccccccccccc    //
//        ........''''',,,,,,,,,,,,,,,;;;;;;;;;;:::ccldddxkkkOkkOOkdlc:;;::;;;,,,,,,,,,;:lolc::::::::;:::::::::::coxkO00KXXNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000000000OOOOOOOOkkkkkkxxxxddddoolllcccccccccccccccccccccccccccccccccccccccccc    //
//       ......''''''',,,,,,,,,,,,,,,,,,;;;;;;;:::cclodxxkkOOOOOOOOkdllcc::;,;;::;,,,,,,,:coolcc::::::::::::::::ldkOO0KXXNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000OOOOOOOOkkkkkkxxxxdddooolllccccccccccccccccccccccccccccccccccccccccccccc    //
//      ......''''''''',,,,,,,,,,,,,,,,;;;;;;:::clloodxxkkOO00000OOOOxooolc:;,'......''',;:loolc::::::::::::::coxkO0KKXXNNNNNNXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000KKKKKK0000000000000000000OOOOOOOOkkkkkxxxxdddooolllccccccccccccccccccccccccccccccccccccccccccccccccc    //
//     .....''''''''''''',,,,,,,,,,,,,,;;;::cllodddxxxkkOO0000000000OOkdodoolcc;,'.....''';:cloolcc:::::::::codkO00KXXNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK00000OOOOkkkxxxxdddddoooooooddddxxxkOO000000000000000OOOOOOOOkkkkkxxxxdddooolllccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//     ....''''''''''''''''',,,,,,,;;;:ccloodxxxxkkkkOOO0000000000000OOkdddddol:;,,''..'',;;:codoolcccc:::cldkOO0KXXNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKK000OOkkxxdddoolllllllcccccccccccccccccccccccccllodxxkO0000000OOOOOOOOkkkkkxxxxdddoolllccccccccccccccccccccccccccccccccccccccccccccccccccccccccc    //
//    .............''.''.'''',,,;;:cloooddxxxxkkkOOO00000KKKKK00K0000OOOkdoooolcc;'...',,;:cc:cloodolccccldxOO0KXXXNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0OOkkkxxxddooollllccccccccccccccccccccccc::::::::::::::::::cccccloddxkOOOOOOOkkkkkkxxxxddooolllcccccccccccccccccccccccccccccccccccccccccccccccclccccccclccc    //
//    .....................',,;:cloddxxxxxxkkkkkkOOOOO000KK000000000OOOOkxdollolc:;;,'.'',:clol:clolcllloxkO0KXXNNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXKK00Oxxdollccccccccccccccccccccccccc:ccc:::::::::::::::::::::::::::::::::cccllodxkkkkkkxxxxdddoolllccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllll    //
//    ..................''',,:clodxxkkkkkkkkkxxxxxdxxxxxkkkkkkOO0000OOOOkkxdoc:clc;;::;;,,,,;cllcclccc::cok0KXXNNXXXXNXXXXXXXXXXXXXXXXXXXKKK0OOkxdolcccccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::cccloddxxdddoolllccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllll    //
//    ............''',,;;:::cclodxxk000OOkkkxxxddddddxxxxkkkkkkkkkkkkOOOkkkxxo:,;:;;,,;;;;;;;;;:ll:cllc:cldkKXXXXXXXXXXXXXXXXXXXXXXXXKK00Okxddollcccccccccccccccccccccccc::::::::::::::::::::::::::::::::::::::::::::::::::::::::ccclloollccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllll    //
//    ...........',;;:cclllooooodxkO0K0OOOkkkkkkkkxxkkkkOOO0000OOOkxxkkkkkkkxxo:,,,...'',;;;::;:clc:cddcclodk0XXXXXXXXXXXXXXXXXXXKK0Okxddolllccccccccccccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllll    //
//    .........',,;:lloddddddddddxkO0K0OOOkkkkkxxxxxxxxkkkkkOOOOOOOOOkkkkkkkxxxo;,,...,;:cc:::;;:llc:okx:coodk0XXXXXXXKK000Okkxxddoollllccccccccccccc:::::cc::ccccccc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllll    //
//    ...'....',,,,';cldxxxxxkxdddxk0K0OOkkkkkxxddoooolodxxxxxxxkkkkOOkkkkkkxxxdc;;..';ccclll:,,;cc:::oOd;:ccld0KXK0Oxdoollcccccccccccccccccccccc::::ccc::ccccccccccccc::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllll    //
//    ''',''.';lllolldxk0OkxxxkxddxkO0OOOkkkkkkxdooxdlc;clcodddddxxkkkkkkkkxxxxxl:,..':llcccc;,,,,;;,;;d0l'';::dOOxollcccccccccccccccccccccccccc:::::::cccccccccccccccc:::c::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllll    //
//    ;;;:ccccodxxxxxkkOOkxxxxxxddxkOOOOOkkkOOkxxdxkkxxodddxxoloddxkkkOkkkkxxxxdl;...;cc:;;,,''..'''''':Ox,,,;;;clolccccccccccccccccccccccccccc:::::::::ccccccccccccccccccc::::cccc::::::::::::::::::::::::::::::::::::::::::::::::::c:cccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllll    //
//    ccldxxxxxxkkkkkkkkkxxxxxxxddxkOOOOkkOOOOkkxxxxxxkkkkkkkkxxxxkkkOOkkkkxxxxdl;..','...........'..'',do''',;,,;:ccccc:cc:::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccc::cc::::ccc:ccccccc:::::::::::c::::::::::::cccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllooolloooooooo    //
//    cldkOOOOOkkkkkkkkkkxxkkxxddxkkkOkkkkOOOkkkkxkkkkkkOOOOOOOOOOOOOOOOOkkkxxxdl,..............''......;,..';:,'';ccc:::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::cccccccccccccccccccccccclccllllllllllllllllllllllllllllllllllllllooooooooooooooooooooo    //
//    lldkOOOOOOOOOOOOkkkkkkkkdddxkkkkkkkkkOOOOOkkkkOOOOOOOOO0000000OOOOkkxxxddl;'.................''''',,'';:;,'';:c::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllloooooooooooooooooooooooooooooo    //
//    lodxOOOOOOOOkkkkkkkkOkkxdddxxkkkkkkkkOOOOOOOOkkkkOOOOOOOOOOOOOkkkxxddolc:,..............''''',,,,,;::cc:;;;;:c::::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooo    //
//    dooxOOOOOOOkkkOOOOOOOOkxdddxxxkkxxxkkOOOO0OOOOOOOOkkkkkkkkkxxxxddollc;,'.................',;;;:::;,;:cll:::ccccc:::::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooo    //
//    ddodkkkkkkkOOOOOOOOOOOkxddxxxxxxxxxxkOO00000OOOkkkkkxxxddddooolllcc:;,'............'''...',:c::cllc::cccccccccccccc:::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooo    //
//    ododkkkkOOOOOO0000000OxdddxxxxxxxxxxxkOO0OOOkkkxxdddoollllllllllcc::;;,,'... .......;:;'..';clccccllllllllolllcc:c:::::::::::::::::::::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllloooo                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract UnTtld is ERC721Creator {
    constructor() ERC721Creator("Untitled", "UnTtld") {}
}