// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Somnium
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0KKdcdXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MNK000KNMMMMMMMMMMMMMMMMX0000XMMMX00000XMMMMMMMMMMMMMMNK0000XWMMMWX00000000000KXNMMMMMMMMMMMMMMMMWKxc,;dl,ccxkdOWMMMMMMMMMMMWNMMMMMMMMMMMMMMMMMN0000NM    //
//    MNd,'',oNMMMMMMMMMMMMMM0:''':0MMMXd,''';kNMMMMMMMMMMW0l,'',l0WMMMWKd;''''''''',;:lx0NMMMMMMMMMMMNx;.,cOx:kWKkd,'lKMMMMMMMMMMKldKWMMMMMMMMMMMMMMk,'',OM    //
//    MMNd''''oNMMMMMMMMMMMM0:''':0WMMMMW0c''''l0WMMMMMMMNx,''';xNMMMMMMMWKd;,,,,,,'''...,cxXMMMMMMMMNd'.:OWWxxWMOd0o'.cXMMMMMMMMM0;.;o0WMMMMMMMMMMMMk,'.,OM    //
//    MMMNd''''oNMMMMMMMMMM0:''.:OWMMMMMMMNx;''';xNMMMMMMXo,.'lKWMMMMMMMMMMWXKKKKKK0Oxo:'''':kNMMMMMMXdlo0MMM00WO:dW0;.,kMMMMMMMMM0;.'',lONMMMMMMMMMMk,'.,OM    //
//    MMMMNd''''oNMMMMMMMM0:.'':0WMMMMMMMMMW0l''''c0WMMMMMWOokNMMMMMMMMMMMMMMMMMMMMMMMMNkc''.'dNMMMMMMMMMMMMMXxo,:0Wk,.;OMMMMMMMMM0;.'''''ckXMMMMMMMM0c'.,OM    //
//    MMMMMNd''''oXMMMMMMKc.'':0WMMMMMMMMMMMMNk;''',dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,'.'dWMMMMMMMMMMWKo,'ckOo,.;xWMMMMMMMMM0;.''''''':xKWMMMMMMNkc;OM    //
//    MMMMMMNd''''oNMMMMMNd,.:0WMMMMMMMMMMMMMMMKo,''':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl''.:0MMMMMMMMMXd;';od:'';o0WMMMMMMMMMM0;.'':c,.''';o0WMMMMMMN0XM    //
//    MMMMMMMNd''''oXMMMMMNdcOWMMMMMMMMMMMMMMMMMWO:''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk''.,OMMMMMMMW0:,ck00d;'';lONMMMMMMMMMM0;.''dXOl,'''',lONMMMMMMMM    //
//    MMMMMMMMNd''''oXMMMMMWNWMMMMMMMMMMMMMMMMMMMMK:.'.;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd''.;OMMMMMMMO;:ONWKdlc:lc,'cOWMMMMMMMM0;.''dWMW0o;'''''ckNMMMMMM    //
//    MMMMMMMMMNd''''oXMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.'.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:.'.cXMMMMMMNo:0MXo::cc:;lxc.,xWMMMMMMM0;.''dWMMMWKx:''''':xXWMMM    //
//    MMMMMMMMMMNd,'''oXMMMMMMMMMMMMMMMMMMMMMMMMMMNl.'.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:''.;0MMMMMMMNooNWd:OX0XNd,dO;.:KMMMMMMM0;.''dWMMMMMMXkc''''';dKWM    //
//    MMMMMMMMMMMNd,'''oXMMMMMMMMMMMMMMMMMMMMMMMMMNl.'.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkc,''':0WMMMMKdokxdKMOdKW00WXcoO;.:KMMMMMMM0;.''dWMMMMMMMMNOl,'''.;0M    //
//    MMMMMMMMMMMMNd,'.cKMMMMMMMMMMMMMMMMMMMMMMMMMNl.'.;0MMMMMMMMMMMMMMMMMWKxoddddoolc,'''';dXMMMMMMXl.'dOk0NXXWX0Kkokl''dWMMMMMMM0;.''dWMMMMMMMMMMW0o;'.,OM    //
//    MMMMMMMMMMMMMNd':0MMMMMMMMMMMMMMMMMMMMMMMMMMNl.'.;0MMMMMMMMMMMMMMMWKd;'.........'';lkXWMMMMMMMMKc''lxO0KKXKxxkd:''oXMMMMMMMM0;.''dWMMMMMMMMMMMMWKd;,kM    //
//    MMMMMMMMMMMMMMNOKMMMMMMMMMMMMMMMMMMMMMMMMMMMNkllloKMMMMMMMMMMMMMMWKdllllllllllodxOXWMMMMMMMMMMMMXd;'':oddoxkOd',cOWMMMMMMMMMXdcllOWMMMMMMMMMMMMMMMXOKM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWWMWWWMMWWWMMMMMMMMMMMMMMMMMMMMWXkdolcl::xOkk0WMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'.c0XXOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk::kXXOONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SMNM is ERC721Creator {
    constructor() ERC721Creator("Somnium", "SMNM") {}
}