// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Circuit Bent Textures 001
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////
//                                                                              //
//                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWWXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMN0xdlccokK0kxkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXxc::;;:;::::;,,;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXo:::;;:::::;;,,,;oKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWOocc:::::::::;;;,,,:ldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWKocccccccc:;;:::;,,,,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMKdlllcclc::cclc:;;;;;::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNOollccc::ccllc:;:;;::cc:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMM0olllccccccc:;;,;;;;;::clxKWMMMMMWN0kkOO0XWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWOlllllllcccc:;;;;;;;,;;:cldKWWNKkdlc;,;;;cok0NMMMMMMMMM    //
//    MMMMMMMMMMMMMMNkllllooolcccc:;;,',,,,,;clloddolllllllc;,;,,:0MMMMMMMMM    //
//    MMMMMMMMMMMMMMNklclloooollllccc:;,;;;,;cllcccclllloddolc;,',xNMMMMMMMM    //
//    MMMMMMMMMMMMMMXxlcllllllolllllll:;,,,,:llcccllllclodxxdoc;,,cOWMMMMMMM    //
//    MMMMMMMMMMMMMMNxlcllllllolllllcc:,'.';cc:;,;:cccccccloddoc;;cOWMMMMMMM    //
//    MMMMMMMMMMMMMMW0ollllllllllllllcc:::::;'''''',,,;;::::cclc;l0WMMMMMMMM    //
//    MMMMMMMMMMMMMMMKdllclllcllllllllllooo:,'.''',''',:cc:;:llllOWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMKollllllllllllldxxxdollc:;,..'..',;c:;,:loOXWMMMMMMMMMM    //
//    MMMMMMMMMMMMMWXklclllllllllccodkkxollllllc;,....'',,,,;:kNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMXkollllloollllllloodollllllllllc:;,'...''':0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWXklllllllllllllllllllllcclox0XNX0dc;..,,'cKMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMKdllllcllllllllllcccclldkKWMMMMMN0dc:;,.:0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXdllllllllclllllodxO0KXNWMMMMMMMMMWNXOocxNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXdccllllllllox0KNWWMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWK0KKKKKKXKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                              //
//                                                                              //
//////////////////////////////////////////////////////////////////////////////////


contract JULAQU is ERC721Creator {
    constructor() ERC721Creator("Circuit Bent Textures 001", "JULAQU") {}
}