// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Reeliinda Blue
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//         ..      ...                                 ..    .       .                     ..                           ...     ..                        ..                                                                                                                                                                                                                                                                                                                                                                                 //
//      :~"8888x :"%888x                         x .d88"    @88>    @88>                 dF                          .=*8888x <"?88h.               . uW8"        ..                                                                                                                                                                                                                                                                                                                                                                         //
//     8    8888Xf  8888>                         5888R     %8P     %8P      u.    u.   '88bu.                      X>  '8888H> '8888               `t888        @L                                                                                                                                                                                                                                                                                                                                                                          //
//    X88x. ?8888k  8888X       .u         .u     '888R      .       .     [email protected] [email protected] '*88888bu         u        '88h. `8888   8888         u      8888   .   9888i   .dL                                                                                                                                                                                                                                                                                                                                                                  //
//    '8888L'8888X  '%88X    ud8888.    ud8888.    888R    [email protected]   [email protected]  ^"8888""8888"   ^"*8888N     us888u.     '8888 '8888    "88>     us888u.   9888.z88N  `Y888k:*888.                                                                                                                                                                                                                                                                                                                                                                 //
//     "888X 8888X:xnHH(`` :888'8888. :888'8888.   888R   ''888E` ''888E`   8888  888R   beWE "888L [email protected] "8888"     `888 '8888.xH888x.  [email protected] "8888"  9888  888E   888E  888I                                                                                                                                                                                                                                                                                                                                                                 //
//       ?8~ 8888X X8888   d888 '88%" d888 '88%"   888R     888E    888E    8888  888R   888E  888E 9888  9888        X" :88*~  `*8888> 9888  9888   9888  888E   888E  888I                                                                                                                                                                                                                                                                                                                                                                 //
//     -~`   8888> X8888   8888.+"    8888.+"      888R     888E    888E    8888  888R   888E  888E 9888  9888      ~"   !"`      "888> 9888  9888   9888  888E   888E  888I                                                                                                                                                                                                                                                                                                                                                                 //
//     :H8x  8888  X8888   8888L      8888L        888R     888E    888E    8888  888R   888E  888F 9888  9888       .H8888h.      ?88  9888  9888   9888  888E   888E  888I                                                                                                                                                                                                                                                                                                                                                                 //
//     8888> 888~  X8888   '8888c. .+ '8888c. .+  .888B .   888&    888&   "*88*" 8888" .888N..888  9888  9888      :"^"88888h.    '!   9888  9888  .8888  888"  x888N><888'                                                                                                                                                                                                                                                                                                                                                                 //
//     48"` '8*~   `8888!`  "88888%    "88888%    ^*888%    R888"   R888"    ""   'Y"    `"888*""   "888*""888"     ^    "88888hx.+"    "888*""888"  `%888*%"     "88"  888                                                                                                                                                                                                                                                                                                                                                                  //
//      ^-==""      `""       "YP'       "YP'       "%       ""      ""                     ""       ^Y"   ^Y'             ^"**""        ^Y"   ^Y'      "`              88F                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                     98"                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                   ./"                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                  ~`                                                                                                                                                                                                                                                                                                                                                                       //
//    Reeliinda Blue Collection is a part of the grand Reeliinda Baby Collection. This project will mint 1 NFT every month to used as Reeliinda Baby's Twitter Account PFP. The previous NFT PFP from the month prior will then be listed for purchase for anyone who is interested in supporting.                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Funding will be used to help the Ravage Universe Brand in its expansion and sustainability. A portion will be put away and used to paying for Reeliinda Baby's Twitter Blue account. Other portions will go into helping fund other project expenses such as web hosting, and AI tools such as ChatGPT membership, and eleven labs creator subscription to produce voice overs for the brands animated projects. Extra funding will be stored up to help fund the creation of other comic stories within the Ravage Universe Brand.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Purchasing these NFTs will help support the project by providing funding for annual Twitter Blue Membership. This project will continue self funded and or with collector's funding to 2027 and beyond depending upon future events. Holding these NFTs will show visible support for the Ravage Universe Brand and the Reeliinda Baby Collection. Reeliinda Blue Collection is formatted as a PFP collection with Support/Fundraising NFTs.                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Holders are free to use NFT artwork as their profile pictures on any social media, streaming, and gaming accounts. Holders do not own the rights to the character Reeliinda Zolly, or the right to reproduce her for their personal brands or business. Holders are also restricted from using her for any commercial usage. Holders are not allowed to re-mint artwork or make derivative collections of Reeliinda Zolly to mint for any reason.                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Reeliinda Zolly - Created by Gabriel "Seven Murillo" Pereyra                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    █▄▄▄▄ ██       ▄   ██     ▄▀  ▄███▄         ▄      ▄   ▄█     ▄   ▄███▄   █▄▄▄▄   ▄▄▄▄▄   ▄███▄                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//    █  ▄▀ █ █       █  █ █  ▄▀    █▀   ▀         █      █  ██      █  █▀   ▀  █  ▄▀  █     ▀▄ █▀   ▀                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//    █▀▀▌  █▄▄█ █     █ █▄▄█ █ ▀▄  ██▄▄        █   █ ██   █ ██ █     █ ██▄▄    █▀▀▌ ▄  ▀▀▀▀▄   ██▄▄                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    █  █  █  █  █    █ █  █ █   █ █▄   ▄▀     █   █ █ █  █ ▐█  █    █ █▄   ▄▀ █  █  ▀▄▄▄▄▀    █▄   ▄▀                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//      █      █   █  █     █  ███  ▀███▀       █▄ ▄█ █  █ █  ▐   █  █  ▀███▀     █             ▀███▀                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//     ▀      █     █▐     █                     ▀▀▀  █   ██       █▐            ▀                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//           ▀      ▐     ▀                                        ▐                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract RBCTB is ERC721Creator {
    constructor() ERC721Creator("Reeliinda Blue", "RBCTB") {}
}