// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Everyday NYC
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                //
//                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO=?$8NDZI?~:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8~ONMMMMMMMMMMMMNDI~MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=?ONMMMMMMMMMMMMMMMD?~:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~7NNND8OO8888O8O8OZ?~==:=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:~==II777$777I77$I+~+7$8?IZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7=~~=++++?77I77II+?$OD8=$D7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOO$+~=~=++IIII++?I7Z$=?NMMO8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8MNND7+~=~==+++????~7MMMMMN?==8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=+DMMMMMMMMMZ=====INMMMMMMMMMD+~~==++7MMMMMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~=~?NMMMMMMMMMMMMO7NMMMMMMMMMMMMO:~~=====MMMMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=~~~:7NMMMMMMMMMMMMMMMMMMMMMMMMMMMD=:~~~~===MMMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMD=~~~~~ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ=~~~===+=MMMMMMMMMMMMMMMMMMMMMMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMN===~=~=OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNI===+====MMMMMMMMMMMMMMNMMMMNNMNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMI+++====DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$?++==+?+MMMMMMMMMMMMMMMMMNMNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM++++++?IDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO$II++?++MMMMMMMMMMMMMMMMMMMNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM?++++?I$8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8Z$7III?8MMMMMMMMMMMMMMMNNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMZ=+??I7$8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOZ$777IMMMMMMMMMMMMMMMMMNMNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMM=+?III$ODMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOZZ$7IMMMMMMMMMMMMMMMMMMNMNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMM++?I7$ODNMMMMMMMMMMMMMMMMMMMMMMMMMMMND8OZ$7MMMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?I77$ODNMMMMMMMMMMMMMMMMMMMMMMMMMMNND8OOOMMMMMMMMMMMMMMMMMMNMNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNI7$Z8DNMMMMMMMMMMMMMMMMMMMMMMMMMDDD8OMMMMMMMMMMMMMMMMMMMNMMNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$ZODNNMMMMMMMMMMMMMMMMMMMMMMMNNDNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8DNMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7DNNMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=+=$8O7$MNNMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+~?88NI=NMNO$DMMMMMMNMIZMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI~?O$~?ZNNN$MMMZMMMMMNM$==7MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,~==,=ID88D::MDDMMDMMMMMM~,+I+MMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8~=I+$O~~?ZNMD$NMMNMMMMMN,,7$?=MMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?M:~+I8MMMMMMNZDMMMMMMM?+ZZOZI+~MMMMMMMMMMMMMMMMMMMMMMMMNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO8NOMMMMMMMMMMMNNMMMMMNNDO88OOZI??=~?NMMMMMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8~~~+$NNMMMMMMMMMMNMMMMMMNNNNNDD8OO$7Z====~~~OMMMMMMMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMM7~=====+?8DNMMMMMMMNMMMMMMMMMND8NNNND8OZ$O=+=~~====~~=?MMMMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMMMM+~=======++=ZDDMMMMMMMM$MMMMMMMMNOI?NNNNND8ZO$+++??++++=II?+8MMMMMMMNNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMMMM=++===++===+?=8DNNMMMMMMMMMMMMMMMNO$??NMNNNNDO87?I$OZ??I?I?I$7I$MMMMMMMNNNNNNN        //
//    MMMMMMMMMMMMMMMMMMMM?$N?7N+=++???I?78DNNNNNMMMMMMMMMMMMMM?+MMMMMND8ON77OM8?I7?I$O$OZ??IMMMMMMNNNNNNN        //
//    MMMMMMMMMMMMMMNM8MM?I8?MODI+++???I77ONDNNNNMMMNDMMMMMMMMMM?MMMMNO8OZO$OMD7I7IN8ID$?D8ZI8MMMMMNNNNNNN        //
//    MMMMMMMMMMMMMMNM8M7$M+ON$88???I?$I$~+NDNNNMMMO8DNMMMMMM?$NMMMMNMN8OZZONMO$$$ZD$7$MD$7877NMMMMMNNNNNN        //
//    MMMMMMMMDMMNDMNMDD7$ZN8I8DMI7II$ZZ++IMNDDNN8++~?NMMDMMII=?MNDNDNDOZ8ZODDZZOZN$OMMZIMO$ZDDMM8MMMNNNNN        //
//    MMMMMMMMMNDNMMNMMZDD$$8MDOM88O$O8O??ONNNNNMMO?DNDMMMNDI$7DDNNNDDD88ODMMND8DDNNMD$MMZNMOONMNMMMMMMNNN        //
//    MMMMMMMMMNNMMMMMNNMNDDZDNMMND88ODIIOO8NMMDMNMNDMNNMMMN$ZZDNMMNDND8DDMMMNDNNMMMNNMNMMDMNNNNMMMMMMMMNN        //
//    MMMMMMMMMMMMMMMMNNNNMNNNDNMNMNDDNZ8DDNNDMNMMMMMMMMMMMDOZNMMMMNNNNNNMMNMNNNMNMNMMMMMMNMMMMNMMMMMMMMMM        //
//    MMMMMMMI......,MNM...NM...MMMNNN...8NMMN ..MMM...,MMMD88..... =NMN...MN+...MMM...MM...NMM...MMMMMMMM        //
//    MMMMMMM7. ......MM...NM...MMMMMM...8MMMM:...MM...MMMMNNN ......=MM...MM+ ..MMM...MM...NMM...MMMMMMMM        //
//    MMMMMMM7..+MM...MM...MM...MMMMMM...8MMMMM...M...MMMMMNMN .,M....MM...MM+ ...MM...MM...MMM...MMMMMMMM        //
//    MMMMMMMI..+MM...MM...MM...MMMMMM...8MMMMMD .. . MMMMMMMN .,MM...MM...MM+....ZM...MM...MMM...MMMMMMMM        //
//    MMMMMMMI.......MMM...MM...MMMMMM...8MMMMMM.....MMMMMMMMN .,MM=..8M...MM+ . ..M...MM.........MMMMMMMM        //
//    MMMMMMM7.......,MM...MM...MMMMMM...8MMMMMMM...,MMMMMMMMN .,MM=..8M...MM+ .M . ...MM.........MMMMMMMM        //
//    MMMMMMM7..+MM...MM...MM...MMMMMM...8MMMMMMM...MMMMMMMMMN .,MM...8M...MM+ .M. ....MM...MMM...MMMMMMMM        //
//    MMMMMMM7. +MM...MM...MM...MMMMMM...8MMMMMMM...MMMMMMMMMN .,MM...MM...MM+ .MM.....MM...MMM...MMMMMMMM        //
//    MMMMMMMI........MM...MM........M........MMM...MMMMMMMMMN . .....MM...MM+ .MMD....MM...MMM...MMMMMMMM        //
//    MMMMMMMI........MM...MM........M........MMM...MMMMMMMMMN ......MMM...MM+ .MMM....MM ..MMM...MMMMMMMM        //
//    MMMMMMMZ,,,,,OMMMM:,,MM:,,,,,,,M~,,,,,,,MMM:,,MMMMMMMMMM,,,,:MMMMM:,,MMI,,NMMM:,,MM,,,MMM:,,MMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        //
//                                                                                                                //
//                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract eNYC is ERC721Creator {
    constructor() ERC721Creator("Everyday NYC", "eNYC") {}
}