// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: pepetronn
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00KKKXXKK000KKKKKK00XXXKKXNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKXNXKKNWWWNXXKKKXXNWWWNNXXXK000KKK0KNWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWNXNNXWMMWKkdddxddxxxxkkkxxxkO0NMMMMMWNXKK0KWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWWNXWMMMW0xoodk0NWMMMMMMMMWXK0OkxxxkKWMMMMMMN00XWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWNNMMMMW0dldkKWMMMMMMMMMNOkXMMMMMMMWXkdxkXMMMMMMNOOWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWWWMMMMNkllxXWMMMMMMMMMMWXl. lWMMMMMMMMMMXkxx0WMMMMNkOWMMMMMMM    //
//    MMMMMMMMMMMMMMMWWNWMMMMXdcoOWWx;dNMNK0O000d,.  dWMMMMMMWNWMMMW0dx0WMMMKxKMMMMMMM    //
//    MMMMMMMMMMMMMMWWMMMMWKdld0WMM0' .;c::clllc.   .;ldk00KOc:0MMMMMWKxkXMMNk0MMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWKdlxXMMMWKl.  ,x0NWMMM0'  .lkxooo;.. 'kWMMMMMMNdxWMWkOMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0ooONMMWOoc:.   oMMMMMMWd. .lNMMMMXc..:dllxOxxKWMkoXMW0KMMMMMMM    //
//    MMMMMMMMMMMMMMWKoldol0NO:,lOK:   :XMMMMX0:  .ONXXXXk. '0MWKo..cKWMkoXMW00MMMMMMM    //
//    MMMMMMMMMMMMMXxokNO. .;cdKWMX;  .dWWNX0c'.  .''',,'.  ,OWM0,';cXMMKdKMWOOMMMMMMM    //
//    MMMMMMMMMMMWOokNMMx.  ,KMMMMX;  .,;,'..      'ok0Kx:'..oNK,.kk:OMMXx0MWO0MMMMMMM    //
//    MMMMMMMMMMWkdKMMKx;   '0MW0d,. .'::.         .kWMMMMNx'.;ox0WNdxWMNdkMKkXMMMMMMM    //
//    MMMMMMMMMMWKNWKkodo.  lXk;..,okKNXl           ;KMMMMMMKc  cXMMNXWMKckWOkWMMMMMMM    //
//    MMMMMMMMMWWW0xx0WMK, .l; .:OWMMMMx.           ;KMMMMWXx:.  lNMMMNN0dKXxKMMMMMMMM    //
//    MMMMMMMMWXWWNWMMMMWKl. .c0WMMMMMK;           .dWMMW0l,;o0o..kMWOoOKOOxOWMMMMMMMM    //
//    MMMMMMMMWKKWMMMMMMWk'.;0WMMMMMMWd.           cKXOo;,ckNMMNkx0Oolk0dloOWMMMMMMMMM    //
//    MMMMMMMMMXOXMMMMMWO'.xNMMMMMMMMWo           .,:::lkKNWMMMWx,,ck0kxddOWMMMMMMMMMM    //
//    MMMMMMMMMMOOWMMMMMNkdxkKNWMMMMMWKc.       .:lx0XWMMO;:O0kd,. 'x0K0dOWMMMMMMMMMMM    //
//    MMMMMMMMMM0lOWMMMMMMWKOkkkddxxxoooc::clodkXMMMMMMW0,  :xOK0:  .cdxKWMMMMMMMMMMMM    //
//    MMMMMMMMMMXdoKWMMMMMMMMNNNXK0KKXNWWMMMMMMMMMMMMNxl;.  oWMMMKo:;';OMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWkdOO0NMMMMXo,,OMMMMMMNKXWMMMMMMNxodocoOx. .OMMMNKkx0NNWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKokXOkO0KXo. 'dOKXNWNl.cNMMWXKKo.  ;KMMx. .d00kk0KWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMM0okWWKOkc.  'clodoc;  :xxxxdxkl.  lWMMk. 'lxOKWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMXkk0XNK;  ,xOkOOkc. c0KKXNWMMk. .d0kkxdxKWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWKOOOx, .d0OOkkO: ,x0KXXKKK0c  .dkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMXk0WWNNXXKkdkkxkkkkxxx:  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoll, .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:...;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract PPTR is ERC1155Creator {
    constructor() ERC1155Creator("pepetronn", "PPTR") {}
}