// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: La Reina de la Casa
/// @author: manifold.xyz

import "./manifold/ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMN00NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMMWKOOKXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMNd;o0XNNKkOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMMX0NMMWWNd;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMMMWNKKXNWx'oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMMMXdoONMMWd.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMMMMM0;'kWMMMXc.lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..xMMMMMMMWX0Ol.,0MMMNd..lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWk::kNNNXK0Oxocokl:dKXKOd:;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWNWWWWWWNNNNNNWWWNXXNWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWOlcccccccccccldk0KKKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.        .'lkKNWMMWWNXKKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.       'oXWMMMMMMMMMMMWX0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;. .,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.      ,OWMMMMMMMMMMMMMMMWK0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     .xWMMMMMMMMMMMMMMMMMMXOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:;:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     ;KMMMMMMMMMMMMMMMMMMMMK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     ;KMMMMMMMMMMMMMMMMMMMMW0KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     ;KMMMMMMMMMMMMMMMMMMMMM00WMMMMMMMMMMMMMWXKOOkkOOKXWMMMMMMMMMMMMMMMMWWWWWMMMMMMMMWWWWWWWMMMMMMMMMMNK0OkkkO0XWMMMMMMMMMMMMMMWNK0OkkkOO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     ;KMMMMMMMMMMMMMMMMMMMMM0OWMMMMMMMMMWXK0Oxo:'.....':okXWMMMMMMMMMMWk:::::xWMMMMWkc:::::xNMMMMMWXOxddoolc,..':dKWMMMMMMMN0xl:'..,coxkkkkkkxx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     'oOKNWMMMMMMMMMMMMMMMMWkOWMMMMMMMW0xkKNWMWNKkc.     .'l0WMMMMMMMMNl.    cNMMMMWo..    cNMMMWKOkOKNWMMMWXx,  .,kWMMMMNx;.   .:kXWMMMMMMMWKx::xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.       ..,cdOXWMMMMMMMMMMMWOo0MMMMMMWKl,dNMMMMMMMMWKo'      .c0WMMMMMMWl.    cNMMMMWo..    cXMMNOkKWMMMMMMMMMWO'   ,OMMMMNx;.  'xNMMMMMMMMMMMMWK:.;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd. ..','...   .':okKNWMMMMWKd;dNMMMMMWk'.:XMMMMMMMMMMMW0c.      'xNMMMMMWl.    cNMMMMWo..    cXMKk0WMMMMMMMMMMMMNc   .oWMMMMMXo.,OWMMMMMMMMMMMMMMMO' 'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd'lOXNNXX0kd:'.   ..,;cllc;..cXMMMMMNd. .dWMMMMMMMMMMMMMNd.      .dNMMMMNl.    cNMMMMWo..    cXKxKWMMMMMMMMMMMMMNo.   lNMMMMMMXxOWMMMMMMMMMMMMMMMW0;  ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWkxNMMMMMMMMMWXk:.         .,dNMMMMMWx.  .kMMMMMMMMMMMMMMMWk'      .xWMMMWl.    cNMMMMWo..    cOx0WMMMMMMMMMMMMMMNl.  .lNMMMMMMMWWMMMMMMMMMMMNXKKKK0:. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW0KMMMMMMMMMMMMMNO:.   .,cokXWMMMMMMK;   .kMMMMMMMMMMMMMMMMWk'      ,0MMMNl.    cNMMMMWo..    ;okWMMMMMMMMMMMMMMMX:   .oWMMMMMMMMMMMMMMMWN0OO0KXNWMNl.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW0KMMMMMMMMMMMMMMMNd'  .,xNMMMMMMMMWx.   .oWMMMMMMMMMMMMMMMMWd.     .dWMMNl.    cNMMMMWo..    .lXMMMMMMMMMMMMMMMM0'   .xWMMMMMMMMMMMMWKxoox0NMMMMMMNc   ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWO0MMMMMMMMMMMMMMMMW0;.  .cKMMMMMMMNl.    :KNNNNNNNNNNNNNNNNNK:.     lNMMNl.    cNMMMMWo..    .xWMMMMMMMMMMMMMMMWd.   'OMMMMMMMMMMWXx:,:kNMMMMMMMMMK;   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWkkWMMMMMMMMMMMMMMMMM0:.  .,OWMMMMMNc     .oKKKKKKKKK00OkxxkO0OddddddOWMMWl.    cNMMMMWo..    ,0MMMMMMMMMMMMMMMMNc    ;KMMMMMMMMW0l'.,xNMMMMMMMMMMMO'   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWdoNMMMMMMMMMMMMMMMMMM0;    ,OWMMMMWl.     ;KMMMMMMMMMMMWNXKKKKNMMMMMMMMMWl.    cNMMMMWo..    :XMMMMMMMMMMMMMMMMO'   .lNMMMMMMW0c. .cKMMMMMMMMMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd;OMMMMMMMMMMMMMMMMMMWk.    ;0MMMMMx.     .lNMMMMMMMMMMMMMMMWX00NMMMMMMMNl.    cNMMMMWo..    cXMMMMMMMMMMMMMMMWd.   .xWMMMMMXd.  .lXMMMMMMMMMMMMMNc    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWo.lNMMMMMMMMMMMMMMMMMMNl.   .cXMMMMX:      .dNMMMMMMMMMMMMMMMMW0ONMMMMMMWl.    cNMMMMWo..    cNMMMMMMMMMMMMMMMX:    'OMMMMMKc.   ;KMMMMMMMMMMMMMM0,    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd..dWMMMMMMMMMMMMMMMMMMO'    .xWMMMWO'      .oNMMMMMMMMMMMMMMMMXkKMMMMMMWl.    cNMMMMWo..    cNMMMMMMMMMMMMMMMO'    ;KMMMMXl.   .xWMMMMMMMMMMMMMMk.    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd. .xWMMMMMMMMMMMMMMMMMK;     ;KMMMMWk'      .lKMMMMMMMMMMMMMMMXkKMMMMMMWl.    cNMMMMWo..    cNMMMMMMMMMMMMMMWd.    cNMMMMk.    'OMMMMMMMMMMMMMMXc.    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.  .dNMMMMMMMMMMMMMMMMNc     .kMMMMMWO;.     .,kNMMMMMMMMMMMMWO0WMMMMMMWl.    cNMMMMWo..    cNMMMMMMMMMMMMMMNc    .oWMMMMx.    .kMMMMMMMMMMMMNk;.     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.   .c0WMMMMMMMMMMMMMMNl.    .oWMMMMMMXd,.     .:ONMMMMMMMMWX0KWMMMMMMMWl.    cNMMMMWo..    cNMMMMMMMMMMMMMMK;    .xWMMMM0;    .lXMMMMMMMMMNOc.       ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWd.     'oKWMMMMMMMMMMMMXc     .oWMMMMMMMWXx:..    .;oOXNNNXKKKNWMMMMMMMMNl.    cNMMMMWo..    cXMMMMMMMMMMMMMM0,    .xMMMMMW0:.   .lKWMMMMWKxc,,co:.    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW0olllllloONMMMMMMMMMMMMNklllllo0WMMMMMMMMMMWKxl:,....':oxO0XWMMMMMMMMMMMWOollllkWMMMMWOolllllkWMMMMMMMMMMMMMMXdlllldKMMMMMMMNOo:,'.;oxOOOkxxkKNWM0ollllxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNxo0WMMMMMMMMMMMMMMMMW0okNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdolloodkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMK,.oWMMMMMMMMMMMMMMMMWo.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKK0Okkxdl:'.  ..,cx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWWMK,.oWMMMMMMWWMMMMMMMMWo.;KMMMMWWWMMMMMMMMMMMMMMMMMMW0kOKNMMMMMMMMWXOo;.    .;xOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWNNX0kxl..oWMMNNNKxllxKWMMMMWo.;KWKxok0XXXKNMMMMMMMMMMMMWOooKWMMMMMMMMMMMMMMNOc.    ..'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0d0WMMWKo..oWW0dKWWNk;..oXMMMWo.;KWOcdXMMMWko0MMMMMMMMMMXl,oXMMMMMMMMMMMMMMMMMMW0c.     .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMK;:KMMMMMK,.oW0,cXMMMMXl..lNMMWo.;KMWNWMWNNW0;cNMMMMMMMW0;.cXMMMMMMMMMMMMMMMMMMMMMNx,..,cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWx.,0MMMMMK,.oNd.,0WWNNX0c'cKMMWo.;KMMW0k0XWM0,;KMMMMMMWO, 'OMMMMMMMMMMMMMMMMMMMMMMMWKx0NWMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWx..lNMMMMK,.dNd..oXWWNNXKKNWMMWo.;KWKlcOWMMMk.;KMMMMMM0,  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdlccoxkOOOOOKNMMMMMMMMMMMMMMNKkO0KKK00Oxolodx0WMMMMMWXOxoccldkOOOOO0NWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMX:..oNMMMK,.oWK; .dNMMMMNXWMMMWo.;KK;.dWMMMNo.;KMMMMMXl. .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;...'lOKNWWWNXOxldKWMMMMMMMMWKd;,oKWMMMMMWXOc. .cXMMWKd:'. .cxKNWWWNX0kooOWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMKo'.:kXW0,.oWMKl..cONWWNNWMMMWo.;K0,.oNMWKd' ;KMMMMMO'  .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,. .lKWMMMMMMMMMWO;'dNMMMMMMWx,..oNMMMMMMMMMMWk'.dWMMWO:. .;OWMMMMMMMMMMKc'cKMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWKkodOXKkxKWMMWKxodOXNWMMMMMWKxONWKdx0NXK0OxONMMMMWo.  .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc'dNMMMMMMMMMMMMWk..lNMMMMWk.  .kMMMMMMMMMMMMWkl0MMMMMNd'cXMMMMMMMMMMMMMK;.;0MMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOXMMMMMMMMMMMWNNO, .xWMMMWo.  .lNMMMMMMMMMMMMWXWMMMMMMNOKMMMMMMMMMMMMWNKc..lNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc    'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMNXKKKXX0:  :XMMMWx.   .:kNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKXXKl. 'OMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkO0XWMMMX:  '0MMMMXl.    .,cx0XWMMMMMMMMMMMMMMMMMMMMWXOkk0KNWMMWo. .xMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dclkXWMMMMMMK;  'OMMMMMNk;.      .':okKWMMMMMMMMMMMMMWXxlcd0WMMMMMMNl  .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.,xNMMMMMMMMMk'  .OMMMMMMMN0o;..      ..:dKWMMMMMMMMW0l''oKWMMMMMMMMK;  .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.     ,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;..cKMMMMMMMMMMWd.  .OMMMMMMMMMMWKOd:'.     .'dNMMMMMW0c..,OWMMMMMMMMMMO'  .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.     ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc. .cXMMMMMMMMMMMXc   .OMMMMMMMMMMMMMMWNOd;.    .oNMMMXo.  ,0MMMMMMMMMMMWd.  .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.     .dNMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.  ,0MMMMMMMMMMMM0,   .OMMMMMMMMMMMMMMMMMMNk,.   ,0MMXl.  .xWMMMMMMMMMMMXc   .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;.    .:OWMMMMMMMMMMMMMMMMMMMMMWNWXc.  .lNMMMMMMMMMMMWx.   .OMMMNKXMMMMMMMMMMMMMMO'   'OMWd.   ;KMMMMMMMMMMMM0,   .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'     .cONMMMMMMMMMMMMMMMMWWX0KW0,   .lNMMMMMMMMMMNx'    .OMMM0;oNMMMMMMMMMMMMM0,  .cXMNc    ;KMMMMMMMMMMWO;.   .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.    .:xKWMMMMMMMMMMMWXXXXNMMXc.   ;0MMMMMMMMNk;.     .OMMWd..cKWMMMMMMMMMMWx. .cKMMWd.   .kWMMMMMMMW0c.     .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;..   .;oxOKXXXKKKKXXWMMMMMMKl.  .:ONWMWN0xc;:oc.   .OMMXc   .ckKNWWMMMWXd''ckNMMMMXd'.  'xXWMWNKkl;:ll.   .dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOdlc:;,;:coxkOKXWMMMMMMMMMMW0xl:;cdO00Okk0XWMXxdddkXMMWOdolc::loxkkO0OkxkXWMMMMMMMWXko:;:ok000Ok0XWMNkdddxKMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNWWMMMMMMMMMMMMMMMMMMMMWWNNWWWMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNWWMMMMMMMMMMMMMMMMWWWNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract REICA is ERC721Creator {
    constructor() ERC721Creator("La Reina de la Casa", "REICA") {}
}