// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: NFTV Open Edition
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMW0xddddddddddddddddddddxKWMMMMMMMMMMMMMMMMMMMMNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKNMMMMMMMMM    //
//    MMMMMMMMMNx;',,,,,,,,,,,,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMWXxooooooooooooooooooooooooooooooookXWMMMMMMMM    //
//    MMMMMMMMMNx;',,,,,,,,,,,,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMWXxooooooooooooooooooooooooooooooookXWMMMMMMMM    //
//    MMMMMMMMMNx;,,,,,,,,,,,,,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMWXxooooooooooooooooooooooooooooooookXWMMMMMMMM    //
//    MMMMMMMMMNx;,,,,,,,,,,,,,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMWXxooooooooooooooooooooooooooooooookXWMMMMMMMM    //
//    MMMMMMMMMNx;,,,,,,,,,,;;;;;;;;;;:kXNNNNNNNNNWMMMMMMMMMWXxooooooooooooooooooododddddddddddOXWMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,:kKKKKKKKKKklccccccccclOWMMMMMMMMWXxoooooooooooooooooooddkKXXXXXXXXXNWMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,c0WMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooooooooooooodOWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,c0WMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooooooooooooodOWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,',,c0WMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooooooooooooodONMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,c0WMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxooooooooooooooooooood0WMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,cKWMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxooooooooodxkkkkkkkkkkKWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,cKWMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxooooooooox0NWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,cKWMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,cKWMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,cKWMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWk;,,,,,,,,,c0WMMMMMMMWKc,,,,,,,,,;kWMMMMMMMMWXxoooooooooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWKkxxxxxxxxxONMMMMMMMMMNOxxxxxxxxxkXWMMMMMMMMMNK000000000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMWWNNWWWWNNNWWMMMMMMMMMMWWNWWWWWWWWWMMMMMMMMMM    //
//    MMMMMMMMMNd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,:OWMMMMMMMMWKdllllllllld0WMMMMMMMMW0olllllllllxXMMMMMMMMM    //
//    MMMMMMMMMXc.................................dWMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,;;,,lKWMMMMMMMM    //
//    MMMMMMMMMXc............................... .dWMMMMMMMMW0c,,,,,,,;,:OWMMMMMMMMWk:,,,,,;,,,lKMMMMMMMMM    //
//    MMMMMMMMMXc............................... .dWMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMXc.................................dWMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMNd;;;;;;;;;;'...........,;;;;;;;;;:OWMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKWMMMMMMMM    //
//    MMMMMMMMMMWNNNNWNNNNNo. ........,ONNNNNNNNWWWMMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd..........;0MMMMMMMMMMMMMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd..........;0MMMMMMMMMMMMMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMW0c,,,,,,,,,:OWMMMMMMMMWk:,,,,,,,,,lKMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMW0c,,,,,,,,,:OWWMMMMMMMWk:,,,,,,,,,lKWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMMNOxxkkkkkxxxxxxxxxxxxxxxkxkkkkkkkkONMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo,,,,,,,,,;xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,,,,,,,,,;xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,,,,,,,,,;xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd......... ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,,,,,,,,,;xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWx..........:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;;;;;;;:xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX0000000000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKNWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract NFTV is ERC1155Creator {
    constructor() ERC1155Creator("NFTV Open Edition", "NFTV") {}
}