// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Editions by Anthony Azekwoh
/// @author: manifold.xyz

import "./manifold/ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                        :~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:                                                                                                                                        //
//                                                                                                                                       [email protected]@!                                                                                                                                       //
//                                                                                                                                       [email protected]^                                ^@?                                                                                                                                       //
//                                                                                                                                       [email protected]^     .^::.            .^::      ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^     [email protected]@@Y           [email protected]@@J     ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^    [email protected]@@@&:          [email protected]@@@&:    ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^   .#@@@@@5         .#@@@@@Y    ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^   [email protected]@@[email protected]@@^        [email protected]@@[email protected]@&:   ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^  .#@@G:&@@P       :&@@P^&@@5   ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^  [email protected]@@~ [email protected]@@~      [email protected]@@~ [email protected]@@^  ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^ :&@@P  .&@@G     :&@@P  :&@@P  ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^ [email protected]@@^   [email protected]@@!    [email protected]@@^   [email protected]@@~ ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^:&@@5    [email protected]@G   ^@@@Y    [email protected]@G ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^[email protected]@P      [email protected]@7  [email protected]@5      [email protected]@!^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^7?7.        7?~ .7?7        .7?~^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^                                ^@7                                                                                                                                       //
//                                                                                                                                       [email protected]^                                ^@?                                                                                                                                       //
//                                                                                                                                       ~#P55555555555555555555555555555555P#~                                                                                                                                       //
//                                                                                                                                        .:^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:.                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract EAA is ERC1155Creator {
    constructor() ERC1155Creator("Editions by Anthony Azekwoh", "EAA") {}
}