// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: famorie and friends
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                      //
//                                                                                                                                      //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,';lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.okc':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.oXXOc'cKWWMMMMMMMMMMN0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.l0KXXk,':xNMMMMMMMMNo'',c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.c000XNK:..oXMMMMMMMO':0k;'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMx.:0000KNX0o.cKMMMMMWo.dXXKl.cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:;cox0XWMMMMMMMMMMx.;OK000KXNNx';KMMMMX;'kK0KXd.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.,ol::::ldOXWMMMMMx.;OK000000XNk';0MMMk.:KK00XNd.cXMMMMMMNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.:0KKKOxoc:;:oONMMk.,OK0000000KNk',OWWo.dX0000XXo.lNMMMMO:,;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0',k0000KKXK0xc,;xNO',kK00000000KNk',0K;,0K0000KNXc.xWMMX:'xk;'kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.l00000000KXX0o';l.,kK000000000KXk';:.lXK00000KN0,,0MWd.lNWK:'xWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',k0000000000KXO:. ,kK0000000000KXx. ,OX000K000KNx.lXx':KXKN0,,0MMMMMXKNMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMNl.l000000000000K0l'cOK00000000000KKd;dKK0K000000XXc.,'lKXK0XWx.lNMMM0;.oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNx:::cclodkO0XWMMMMM0,.x00000000000000OO0000000000000000KKK0000000000XOc:kXK0K0KNK;,0MMX:...xMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMK;.lxddoolc::::clxOXWx.;k00000000000000000K000OOOOkkkkOOO0000KK0000000KKKKK0000KNWl.xMXc.dx.cNMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWd.;O00KKKXXK0kxoc:;:c'.cO00000000000Oxdlc:;;;;;;;;;;;;;;;;;:cldxO0KK00000K00000XWd.ck;,xNX;'0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXc.c0000000000KKXKOdl,..o000000kdl:;,;:cloxkO000KKKKKK00Okxdlc;;,;coxO0K00000K0KNx..'l0XXNl.xMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMK:.l000000000000000K0xok00ko:,,,:ldO0XXNNNNNNNNWWWWWWWWWWWWWWNXOxo:,,:lxO0K0000XOllOKK0KNd.oWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWOloONMMK;.o000000000000000000xl;',:ok0KKKKKKKKKKKKKKXXXXXNNNNWWWWWWWWWWWNKOo:,,cdOKK00KKK0000KNx.lWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMO'':,:kNM0;.o00000000000000kl,';lx0KKKKKKKKKKKKKKKKKKKKKKKKKKXXXNNNWWWWWWWWWWNKxc,,cx0K0000000KNx.lWMMMMNKXWMMMMMMM    //
//    MMMMMMMMMMWo.lX0l,;d0O;.o00000000000d:',lk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNWWWWWWWWWWKx:';oO0000K0KNd.oWMMM0:',oXMMMMMM    //
//    MMMMMMMMMMNc.l0KX0d:,:;..lO0000000d;.;d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNWWWWWWWWNOl',lO0000XNl.xMMWO,,kl.dWMMMMM    //
//    MMMMMMMMMMWl.l0000KX0xl;..oO0000x;.;d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNXKKKKKKKKKKKKKXXNNWWWWWWWWKo,'lOK0X0,;KXkc':ON0,;KMMMMM    //
//    MMMMMMMMMMMd.:0000000KKKOxk000kc.,d0KKKKKKKKK000000KKKKKKKKKKKKKKKXNWWWNXKKKKKKKKKKKKKKKXXNWWWWWWWWKo',d0Ko.':;;ckK0KXc.kMMMMM    //
//    MMMMMMMMMMMO',k00000000000000d,.cOKKK000000OOOOOOOOO0000000KKKKKKKKXXNXXKKKKKXXNNXXXKKKKKKKXNWWWWWWWN0:.:kd:cok0K00KKXl.dMMMMM    //
//    MMMMMMMMMMMX:.o000000000000Ol.,d00000OOOOOOOOOOOOOOOOOOOOOOO00000KKKKKKKKKKKNWWWWWWWNXKKKKKKKXNWWWWWWWXd''d0KK000KK0KXl.xMMMMM    //
//    MMMMMMMMMMMMk.,k0000000000k:.;k0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKKKKKKNWWWWWWWWWWNXKKKKKKKXNWWWWWWWO;.l0K000KK0KK:.OMMWWW    //
//    MMMMMMMMMMMMNl.cO00000000k;.:kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00KKKKKNWWWWWWWWWWWWNKKKKKKKKNNWWWWWWK:.cO0000K0Kk.'ooc:;:    //
//    MMMMMMMMMMMMMK:.o0000000k;.cOOO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKXNWWWWWWWWWWWNXKKKKKKKKXNWWWWWWKc.c0K000K0c.':lxx,.    //
//    MMWNX0OOkkkOO0x'.d00000k;..:c::cccccllloddxkkOOO00OOOOOOOOOOOOOOOOOOOOOOO00KXNWWWWWWWWWWWNKKKKKKKKKXNWWWWWNo..l000000Ok0KXKo.;    //
//    oc::::::c::::::'.,x000Oc.':::::::::;;;,,,,,,,,;;clodxOOOOOOOOOOOOOOOOOOOOOO00KXNWWWWWWWWWNKKKKKKKKKKKNWWWNx'''.dK0000000KKo.;0    //
//     ,dO0KKXXKKKK0OkddO000o.,x0OOO000OOOOOOOOkkxdolc:;,,,,;:ldkO0OOOOOOOOOOOOOOOO00KXNNNNWNNXKKKKKKKKKKKKKXNNx',Ox.,kK000K0KKo.:KM    //
//    l',oO0000000000000000x'.oOOOOOOOOOOOOOOOOOOOOOOO0OOkxol:,'',:lxkOOOOOOOOOOOOOOO00KKKXXXKKKKKKKKKKKKKKKK0o.:0WXc.l00000K0c.lXMM    //
//    W0l',lk0000000000000Oc.:OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdl:,'',:okOOOOOOOOOOOO00KKKKKK0OOOOO00KKKKK0d,'oXWWWO''kK0KKk;'xNMMM    //
//    MMWKo,'cx00000000000x'.dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00Oxol;'':okOOOOOOOOOOxdol:;,''....',;cdkd;.;kNWWWWXc.o00Kx..,lloxO    //
//    MMMMWXd;':dO00000000c.;kOOOOOOOOOOOOOOOOOOOOOOOOkxddxxkOOOOOOOOO0Oko;''cdOO0Oxl:'..               ...;x0KNWWWWWd.:OKKOdddooc..    //
//    MMMWNXKkc..,d000000k,.lOOOOOOOOOOOOOOOOOOOOkdc;,,,,,,,,,:okOOOO0OOOOOxl,.;ll,.                      .:OKKXNWWWWO',kK00KKXXO:.;    //
//    Xd::::::::clx000000x.'x0OOOOOOOOOOOOOOOOOxc'';coxkkkkxdl:'':xOOOOOOOOO0Od;.                          .oKKKNWWWW0,'xK00KKk:':kN    //
//    0:.'oO0KKKK00000000o.,k0OOOOOOOOOOOOOOOkl.'cxOOOOOOOOOOOOkl'.lk0OOOOOOOO0x'                           c0KKXWWWWK;.xK0Kk:';kNMM    //
//    MNk;.;dO00000000000l.;kOOOOOOOOOOOOOOOk:.;xOOOOOO00OOOOOOO0x;.:xkOOOOOOOOOc.                         .c0KKXNWWW0,.xKkc.;kNMMMM    //
//    MMMNk:.;dO000000000l.;OOOOOOOOOOOOOOOOl.,k0OOkxolc:;;,,;;::c:...lOOOOOOOOOOl.                        .dKKKXNWWWO',dl',dXMMMMMM    //
//    MMMMMNO:.;dO0000000l.;kOOOOOOOOOOOOOOk,.lkdc;'..          'c:,. ,k0OOOOOOOOOd,.                      :OKKKKNWWWx..',dXMMMMMMMM    //
//    MMMMMMMNO:.;dO00000o.,k0OOOOOOOOOOOO0x'.,,';od'           ;0Xx' 'x0OOOOOOOOOOko,.                   ,kKKKKKNWWXc.'dXMMMMMMMMMM    //
//    MMMMMMMMMWO:.;dO000x''dOOOOOOOOOOOOOOk; 'ok0XXl.         .cKNx. ,k0OOOOOOOOOOOOko;.               .;kKKKKKKNWWk.'OWMMMMMMMMMMM    //
//    MMMMMMMMMMMNO:.;dO0O;.lOOOOOOOOOOOOOOOo.,kOkKXKo..      .l0Xx,.,lOOOOOOOOOOOOOOOOOxl;..         ...,lx0KKKXNWK:.dWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNk:.;dOl.;kOOOOOOOOOOOOOOOl..cOXXXKOxlc:clxOK0o''okOOOOkolcldkOOOOOOOOOOkdl:;,'',;cxOxl;',cx0XWXl.lXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNx'.cd,.lOOOOOOOOOOOOOOOOd;.;oO00XXNKKNNKxc'':xOOOOkl'.   .'cxOOOOOOOOOO0KK0000KKKKKKKko;';xKo.:KMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWXOo:,;dOo.'xOOOOOOOOOOOOOOOOOd:,',cccll::;,,;lxOOOOOk:.        'oOOOOOOOOO0KKKKKKKKKKKKKKK0xc'..:KMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMKd:'':ok000Oc.;kOOOOOOOOOOOOOOOOOOkxoc::::ccoxkOOOOOOO0o.          .dOOOOOOOO0KKKKKKKKKKKKKKKKX0;.cXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMM0:'',::;,,,;,..;xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Oc.   .''.   .cOOOOOOOO0KKKKKKKKKKKKKKXXk,'dNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWNXKK00OOkkxxc.,dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOl. .'lkkl,...oOOOOOOOO0KKKKKKKKKKKKKXKo';0WMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWk,.cxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkolokOOOOOxdxOOOOOOOO00KKKKKKKKKKKXXk;'dXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMXd,':dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKKKKXOc'c0WMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:',cdkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKKX0l.;ONMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:,,;coxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKXk,.:cxOKXWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;,,,:clodxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKXx..cl;,lddddxkO0XWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxdlc;..'oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKKKKKKKKKXk.,o::;lO00OkxddddddkXMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:,.cOOOOOOOOOOOOOOOOOOOOOOxdkOOOOOOOOOo,:x0KKKKKKNd.'c;;,;lllllodxxdl;';kWMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kddc,c, ,kOOOOOOOxclkOOOOOOOOOO:.:kOOOOOOOOl...,cdkOOOd'.l,.:;dK0Okddooooodkd:dWMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdoooodkx:;,..cOOOOOOOc..,dOOOOOOOO0o..,dOOOOOO0o.,:..',''...':;c:lOkdOK0xk0K0d:o0x;xWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdooloxO0KKK00d;;'..;oxkkxl..;'.,cxO0OOOkc....;lxkkOx,.'.'xKk,...';',,:xl,'o0l;:cxO:,c::,lNMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMXxlllxO0KKKK0K00000d:;,.....'....,,....,:cc;'..;oc,'''','''.,dxoc;'',;;okl;:lkc:d;l0d::,cKO,,OWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMM0:ck000KK0KKK0000KKK0x;,,',,...'',,;;,'. .';:co;,okkxc.;odc..::,,;cc:;;;kW0x0NNOl;c0NX0do0NWK:cXMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMKc,:oxk000KKK000Oxdollllodo,...,;,',cllodl,.,lxkl,oOO0d,l0x, .;,',,co,,l:kW0:c0NNXKXNWWNNNWWWWO,lNMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXcckl:cllllllllolll::oOkc:kk,.,'.,';oc;,;l0Xx;.:Ok;:xddl,lKl. :c.:l,lo:::dXWWx..ckXNWWWWNNWWNNWNc'OMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWd';cc,l0Ol,ckOdcxKk;':xx,,:;;;::'cxxoc'.,c;cdo,.,c;:llll:::'..;;;oc,;;;lkNWNWKc,:::lxKNNWWWWWNWWo.dMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWd.;k0c;oc:c;ok:,cxl;xd:;;k0x0Ko;;:d:'c;.':'.,''..ckKKKKK0Od;..;;;,,codOXWNWWWWO:dXK00XWNWWWNWNWX:.kMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMX;'x00klcd0Nx:;:o:c:cKNKk0NWWX0d:l:,,,;;,''';:;'.cKOllO0l;dKO;'cldO0KNWWNWWWWNWWd;kWNNNNWWNNWWWNd.:XMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWd.:O0O0KNWNNNK0Kklol:dxxxkkkdloc:ddoooolcclolllc'c0OllxdookKk,c0XNNNNWNWWNWWWWNWXc:KWNNWWWWNNWNd.,0MMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMN:.o0O0OKNWNNNNNNNX0dld:;o:,ll:dxkKNNNNXXXXXXXKK0k:;xKOxxk00o'.xWN00XNWWNNN0xxkXWWk,oNWWNWWNNWKl.:0WMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMX:.o0O0O0XWNNNWNNNNNNK0Kk:,dkOKK0NWWNNWWNXKKXWNNNNx..c,,:';,. .xKoodlxKK0Kx:dkcdNWNc,0WNWWWWXx,'xNMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWo.:O00O0KNNNNNNNWNNNNNNWKl,x0dodokKKKK0dlodoONNNW0,.....  .;..x0ldxlxKKKX0xddd0NWWx'oNWWN0o;,oKWMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMM0,.o00000KNWWNNNNNNNWWNNWXc.;cdxcdKKKKkc:oxcxNWNWK,.:.    ,x;.xWKOkKNWWWWWWNXNWWWWK;,dxl;,:dXWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWO,.lO0000KNNNNNNNNWWN0xl:'.,xkx0NWWNWNKOkxONWNNWK;.c'    ,k:.dWNWWNWNNNNWNWNNWWWWWo....:KWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMM0:.;dO0O00XNNNNNWXx:',:od;.oNWNNNNWNNNNWWWNNWNWK;.l,    ,k:.dWWNNWNNWNNNNWWWWNWWWk.:d',0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNk:.,lxO00KXNNKo,.;d0KKKo.:XWNNNNNNNWWNNNNNNNWK;.l;    ,k:.dWWX00XWNWWWN0xxOXWWWK;'xc.oWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;',:ldkxc'.:x0KKKKKo.lKKNWWNWWWNNXKNNNWNWK;.o;    ,k:.oW0oddlkKK0Kx:dx:xWWWNc.dd.:NMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl;....:dOKKKKKKKl.;ddokXKKX0dlodoONNNWK;.o:    ,k:.oWOlddlxXKKX0dddd0WWWWo.co.cNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..:dk0KKKK0KKKl 'dxcd000Kkc:oxcdNWNWK;.oc    ,k:.oNNKkkKNWWWWWNXXNWWWWWx...'kWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.;odx0KKKKx;l0k'.lkx0NNWNNNKkkxOXWNNWK;.dc    ,k:.oNWWWWWNWNWWWWNNWWNWWWk..oKWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.co;:k0xkK0:..'',xNWWNNNNWWWWWWWNNNNNWK;.dc    ,k:.oNNWWWWWNNWWNWWNNNNWWWk.:XMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;'.cOl,dKo.'oxOXNNNNNNWNNWWWWNNWNNNNWK;.dl    ,k:.dNWWNNWWWNWWWXOOKNWWWWx.cNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNX0c';..cl..oKNNNNNNWNNNNNNWNNNNWWWNNWK,.dl    ,k:.dWKxdddOXKKXOlodlkWWWNo.oWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..:;,,cx0XNWXkddd0NNNNXkdxxdONNWNW0,.xc    ,k:.dWkcxk:oK00KklodlkWWWO''OMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'c00OO000XNW0coO:l0000k:o0OclXWWNW0'.xc    ;k:.dWNOxxkXWNNNWX0OKWWXd''kWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;o0OO0OOOKNWNOddxKNNXXXOxxdx0NNWNWO''xc    ;k;.xWWWWWWNNWWNNNWWXkl,,oKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;l00OO00O0XWNWWWWWWWWNNNWWWWNNNNNWO''x:    ;k;.xWNWWWNNWWWNXOdc'.,xXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.;cdkO000KNNNNNNNWWWNNNNNNNWNNNNWk.,x:    :k;.xWNWWNXKOdl:,,:c.'OMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx...',;clok0XNNWWWWWWWWWWNNWNNNNWk.,x;    :x,.okdoc:;;;:ldOXWk.:NMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.dxlc:,'',,;:clooddxxkkkkkkkkkkc..:.    .'..,;:codk0XNWWNWNl.dWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0''x0O00OOkxddddolc:::;;;;;;;;;;;;;::cclodxkO0XNNWWWWNNNWNNWK,'0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.'x0O00OOOOKNWWWWWWWNNNNNNNNNNNNNNWNNKO0NWWNWWNWWNNWWNWWNWWx.cNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.'k0O0OO0O0XWWNNNNNNNNNNNNNWNX0kdol:::lkNWNNWWWWWWWWWWWWNWXc.xMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.,k0O0OOO0XNWNNNNNNNNNNNNNNWO;,c,.'lxO00NWNNNNNNWWWWWWWWNWO',KMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.,k0OOOOOKNWNNNNNNNNNNNNNNWK:.xWK;,k0OO0XWNNNNNNWWWWWWWNWWo.lWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.;O0OOOO0KNNNNNNNNNWWWNNNNNo.cNMWo.cO0O0XWNNWWNNWNNWNWWNWX;.kMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM███████╗ █████╗M███╗MMM███╗ ██████╗ ██████╗ ██╗███████╗NNNWWWNWO',0MMMO''k0O0XWNNWWNNNNNWNNNWWk.:XMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM██╔════╝██╔══██╗████╗M████║██╔═══██╗██╔══██╗██║██╔════╝NNNNNNWX:.xWMMMNc.l0O0XWNNWWNNWNWNNNNWNl.dWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM█████╗MM███████║██╔████╔██║██║MMM██║██████╔╝██║█████╗NNNNNNWWNd.cNMMMMMx.;k00XWNNWWWWWWWWWNNW0,'0MMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM██╔══╝MM██╔══██║██║╚██╔╝██║██║MMM██║██╔══██╗██║██╔══╝NNNNNNWW0''0MMMMMMK,.d00XWNNWWWWWWWWWNWWx.cNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM██║MMMMM██║MM██║██║M╚═╝M██║╚██████╔╝██║0O██║██║███████╗NNNWXKc.dWMMMMMMNc.lO0XWNNWWWWWWNWNNWX:.xMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMM╚═╝MMMMM╚═╝MM╚═╝╚═╝MMMMM╚═╝ ╚═════╝x╚═╝0O╚═╝╚═╝╚══════╝NNNWx;.;XMMMMMMMMd.;O0XNNNNNNWWWWWNWWO',KMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.d0OOOOKNWWNNWNNNWNNWK; .kMMMMMMMMMO''x0KNNNNNNNNNWWNWWo.lWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO''x0OOO0KNNWNNNNNNNNWNo..lNMMMMMMMMMX;.d0KNWNNNNNNNNNNWX;.OMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.,k0OOO0XNNNNNNNWNNNWO''o0MMMMMMMMMMNc.lO0XWWWNNNNNNWWWk.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.;O0OOO0XWNNNNNNNNNWNl.oNWMMMMMMMMMMMo.;k0KNNNNWNNNNNWX:.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.:dO0O0XWNNNNNNNWNXd.;KMMMMMMMMMMMMMd..':oOXNWWWWWNKx;.,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..,cokKNNNNNXKOdc' ,0MMMMMMMMMMMMMMd.   ..,:cllc:,..,c';kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   ..',;;;,,'......kWMMMMMMMMMMMMMK;.  ...........',cl;.oNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.. ...........'''. ,0MMMMMMMMMMMMMMKc.   .......''''',l:.oWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;.  ....''''''''''..oNWMMMMMMMMMMMMMWOc.   ......''''',;.;KMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo..  ...'''''''''. :KNMMMMMMMMMMMMMMMWKd:.    ........ .xWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.   ...'''''''. cXNMMMMMMMMMMMMMMMMMMWKko:,..    ..:OWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc..  ........ 'OMMMMMMMMMMMMMMMMMMMMMMMMWNKOkxxxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:..      'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl,....:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                      //
//                                                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract FAMORIE is ERC721Creator {
    constructor() ERC721Creator("famorie and friends", "FAMORIE") {}
}